In [1]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "HOW_TO_RUN.md":
            print("HOW_TO_RUN:")
            print(os.path.join(root, file))

HOW_TO_RUN:
/kaggle/input/datasets/tejasweerajput/amazon-v3/HOW_TO_RUN.md

In [2]:
guide_path = "/kaggle/input/datasets/tejasweerajput/amazon-v3/HOW_TO_RUN.md"

with open(guide_path, "r", encoding="utf-8") as f:
    print(f.read())

# HOW TO RUN THIS PROJECT — Complete Beginner's Guide

This assumes you know nothing about the setup. Every command below is
copy-pasteable. Where something can go wrong, there's a "Why this error
happens" note right after it, because we hit these exact errors ourselves
while building this checkpoint.

---

## 0. Two ways to run this: Kaggle vs. a Claude/chat sandbox

This project was built inside a **small sandbox**: 1 CPU core, ~4GB RAM,
~10GB free disk, no GPU. That is NOT enough to hold the full dataset
comfortably. Everything below is written for that constrained
environment, because that's almost certainly what you have too if you're
running this inside a Claude conversation.

If you instead have **Kaggle** (free, and what the original project
was designed for): you get more disk and RAM, so some of the workarounds
below (like "build one index at a time") become unnecessary — you can
probably hold both S2 and S3 full indexes at once. Everything still
works the same way, just faster and with fewer disk-related errors.

---

## 1. Get the files in place

You need, in one folder:

```
train_source1.tsv
train_source2.tsv
train_source3.tsv
train_ground_truth.tsv
```

(Test files — `test_source1/2/3.tsv` — are NOT needed for anything in
this guide. You only need them once you get to the "score the test set"
step, which this checkpoint hasn't reached yet.)

Unzip the checkpoint package (`amazon_ml_checkpoint_v2.zip`) somewhere.
You should see:

```
modules/            <- the actual code
measurements/        <- scripts that measure recall
checkpoints/          <- saved results (JSON) from past runs
notebook_progress/    <- unfinished notebook cells (cells 1-3 only)
STATUS.md
HANDOFF_TO_NEXT_CLAUDE.md
MEASURED_RESULTS_FULLSCALE.md
DATA_STATUS.md
CHECKPOINT_MANIFEST.txt
```

**Why this matters**: the raw `.tsv` data files are NOT inside the zip
(they'd make it huge and you already have them). The zip is code +
results only. If you run a command below and get
`FileNotFoundError: train_source2.tsv`, it means you haven't put the
TSV files where the command expects them — fix the path in the command,
don't assume the zip forgot something.

---

## 2. Check you have Python and disk/RAM

```bash
python3 --version
df -h .          # check free disk space
free -h          # check free RAM (Linux/Mac; on Mac use `vm_stat` instead)
```

**Why this matters**: building one full index (S2 or S3) needs about
**6-6.5 GB of free disk**. If `df -h` shows less than ~7GB free in the
folder you're working in, stop now and free up space first — the build
will fail partway through with a disk-full error otherwise, and you'll
have wasted 5-10 minutes of build time to find that out.

If `python3` isn't found, try `python` instead. This project uses only
Python's standard library (`sqlite3`, `csv`, `json`, `unicodedata`) —
you do NOT need to `pip install` anything to run the scripts in this
guide.

---

## 3. Build the S2 index (the single most common source of errors)

Open a terminal, `cd` into the `modules/` folder from the zip, then run:

```bash
cd modules/
python3 -c "
from indexer import build_index
build_index('/full/path/to/train_source2.tsv', 'S2', limit=None, backend='sqlite', db_path='./s2_full.sqlite')
"
```

Replace `/full/path/to/train_source2.tsv` with wherever you actually put
the file. Use the FULL path, not a relative one, to avoid confusion.

### Error: `ModuleNotFoundError: No module named 'indexer'`

**Why this happens**: Python only looks for `indexer.py` in your current
folder (or on `PYTHONPATH`). If you run the command from anywhere other
than inside `modules/`, it can't find it.

**Fix**: make sure you actually `cd`'d into `modules/` first. If you're
running this from a script located elsewhere, add this to the top of
your Python code instead of `cd`-ing:
```python
import sys
sys.path.insert(0, '/full/path/to/modules')
from indexer import build_index
```

### Error: the command just... stops, with no error, partway through

Example output you might see:
```
[indexer]   indexed 3,000,000 S2 records...
```
...and then nothing more, no error, no crash message.

**Why this happens**: this is NOT a bug. Some environments (this
includes the Claude sandbox this was built in) put a hard time limit on
a single command — we hit exactly this at ~280 seconds, after ~3.3
million of 5 million rows. The process gets killed by the environment,
not by the code.

**Fix**: just run the exact same command again. The indexer checkpoints
its progress to a `.manifest.json` file every ~200,000 rows, so it will
print:
```
[indexer] Resuming S2 index at ./s2_full.sqlite: 3,293,469 rows already indexed, continuing from there.
```
and pick up where it left off, instead of starting over. Keep re-running
the same command until you see:
```
[indexer] Finished S2: 5,034,616 records, 26,696,614 distinct blocking keys.
```
That's how you know it's actually done — not the absence of an error,
but this specific "Finished" line.

### Error: `sqlite3.OperationalError: database or disk image is malformed` (or similar disk errors)

**Why this happens**: you ran out of disk space mid-write. A full S2 or
S3 index needs ~6-6.5 GB.

**Fix**: delete the partial index files (`s2_full.sqlite`,
`s2_full.sqlite-wal`, `s2_full.sqlite-shm`, `s2_full.sqlite.manifest.json`)
and free up more disk space before starting over — a corrupted SQLite
file from a disk-full crash usually can't be resumed cleanly, it's safer
to restart that one index from zero.

---

## 4. Measure S2 recall against the index you just built

Still assuming you're in the `modules/` folder (or have it on your path),
`cd` to `measurements/` and run:

```bash
cd ../measurements/
python3 -c "
import sys
sys.path.insert(0, '../modules')
sys.argv = ['x', 'S2', '../modules/s2_full.sqlite', './recall_s2.json', '30000']
exec(open('measure_full_single_source.py').read())
"
```

What the 4 arguments after `'S2'` mean:
1. `'S2'` — which source you're measuring
2. `'../modules/s2_full.sqlite'` — path to the index you built in step 3
3. `'./recall_s2.json'` — where to save progress/results (a checkpoint file)
4. `'30000'` — how many S1 rows to sample. Bigger = more accurate but
   slower. 30,000 took about 6 minutes total on the 1-core sandbox this
   was built in.

### Error: same "stops with no error partway through" as step 3

**Why**: same reason — a per-command time limit. Same fix — just re-run
the identical command. It resumes from `recall_s2.json` automatically
(you'll see `[S2] resuming at sample_index=...`).

### Error: recall numbers look wrong / much lower than expected (e.g. ~46%)

**Why this happens**: this is the single most important gotcha in this
whole project. If you built the S2 index with `limit=2500000` (or any
number less than the full row count) instead of `limit=None`, then a lot
of the ground-truth matches literally cannot exist in your index — they
live in the un-indexed rows. The recall number you get back will look
like a bug, but it's actually measuring "recall including matches that
had zero chance of being found," which is meaningless.

**Fix**: always build with `limit=None` (the full file) if you want a
real recall number. If you deliberately want to test on a smaller
partial index for speed, that's fine — just don't compare that number
to a full-index number, and label it clearly as partial in any notes you
keep (see `MEASURED_RESULTS.md` in the zip for exactly this mistake
happening once already, and how it was caught).

### How you'll know it's really done

```
[S2] DONE. n_processed=30,000 actual=49,982 found=47,551 recall=95.1362%
```
The word `DONE` and a final `recall=` line — not just the absence of
new output.

---

## 5. Free disk space, then repeat for S3

You almost certainly do NOT have enough disk to hold both the S2 index
and the S3 index at once (each is ~6+ GB, most sandboxes here have
~10GB total). So:

```bash
rm ../modules/s2_full.sqlite ../modules/s2_full.sqlite-wal ../modules/s2_full.sqlite-shm ../modules/s2_full.sqlite.manifest.json
```

**Why this is safe**: you already have the recall result saved in
`recall_s2.json` — deleting the multi-gigabyte index file doesn't lose
that measurement, it only deletes the (rebuildable) lookup structure.

Then repeat steps 3 and 4 exactly, but with `S3` instead of `S2`
everywhere (`train_source3.tsv`, `s3_full.sqlite`, `recall_s3.json`).

### Error: `finalize()` step seems to hang or re-read the whole file for no reason

**Why this happens**: if a build gets interrupted (see step 3's timeout
note) AFTER all rows are inserted but BEFORE the final "build index /
mark complete" step, re-running `build_index(...)` normally will still
re-*parse* every row (just to check "have I already indexed this one?"),
which is slow and looks pointless if 100% of rows are already in.

**Fix** — skip straight to finalizing without re-reading the source file:
```python
import sys
sys.path.insert(0, '/full/path/to/modules')
from indexer import SqliteIndex
idx = SqliteIndex('S3', '/full/path/to/s3_full.sqlite')
idx.count = 5285603   # the exact row count already indexed (source3 = 5,285,603)
idx.finalize()
```
This is exactly what was done to finish the S3 index in this checkpoint.

---

## 6. Combine the two numbers into one "combined recall"

Once you have both `recall_s2.json` and `recall_s3.json` marked `done`,
combine them by hand (don't just average the two percentages — weight
by actual match count):

```python
import json
s2 = json.load(open('recall_s2.json'))
s3 = json.load(open('recall_s3.json'))
combined_actual = s2['actual'] + s3['actual']
combined_found  = s2['found']  + s3['found']
print(f"S2 recall: {s2['found']/s2['actual']:.4%}")
print(f"S3 recall: {s3['found']/s3['actual']:.4%}")
print(f"Combined:  {combined_found/combined_actual:.4%}")
```

---

## 7. If you want to try improving recall (cap-loosening experiment)

Open `modules/blocking.py`, find `DEFAULT_FREQ_CAPS` near the bottom, and
change:
```python
"AL2": 80,
...
"A4W": 10,
"AT2": 20,
```
to something looser, e.g.:
```python
"AL2": 150,
...
"A4W": 20,
"AT2": 40,
```
Save the file, then **re-run step 4's measurement command** (no need to
rebuild the index — caps are applied at query time, not index-build
time). Compare the new recall AND the new average candidate count per
S1 row (printed in the script's output) against the checkpoint's
baseline numbers in `MEASURED_RESULTS_FULLSCALE.md`.

**Why this is worth trying**: these three caps are the tightest in the
whole system and were flagged twice as the likely cause of recall
dropping as the dataset gets bigger, but never actually tested.

---

## 8. General troubleshooting checklist

If something breaks and none of the above matches, check these in order:

1. **Are you in the right folder?** Most errors here are path errors.
   Run `pwd` and `ls` to confirm what's actually around you before
   assuming the code is broken.
2. **Did a command "silently stop"?** That's a time limit, not a crash —
   just re-run the exact same command; everything here is checkpointed.
3. **Disk full?** Run `df -h .` before every index build. You need ~6-7GB
   free per full index.
4. **Comparing two recall numbers that don't match expectations?** Check
   whether both were measured against a FULL index (`limit=None`) or
   whether one was partial — this single mix-up caused a false "46%
   recall" scare earlier in this project (see `MEASURED_RESULTS.md`).
5. **Still stuck?** Read `HANDOFF_TO_NEXT_CLAUDE.md` in the zip — it has
   the exact commands that were run to produce every number in
   `MEASURED_RESULTS_FULLSCALE.md`, so you can diff your output against
   what's expected there.

In [3]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    if "HOW_TO_RUN.md" in files:
        print("CHECKPOINT ROOT:")
        print(root)

CHECKPOINT ROOT:
/kaggle/input/datasets/tejasweerajput/amazon-v3

In [4]:
CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"

print(CHECKPOINT_ROOT)

/kaggle/input/datasets/tejasweerajput/amazon-v3

In [5]:
import os

print("CHECKPOINT CONTENTS:\n")

for item in sorted(os.listdir(CHECKPOINT_ROOT)):
    print(item)

CHECKPOINT CONTENTS:

CHECKPOINT_MANIFEST.txt
DATA_STATUS.md
HANDOFF_TO_NEXT_CLAUDE.md
HOW_TO_RUN.md
MEASURED_RESULTS.md
MEASURED_RESULTS_FULLSCALE.md
PHASE1_ARCHITECTURE_AUDIT.md
PROMPT_FOR_NEXT_CLAUDE.md
STATUS.md
checkpoints
measurements
modules
notebook_progress

In [6]:
import os
import json

CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"
CHECKPOINT_DIR = os.path.join(CHECKPOINT_ROOT, "checkpoints")

print("CHECKPOINT FILES:")
for file in sorted(os.listdir(CHECKPOINT_DIR)):
    print(" -", file)

print("\n\nRESULTS:\n")

for file in sorted(os.listdir(CHECKPOINT_DIR)):
    if file.endswith(".json"):
        path = os.path.join(CHECKPOINT_DIR, file)

        print(f"\n===== {file} =====")

        with open(path, "r") as f:
            data = json.load(f)

        print(json.dumps(data, indent=2))

CHECKPOINT FILES:
 - recall_s2_full_DONE.json
 - recall_s2_loosecaps_DONE.json
 - recall_s3_full_DONE.json


RESULTS:


===== recall_s2_full_DONE.json =====
{
  "sample_target": 30000,
  "stride": 73,
  "next_sample_index": 30000,
  "n_processed": 30000,
  "n_with_gt": 26054,
  "actual": 49982,
  "found": 47551,
  "candidates_per_s1": [
    90,
    13,
    337,
    57,
    195,
    142,
    403,
    189,
    313,
    106,
    478,
    322,
    20,
    354,
    469,
    212,
    9,
    157,
    169,
    158,
    304,
    388,
    20,
    46,
    137,
    163,
    433,
    33,
    420,
    27,
    465,
    85,
    213,
    171,
    29,
    110,
    277,
    253,
    23,
    306,
    28,
    89,
    17,
    118,
    366,
    114,
    69,
    366,
    260,
    77,
    8,
    17,
    86,
    140,
    16,
    126,
    300,
    201,
    148,
    99,
    16,
    354,
    34,
    360,
    24,
    145,
    3,
    137,
    156,
    246,
    327,
    157,
    192,
    117,
    212,
    103,
    63,
    281,
    31,
    185,
    36,
    98,
    368,
    138,
    36,
    226,
    216,
    564,
    180,
    67,
    27,
    394,
    351,
    306,
    241,
    449,
    152,
    73,
    191,
    105,
    119,
    7,
    175,
    216,
    184,
    321,
    172,
    446,
    262,
    144,
    12,
    257,
    52,
    203,
    6,
    208,
    258,
    93,
    118,
    22,
    143,
    284,
    982,
    228,
    212,
    262,
    126,
    186,
    177,
    83,
    386,
    110,
    291,
    87,
    312,
    298,
    206,
    132,
    283,
    277,
    25,
    158,
    27,
    364,
    80,
    400,
    258,
    230,
    90,
    383,
    195,
    382,
    67,
    71,
    281,
    272,
    185,
    69,
    37,
    832,
    126,
    45,
    224,
    13,
    613,
    254,
    25,
    10,
    62,
    187,
    63,
    234,
    347,
    245,
    105,
    12,
    156,
    349,
    42,
    168,
    238,
    84,
    210,
    2,
    102,
    454,
    253,
    110,
    215,
    31,
    318,
    133,
    18,
    326,
    772,
    574,
    109,
    358,
    510,
    201,
    201,
    23,
    104,
    117,
    463,
    500,
    8,
    273,
    324,
    173,
    136,
    97,
    125,
    469,
    484,
    489,
    77,
    155,
    155,
    129,
    726,
    18,
    266,
    11,
    114,
    292,
    272,
    286,
    391,
    57,
    56,
    7,
    227,
    26,
    156,
    92,
    287,
    52,
    321,
    109,
    228,
    39,
    167,
    152,
    206,
    636,
    264,
    693,
    315,
    239,
    96,
    123,
    328,
    131,
    120,
    133,
    74,
    342,
    178,
    0,
    290,
    65,
    110,
    120,
    88,
    197,
    78,
    115,
    26,
    266,
    22,
    447,
    35,
    169,
    435,
    220,
    12,
    189,
    14,
    134,
    165,
    243,
    50,
    413,
    277,
    247,
    233,
    250,
    157,
    61,
    169,
    143,
    614,
    127,
    128,
    375,
    331,
    199,
    97,
    340,
    334,
    630,
    334,
    330,
    266,
    99,
    62,
    496,
    111,
    293,
    75,
    115,
    137,
    155,
    395,
    278,
    163,
    49,
    269,
    89,
    364,
    42,
    221,
    231,
    1,
    83,
    291,
    460,
    71,
    132,
    85,
    150,
    191,
    70,
    90,
    86,
    4,
    12,
    85,
    18,
    433,
    119,
    223,
    50,
    11,
    149,
    356,
    325,
    76,
    383,
    349,
    200,
    390,
    16,
    137,
    389,
    193,
    55,
    105,
    20,
    20,
    61,
    20,
    34,
    67,
    45,
    224,
    28,
    363,
    296,
    376,
    178,
    39,
    215,
    289,
    49,
    13,
    167,
    188,
    22,
    161,
    18,
    1,
    20,
    209,
    105,
    61,
    127,
    92,
    83,
    410,
    308,
    393,
    116,
    21,
    382,
    278,
    201,
    16,
    53,
    140,
    358,
    98,
    650,
    9,
    40,
    14,
    215,
    115,
    122,
    96,
    32,
    292,
    5,
    302,
    374,
    95,
    286,
    195,
    70,
    309,
    1,
    374,
    539,
    122,
    297,
    326,
    256,
    506,
    310,
    174,
    80,
    44,
    107,
    391,
    232,
    144,
    333,
    97,
    64,
    151,
    287,
    48,
    81,
    289,
    240,
    258,
    233,
    25,
    177,
    115,
    212,
    223,
    49,
    2,
    71,
    232,
    145,
    91,
    350,
    155,
    228,
    265,
    364,
    352,
    27,
    58,
    545,
    117,
    274,
    296,
    266,
    48,
    77,
    585,
    39,
    161,
    482,
    120,
    54,
    342,
    6,
    140,
    1,
    106,
    71,
    135,
    314,
    562,
    533,
    314,
    104,
    39,
    113,
    302,
    229,
    311,
    324,
    330,
    382,
    342,
    52,
    17,
    510,
    38,
    262,
    24,
    56,
    164,
    82,
    380,
    367,
    56,
    346,
    6,
    359,
    201,
    48,
    40,
    56,
    229,
    223,
    357,
    280,
    77,
    76,
    325,
    446,
    147,
    61,
    325,
    122,
    83,
    462,
    21,
    124,
    103,
    23,
    71,
    38,
    195,
    217,
    338,
    109,
    132,
    223,
    0,
    277,
    53,
    510,
    359,
    87,
    115,
    189,
    11,
    184,
    824,
    58,
    219,
    158,
    167,
    403,
    11,
    117,
    304,
    67,
    180,
    137,
    733,
    160,
    109,
    71,
    92,
    200,
    45,
    61,
    15,
    129,
    229,
    190,
    358,
    220,
    466,
    397,
    262,
    3,
    39,
    315,
    268,
    466,
    31,
    65,
    21,
    198,
    188,
    23,
    23,
    156,
    169,
    601,
    375,
    134,
    107,
    318,
    574,
    165,
    510,
    291,
    219,
    238,
    259,
    54,
    15,
    221,
    13,
    152,
    210,
    177,
    35,
    573,
    373,
    244,
    83,
    561,
    261,
    56,
    79,
    392,
    41,
    23,
    27,
    224,
    46,
    181,
    19,
    344,
    226,
    187,
    142,
    382,
    427,
    186,
    125,
    120,
    375,
    69,
    173,
    125,
    197,
    384,
    79,
    433,
    61,
    149,
    242,
    334,
    693,
    55,
    91,
    119,
    153,
    326,
    186,
    167,
    515,
    625,
    10,
    286,
    36,
    14,
    309,
    293,
    47,
    429,
    325,
    189,
    15,
    157,
    151,
    21,
    445,
    126,
    419,
    248,
    128,
    6,
    46,
    555,
    211,
    113,
    156,
    181,
    728,
    132,
    30,
    213,
    308,
    377,
    188,
    379,
    393,
    48,
    129,
    61,
    26,
    416,
    443,
    539,
    196,
    212,
    148,
    491,
    556,
    197,
    198,
    483,
    33,
    688,
    502,
    366,
    312,
    21,
    414,
    133,
    145,
    117,
    555,
    282,
    424,
    260,
    510,
    543,
    82,
    143,
    379,
    455,
    104,
    302,
    162,
    163,
    47,
    245,
    443,
    251,
    184,
    96,
    153,
    419,
    154,
    146,
    471,
    350,
    26,
    341,
    211,
    197,
    104,
    16,
    3,
    72,
    192,
    369,
    88,
    36,
    319,
    186,
    38,
    28,
    231,
    177,
    257,
    163,
    432,
    131,
    81,
    94,
    92,
    67,
    412,
    207,
    752,
    382,
    253,
    177,
    58,
    35,
    84,
    119,
    369,
    107,
    239,
    276,
    6,
    378,
    131,
    204,
    10,
    409,
    20,
    510,
    624,
    203,
    20,
    549,
    280,
    292,
    273,
    597,
    632,
    14,
    353,
    134,
    124,
    18,
    50,
    448,
    171,
    248,
    2,
    318,
    206,
    476,
    49,
    592,
    340,
    31,
    182,
    18,
    88,
    287,
    470,
    132,
    130,
    180,
    380,
    426,
    88,
    89,
    176,
    2,
    180,
    372,
    155,
    96,
    3,
    249,
    241,
    340,
    112,
    414,
    207,
    437,
    231,
    95,
    288,
    361,
    221,
    142,
    189,
    264,
    14,
    471,
    54,
    67,
    12,
    18,
    51,
    27,
    0,
    142,
    303,
    50,
    134,
    191,
    632,
    74,
    147,
    131,
    357,
    156,
    85,
    439,
    153,
    129,
    5,
    348,
    51,
    64,
    191,
    23,
    352,
    177,
    349,
    36,
    617,
    57,
    232,
    181,
    46,
    19,
    12,
    220,
    334,
    234,
    188,
    74,
    13,
    261,
    74,
    34,
    5,
    258,
    110,
    83,
    110,
    186,
    298,
    10,
    201,
    187,
    31,
    18,
    233,
    114,
    21,
    117,
    155,
    257,
    123,
    102,
    133,
    357,
    310,
    143,
    20,
    280,
    87,
    273,
    117,
    220,
    437,
    18,
    734,
    114,
    266,
    217,
    230,
    58,
    136,
    450,
    75,
    376,
    30,
    20,
    419,
    59,
    295,
    137,
    77,
    22,
    183,
    378,
    352,
    276,
    249,
    321,
    557,
    240,
    19,
    241,
    200,
    49,
    47,
    194,
    266,
    192,
    142,
    267,
    142,
    40,
    496,
    396,
    170,
    241,
    269,
    3,
    109,
    280,
    266,
    534,
    372,
    197,
    256,
    242,
    313,
    47,
    96,
    95,
    382,
    303,
    107,
    323,
    339,
    596,
    190,
    79,
    348,
    51,
    251,
    93,
    26,
    14,
    175,
    173,
    330,
    324,
    96,
    40,
    124,
    153,
    29,
    190,
    78,
    467,
    249,
    7,
    289,
    128,
    206,
    203,
    140,
    227,
    121,
    362,
    231,
    213,
    61,
    32,
    172,
    29,
    210,
    205,
    91,
    178,
    187,
    180,
    299,
    275,
    6,
    78,
    136,
    176,
    335,
    102,
    483,
    23,
    50,
    72,
    167,
    560,
    93,
    181,
    77,
    453,
    78,
    84,
    462,
    37,
    105,
    301,
    444,
    18,
    243,
    288,
    255,
    249,
    223,
    124,
    175,
    7,
    309,
    63,
    72,
    180,
    25,
    209,
    17,
    328,
    5,
    283,
    5,
    134,
    483,
    641,
    164,
    194,
    362,
    182,
    162,
    26,
    30,
    19,
    325,
    221,
    325,
    566,
    54,
    439,
    283,
    131,
    401,
    198,
    71,
    513,
    99,
    160,
    68,
    18,
    286,
    384,
    13,
    222,
    304,
    156,
    279,
    97,
    140,
    211,
    614,
    242,
    187,
    507,
    24,
    9,
    32,
    351,
    62,
    38,
    62,
    292,
    51,
    251,
    275,
    47,
    141,
    52,
    64,
    311,
    105,
    82,
    29,
    299,
    112,
    22,
    188,
    224,
    156,
    42,
    10,
    230,
    376,
    252,
    115,
    212,
    432,
    244,
    150,
    346,
    664,
    208,
    267,
    16,
    172,
    172,
    45,
    437,
    150,
    105,
    153,
    158,
    545,
    27,
    237,
    19,
    144,
    36,
    106,
    277,
    47,
    756,
    101,
    555,
    12,
    51,
    2,
    12,
    394,
    950,
    200,
    103,
    249,
    162,
    413,
    205,
    138,
    354,
    10,
    276,
    31,
    104,
    233,
    10,
    469,
    132,
    166,
    170,
    304,
    159,
    445,
    293,
    6,
    535,
    638,
    219,
    291,
    83,
    162,
    227,
    212,
    12,
    24,
    147,
    113,
    82,
    340,
    344,
    408,
    278,
    8,
    80,
    137,
    70,
    158,
    176,
    447,
    251,
    23,
    148,
    201,
    46,
    64,
    7,
    4,
    27,
    731,
    110,
    166,
    445,
    30,
    336,
    120,
    135,
    62,
    75,
    317,
    122,
    189,
    73,
    23,
    329,
    264,
    325,
    108,
    25,
    565,
    41,
    42,
    58,
    19,
    131,
    316,
    170,
    247,
    503,
    208,
    118,
    258,
    524,
    114,
    453,
    686,
    112,
    359,
    173,
    425,
    317,
    38,
    3,
    59,
    360,
    221,
    241,
    26,
    26,
    101,
    271,
    146,
    269,
    182,
    219,
    225,
    341,
    99,
    211,
    79,
    48,
    676,
    107,
    10,
    127,
    67,
    272,
    62,
    165,
    360,
    103,
    15,
    302,
    203,
    496,
    140,
    222,
    326,
    26,
    248,
    75,
    279,
    359,
    418,
    204,
    159,
    242,
    8,
    347,
    22,
    279,
    163,
    256,
    120,
    114,
    115,
    612,
    322,
    403,
    8,
    171,
    129,
    99,
    621,
    217,
    53,
    198,
    36,
    354,
    232,
    71,
    244,
    89,
    262,
    459,
    319,
    62,
    171,
    168,
    80,
    24,
    893,
    223,
    140,
    135,
    7,
    86,
    293,
    45,
    326,
    207,
    227,
    13,
    206,
    363,
    297,
    20,
    122,
    193,
    575,
    261,
    1,
    633,
    315,
    315,
    246,
    126,
    211,
    118,
    656,
    5,
    268,
    69,
    102,
    86,
    274,
    7,
    229,
    399,
    61,
    276,
    119,
    453,
    270,
    87,
    332,
    155,
    110,
    88,
    47,
    23,
    66,
    345,
    476,
    7,
    68,
    3,
    389,
    516,
    174,
    50,
    245,
    215,
    308,
    47,
    91,
    8,
    204,
    264,
    139,
    79,
    103,
    507,
    356,
    327,
    279,
    125,
    2,
    585,
    380,
    168,
    199,
    548,
    44,
    152,
    255,
    66,
    104,
    263,
    268,
    209,
    444,
    29,
    345,
    33,
    298,
    246,
    193,
    65,
    69,
    59,
    324,
    664,
    189,
    93,
    901,
    292,
    153,
    443,
    233,
    184,
    83,
    42,
    404,
    280,
    375,
    586,
    66,
    55,
    64,
    296,
    324,
    67,
    30,
    18,
    96,
    508,
    217,
    318,
    173,
    96,
    99,
    976,
    766,
    743,
    280,
    76,
    420,
    61,
    116,
    206,
    446,
    117,
    347,
    615,
    151,
    112,
    241,
    32,
    254,
    178,
    15,
    44,
    7,
    250,
    44,
    99,
    130,
    192,
    172,
    38,
    547,
    272,
    354,
    280,
    105,
    269,
    295,
    36,
    1,
    376,
    199,
    308,
    137,
    73,
    79,
    33,
    277,
    326,
    77,
    48,
    55,
    232,
    69,
    407,
    212,
    149,
    2,
    177,
    127,
    338,
    102,
    47,
    281,
    175,
    461,
    248,
    142,
    230,
    25,
    40,
    38,
    444,
    258,
    84,
    246,
    301,
    243,
    47,
    30,
    287,
    372,
    49,
    59,
    103,
    142,
    174,
    194,
    80,
    284,
    208,
    323,
    4,
    444,
    218,
    45,
    196,
    133,
    94,
    373,
    140,
    58,
    334,
    342,
    946,
    5,
    34,
    195,
    313,
    112,
    27,
    318,
    125,
    8,
    70,
    102,
    140,
    101,
    391,
    296,
    104,
    288,
    301,
    269,
    8,
    105,
    3,
    112,
    154,
    183,
    156,
    96,
    405,
    96,
    179,
    23,
    128,
    197,
    54,
    105,
    111,
    119,
    302,
    420,
    255,
    169,
    137,
    222,
    122,
    312,
    106,
    304,
    27,
    184,
    252,
    269,
    1,
    268,
    185,
    12,
    14,
    521,
    349,
    18,
    96,
    127,
    4,
    104,
    644,
    150,
    643,
    86,
    100,
    22,
    236,
    53,
    216,
    113,
    322,
    96,
    156,
    213,
    394,
    57,
    58,
    12,
    91,
    321,
    241,
    44,
    53,
    209,
    159,
    244,
    317,
    52,
    41,
    286,
    586,
    508,
    21,
    329,
    295,
    511,
    33,
    142,
    763,
    270,
    24,
    559,
    477,
    299,
    11,
    150,
    619,
    394,
    136,
    141,
    330,
    17,
    333,
    42,
    5,
    376,
    424,
    546,
    16,
    215,
    562,
    81,
    159,
    532,
    119,
    201,
    380,
    26,
    17,
    230,
    32,
    392,
    130,
    10,
    141,
    229,
    264,
    239,
    122,
    194,
    126,
    114,
    527,
    409,
    142,
    80,
    457,
    679,
    167,
    83,
    213,
    328,
    834,
    21,
    120,
    54,
    167,
    351,
    190,
    57,
    92,
    111,
    111,
    110,
    197,
    86,
    142,
    47,
    39,
    136,
    263,
    15,
    319,
    109,
    17,
    41,
    147,
    90,
    185,
    226,
    170,
    50,
    29,
    259,
    157,
    502,
    113,
    43,
    164,
    77,
    118,
    168,
    50,
    441,
    118,
    274,
    213,
    143,
    208,
    262,
    63,
    308,
    99,
    32,
    121,
    172,
    229,
    129,
    199,
    135,
    172,
    62,
    422,
    399,
    236,
    159,
    108,
    223,
    63,
    232,
    109,
    59,
    125,
    117,
    255,
    87,
    185,
    181,
    278,
    78,
    79,
    22,
    317,
    448,
    225,
    78,
    137,
    62,
    159,
    332,
    35,
    151,
    99,
    108,
    410,
    9,
    27,
    73,
    209,
    177,
    114,
    18,
    318,
    71,
    142,
    254,
    53,
    476,
    129,
    79,
    288,
    279,
    143,
    63,
    285,
    361,
    414,
    380,
    70,
    205,
    171,
    43,
    311,
    100,
    723,
    244,
    121,
    152,
    25,
    517,
    707,
    73,
    69,
    722,
    270,
    356,
    515,
    214,
    468,
    642,
    324,
    51,
    3,
    83,
    93,
    48,
    312,
    408,
    559,
    73,
    169,
    239,
    210,
    99,
    64,
    36,
    195,
    253,
    426,
    188,
    127,
    665,
    200,
    110,
    66,
    343,
    9,
    207,
    542,
    316,
    164,
    25,
    381,
    381,
    242,
    186,
    219,
    39,
    230,
    125,
    548,
    4,
    372,
    167,
    77,
    179,
    99,
    242,
    31,
    535,
    150,
    342,
    292,
    172,
    188,
    389,
    105,
    127,
    36,
    173,
    139,
    80,
    80,
    109,
    63,
    88,
    224,
    642,
    154,
    61,
    206,
    49,
    31,
    382,
    237,
    326,
    42,
    166,
    34,
    313,
    187,
    219,
    443,
    47,
    22,
    110,
    20,
    144,
    123,
    510,
    349,
    603,
    364,
    314,
    279,
    5,
    30,
    115,
    414,
    79,
    322,
    222,
    171,
    332,
    130,
    14,
    452,
    29,
    4,
    201,
    207,
    113,
    22,
    27,
    551,
    127,
    156,
    296,
    165,
    9,
    30,
    148,
    314,
    195,
    89,
    328,
    513,
    63,
    98,
    150,
    39,
    293,
    491,
    521,
    12,
    268,
    84,
    346,
    241,
    110,
    224,
    62,
    206,
    23,
    349,
    236,
    158,
    246,
    291,
    59,
    188,
    257,
    348,
    175,
    34,
    256,
    370,
    176,
    237,
    252,
    133,
    6,
    218,
    390,
    41,
    41,
    333,
    14,
    542,
    82,
    341,
    517,
    143,
    156,
    255,
    422,
    202,
    431,
    92,
    12,
    240,
    616,
    204,
    401,
    163,
    185,
    151,
    195,
    219,
    169,
    98,
    369,
    245,
    107,
    69,
    302,
    65,
    318,
    190,
    108,
    292,
    225,
    463,
    183,
    197,
    197,
    375,
    47,
    114,
    349,
    402,
    343,
    63,
    9,
    300,
    364,
    127,
    823,
    334,
    283,
    243,
    45,
    150,
    471,
    274,
    224,
    244,
    8,
    37,
    296,
    357,
    71,
    254,
    250,
    288,
    205,
    117,
    161,
    10,
    24,
    227,
    74,
    236,
    32,
    425,
    114,
    92,
    87,
    336,
    9,
    97,
    98,
    324,
    88,
    83,
    12,
    139,
    561,
    9,
    10,
    26,
    193,
    171,
    197,
    197,
    153,
    117,
    233,
    68,
    71,
    199,
    108,
    153,
    308,
    73,
    396,
    265,
    49,
    115,
    66,
    11,
    179,
    305,
    94,
    484,
    692,
    170,
    302,
    62,
    149,
    272,
    127,
    408,
    61,
    176,
    116,
    180,
    11,
    232,
    21,
    206,
    857,
    129,
    128,
    138,
    389,
    520,
    238,
    123,
    26,
    219,
    1,
    468,
    28,
    139,
    218,
    257,
    211,
    114,
    30,
    151,
    26,
    324,
    115,
    304,
    196,
    135,
    295,
    76,
    207,
    106,
    166,
    805,
    233,
    284,
    41,
    278,
    7,
    113,
    305,
    95,
    388,
    218,
    418,
    49,
    94,
    118,
    41,
    14,
    400,
    142,
    31,
    125,
    303,
    23,
    55,
    148,
    436,
    200,
    426,
    1,
    252,
    281,
    5,
    186,
    413,
    372,
    76,
    308,

In [7]:
import os

CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"

NOTEBOOK_DIR = os.path.join(
    CHECKPOINT_ROOT,
    "notebook_progress"
)

print("Notebook progress files:\n")

for file in sorted(os.listdir(NOTEBOOK_DIR)):
    print(file)

Notebook progress files:

cell01.py
cell02.py
cell03.py

In [8]:
for file in ["cell01.py", "cell02.py", "cell03.py"]:
    path = os.path.join(NOTEBOOK_DIR, file)

    print("\n" + "="*80)
    print(file)
    print("="*80)

    with open(path, "r", encoding="utf-8") as f:
        print(f.read())

================================================================================
cell01.py
================================================================================
import os
import re
import sys
import gc
import csv
import json
import time
import sqlite3
import tempfile
import unicodedata
import statistics
from pathlib import Path
from collections import defaultdict
from functools import lru_cache
from datetime import datetime, timezone

import numpy as np
import pandas as pd

print("=" * 70)
print("AMAZON ML CHALLENGE -- BUSINESS ENTITY RESOLUTION")
print("Production pipeline -- Phase 2")
print("=" * 70)
print(f"Python      : {sys.version.split()[0]}")
print(f"Pandas      : {pd.__version__}")
print(f"NumPy       : {np.__version__}")
print(f"Run started : {datetime.now(timezone.utc).isoformat()}")

# ============================================================
# CONFIGURATION
# ============================================================
# SMOKE_TEST=True is the ONLY sanctioned use of a small/10K-style
# dataset. It does not change any logic -- it only shrinks the
# row limits and, if a train_10k-style directory is discoverable,
# prefers it for the TRAIN side (there is no small equivalent for
# TEST, so TEST simply gets a small S1 row cap instead).
#
# Flip this to False (the default) for the real, full-scale run.

SMOKE_TEST = False

CONFIG = {
    # ---- scale controls (None = full data, the production setting) ----
    "smoke_test": SMOKE_TEST,
    "train_index_limit": 20_000 if SMOKE_TEST else None,   # rows of S2/S3 to index
    "train_s1_limit": 2_000 if SMOKE_TEST else None,       # rows of train S1 to process
    "test_index_limit": 20_000 if SMOKE_TEST else None,
    "test_s1_limit": 2_000 if SMOKE_TEST else None,

    # ---- sharding / checkpointing ----
    "shard_size": 5_000 if SMOKE_TEST else 100_000,        # S1 rows per checkpointed shard

    # ---- modeling ----
    "random_seed": 42,
    "val_fraction": 0.2,          # fraction of S1 entities held out for validation
    "use_gpu": True,               # only affects the model stage; ignored if no GPU present

    # ---- backends ----
    "index_backend": "sqlite",     # "sqlite" is mandatory at full scale; "memory" only for tiny smoke tests
}

WORK = Path("/kaggle/working/amazon_ml_solution")
DIRS = {
    "work": WORK,
    "idx_train": WORK / "index_train",
    "idx_test": WORK / "index_test",
    "shards_train": WORK / "shards_train",
    "shards_test": WORK / "shards_test",
    "checkpoints": WORK / "checkpoints",
    "models": WORK / "models",
    "output": WORK / "output",
}

for name, path in DIRS.items():
    path.mkdir(parents=True, exist_ok=True)

print("\nWorking directories:")
for name, path in DIRS.items():
    print(f"  {name:14s}: {path}")

print("\nConfiguration:")
for k, v in CONFIG.items():
    print(f"  {k:20s}: {v}")

RANDOM_SEED = CONFIG["random_seed"]
np.random.seed(RANDOM_SEED)

EXPECTED_SOURCE_COLUMNS = ["entity_id", "business_name", "business_address", "country"]
EXPECTED_GT_COLUMNS = ["source1_entity_id", "matched_entity_ids"]


================================================================================
cell02.py
================================================================================
# ============================================================
# CELL 2 -- Install / detect optional dependencies
# ============================================================
# The pipeline must work correctly even with NO internet access
# (Kaggle competition kernels often run with internet disabled).
# Every optional dependency below has a pure-stdlib or sklearn
# fallback, so a failed install never breaks the notebook -- it
# only means a slower code path is used, and that is printed
# clearly so it's never a silent surprise.

def _try_pip_install(package):
    try:
        import subprocess
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", package],
            capture_output=True, text=True, timeout=180,
        )
        return result.returncode == 0
    except Exception as e:
        print(f"  [install] {package}: skipped ({e})")
        return False


# ---- rapidfuzz: fast C-accelerated string similarity ----
try:
    import rapidfuzz  # noqa: F401
    HAS_RAPIDFUZZ = True
except ImportError:
    print("[deps] rapidfuzz not found -- attempting install...")
    if _try_pip_install("rapidfuzz"):
        try:
            import rapidfuzz  # noqa: F401
            HAS_RAPIDFUZZ = True
        except ImportError:
            HAS_RAPIDFUZZ = False
    else:
        HAS_RAPIDFUZZ = False

if HAS_RAPIDFUZZ:
    from rapidfuzz.fuzz import ratio as _rapidfuzz_ratio
    print("[deps] rapidfuzz          : available (fast string similarity)")
else:
    print("[deps] rapidfuzz          : NOT available -- falling back to pure-Python "
          "difflib for similarity (slower, correctness unaffected)")

# ---- lightgbm: optional, faster/stronger GBM than sklearn's ----
try:
    import lightgbm as lgb  # noqa: F401
    HAS_LIGHTGBM = True
except ImportError:
    print("[deps] lightgbm not found -- attempting install...")
    if _try_pip_install("lightgbm"):
        try:
            import lightgbm as lgb  # noqa: F401
            HAS_LIGHTGBM = True
        except ImportError:
            HAS_LIGHTGBM = False
    else:
        HAS_LIGHTGBM = False

print(f"[deps] lightgbm           : {'available' if HAS_LIGHTGBM else 'NOT available -- will use sklearn HistGradientBoostingClassifier'}")

# ---- sklearn: required, ships with Kaggle images ----
import sklearn
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import precision_score, recall_score, fbeta_score
print(f"[deps] scikit-learn       : {sklearn.__version__}")

# ---- GPU detection (informational only -- see CELL 17 for how/if it's used) ----
GPU_AVAILABLE = False
if CONFIG["use_gpu"]:
    try:
        import subprocess
        result = subprocess.run(["nvidia-smi"], capture_output=True, text=True, timeout=10)
        GPU_AVAILABLE = (result.returncode == 0)
    except Exception:
        GPU_AVAILABLE = False

print(f"[deps] GPU detected       : {GPU_AVAILABLE}")
print(
    "[deps] Note: blocking, SQLite indexing and string normalization are "
    "CPU/I/O-bound and are NOT moved to GPU -- a GPU only helps (optionally) "
    "at the model-training stage, and only if a GPU-capable booster is "
    "available. The pipeline is fully correct with GPU_AVAILABLE=False."
)


================================================================================
cell03.py
================================================================================
# ============================================================
# CELL 3 -- Locate Kaggle dataset paths (never hard-coded)
# ============================================================
# Walks /kaggle/input looking for the directories that contain
# the train/test files, instead of hard-coding a specific dataset
# slug or a local Windows path. This is what makes the notebook
# survive the dataset being re-attached under a different name or
# version, and makes it runnable outside Kaggle (e.g. this audit
# sandbox) by falling back to FALLBACK_SEARCH_ROOTS.

TRAIN_REQUIRED = {"train_source1.tsv", "train_source2.tsv", "train_source3.tsv", "train_ground_truth.tsv"}
TEST_REQUIRED = {"test_source1.tsv", "test_source2.tsv", "test_source3.tsv"}

# Extra roots to search besides /kaggle/input, so the same notebook
# also runs somewhere that isn't Kaggle (e.g. for local debugging).
FALLBACK_SEARCH_ROOTS = ["/kaggle/input", "/mnt/user-data/uploads", os.getcwd()]

TRAIN_10K_HINT = {"train_source1.tsv", "train_source2.tsv", "train_source3.tsv", "train_ground_truth.tsv"}


def _find_dir_containing(required_files, search_roots, prefer_substring=None):
    """
    Walks each search root and returns the first directory that
    contains every file in `required_files`. If prefer_substring is
    given and multiple directories match, the one whose path
    contains that substring is preferred (used to let SMOKE_TEST
    prefer a train_10k-style directory when one exists).
    """
    candidates = []

    for root in search_roots:
        root_path = Path(root)
        if not root_path.exists():
            continue
        for dirpath, _dirnames, filenames in os.walk(root_path):
            filenames = set(filenames)
            if required_files.issubset(filenames):
                candidates.append(dirpath)

    if not candidates:
        return None

    if prefer_substring:
        preferred = [c for c in candidates if prefer_substring in c]
        if preferred:
            return sorted(preferred)[0]

    return sorted(candidates)[0]


def discover_dataset_paths(smoke_test=False):

    train_prefer = "train_10k" if smoke_test else None

    train_dir = _find_dir_containing(TRAIN_REQUIRED, FALLBACK_SEARCH_ROOTS, prefer_substring=train_prefer)
    test_dir = _find_dir_containing(TEST_REQUIRED, FALLBACK_SEARCH_ROOTS)

    if train_dir is None:
        raise FileNotFoundError(
            "Could not find a directory containing all of "
            f"{sorted(TRAIN_REQUIRED)} under any of {FALLBACK_SEARCH_ROOTS}. "
            "Attach the competition dataset to this notebook (Add Data) and re-run."
        )

    paths = {
        "train_s1": os.path.join(train_dir, "train_source1.tsv"),
        "train_s2": os.path.join(train_dir, "train_source2.tsv"),
        "train_s3": os.path.join(train_dir, "train_source3.tsv"),
        "train_gt": os.path.join(train_dir, "train_ground_truth.tsv"),
    }

    if test_dir is not None:
        paths.update({
            "test_s1": os.path.join(test_dir, "test_source1.tsv"),
            "test_s2": os.path.join(test_dir, "test_source2.tsv"),
            "test_s3": os.path.join(test_dir, "test_source3.tsv"),
        })
    else:
        print(
            "[paths] WARNING: no directory with all of "
            f"{sorted(TEST_REQUIRED)} was found -- test-set cells (20-26) "
            "will be skipped until the test data is attached."
        )

    return paths


DATA_PATHS = discover_dataset_paths(smoke_test=CONFIG["smoke_test"])

print("Discovered dataset paths:")
for k, v in DATA_PATHS.items():
    exists = os.path.exists(v)
    print(f"  {k:10s}: {v}  [{'OK' if exists else 'MISSING'}]")

HAS_TEST_DATA = "test_s1" in DATA_PATHS

In [9]:
exec(open(
    "/kaggle/input/datasets/tejasweerajput/amazon-v3/"
    "notebook_progress/cell01.py"
).read())

======================================================================
AMAZON ML CHALLENGE -- BUSINESS ENTITY RESOLUTION
Production pipeline -- Phase 2
======================================================================
Python      : 3.12.13
Pandas      : 2.3.3
NumPy       : 2.0.2
Run started : 2026-09-27T06:09:58.362549+00:00

Working directories:
  work          : /kaggle/working/amazon_ml_solution
  idx_train     : /kaggle/working/amazon_ml_solution/index_train
  idx_test      : /kaggle/working/amazon_ml_solution/index_test
  shards_train  : /kaggle/working/amazon_ml_solution/shards_train
  shards_test   : /kaggle/working/amazon_ml_solution/shards_test
  checkpoints   : /kaggle/working/amazon_ml_solution/checkpoints
  models        : /kaggle/working/amazon_ml_solution/models
  output        : /kaggle/working/amazon_ml_solution/output

Configuration:
  smoke_test          : False
  train_index_limit   : None
  train_s1_limit      : None
  test_index_limit    : None
  test_s1_limit       : None
  shard_size          : 100000
  random_seed         : 42
  val_fraction        : 0.2
  use_gpu             : True
  index_backend       : sqlite

In [10]:
exec(open(
    "/kaggle/input/datasets/tejasweerajput/amazon-v3/"
    "notebook_progress/cell02.py"
).read())

[deps] rapidfuzz not found -- attempting install...
[deps] rapidfuzz          : available (fast string similarity)
[deps] lightgbm           : available
[deps] scikit-learn       : 1.6.1
[deps] GPU detected       : True
[deps] Note: blocking, SQLite indexing and string normalization are CPU/I/O-bound and are NOT moved to GPU -- a GPU only helps (optionally) at the model-training stage, and only if a GPU-capable booster is available. The pipeline is fully correct with GPU_AVAILABLE=False.

In [11]:
exec(open(
    "/kaggle/input/datasets/tejasweerajput/amazon-v3/"
    "notebook_progress/cell03.py"
).read())

Discovered dataset paths:
  train_s1  : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source1.tsv  [OK]
  train_s2  : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source2.tsv  [OK]
  train_s3  : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv  [OK]
  train_gt  : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_ground_truth.tsv  [OK]
  test_s1   : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source1.tsv  [OK]
  test_s2   : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv  [OK]
  test_s3   : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source3.tsv  [OK]

In [12]:
import os

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

for f in sorted(os.listdir(MODULES)):
    if f.endswith(".py"):
        print(f)

blocking.py
candidates.py
checkpoint.py
data_loader.py
features.py
indexer.py
labels.py
normalize.py
similarity.py

In [14]:
import sys
import os

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

# Put checkpoint modules first on Python's import path
sys.path.insert(0, MODULES)

print("Modules path exists:", os.path.exists(MODULES))
print("indexer.py exists:", os.path.exists(os.path.join(MODULES, "indexer.py")))

from indexer import build_index

print("SUCCESS: indexer imported.")

Modules path exists: True
indexer.py exists: True
SUCCESS: indexer imported.

In [17]:
import os
import sys

# Checkpoint modules
MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

from indexer import build_index

# Full S2 training file
train_s2 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source2.tsv"
)

# Writable location for the SQLite index
S2_INDEX = (
    "/kaggle/working/amazon_ml_solution/"
    "index_train/s2_full.sqlite"
)

os.makedirs(os.path.dirname(S2_INDEX), exist_ok=True)

print("S2 exists:", os.path.exists(train_s2))
print("S2 path:", train_s2)
print("Index path:", S2_INDEX)

assert os.path.exists(train_s2), "S2 training file not found!"

build_index(
    train_s2,
    "S2",
    limit=None,
    backend="sqlite",
    db_path=S2_INDEX
)

S2 exists: True
S2 path: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source2.tsv
Index path: /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite
[indexer] Building sqlite index for S2 from: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source2.tsv
[indexer]   indexed 500,000 S2 records...
[indexer]   indexed 1,000,000 S2 records...
[indexer]   indexed 1,500,000 S2 records...
[indexer]   indexed 2,000,000 S2 records...
[indexer]   indexed 2,500,000 S2 records...
[indexer]   indexed 3,000,000 S2 records...
[indexer]   indexed 3,500,000 S2 records...
[indexer]   indexed 4,000,000 S2 records...
[indexer]   indexed 4,500,000 S2 records...
[indexer]   indexed 5,000,000 S2 records...
[indexer] Finished S2: 5,034,616 records, 26,696,614 distinct blocking keys.

In [19]:
import os
import re
import sys

CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"
MODULES = os.path.join(CHECKPOINT_ROOT, "modules")
MEASUREMENTS = os.path.join(CHECKPOINT_ROOT, "measurements")

TRAIN_GT = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_ground_truth.tsv"
)

SOURCE_SCRIPT = os.path.join(
    MEASUREMENTS,
    "measure_full_single_source.py"
)

PATCHED_SCRIPT = "/kaggle/working/measure_full_single_source_kaggle.py"

# Read original measurement script
with open(SOURCE_SCRIPT, "r", encoding="utf-8") as f:
    code = f.read()

# Replace the old sandbox ground-truth path with the Kaggle path
old_path = "/mnt/user-data/uploads/train_ground_truth.tsv"

if old_path not in code:
    print("WARNING: old path was not found in script.")
    print("We will inspect the relevant path references instead.")
    for line in code.splitlines():
        if "ground_truth" in line or "/mnt/user-data" in line:
            print(line)
else:
    code = code.replace(old_path, TRAIN_GT)

# Save patched copy in writable /kaggle/working
with open(PATCHED_SCRIPT, "w", encoding="utf-8") as f:
    f.write(code)

print("Patched script:", PATCHED_SCRIPT)
print("Ground truth exists:", os.path.exists(TRAIN_GT))

Patched script: /kaggle/working/measure_full_single_source_kaggle.py
Ground truth exists: True

In [21]:
import os

CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"
MEASUREMENTS = os.path.join(CHECKPOINT_ROOT, "measurements")

SOURCE_SCRIPT = os.path.join(
    MEASUREMENTS,
    "measure_full_single_source.py"
)

PATCHED_SCRIPT = "/kaggle/working/measure_full_single_source_kaggle.py"

TRAIN_S1 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source1.tsv"
)

TRAIN_GT = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_ground_truth.tsv"
)

with open(SOURCE_SCRIPT, "r", encoding="utf-8") as f:
    code = f.read()

# Replace all sandbox-specific paths used by this measurement script
replacements = {
    "/mnt/user-data/uploads/train_source1.tsv": TRAIN_S1,
    "/mnt/user-data/uploads/train_ground_truth.tsv": TRAIN_GT,
}

for old, new in replacements.items():
    code = code.replace(old, new)

with open(PATCHED_SCRIPT, "w", encoding="utf-8") as f:
    f.write(code)

print("PATCHED SCRIPT READY")
print("S1 exists :", os.path.exists(TRAIN_S1))
print("GT exists :", os.path.exists(TRAIN_GT))

# Verify no old paths remain
for old in replacements:
    print(
        old,
        "remaining:",
        old in code
    )

PATCHED SCRIPT READY
S1 exists : True
GT exists : True
/mnt/user-data/uploads/train_source1.tsv remaining: False
/mnt/user-data/uploads/train_ground_truth.tsv remaining: False

In [22]:
import sys

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

sys.argv = [
    "measure_full_single_source.py",
    "S2",
    "/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite",
    "/kaggle/working/amazon_ml_solution/checkpoints/recall_s2.json",
    "30000"
]

exec(
    open(
        "/kaggle/working/measure_full_single_source_kaggle.py",
        encoding="utf-8"
    ).read()
)

[S2] resuming at sample_index=0 (0/30,000)
[S2] ground truth loaded: 2,206,821 rows in 11.7s
[S2] processed 500/30,000 recall_so_far=0.9622 rate=145.6 rows/s elapsed=3s
[S2] processed 1,000/30,000 recall_so_far=0.9590 rate=144.6 rows/s elapsed=7s
[S2] processed 1,500/30,000 recall_so_far=0.9598 rate=145.4 rows/s elapsed=10s
[S2] processed 2,000/30,000 recall_so_far=0.9590 rate=146.1 rows/s elapsed=14s
[S2] processed 2,500/30,000 recall_so_far=0.9582 rate=146.4 rows/s elapsed=17s
[S2] processed 3,000/30,000 recall_so_far=0.9593 rate=147.6 rows/s elapsed=20s
[S2] processed 3,500/30,000 recall_so_far=0.9583 rate=148.1 rows/s elapsed=24s
[S2] processed 4,000/30,000 recall_so_far=0.9582 rate=138.8 rows/s elapsed=29s
[S2] processed 4,500/30,000 recall_so_far=0.9584 rate=139.9 rows/s elapsed=32s
[S2] processed 5,000/30,000 recall_so_far=0.9589 rate=140.7 rows/s elapsed=36s
[S2] processed 5,500/30,000 recall_so_far=0.9586 rate=141.4 rows/s elapsed=39s
[S2] processed 6,000/30,000 recall_so_far=0.9588 rate=142.1 rows/s elapsed=42s
[S2] processed 6,500/30,000 recall_so_far=0.9592 rate=142.7 rows/s elapsed=46s
[S2] processed 7,000/30,000 recall_so_far=0.9590 rate=142.8 rows/s elapsed=49s
[S2] processed 7,500/30,000 recall_so_far=0.9592 rate=143.3 rows/s elapsed=52s
[S2] processed 8,000/30,000 recall_so_far=0.9590 rate=143.5 rows/s elapsed=56s
[S2] processed 8,500/30,000 recall_so_far=0.9581 rate=143.7 rows/s elapsed=59s
[S2] processed 9,000/30,000 recall_so_far=0.9583 rate=144.1 rows/s elapsed=62s
[S2] processed 9,500/30,000 recall_so_far=0.9582 rate=144.6 rows/s elapsed=66s
[S2] processed 10,000/30,000 recall_so_far=0.9579 rate=144.8 rows/s elapsed=69s
[S2] processed 10,500/30,000 recall_so_far=0.9576 rate=145.1 rows/s elapsed=72s
[S2] processed 11,000/30,000 recall_so_far=0.9573 rate=145.3 rows/s elapsed=76s
[S2] processed 11,500/30,000 recall_so_far=0.9574 rate=145.6 rows/s elapsed=79s
[S2] processed 12,000/30,000 recall_so_far=0.9576 rate=145.7 rows/s elapsed=82s
[S2] processed 12,500/30,000 recall_so_far=0.9577 rate=145.9 rows/s elapsed=86s
[S2] processed 13,000/30,000 recall_so_far=0.9576 rate=146.0 rows/s elapsed=89s
[S2] processed 13,500/30,000 recall_so_far=0.9572 rate=146.3 rows/s elapsed=92s
[S2] processed 14,000/30,000 recall_so_far=0.9571 rate=146.3 rows/s elapsed=96s
[S2] processed 14,500/30,000 recall_so_far=0.9572 rate=146.4 rows/s elapsed=99s
[S2] processed 15,000/30,000 recall_so_far=0.9571 rate=146.6 rows/s elapsed=102s
[S2] processed 15,500/30,000 recall_so_far=0.9574 rate=146.7 rows/s elapsed=106s
[S2] processed 16,000/30,000 recall_so_far=0.9573 rate=146.7 rows/s elapsed=109s
[S2] processed 16,500/30,000 recall_so_far=0.9575 rate=147.0 rows/s elapsed=112s
[S2] processed 17,000/30,000 recall_so_far=0.9570 rate=147.1 rows/s elapsed=116s
[S2] processed 17,500/30,000 recall_so_far=0.9568 rate=147.3 rows/s elapsed=119s
[S2] processed 18,000/30,000 recall_so_far=0.9563 rate=147.2 rows/s elapsed=122s
[S2] processed 18,500/30,000 recall_so_far=0.9565 rate=147.3 rows/s elapsed=126s
[S2] processed 19,000/30,000 recall_so_far=0.9566 rate=147.4 rows/s elapsed=129s
[S2] processed 19,500/30,000 recall_so_far=0.9563 rate=147.4 rows/s elapsed=132s
[S2] processed 20,000/30,000 recall_so_far=0.9567 rate=147.5 rows/s elapsed=136s
[S2] processed 20,500/30,000 recall_so_far=0.9570 rate=147.5 rows/s elapsed=139s
[S2] processed 21,000/30,000 recall_so_far=0.9567 rate=147.6 rows/s elapsed=142s
[S2] processed 21,500/30,000 recall_so_far=0.9564 rate=147.6 rows/s elapsed=146s
[S2] processed 22,000/30,000 recall_so_far=0.9564 rate=147.8 rows/s elapsed=149s
[S2] processed 22,500/30,000 recall_so_far=0.9568 rate=147.9 rows/s elapsed=152s
[S2] processed 23,000/30,000 recall_so_far=0.9569 rate=148.1 rows/s elapsed=155s
[S2] processed 23,500/30,000 recall_so_far=0.9568 rate=147.9 rows/s elapsed=159s
[S2] processed 24,000/30,000 recall_so_far=0.9567 rate=148.0 rows/s elapsed=162s
[S2] processed 24,500/30,000 recall_so_far=0.9566 rate=148.1 rows/s elapsed=165s
[S2] processed 25,000/30,000 recall_so_far=0.9564 rate=148.1 rows/s elapsed=169s
[S2] processed 25,500/30,000 recall_so_far=0.9566 rate=148.1 rows/s elapsed=172s
[S2] processed 26,000/30,000 recall_so_far=0.9567 rate=148.1 rows/s elapsed=176s
[S2] processed 26,500/30,000 recall_so_far=0.9564 rate=148.2 rows/s elapsed=179s
[S2] processed 27,000/30,000 recall_so_far=0.9564 rate=148.2 rows/s elapsed=182s
[S2] processed 27,500/30,000 recall_so_far=0.9562 rate=148.2 rows/s elapsed=186s
[S2] processed 28,000/30,000 recall_so_far=0.9563 rate=148.2 rows/s elapsed=189s
[S2] processed 28,500/30,000 recall_so_far=0.9566 rate=148.2 rows/s elapsed=192s
[S2] processed 29,000/30,000 recall_so_far=0.9569 rate=148.3 rows/s elapsed=196s
[S2] processed 29,500/30,000 recall_so_far=0.9568 rate=148.3 rows/s elapsed=199s
[S2] processed 30,000/30,000 recall_so_far=0.9568 rate=148.3 rows/s elapsed=202s
[S2] DONE. n_processed=30,000 actual=49,982 found=47,825 recall=95.6844%

In [23]:
import shutil

total, used, free = shutil.disk_usage("/kaggle/working")

print(f"Total : {total / 1024**3:.2f} GB")
print(f"Used  : {used / 1024**3:.2f} GB")
print(f"Free  : {free / 1024**3:.2f} GB")

Total : 19.52 GB
Used  : 8.29 GB
Free  : 11.21 GB

In [24]:
import os

S2_INDEX = "/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite"

if os.path.exists(S2_INDEX):
    size_gb = os.path.getsize(S2_INDEX) / 1024**3
    print(f"Deleting S2 index: {size_gb:.2f} GB")
    os.remove(S2_INDEX)
    print("S2 index deleted.")
else:
    print("S2 index already absent.")

Deleting S2 index: 5.95 GB
S2 index deleted.

In [25]:
import shutil

total, used, free = shutil.disk_usage("/kaggle/working")
print(f"Free space: {free / 1024**3:.2f} GB")

Free space: 11.21 GB

In [26]:
import os

S2_INDEX = "/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite"

if os.path.exists(S2_INDEX):
    size_gb = os.path.getsize(S2_INDEX) / (1024**3)
    print(f"S2 index STILL EXISTS: {size_gb:.2f} GB")
else:
    print("S2 index is deleted.")

S2 index is deleted.

In [28]:
import sys
import os

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

from indexer import build_index

train_s3 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source3.tsv"
)

S3_INDEX = (
    "/kaggle/working/amazon_ml_solution/"
    "index_train/s3_full.sqlite"
)

os.makedirs(os.path.dirname(S3_INDEX), exist_ok=True)

print("S3 exists:", os.path.exists(train_s3))
print("S3 path:", train_s3)
print("Index path:", S3_INDEX)

assert os.path.exists(train_s3), "S3 training file not found!"

build_index(
    train_s3,
    "S3",
    limit=None,
    backend="sqlite",
    db_path=S3_INDEX
)

S3 exists: True
S3 path: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv
Index path: /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
[indexer] Building sqlite index for S3 from: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv
[indexer]   indexed 500,000 S3 records...
[indexer]   indexed 1,000,000 S3 records...
[indexer]   indexed 1,500,000 S3 records...
[indexer]   indexed 2,000,000 S3 records...
[indexer]   indexed 2,500,000 S3 records...
[indexer]   indexed 3,000,000 S3 records...
[indexer]   indexed 3,500,000 S3 records...
[indexer]   indexed 4,000,000 S3 records...
[indexer]   indexed 4,500,000 S3 records...
[indexer]   indexed 5,000,000 S3 records...
[indexer] Finished S3: 5,285,603 records, 28,341,068 distinct blocking keys.

In [29]:
import os

CHECKPOINT_ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"
MEASUREMENTS = os.path.join(CHECKPOINT_ROOT, "measurements")

SOURCE_SCRIPT = os.path.join(
    MEASUREMENTS,
    "measure_full_single_source.py"
)

S3_SCRIPT = "/kaggle/working/measure_s3_kaggle.py"

TRAIN_S1 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source1.tsv"
)

TRAIN_S3 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source3.tsv"
)

TRAIN_GT = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_ground_truth.tsv"
)

with open(SOURCE_SCRIPT, "r", encoding="utf-8") as f:
    code = f.read()

# Replace original sandbox paths with Kaggle paths
replacements = {
    "/mnt/user-data/uploads/train_source1.tsv": TRAIN_S1,
    "/mnt/user-data/uploads/train_source3.tsv": TRAIN_S3,
    "/mnt/user-data/uploads/train_ground_truth.tsv": TRAIN_GT,
}

for old, new in replacements.items():
    code = code.replace(old, new)

with open(S3_SCRIPT, "w", encoding="utf-8") as f:
    f.write(code)

print("S3 measurement script ready.")
print("S1 exists:", os.path.exists(TRAIN_S1))
print("S3 exists:", os.path.exists(TRAIN_S3))
print("GT exists:", os.path.exists(TRAIN_GT))

S3 measurement script ready.
S1 exists: True
S3 exists: True
GT exists: True

In [30]:
import sys

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

sys.argv = [
    "measure_full_single_source.py",
    "S3",
    "/kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite",
    "/kaggle/working/amazon_ml_solution/checkpoints/recall_s3.json",
    "30000"
]

exec(
    open(
        "/kaggle/working/measure_s3_kaggle.py",
        encoding="utf-8"
    ).read()
)

[S3] resuming at sample_index=0 (0/30,000)
[S3] ground truth loaded: 2,206,821 rows in 14.3s
[S3] processed 500/30,000 recall_so_far=0.9495 rate=15.0 rows/s elapsed=33s
[S3] processed 1,000/30,000 recall_so_far=0.9456 rate=22.1 rows/s elapsed=45s
[S3] processed 1,500/30,000 recall_so_far=0.9465 rate=28.2 rows/s elapsed=53s
[S3] processed 2,000/30,000 recall_so_far=0.9490 rate=34.1 rows/s elapsed=59s
[S3] processed 2,500/30,000 recall_so_far=0.9493 rate=39.5 rows/s elapsed=63s
[S3] processed 3,000/30,000 recall_so_far=0.9487 rate=44.7 rows/s elapsed=67s
[S3] processed 3,500/30,000 recall_so_far=0.9481 rate=49.4 rows/s elapsed=71s
[S3] processed 4,000/30,000 recall_so_far=0.9460 rate=53.7 rows/s elapsed=74s
[S3] processed 4,500/30,000 recall_so_far=0.9458 rate=57.7 rows/s elapsed=78s
[S3] processed 5,000/30,000 recall_so_far=0.9459 rate=61.3 rows/s elapsed=81s
[S3] processed 5,500/30,000 recall_so_far=0.9452 rate=64.8 rows/s elapsed=85s
[S3] processed 6,000/30,000 recall_so_far=0.9460 rate=68.0 rows/s elapsed=88s
[S3] processed 6,500/30,000 recall_so_far=0.9466 rate=70.9 rows/s elapsed=92s
[S3] processed 7,000/30,000 recall_so_far=0.9468 rate=73.6 rows/s elapsed=95s
[S3] processed 7,500/30,000 recall_so_far=0.9468 rate=76.1 rows/s elapsed=98s
[S3] processed 8,000/30,000 recall_so_far=0.9467 rate=78.5 rows/s elapsed=102s
[S3] processed 8,500/30,000 recall_so_far=0.9460 rate=80.5 rows/s elapsed=106s
[S3] processed 9,000/30,000 recall_so_far=0.9470 rate=82.5 rows/s elapsed=109s
[S3] processed 9,500/30,000 recall_so_far=0.9466 rate=84.4 rows/s elapsed=113s
[S3] processed 10,000/30,000 recall_so_far=0.9470 rate=86.2 rows/s elapsed=116s
[S3] processed 10,500/30,000 recall_so_far=0.9467 rate=87.9 rows/s elapsed=119s
[S3] processed 11,000/30,000 recall_so_far=0.9466 rate=89.6 rows/s elapsed=123s
[S3] processed 11,500/30,000 recall_so_far=0.9461 rate=91.1 rows/s elapsed=126s
[S3] processed 12,000/30,000 recall_so_far=0.9460 rate=92.6 rows/s elapsed=130s
[S3] processed 12,500/30,000 recall_so_far=0.9465 rate=94.0 rows/s elapsed=133s
[S3] processed 13,000/30,000 recall_so_far=0.9463 rate=95.3 rows/s elapsed=136s
[S3] processed 13,500/30,000 recall_so_far=0.9461 rate=96.6 rows/s elapsed=140s
[S3] processed 14,000/30,000 recall_so_far=0.9460 rate=97.7 rows/s elapsed=143s
[S3] processed 14,500/30,000 recall_so_far=0.9461 rate=98.8 rows/s elapsed=147s
[S3] processed 15,000/30,000 recall_so_far=0.9460 rate=100.0 rows/s elapsed=150s
[S3] processed 15,500/30,000 recall_so_far=0.9460 rate=101.0 rows/s elapsed=153s
[S3] processed 16,000/30,000 recall_so_far=0.9463 rate=101.9 rows/s elapsed=157s
[S3] processed 16,500/30,000 recall_so_far=0.9468 rate=103.0 rows/s elapsed=160s
[S3] processed 17,000/30,000 recall_so_far=0.9470 rate=103.9 rows/s elapsed=164s
[S3] processed 17,500/30,000 recall_so_far=0.9470 rate=104.8 rows/s elapsed=167s
[S3] processed 18,000/30,000 recall_so_far=0.9475 rate=105.0 rows/s elapsed=171s
[S3] processed 18,500/30,000 recall_so_far=0.9477 rate=105.8 rows/s elapsed=175s
[S3] processed 19,000/30,000 recall_so_far=0.9478 rate=106.6 rows/s elapsed=178s
[S3] processed 19,500/30,000 recall_so_far=0.9478 rate=107.3 rows/s elapsed=182s
[S3] processed 20,000/30,000 recall_so_far=0.9476 rate=108.0 rows/s elapsed=185s
[S3] processed 20,500/30,000 recall_so_far=0.9473 rate=108.8 rows/s elapsed=188s
[S3] processed 21,000/30,000 recall_so_far=0.9473 rate=109.4 rows/s elapsed=192s
[S3] processed 21,500/30,000 recall_so_far=0.9471 rate=110.1 rows/s elapsed=195s
[S3] processed 22,000/30,000 recall_so_far=0.9471 rate=110.7 rows/s elapsed=199s
[S3] processed 22,500/30,000 recall_so_far=0.9471 rate=111.3 rows/s elapsed=202s
[S3] processed 23,000/30,000 recall_so_far=0.9473 rate=111.9 rows/s elapsed=205s
[S3] processed 23,500/30,000 recall_so_far=0.9474 rate=112.4 rows/s elapsed=209s
[S3] processed 24,000/30,000 recall_so_far=0.9476 rate=112.9 rows/s elapsed=213s
[S3] processed 24,500/30,000 recall_so_far=0.9479 rate=113.5 rows/s elapsed=216s
[S3] processed 25,000/30,000 recall_so_far=0.9478 rate=114.0 rows/s elapsed=219s
[S3] processed 25,500/30,000 recall_so_far=0.9477 rate=114.5 rows/s elapsed=223s
[S3] processed 26,000/30,000 recall_so_far=0.9477 rate=114.9 rows/s elapsed=226s
[S3] processed 26,500/30,000 recall_so_far=0.9479 rate=115.5 rows/s elapsed=230s
[S3] processed 27,000/30,000 recall_so_far=0.9478 rate=115.9 rows/s elapsed=233s
[S3] processed 27,500/30,000 recall_so_far=0.9478 rate=116.3 rows/s elapsed=236s
[S3] processed 28,000/30,000 recall_so_far=0.9480 rate=116.7 rows/s elapsed=240s
[S3] processed 28,500/30,000 recall_so_far=0.9480 rate=117.1 rows/s elapsed=243s
[S3] processed 29,000/30,000 recall_so_far=0.9482 rate=117.5 rows/s elapsed=247s
[S3] processed 29,500/30,000 recall_so_far=0.9483 rate=117.9 rows/s elapsed=250s
[S3] processed 30,000/30,000 recall_so_far=0.9486 rate=118.3 rows/s elapsed=254s
[S3] DONE. n_processed=30,000 actual=53,503 found=50,751 recall=94.8564%

In [31]:
import os

ROOT = "/kaggle/input/datasets/tejasweerajput/amazon-v3"
MODULES = os.path.join(ROOT, "modules")

for name in [
    "candidates.py",
    "features.py",
    "labels.py",
    "similarity.py",
]:
    path = os.path.join(MODULES, name)
    print("\n" + "="*70)
    print(name)
    print("="*70)

    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    print(text[:12000])

======================================================================
candidates.py
======================================================================
"""
candidates.py
============================================================
CHANGE from the original: index.bucket(key_type, composed) is now
called as index.bucket(key_type, composed, limit=cap + 1).

Why cap + 1 and not cap: we still need to distinguish "bucket size
== cap exactly" (keep it) from "bucket size > cap" (drop it), so we
ask for one more row than the cap allows. For MemoryIndex this is
free (already in RAM). For SqliteIndex this turns a potentially
huge, wasted `SELECT ... ` + fetchall() on a hot key into a bounded
`SELECT ... LIMIT cap+1` -- seeSee indexer.py's module docstring
for the full reasoning and why this matters specifically at full
(5M+ row) production scale, not at the 100K-row dev scale the
original numbers were measured on.

Everything else in this file (the candidate dict shape, key_types/
min_freq bookkeeping, generate_candidate_pairs_for_row) is
UNCHANGED.
"""

from blocking import (
    make_name_keys,
    make_unicode_name_keys,
    make_address_keys,
    make_a4_keys,
    make_at2_keys,
    DEFAULT_FREQ_CAPS,
)
from indexer import compose_key


def find_candidates(s1_row, index, freq_caps=None):

    freq_caps = freq_caps or DEFAULT_FREQ_CAPS

    country = s1_row.get("country", "").strip()
    name = s1_row.get("business_name", "")
    address = s1_row.get("business_address", "")

    all_keys = (
        make_name_keys(name)
        + make_unicode_name_keys(name)
        + make_address_keys(address)
        + make_a4_keys(address)
        + make_at2_keys(address)
    )

    candidates = {}

    for key_type, key_value in all_keys:

        cap = freq_caps.get(key_type, DEFAULT_FREQ_CAPS.get(key_type, 500))

        composed = compose_key(country, key_value)

        # Ask for at most cap + 1 rows. If we get back cap + 1, the
        # true bucket is > cap somewhere at or beyond that row, so
        # it's still correctly treated as "too broad" below -- we
        # just never had to materialize the rest of it.
        bucket = index.bucket(key_type, composed, limit=cap + 1)
        bucket_size = len(bucket)

        if bucket_size == 0:
            continue

        if bucket_size > cap:
            continue

        for suffix in bucket:

            entry = candidates.get(suffix)

            if entry is None:
                candidates[suffix] = {
                    "key_types": {key_type},
                    "min_freq": bucket_size,
                }
            else:
                entry["key_types"].add(key_type)
                entry["min_freq"] = min(entry["min_freq"], bucket_size)

    return candidates


def generate_candidate_pairs_for_row(s1_row, indexes_by_source, freq_caps=None):

    s1_id = s1_row.get("entity_id", "")
    rows = []

    for source, index in indexes_by_source.items():

        candidates = find_candidates(s1_row, index, freq_caps=freq_caps)

        for suffix, info in candidates.items():

            candidate_id = f"{source}-{suffix}"

            rows.append(
                {
                    "source1_entity_id": s1_id,
                    "candidate_entity_id": candidate_id,
                    "source": source,
                    "blocking_key_types": "|".join(sorted(info["key_types"])),
                    "blocking_num_keys": len(info["key_types"]),
                    "blocking_min_freq": info["min_freq"],
                }
            )

    return rows


======================================================================
features.py
======================================================================
"""
features.py
============================================================
CHANGES from the original (see PHASE1_ARCHITECTURE_AUDIT.md,
sections "Existing feature set" and "Runtime optimization plan"
for the measurements behind these changes):

1. NON-LATIN FIX (correctness, not just speed):
   name_char_similarity / name_levenshtein_similarity / etc. used
   to be computed ONLY on normalize_business_name()/normalize_address(),
   which strip non-Latin scripts to "". For a true-match pair where
   both sides are in Devanagari/Telugu/Kannada/Bengali, every
   similarity feature silently became 0 or the "missing" default,
   even though the strings are genuinely very similar. This module
   now also computes the same feature suite on a script-agnostic
   normalization (normalize.normalize_unicode_preserving) and uses
   whichever normalization actually has content, so the ML model
   gets real signal on non-Latin rows instead of a constant.

2. SPEED: the original had TWO independent implementations of
   "edit-distance-based ratio" per field (text_similarity() via
   difflib.SequenceMatcher, and levenshtein_similarity() via
   rapidfuzz). difflib's SequenceMatcher is pure Python and is the
   single most expensive call in the old feature set -- at the
   ~440M-pair scale estimated for the full test set, removing one
   of the two redundant passes per field is a meaningful win.
   rapidfuzz.fuzz.ratio() is a compatible-by-design, C-accelerated
   reimplementation of the same "difflib-style" ratio, so
   name_char_similarity / address_char_similarity are now computed
   with it too. If rapidfuzz is unavailable, this falls back to the
   original difflib implementation exactly as before -- no feature
   changes shape, only which backend computes it.

3. Feature list is APPENDED to, not reordered or removed, so
   existing train_features_*.tsv files stay a strict prefix-
   compatible subset of the new schema (old columns keep the same
   name and meaning).
"""

from functools import lru_cache

from normalize import (
    normalize_business_name,
    normalize_address,
    normalize_business_name_script_agnostic,
    normalize_unicode_preserving,
    is_non_latin,
)

from similarity import token_similarity, address_number_match, country_match


# --------------------------------------------------------------
# Ratio backend: rapidfuzz preferred (C-accelerated, difflib-
# compatible ratio), pure-Python difflib as a guaranteed fallback.
# One implementation now serves BOTH "char_similarity" and
# "levenshtein_similarity" -- see change #2 above.
# --------------------------------------------------------------

try:
    from rapidfuzz.fuzz import ratio as _rapidfuzz_ratio

    def _ratio(a, b):
        if not a or not b:
            return 0.0
        return _rapidfuzz_ratio(a, b) / 100.0

except ImportError:

    from difflib import SequenceMatcher

    def _ratio(a, b):
        if not a or not b:
            return 0.0
        return SequenceMatcher(None, a, b).ratio()


levenshtein_similarity = _ratio  # kept as a public name for compatibility


@lru_cache(maxsize=2_000_000)
def cached_normalize_business_name(value):
    return normalize_business_name(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_address(value):
    return normalize_address(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_business_name_unicode(value):
    return normalize_business_name_script_agnostic(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_address_unicode(value):
    return normalize_unicode_preserving(value)


# --------------------------------------------------------------
# Character n-gram Jaccard
# --------------------------------------------------------------

def char_ngram_jaccard(a, b, n=2):

    if not a or not b:
        return 0.0

    if len(a) < n or len(b) < n:
        return 0.0

    grams_a = {a[i:i + n] for i in range(len(a) - n + 1)}
    grams_b = {b[i:i + n] for i in range(len(b) - n + 1)}

    if not grams_a or not grams_b:
        return 0.0

    return len(grams_a & grams_b) / len(grams_a | grams_b)


def prefix_similarity(a, b, k=4):

    if not a or not b:
        return 0.0

    a_p, b_p = a[:k], b[:k]
    max_len = min(len(a_p), len(b_p))

    if max_len == 0:
        return 0.0

    matched = sum(1 for x, y in zip(a_p, b_p) if x == y)
    return matched / max_len


def suffix_similarity(a, b, k=4):

    if not a or not b:
        return 0.0

    a_s, b_s = a[-k:], b[-k:]
    max_len = min(len(a_s), len(b_s))

    if max_len == 0:
        return 0.0

    matched = sum(1 for x, y in zip(reversed(a_s), reversed(b_s)) if x == y)
    return matched / max_len


def token_overlap_count(a, b):

    if not a or not b:
        return 0

    return len(set(a.split()) & set(b.split()))


# --------------------------------------------------------------
# Feature columns
# --------------------------------------------------------------
# Original columns are UNCHANGED in name, meaning and position.
# New columns are appended at the end.

FEATURE_COLUMNS = [

    # Name features (original)
    "name_exact_match",
    "name_char_similarity",
    "name_levenshtein_similarity",
    "name_token_jaccard",
    "name_token_overlap",
    "name_compact_similarity",
    "name_prefix_similarity",
    "name_suffix_similarity",
    "name_char_ngram_jaccard",

    # Address features (original)
    "address_exact_match",
    "address_char_similarity",
    "address_levenshtein_similarity",
    "address_token_jaccard",
    "address_token_overlap",
    "address_number_match",
    "address_char_ngram_jaccard",

    # Other (original)
    "country_match",
    "name_missing",
    "address_missing",
    "combined_name_address_score",

    # ---- NEW: non-Latin fallback signal ----
    "name_is_non_latin",
    "address_is_non_latin",
    "name_char_similarity_unicode",
    "name_token_jaccard_unicode",
]


def calculate_features(name1, address1, country1, name2, address2, country2):

    # -------- ASCII-folded normalization (original path) --------
    n1 = cached_normalize_business_name(name1)
    n2 = cached_normalize_business_name(name2)
    a1 = cached_normalize_address(address1)
    a2 = cached_normalize_address(address2)

    name_missing = int(not n1 or not n2)
    address_missing = int(not a1 or not a2)

    name_char_sim = _ratio(n1, n2)
    name_lev_sim = _ratio(n1, n2)  # same backend now, see module docstring #2
    name_tok_jaccard = token_similarity(n1, n2)
    name_compact_sim = _ratio(n1.replace(" ", ""), n2.replace(" ", ""))

    address_char_sim = _ratio(a1, a2)
    address_lev_sim = _ratio(a1, a2)
    address_tok_jaccard = token_similarity(a1, a2)

    combined = 0.6 * name_char_sim + 0.4 * address_char_sim

    # -------- NEW: script-agnostic fallback for non-Latin names --------
    # Only pay for the extra normalization/similarity work when the
    # ASCII-folded form actually lost content -- cheap for the
    # (majority) Latin-script rows, since is_non_latin() short-
    # circuits on the already-cached ascii_form.
    name_non_latin = is_non_latin(name1) or is_non_latin(name2)

    if name_non_latin:
        un1 = cached_normalize_business_name_unicode(name1)
        un2 = cached_normalize_business_name_unicode(name2)
        name_char_sim_unicode = _ratio(un1, un2)
        name_tok_jaccard_unicode = token_similarity(un1, un2)
    else:
        name_char_sim_unicode = name_char_sim
        name_tok_jaccard_unicode = name_tok_jaccard

    address_non_latin = is_non_latin(address1) or is_non_latin(address2)

    return {

        "name_exact_match": int(bool(n1) and n1 == n2),
        "name_char_similarity": name_char_sim,
        "name_levenshtein_similarity": name_lev_sim,
        "name_token_jaccard": name_tok_jaccard,
        "name_token_overlap": token_overlap_count(n1, n2),
        "name_compact_similarity": name_compact_sim,
        "name_prefix_similarity": prefix_similarity(n1, n2),
        "name_suffix_similarity": suffix_similarity(n1, n2),
        "name_char_ngram_jaccard": char_ngram_jaccard(n1, n2),

        "address_exact_match": int(bool(a1) and a1 == a2),
        "address_char_similarity": address_char_sim,
        "address_levenshtein_similarity": address_lev_sim,
        "address_token_jaccard": address_tok_jaccard,
        "address_token_overlap": token_overlap_count(a1, a2),
        "address_number_match": address_number_match(address1, address2),
        "address_char_ngram_jaccard": char_ngram_jaccard(a1, a2),

        "country_match": country_match(country1, country2),
        "name_missing": name_missing,
        "address_missing": address_missing,
        "combined_name_address_score": combined,

        "name_is_non_latin": int(name_non_latin),
        "address_is_non_latin": int(address_non_latin),
        "name_char_similarity_unicode": name_char_sim_unicode,
        "name_token_jaccard_unicode": name_tok_jaccard_unicode,
    }


======================================================================
labels.py
======================================================================
"""
labels.py
============================================================
PRESERVED: load_ground_truth() / label_for() are UNCHANGED and
still correct -- keep using them for train_10k-scale work where
their extra convenience (pre-split "S2"/"S3"/"all" sets) is cheap.

ADDED: load_ground_truth_compact(), a memory-lean alternative for
the full 2.2M-row train_ground_truth.tsv.

MEASURED (this sandbox, 3.9 GB total RAM, Python 3.12):
  load_ground_truth() on the full file -> 2,206,821 entries,
  peak RSS ~2.84 GB, ~25s.

That is the ENTIRE per-S1-row ground truth structure sitting in
RAM before candidate generation, feature calculation, indexes, or
anything else has been loaded -- on a Kaggle instance with, say,
13-16 GB total RAM, this is a meaningful fixed cost, and on a
smaller instance it can be the difference between fitting in
memory and an OOM kill mid-run (which is exactly what truncated a
larger validation run attempted during this audit).

The cost comes from storing THREE Python sets per S1 row
("S2", "S3", "all") instead of one -- each empty/small set has
real fixed overhead (hash table allocation) independent of how
many ids it holds, so building three per row roughly triples the
per-row container overhead versus storing the raw id set once and
filtering by prefix on demand (which is O(len(entry)), and entries
have on average only a handful of matches).

load_ground_truth_compact() stores exactly one frozenset per row.
matches_for_source()/label_for_compact() below reconstruct the
"S2 only" / "S3 only" view on demand, at effectively no extra cost
since per-row match counts are small (median well under 10, per
analyze_ground_truth.py's own distribution check).
"""

import csv


def load_ground_truth(path):
    """
    UNCHANGED. Returns dict: source1_entity_id -> {
        "S2": set of matched S2 ids,
        "S3": set of matched S3 ids,
        "all": set of every matched id (any source),
    }
    """

    ground_truth = {}

    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:

        reader = csv.DictReader(f, delimiter="\t")

        for row in reader:

            s1_id = row["source1_entity_id"]
            raw = (row.get("matched_entity_ids") or "").strip()

            if raw:
                all_ids = {x.strip() for x in raw.split(",") if x.strip()}
            else:
                all_ids = set()

            ground_truth[s1_id] = {
                "S2": {x for x in all_ids if x.startswith("S2-")},
                "S3": {x for x in all_ids if x.startswith("S3-")},
                "all": all_ids,
            }

    return ground_truth


def label_for(s1_id, candidate_id, ground_truth):
    entry = ground_truth.get(s1_id)
    if not entry:
        return 0
    return int(candidate_id in entry["all"])


# ============================================================
# NEW: memory-lean loader for full-scale (2.2M+ row) ground truth
# ============================================================

_EMPTY_FROZENSET = frozenset()


def load_ground_truth_compact(path):
    """
    Returns dict: source1_entity_id -> frozenset of matched ids
    (mixed S2-*/S3-*). One container per row instead of three.

    frozenset (vs set) is used because these are never mutated
    after loading, and CPython's frozenset has slightly less
    per-object overhead than a mutable set for read-only use.
    """

    ground_truth = {}

    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:

        reader = csv.DictReader(f, delimiter="\t")

        for row in reader:

            s1_id = row["source1_entity_id"]
            raw = (row.get("matched_entity_ids") or "").strip()

            if raw:
                ground_truth[s1_id] = frozenset(
                    x.strip() for x in raw.split(",") if x.strip()
                )
            else:
                ground_truth[s1_id] = _EMPTY_FROZENSET

    return ground_truth


def matches_for_source(entry, source_prefix):
    """
    entry: a frozenset from load_ground_truth_compact(). Filters
    by prefix on demand -- cheap, since entry is typically only a
    handful of ids (see analyze_ground_truth.py's match_count
    distribution: median match count is small).
    """
    if not entry:
        return _EMPTY_FROZENSET
    return frozenset(x for x in entry if x.startswith(source_prefix))


def label_for_compact(s1_id, candidate_id, ground_truth):
    entry = ground_truth.get(s1_id)
    if not entry:
        return 0
    return int(candidate_id in entry)


======================================================================
similarity.py
======================================================================
from difflib import SequenceMatcher
import re

from normalize import (
    normalize_business_name,
    normalize_address
)


def text_similarity(text1, text2):
    """
    Character-level similarity.
    """

    if not text1 or not text2:
        return 0.0

    return SequenceMatcher(
        None,
        text1,
        text2
    ).ratio()


def token_similarity(text1, text2):
    """
    Compare sets of words.

    Example:

    "payne enterprises"
    "payne enterprises llc"

    share the important tokens.
    """

    if not text1 or not text2:
        return 0.0

    tokens1 = set(text1.split())
    tokens2 = set(text2.split())

    if not tokens1 or not tokens2:
        return 0.0

    intersection = tokens1 & tokens2
    union = tokens1 | tokens2

    return len(intersection) / len(union)


def name_similarity(name1, name2):
    """
    Combine character and token similarity.
    """

    name1 = normalize_business_name(name1)
    name2 = normalize_business_name(name2)

    char_score = text_similarity(
        name1,
        name2
    )

    token_score = token_similarity(
        name1,
        name2
    )

    # Give more importance to character similarity,
    # while also considering shared words.
    return (
        0.6 * char_score
        +
        0.4 * token_score
    )


def address_similarity(address1, address2):
    """
    Compare normalized addresses.
    """

    address1 = normalize_address(address1)
    address2 = normalize_address(address2)

    return text_similarity(
        address1,
        address2
    )


def country_match(country1, country2):
    """
    Compare countries.

    1.0 = same country
    0.0 = different country
    """

    if not country1 or not country2:
        return 0.0

    return 1.0 if (
        country1.strip().lower()
        ==
        country2.strip().lower()
    ) else 0.0


def extract_address_numbers(address):
    """
    Extract numeric parts from an address.
    """

    if not address:
        return []

    address = normalize_address(address)

    return re.findall(
        r"\d+",
        address
    )


def address_number_match(address1, address2):
    """
    Compare numeric parts of addresses.

    1.0 = numbers match
    0.0 = numbers differ
    0.5 = number unavailable in one/both
    """

    numbers1 = extract_address_numbers(
        address1
    )

    numbers2 = extract_address_numbers(
        address2
    )

    if not numbers1 or not numbers2:
        return 0.5


In [32]:
import os
from pathlib import Path

WORK = Path("/kaggle/working/amazon_ml_solution")

print("=" * 70)
print("CURRENT PIPELINE STATE")
print("=" * 70)

for folder in [
    "index_train",
    "index_test",
    "shards_train",
    "shards_test",
    "checkpoints",
    "models",
    "output",
]:
    p = WORK / folder
    print(f"\n[{folder}]")
    if p.exists():
        files = list(p.iterdir())
        print("count:", len(files))
        for f in files[:20]:
            print(" ", f.name, f"{f.stat().st_size/1024/1024:.1f} MB")
        if len(files) > 20:
            print(" ...")
    else:
        print("MISSING")

======================================================================
CURRENT PIPELINE STATE
======================================================================

[index_train]
count: 7
  s2_full.sqlite-wal 2392.2 MB
  s2_full.sqlite.manifest.json 0.0 MB
  s3_full.sqlite 6703.0 MB
  s3_full.sqlite.manifest.json 0.0 MB
  s3_full.sqlite-wal 2647.6 MB
  s3_full.sqlite-shm 5.2 MB
  s2_full.sqlite-shm 4.7 MB

[index_test]
count: 0

[shards_train]
count: 0

[shards_test]
count: 0

[checkpoints]
count: 2
  recall_s3.json 0.1 MB
  recall_s2.json 0.1 MB

[models]
count: 0

[output]
count: 0

In [33]:
import os
import sys
from pathlib import Path

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

WORK = Path("/kaggle/working/amazon_ml_solution")
SHARDS = WORK / "shards_train"
SHARDS.mkdir(parents=True, exist_ok=True)

TRAIN_S1 = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_source1.tsv"
)

TRAIN_GT = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train/train_ground_truth.tsv"
)

S2_INDEX = WORK / "index_train" / "s2_full.sqlite"
S3_INDEX = WORK / "index_train" / "s3_full.sqlite"

print("S1 exists :", os.path.exists(TRAIN_S1))
print("GT exists :", os.path.exists(TRAIN_GT))
print("S2 index  :", S2_INDEX.exists())
print("S3 index  :", S3_INDEX.exists())
print("Output dir:", SHARDS)

print("\nExisting shards:")
for f in sorted(SHARDS.glob("*")):
    print(" ", f.name, f"{f.stat().st_size/1024/1024:.1f} MB")

S1 exists : True
GT exists : True
S2 index  : False
S3 index  : True
Output dir: /kaggle/working/amazon_ml_solution/shards_train

Existing shards:

In [34]:
from pathlib import Path

IDX = Path("/kaggle/working/amazon_ml_solution/index_train")

print("=" * 70)
print("S2 FILE RECOVERY CHECK")
print("=" * 70)

for name in [
    "s2_full.sqlite",
    "s2_full.sqlite-wal",
    "s2_full.sqlite-shm",
    "s2_full.sqlite.manifest.json",
]:
    p = IDX / name
    print(f"{name:35s} exists={p.exists():5} ", end="")
    if p.exists():
        print(f"size={p.stat().st_size / (1024**3):.3f} GB")
    else:
        print()

print("\nDirectory listing:")
for p in sorted(IDX.glob("s2_full*")):
    print(f"  {p.name:35s} {p.stat().st_size / (1024**3):.3f} GB")

======================================================================
S2 FILE RECOVERY CHECK
======================================================================
s2_full.sqlite                      exists=    0
s2_full.sqlite-wal                  exists=    1 size=2.336 GB
s2_full.sqlite-shm                  exists=    1 size=0.005 GB
s2_full.sqlite.manifest.json        exists=    1 size=0.000 GB

Directory listing:
  s2_full.sqlite-shm                  0.005 GB
  s2_full.sqlite-wal                  2.336 GB
  s2_full.sqlite.manifest.json        0.000 GB

In [35]:
import sqlite3
from pathlib import Path

S2 = Path("/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite")

print("=" * 70)
print("SQLITE WAL RECOVERY TEST")
print("=" * 70)

# DO NOT create/delete/modify anything yet.
# We only test whether SQLite can open the existing WAL state.

try:
    con = sqlite3.connect(str(S2))
    print("SQLite connection: SUCCESS")

    cur = con.cursor()

    cur.execute("PRAGMA journal_mode;")
    print("journal_mode:", cur.fetchone())

    cur.execute("PRAGMA integrity_check;")
    result = cur.fetchone()[0]
    print("integrity_check:", result)

    con.close()

except Exception as e:
    print("SQLite connection ERROR:")
    print(type(e).__name__, str(e))

======================================================================
SQLITE WAL RECOVERY TEST
======================================================================
SQLite connection: SUCCESS
journal_mode: ('delete',)
integrity_check: ok

In [36]:
import sqlite3
from pathlib import Path

S2 = Path("/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite")

print("=" * 70)
print("S2 DATABASE CONTENT VERIFICATION")
print("=" * 70)

con = sqlite3.connect(str(S2))
cur = con.cursor()

# 1. List tables
cur.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
""")

tables = [r[0] for r in cur.fetchall()]

print("\nTables:")
for t in tables:
    print(" ", t)

# 2. Show schema
print("\nSchema:")
for t in tables:
    cur.execute(f"PRAGMA table_info('{t}')")
    cols = cur.fetchall()
    print(f"\n[{t}]")
    for c in cols:
        print(" ", c)

con.close()

======================================================================
S2 DATABASE CONTENT VERIFICATION
======================================================================

Tables:

Schema:

In [37]:
from pathlib import Path

IDX = Path("/kaggle/working/amazon_ml_solution/index_train")

print("=" * 70)
print("CURRENT S2 STATE")
print("=" * 70)

for p in sorted(IDX.glob("s2_full*")):
    print(
        f"{p.name:35s} "
        f"{p.stat().st_size / (1024**3):.6f} GB"
    )

======================================================================
CURRENT S2 STATE
======================================================================
s2_full.sqlite                      0.000000 GB
s2_full.sqlite-shm                  0.004547 GB
s2_full.sqlite.manifest.json        0.000000 GB

In [38]:
from pathlib import Path

manifest = Path(
    "/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite.manifest.json"
)

print("=" * 70)
print("S2 MANIFEST")
print("=" * 70)

print(manifest.read_text())

======================================================================
S2 MANIFEST
======================================================================
{"source_prefix": "S2", "rows_indexed": 5034616, "complete": true}

In [39]:
from pathlib import Path

INDEXER = Path(
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-v3/modules/indexer.py"
)

text = INDEXER.read_text(encoding="utf-8")

print("=" * 70)
print("INDEXER COMPLETE-MANIFEST LOGIC")
print("=" * 70)

lines = text.splitlines()

for i, line in enumerate(lines):
    if "complete" in line.lower() or "manifest" in line.lower():
        start = max(0, i - 5)
        end = min(len(lines), i + 8)
        print(f"\n--- lines {start+1}-{end} ---")
        for j in range(start, end):
            print(f"{j+1:4d}: {lines[j]}")

======================================================================
INDEXER COMPLETE-MANIFEST LOGIC
======================================================================

--- lines 18-30 ---
  18:    of the biggest avoidable costs in candidate generation. With a
  19:    LIMIT of cap+1, an oversized bucket now costs O(cap) to detect
  20:    as oversized, not O(bucket size).
  21:
  22: 2. SqliteIndex now commits periodically (every flush(), not only
  23:    at finalize()) and writes a small JSON manifest recording how
  24:    many source rows have been indexed. On restart, build_index()
  25:    checks the manifest: if a source's index previously finished,
  26:    it is reused as-is (no rebuild); if it was left partway
  27:    through, indexing resumes from the last completed row instead
  28:    of starting over. This is what makes a Kaggle session
  29:    interruption DURING index-building recoverable -- previously
  30:    the whole build sat inside one open SQLite transaction with no

--- lines 20-32 ---
  20:    as oversized, not O(bucket size).
  21:
  22: 2. SqliteIndex now commits periodically (every flush(), not only
  23:    at finalize()) and writes a small JSON manifest recording how
  24:    many source rows have been indexed. On restart, build_index()
  25:    checks the manifest: if a source's index previously finished,
  26:    it is reused as-is (no rebuild); if it was left partway
  27:    through, indexing resumes from the last completed row instead
  28:    of starting over. This is what makes a Kaggle session
  29:    interruption DURING index-building recoverable -- previously
  30:    the whole build sat inside one open SQLite transaction with no
  31:    recorded progress, so a kill at row 4,900,000 of 5,000,000 lost
  32:    the entire build.

--- lines 22-34 ---
  22: 2. SqliteIndex now commits periodically (every flush(), not only
  23:    at finalize()) and writes a small JSON manifest recording how
  24:    many source rows have been indexed. On restart, build_index()
  25:    checks the manifest: if a source's index previously finished,
  26:    it is reused as-is (no rebuild); if it was left partway
  27:    through, indexing resumes from the last completed row instead
  28:    of starting over. This is what makes a Kaggle session
  29:    interruption DURING index-building recoverable -- previously
  30:    the whole build sat inside one open SQLite transaction with no
  31:    recorded progress, so a kill at row 4,900,000 of 5,000,000 lost
  32:    the entire build.
  33:
  34: 3. Kaggle-path discovery: `discover_dataset_root()` walks

--- lines 150-162 ---
 150: # SQLITE (DISK-BACKED) BACKEND -- with capped fetch + checkpoint
 151: # ============================================================
 152:
 153: class SqliteIndex:
 154:
 155:     def __init__(self, source_prefix, db_path, manifest_path=None):
 156:
 157:         self.source_prefix = source_prefix
 158:         self.db_path = db_path
 159:         self.manifest_path = manifest_path or (str(db_path) + ".manifest.json")
 160:         self.count = 0
 161:
 162:         self.conn = sqlite3.connect(db_path)

--- lines 154-166 ---
 154:
 155:     def __init__(self, source_prefix, db_path, manifest_path=None):
 156:
 157:         self.source_prefix = source_prefix
 158:         self.db_path = db_path
 159:         self.manifest_path = manifest_path or (str(db_path) + ".manifest.json")
 160:         self.count = 0
 161:
 162:         self.conn = sqlite3.connect(db_path)
 163:         self.conn.execute("PRAGMA synchronous = OFF")
 164:         self.conn.execute("PRAGMA journal_mode = WAL")  # survives a crash mid-write
 165:
 166:         self.conn.execute(

--- lines 175-187 ---
 175:
 176:         self._buffer = []
 177:         self._attr_buffer = []
 178:         self._index_built = False
 179:
 180:     # -------- manifest / resume --------
 181:
 182:     def _read_manifest(self):
 183:         if os.path.exists(self.manifest_path):
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:

--- lines 177-189 ---
 177:         self._attr_buffer = []
 178:         self._index_built = False
 179:
 180:     # -------- manifest / resume --------
 181:
 182:     def _read_manifest(self):
 183:         if os.path.exists(self.manifest_path):
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {

--- lines 178-190 ---
 178:         self._index_built = False
 179:
 180:     # -------- manifest / resume --------
 181:
 182:     def _read_manifest(self):
 183:         if os.path.exists(self.manifest_path):
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,

--- lines 179-191 ---
 179:
 180:     # -------- manifest / resume --------
 181:
 182:     def _read_manifest(self):
 183:         if os.path.exists(self.manifest_path):
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,
 191:             "rows_indexed": rows_indexed,

--- lines 183-195 ---
 183:         if os.path.exists(self.manifest_path):
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,
 191:             "rows_indexed": rows_indexed,
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:

--- lines 184-196 ---
 184:             with open(self.manifest_path, "r", encoding="utf-8") as f:
 185:                 return json.load(f)
 186:         return None
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,
 191:             "rows_indexed": rows_indexed,
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:
 196:             json.dump(manifest, f)

--- lines 187-199 ---
 187:
 188:     def _write_manifest(self, rows_indexed, complete):
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,
 191:             "rows_indexed": rows_indexed,
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:
 196:             json.dump(manifest, f)
 197:         os.replace(tmp_path, self.manifest_path)
 198:
 199:     def resume_point(self):

--- lines 189-201 ---
 189:         manifest = {
 190:             "source_prefix": self.source_prefix,
 191:             "rows_indexed": rows_indexed,
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:
 196:             json.dump(manifest, f)
 197:         os.replace(tmp_path, self.manifest_path)
 198:
 199:     def resume_point(self):
 200:         """
 201:         Returns (rows_already_indexed, already_complete). The

--- lines 191-203 ---
 191:             "rows_indexed": rows_indexed,
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:
 196:             json.dump(manifest, f)
 197:         os.replace(tmp_path, self.manifest_path)
 198:
 199:     def resume_point(self):
 200:         """
 201:         Returns (rows_already_indexed, already_complete). The
 202:         caller (build_index) uses this to decide how many input
 203:         rows to skip, and whether to skip building this source's

--- lines 192-204 ---
 192:             "complete": complete,
 193:         }
 194:         tmp_path = self.manifest_path + ".tmp"
 195:         with open(tmp_path, "w", encoding="utf-8") as f:
 196:             json.dump(manifest, f)
 197:         os.replace(tmp_path, self.manifest_path)
 198:
 199:     def resume_point(self):
 200:         """
 201:         Returns (rows_already_indexed, already_complete). The
 202:         caller (build_index) uses this to decide how many input
 203:         rows to skip, and whether to skip building this source's
 204:         index at all.

--- lines 196-208 ---
 196:             json.dump(manifest, f)
 197:         os.replace(tmp_path, self.manifest_path)
 198:
 199:     def resume_point(self):
 200:         """
 201:         Returns (rows_already_indexed, already_complete). The
 202:         caller (build_index) uses this to decide how many input
 203:         rows to skip, and whether to skip building this source's
 204:         index at all.
 205:         """
 206:         manifest = self._read_manifest()
 207:         if manifest is None:
 208:             return 0, False

--- lines 201-213 ---
 201:         Returns (rows_already_indexed, already_complete). The
 202:         caller (build_index) uses this to decide how many input
 203:         rows to skip, and whether to skip building this source's
 204:         index at all.
 205:         """
 206:         manifest = self._read_manifest()
 207:         if manifest is None:
 208:             return 0, False
 209:         return manifest.get("rows_indexed", 0), manifest.get("complete", False)
 210:
 211:     # -------- ingest --------
 212:
 213:     def add_record(self, entity_id, name, address, country):

--- lines 202-214 ---
 202:         caller (build_index) uses this to decide how many input
 203:         rows to skip, and whether to skip building this source's
 204:         index at all.
 205:         """
 206:         manifest = self._read_manifest()
 207:         if manifest is None:
 208:             return 0, False
 209:         return manifest.get("rows_indexed", 0), manifest.get("complete", False)
 210:
 211:     # -------- ingest --------
 212:
 213:     def add_record(self, entity_id, name, address, country):
 214:

--- lines 204-216 ---
 204:         index at all.
 205:         """
 206:         manifest = self._read_manifest()
 207:         if manifest is None:
 208:             return 0, False
 209:         return manifest.get("rows_indexed", 0), manifest.get("complete", False)
 210:
 211:     # -------- ingest --------
 212:
 213:     def add_record(self, entity_id, name, address, country):
 214:
 215:         _, suffix = split_entity_id(entity_id)
 216:         suffix = str(suffix)

--- lines 246-258 ---
 246:         # Commit on every flush (not just at finalize()) so a kill
 247:         # between flushes loses at most one buffer's worth of rows,
 248:         # and record how far we got so a restart knows where to
 249:         # resume from.
 250:         self.conn.commit()
 251:         self._write_manifest(rows_indexed=self.count, complete=False)
 252:
 253:     def finalize(self):
 254:
 255:         self._flush()
 256:
 257:         if not self._index_built:
 258:             self.conn.execute(

--- lines 260-272 ---
 260:                 "ON postings(key_type, key_value)"
 261:             )
 262:             self.conn.commit()
 263:             self._index_built = True
 264:
 265:         self._write_manifest(rows_indexed=self.count, complete=True)
 266:
 267:     # -------- query --------
 268:
 269:     def bucket(self, key_type, key_value, limit=None):
 270:         if limit is not None:
 271:             cur = self.conn.execute(
 272:                 "SELECT suffix FROM postings WHERE key_type=? AND key_value=? LIMIT ?",

--- lines 296-308 ---
 296: # ============================================================
 297: # BUILD (with resume)
 298: # ============================================================
 299:
 300: def build_index(path, source_prefix, limit=None, backend="memory", db_path=None,
 301:                  manifest_path=None):
 302:     """
 303:     Same signature and behavior as before for backend="memory"
 304:     (no persistence is possible for an in-RAM structure across a
 305:     kernel restart -- if the run dies, a memory-backend index must
 306:     be rebuilt from scratch; use backend="sqlite" for anything
 307:     that needs to survive a Kaggle interruption, per the
 308:     checkpoint/resume plan).

--- lines 305-317 ---
 305:     kernel restart -- if the run dies, a memory-backend index must
 306:     be rebuilt from scratch; use backend="sqlite" for anything
 307:     that needs to survive a Kaggle interruption, per the
 308:     checkpoint/resume plan).
 309:
 310:     backend="sqlite" now resumes: if db_path + its manifest show a
 311:     previously COMPLETE build for this source, the existing
 312:     database is reopened and returned immediately (no re-read of
 313:     `path` at all). If the manifest shows a partial build, only
 314:     the remaining rows of `path` are read and appended.
 315:     """
 316:
 317:     if backend == "sqlite":

--- lines 306-318 ---
 306:     be rebuilt from scratch; use backend="sqlite" for anything
 307:     that needs to survive a Kaggle interruption, per the
 308:     checkpoint/resume plan).
 309:
 310:     backend="sqlite" now resumes: if db_path + its manifest show a
 311:     previously COMPLETE build for this source, the existing
 312:     database is reopened and returned immediately (no re-read of
 313:     `path` at all). If the manifest shows a partial build, only
 314:     the remaining rows of `path` are read and appended.
 315:     """
 316:
 317:     if backend == "sqlite":
 318:         if db_path is None:

--- lines 308-320 ---
 308:     checkpoint/resume plan).
 309:
 310:     backend="sqlite" now resumes: if db_path + its manifest show a
 311:     previously COMPLETE build for this source, the existing
 312:     database is reopened and returned immediately (no re-read of
 313:     `path` at all). If the manifest shows a partial build, only
 314:     the remaining rows of `path` are read and appended.
 315:     """
 316:
 317:     if backend == "sqlite":
 318:         if db_path is None:
 319:             raise ValueError("db_path is required for the sqlite backend")
 320:

--- lines 316-328 ---
 316:
 317:     if backend == "sqlite":
 318:         if db_path is None:
 319:             raise ValueError("db_path is required for the sqlite backend")
 320:
 321:         index = SqliteIndex(source_prefix, db_path, manifest_path=manifest_path)
 322:         rows_done, complete = index.resume_point()
 323:
 324:         if complete:
 325:             print(
 326:                 f"[indexer] {source_prefix} index at {db_path} is already "
 327:                 f"complete ({rows_done:,} rows) -- reusing, no rebuild."
 328:             )

--- lines 317-329 ---
 317:     if backend == "sqlite":
 318:         if db_path is None:
 319:             raise ValueError("db_path is required for the sqlite backend")
 320:
 321:         index = SqliteIndex(source_prefix, db_path, manifest_path=manifest_path)
 322:         rows_done, complete = index.resume_point()
 323:
 324:         if complete:
 325:             print(
 326:                 f"[indexer] {source_prefix} index at {db_path} is already "
 327:                 f"complete ({rows_done:,} rows) -- reusing, no rebuild."
 328:             )
 329:             index.count = rows_done

--- lines 319-331 ---
 319:             raise ValueError("db_path is required for the sqlite backend")
 320:
 321:         index = SqliteIndex(source_prefix, db_path, manifest_path=manifest_path)
 322:         rows_done, complete = index.resume_point()
 323:
 324:         if complete:
 325:             print(
 326:                 f"[indexer] {source_prefix} index at {db_path} is already "
 327:                 f"complete ({rows_done:,} rows) -- reusing, no rebuild."
 328:             )
 329:             index.count = rows_done
 330:             return index
 331:

--- lines 322-334 ---
 322:         rows_done, complete = index.resume_point()
 323:
 324:         if complete:
 325:             print(
 326:                 f"[indexer] {source_prefix} index at {db_path} is already "
 327:                 f"complete ({rows_done:,} rows) -- reusing, no rebuild."
 328:             )
 329:             index.count = rows_done
 330:             return index
 331:
 332:         if rows_done:
 333:             print(
 334:                 f"[indexer] Resuming {source_prefix} index at {db_path}: "

In [40]:
import shutil
from pathlib import Path

WORK = Path("/kaggle/working/amazon_ml_solution")

total, used, free = shutil.disk_usage(WORK)

print("=" * 70)
print("KAGGLE DISK SPACE CHECK")
print("=" * 70)
print(f"Total : {total / (1024**3):.2f} GB")
print(f"Used  : {used  / (1024**3):.2f} GB")
print(f"Free  : {free  / (1024**3):.2f} GB")

print("\nCurrent index sizes:")
for p in sorted((WORK / "index_train").glob("*")):
    print(f"{p.name:35s} {p.stat().st_size / (1024**3):.3f} GB")

======================================================================
KAGGLE DISK SPACE CHECK
======================================================================
Total : 19.52 GB
Used  : 17.43 GB
Free  : 2.08 GB

Current index sizes:
s2_full.sqlite                      0.000 GB
s2_full.sqlite-shm                  0.005 GB
s2_full.sqlite.manifest.json        0.000 GB
s3_full.sqlite                      6.546 GB
s3_full.sqlite-shm                  0.005 GB
s3_full.sqlite-wal                  2.586 GB
s3_full.sqlite.manifest.json        0.000 GB

In [41]:
import sqlite3
from pathlib import Path

S3 = Path("/kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite")

print("=" * 70)
print("S3 SQLITE CHECK")
print("=" * 70)

conn = sqlite3.connect(str(S3))

print("journal_mode :", conn.execute("PRAGMA journal_mode;").fetchone()[0])
print("page_count   :", conn.execute("PRAGMA page_count;").fetchone()[0])
print("page_size    :", conn.execute("PRAGMA page_size;").fetchone()[0])
print("wal_frames   :", conn.execute("PRAGMA wal_checkpoint(PASSIVE);").fetchone())

conn.close()

print("\nFiles:")
for p in sorted(S3.parent.glob("s3_full.sqlite*")):
    print(f"{p.name:35s} {p.stat().st_size / (1024**3):.3f} GB")

======================================================================
S3 SQLITE CHECK
======================================================================
journal_mode : wal
page_count   : 1715963
page_size    : 4096
wal_frames   : (0, 673837, 673837)

Files:
s3_full.sqlite                      6.546 GB
s3_full.sqlite-shm                  0.005 GB
s3_full.sqlite-wal                  2.586 GB
s3_full.sqlite.manifest.json        0.000 GB

In [42]:
import os
from pathlib import Path

print("=" * 80)
print("SEARCHING FOR ANY REMAINING S2 ARTIFACTS")
print("=" * 80)

roots = [
    Path("/kaggle/working"),
    Path("/tmp"),
]

patterns = [
    "*s2_full*",
    "*S2*",
]

for root in roots:
    print(f"\n--- {root} ---")
    try:
        matches = []
        for pattern in patterns:
            matches.extend(root.rglob(pattern))

        seen = set()
        for p in sorted(matches):
            if str(p) in seen:
                continue
            seen.add(str(p))

            try:
                size = p.stat().st_size / (1024**3)
                print(f"{p}    {size:.6f} GB")
            except Exception as e:
                print(f"{p}    [stat failed: {e}]")

    except Exception as e:
        print("SEARCH ERROR:", e)

================================================================================
SEARCHING FOR ANY REMAINING S2 ARTIFACTS
================================================================================

--- /kaggle/working ---
/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite    0.000000 GB
/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite-shm    0.004547 GB
/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite.manifest.json    0.000000 GB

--- /tmp ---

In [43]:
import gc
import sqlite3

print("=" * 80)
print("SEARCHING LIVE PYTHON OBJECTS FOR SQLITE CONNECTIONS")
print("=" * 80)

found = []

for obj in gc.get_objects():
    try:
        if isinstance(obj, sqlite3.Connection):
            found.append(obj)
    except Exception:
        pass

print("SQLite connections found:", len(found))

for i, conn in enumerate(found):
    try:
        print(f"\nConnection {i}")
        print("  journal_mode:", conn.execute("PRAGMA journal_mode").fetchone())
        print("  database_list:", conn.execute("PRAGMA database_list").fetchall())
    except Exception as e:
        print("  ERROR:", repr(e))

================================================================================
SEARCHING LIVE PYTHON OBJECTS FOR SQLITE CONNECTIONS
================================================================================
SQLite connections found: 7

Connection 0
  ERROR: ProgrammingError('SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 131983514519104 and this is thread id 131983848727680.')

Connection 1
  journal_mode: ('delete',)
  database_list: [(0, 'main', '/root/.ipython/profile_default/history.sqlite')]

Connection 2
  journal_mode: ('wal',)
  database_list: [(0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite')]

Connection 3
  journal_mode: ('wal',)
  database_list: [(0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite')]

Connection 4
  journal_mode: ('wal',)
  database_list: [(0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite')]

Connection 5
  ERROR: ProgrammingError('Cannot operate on a closed database.')

Connection 6
  ERROR: ProgrammingError('Cannot operate on a closed database.')

In [44]:
import gc
import sqlite3

print("=" * 80)
print("INSPECTING LIVE S2 SQLITE CONNECTION")
print("=" * 80)

connections = []

for obj in gc.get_objects():
    try:
        if isinstance(obj, sqlite3.Connection):
            connections.append(obj)
    except Exception:
        pass

print("SQLite connections:", len(connections))

# Connection 2 from your previous output
s2_conn = connections[2]

print("\nDatabase:")
print(s2_conn.execute("PRAGMA database_list;").fetchall())

print("\nJournal mode:")
print(s2_conn.execute("PRAGMA journal_mode;").fetchall())

print("\nPage count:")
print(s2_conn.execute("PRAGMA page_count;").fetchall())

print("\nPage size:")
print(s2_conn.execute("PRAGMA page_size;").fetchall())

print("\nIn transaction:")
print(s2_conn.in_transaction)

print("\nSQLite objects:")
tables = s2_conn.execute("""
    SELECT name, type
    FROM sqlite_master
    ORDER BY name;
""").fetchall()

for row in tables:
    print(row)

print("\nSQLite schema:")
schema = s2_conn.execute("""
    SELECT name, type, sql
    FROM sqlite_master
    ORDER BY name;
""").fetchall()

for row in schema:
    print(row)

================================================================================
INSPECTING LIVE S2 SQLITE CONNECTION
================================================================================
SQLite connections: 7

Database:
[(0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite')]

Journal mode:
[('wal',)]

Page count:
[(1559633,)]

Page size:
[(4096,)]

In transaction:
False

SQLite objects:
('attrs', 'table')
('idx_postings', 'index')
('postings', 'table')
('sqlite_autoindex_attrs_1', 'index')

SQLite schema:
('attrs', 'table', 'CREATE TABLE attrs (suffix TEXT PRIMARY KEY, name TEXT, address TEXT, country TEXT)')
('idx_postings', 'index', 'CREATE INDEX idx_postings ON postings(key_type, key_value)')
('postings', 'table', 'CREATE TABLE postings (key_type TEXT, key_value TEXT, suffix TEXT)')
('sqlite_autoindex_attrs_1', 'index', None)

In [45]:
print("=" * 80)
print("VERIFYING LIVE S2 INDEX CONTENT")
print("=" * 80)

# Count indexed rows
print("\n1. POSTINGS COUNT")
postings_count = s2_conn.execute(
    "SELECT COUNT(*) FROM postings;"
).fetchone()[0]
print("postings rows:", postings_count)

# Count attribute records
print("\n2. ATTRS COUNT")
attrs_count = s2_conn.execute(
    "SELECT COUNT(*) FROM attrs;"
).fetchone()[0]
print("attrs rows:", attrs_count)

# Count distinct blocking keys
print("\n3. DISTINCT BLOCKING KEYS")
distinct_keys = s2_conn.execute("""
    SELECT COUNT(*)
    FROM (
        SELECT key_type, key_value
        FROM postings
        GROUP BY key_type, key_value
    );
""").fetchone()[0]
print("distinct blocking keys:", distinct_keys)

# Check a few rows
print("\n4. SAMPLE POSTINGS")
rows = s2_conn.execute("""
    SELECT key_type, key_value, suffix
    FROM postings
    LIMIT 5;
""").fetchall()

for row in rows:
    print(row)

print("\n5. SAMPLE ATTRS")
rows = s2_conn.execute("""
    SELECT suffix, name, address, country
    FROM attrs
    LIMIT 5;
""").fetchall()

for row in rows:
    print(row)

print("\n" + "=" * 80)
print("VERIFICATION COMPLETE")
print("=" * 80)

================================================================================
VERIFYING LIVE S2 INDEX CONTENT
================================================================================

1. POSTINGS COUNT
postings rows: 84986905

2. ATTRS COUNT
attrs rows: 5034616

3. DISTINCT BLOCKING KEYS
distinct blocking keys: 26696614

4. SAMPLE POSTINGS
('UNP4', 'INDIA||रामम', '166376419')
('UNP6', 'INDIA||राममार', '166376419')
('UFL', 'INDIA||राम|लिम', '166376419')
('AN', 'INDIA||570|new', '166376419')
('A2', 'INDIA||570|kh|no', '166376419')

5. SAMPLE ATTRS
('166376419', 'राम मार्केटिंग प्राइवेट लिमिटेड', 'KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi', 'India')
('764573417', '-- Holloway Peak Inc Seafood', '105 ELM ST, MORGANTON, NC', 'US')
('639257739', 'आदित्य प्रॉपर्टीज एलएलपी', 'G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh', 'India')
('163963287', 'Summit Inc', 'GREENSBORO, NC, 19 1/2 STARDUST TRAIL', 'US')
('49942811', 'Delta Tetlecommunication Inc', '914 PIERPONT AVE, CLEVELAND, OH', 'US')

================================================================================
VERIFICATION COMPLETE
================================================================================

In [46]:
print("=" * 80)
print("S2 LIVE DATABASE / WAL STATE")
print("=" * 80)

print("\nDatabase list:")
print(s2_conn.execute("PRAGMA database_list;").fetchall())

print("\nJournal mode:")
print(s2_conn.execute("PRAGMA journal_mode;").fetchall())

print("\nPage count:")
print(s2_conn.execute("PRAGMA page_count;").fetchall())

print("\nFreelist count:")
print(s2_conn.execute("PRAGMA freelist_count;").fetchall())

print("\nSchema version:")
print(s2_conn.execute("PRAGMA schema_version;").fetchall())

print("\nUser version:")
print(s2_conn.execute("PRAGMA user_version;").fetchall())

print("\nConnection transaction state:")
print("in_transaction =", s2_conn.in_transaction)

print("\nFilesystem:")
from pathlib import Path

s2_path = Path(
    "/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite"
)

for p in sorted(s2_path.parent.glob("s2_full.sqlite*")):
    print(
        f"{p.name:40s} "
        f"{p.stat().st_size / (1024**3):.6f} GB"
    )

================================================================================
S2 LIVE DATABASE / WAL STATE
================================================================================

Database list:
[(0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite')]

Journal mode:
[('wal',)]

Page count:
[(1559633,)]

Freelist count:
[(0,)]

Schema version:
[(3,)]

User version:
[(0,)]

Connection transaction state:
in_transaction = False

Filesystem:
s2_full.sqlite                           0.000000 GB
s2_full.sqlite-shm                       0.004547 GB
s2_full.sqlite.manifest.json             0.000000 GB

In [47]:
import os
from pathlib import Path

WORK = Path("/kaggle/working/amazon_ml_solution")

print("=" * 70)
print("CURRENT PIPELINE STATUS")
print("=" * 70)

for d in [
    "index_train",
    "index_test",
    "shards_train",
    "shards_test",
    "checkpoints",
    "models",
    "output",
]:
    p = WORK / d
    print(f"\n[{d}]")
    if not p.exists():
        print("  MISSING")
        continue

    files = list(p.iterdir())
    print(f"  files: {len(files)}")

    for f in sorted(files)[:20]:
        try:
            size_gb = f.stat().st_size / (1024**3)
            print(f"  {f.name:50s} {size_gb:.3f} GB")
        except:
            print(f"  {f.name}")

print("\nDONE")

======================================================================
CURRENT PIPELINE STATUS
======================================================================

[index_train]
  files: 7
  s2_full.sqlite                                     0.000 GB
  s2_full.sqlite-shm                                 0.005 GB
  s2_full.sqlite.manifest.json                       0.000 GB
  s3_full.sqlite                                     6.546 GB
  s3_full.sqlite-shm                                 0.005 GB
  s3_full.sqlite-wal                                 2.586 GB
  s3_full.sqlite.manifest.json                       0.000 GB

[index_test]
  files: 0

[shards_train]
  files: 0

[shards_test]
  files: 0

[checkpoints]
  files: 2
  recall_s2.json                                     0.000 GB
  recall_s3.json                                     0.000 GB

[models]
  files: 0

[output]
  files: 0

DONE

In [48]:
print("S2 live connection:", "s2_conn" in globals())

if "s2_conn" in globals():
    print("S2 page count:", s2_conn.execute("PRAGMA page_count").fetchone()[0])
    print("S2 page size :", s2_conn.execute("PRAGMA page_size").fetchone()[0])

    print(
        "S2 attrs:",
        s2_conn.execute("SELECT COUNT(*) FROM attrs").fetchone()[0]
    )

    print(
        "S2 postings:",
        s2_conn.execute("SELECT COUNT(*) FROM postings").fetchone()[0]
    )
else:
    print("WARNING: s2_conn is not available.")
    print("DO NOT recreate the S2 database.")

S2 live connection: True
S2 page count: 1559633
S2 page size : 4096
S2 attrs: 5034616
S2 postings: 84986905

In [49]:
import os

NB_DIR = "/kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress"

print("Notebook progress files:")
for f in sorted(os.listdir(NB_DIR)):
    print(f)

Notebook progress files:
cell01.py
cell02.py
cell03.py

In [50]:
import re
from pathlib import Path

for path in sorted(Path(NB_DIR).glob("*.py")):
    txt = path.read_text(errors="replace")

    hits = []

    for term in [
        "LightGBM",
        "LGBMClassifier",
        "HistGradientBoostingClassifier",
        "fbeta_score",
        "predict_proba",
        "threshold",
        "validation",
        "train_model",
        "candidate_pairs",
        "matching_results",
    ]:
        if term.lower() in txt.lower():
            hits.append(term)

    if hits:
        print(f"\n{'='*70}")
        print(path.name)
        print("FOUND:", ", ".join(hits))
        print("="*70)

======================================================================
cell01.py
FOUND: validation
======================================================================

======================================================================
cell02.py
FOUND: LightGBM, HistGradientBoostingClassifier, fbeta_score
======================================================================

In [51]:
# ============================================================
# NEXT CELL -- Inspect the existing production notebook cells
# ============================================================

from pathlib import Path
import re

ROOT = Path("/kaggle/input/datasets/tejasweerajput/amazon-v3")

# Find notebook progress / source files
for p in ROOT.rglob("*"):
    if p.is_file() and (
        "notebook" in str(p).lower()
        or p.name.endswith(".py")
    ):
        print(p)

/kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress/cell03.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress/cell01.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress/cell02.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/measurements/measure_reachable_recall.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/measurements/measure_recall_resumable.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/measurements/measure_full_single_source.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/checkpoint.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/candidates.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/blocking.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/similarity.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/data_loader.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/indexer.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/normalize.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/features.py
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/labels.py

In [52]:
from pathlib import Path

P = Path("/kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress")

print("EXISTS:", P.exists())
print("PATH  :", P)

if P.exists():
    files = sorted(P.glob("cell*.py"))
    print("\nNUMBER OF CELLS:", len(files))

    for f in files:
        print(f.name)

EXISTS: True
PATH  : /kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress

NUMBER OF CELLS: 3
cell01.py
cell02.py
cell03.py

EXISTS: True
PATH  : /kaggle/input/datasets/tejasweerajput/amazon-v3/notebook_progress

NUMBER OF CELLS: 3
cell01.py
cell02.py
cell03.py

In [54]:
# ============================================================
# STEP 1 — INSPECT EXISTING PIPELINE APIs
# ============================================================

import sys
import inspect
import os

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

import candidates
import features
import labels
import data_loader
import blocking
import indexer
import similarity

mods = {
    "candidates": candidates,
    "features": features,
    "labels": labels,
    "data_loader": data_loader,
    "blocking": blocking,
    "indexer": indexer,
    "similarity": similarity,
}

for mod_name, mod in mods.items():
    print("\n" + "=" * 80)
    print(mod_name.upper())
    print("=" * 80)

    for name, obj in inspect.getmembers(mod):
        if inspect.isfunction(obj) and not name.startswith("_"):
            try:
                sig = inspect.signature(obj)
            except Exception:
                sig = "(signature unavailable)"

            print(f"\n{name}{sig}")

================================================================================
CANDIDATES
================================================================================

compose_key(country, key_value)

find_candidates(s1_row, index, freq_caps=None)

generate_candidate_pairs_for_row(s1_row, indexes_by_source, freq_caps=None)

make_a4_keys(address, window=3)

make_address_keys(address)

make_at2_keys(address)

make_name_keys(name)

make_unicode_name_keys(name)

================================================================================
FEATURES
================================================================================

address_number_match(address1, address2)

calculate_features(name1, address1, country1, name2, address2, country2)

char_ngram_jaccard(a, b, n=2)

country_match(country1, country2)

is_non_latin(text)

levenshtein_similarity(a, b)

lru_cache(maxsize=128, typed=False)

normalize_address(address)

normalize_business_name(name)

normalize_business_name_script_agnostic(name)

normalize_unicode_preserving(text)

prefix_similarity(a, b, k=4)

suffix_similarity(a, b, k=4)

token_overlap_count(a, b)

token_similarity(text1, text2)

================================================================================
LABELS
================================================================================

label_for(s1_id, candidate_id, ground_truth)

label_for_compact(s1_id, candidate_id, ground_truth)

load_ground_truth(path)

load_ground_truth_compact(path)

matches_for_source(entry, source_prefix)

================================================================================
DATA_LOADER
================================================================================

preview_file(path, n=5)

read_tsv(path)

================================================================================
BLOCKING
================================================================================

make_a4_keys(address, window=3)

make_address_keys(address)

make_all_keys(name, address)

make_at2_keys(address)

make_name_keys(name)

make_unicode_name_keys(name)

normalize_address(address)

normalize_business_name(name)

================================================================================
INDEXER
================================================================================

build_index(path, source_prefix, limit=None, backend='memory', db_path=None, manifest_path=None)

compose_key(country, key_value)

discover_dataset_root(required_files=('train_source1.tsv',), search_root='/kaggle/input')

join_entity_id(prefix, suffix)

make_a4_keys(address, window=3)

make_address_keys(address)

make_at2_keys(address)

make_name_keys(name)

make_unicode_name_keys(name)

read_tsv(path)

split_entity_id(entity_id)

================================================================================
SIMILARITY
================================================================================

address_number_match(address1, address2)

address_similarity(address1, address2)

calculate_similarity(row1, row2)

country_match(country1, country2)

extract_address_numbers(address)

name_similarity(name1, name2)

normalize_address(address)

normalize_business_name(name)

text_similarity(text1, text2)

token_similarity(text1, text2)

In [55]:
# ============================================================
# STEP 2 — PRINT THE ACTUAL PRODUCTION MODULES
# ============================================================

from pathlib import Path

for fname in [
    "candidates.py",
    "features.py",
    "labels.py",
]:
    path = Path(MODULES) / fname

    print("\n\n" + "#" * 100)
    print(f"# {fname}")
    print("#" * 100)

    with open(path, "r", encoding="utf-8") as f:
        print(f.read())

####################################################################################################
# candidates.py
####################################################################################################
"""
candidates.py
============================================================
CHANGE from the original: index.bucket(key_type, composed) is now
called as index.bucket(key_type, composed, limit=cap + 1).

Why cap + 1 and not cap: we still need to distinguish "bucket size
== cap exactly" (keep it) from "bucket size > cap" (drop it), so we
ask for one more row than the cap allows. For MemoryIndex this is
free (already in RAM). For SqliteIndex this turns a potentially
huge, wasted `SELECT ... ` + fetchall() on a hot key into a bounded
`SELECT ... LIMIT cap+1` -- seeSee indexer.py's module docstring
for the full reasoning and why this matters specifically at full
(5M+ row) production scale, not at the 100K-row dev scale the
original numbers were measured on.

Everything else in this file (the candidate dict shape, key_types/
min_freq bookkeeping, generate_candidate_pairs_for_row) is
UNCHANGED.
"""

from blocking import (
    make_name_keys,
    make_unicode_name_keys,
    make_address_keys,
    make_a4_keys,
    make_at2_keys,
    DEFAULT_FREQ_CAPS,
)
from indexer import compose_key


def find_candidates(s1_row, index, freq_caps=None):

    freq_caps = freq_caps or DEFAULT_FREQ_CAPS

    country = s1_row.get("country", "").strip()
    name = s1_row.get("business_name", "")
    address = s1_row.get("business_address", "")

    all_keys = (
        make_name_keys(name)
        + make_unicode_name_keys(name)
        + make_address_keys(address)
        + make_a4_keys(address)
        + make_at2_keys(address)
    )

    candidates = {}

    for key_type, key_value in all_keys:

        cap = freq_caps.get(key_type, DEFAULT_FREQ_CAPS.get(key_type, 500))

        composed = compose_key(country, key_value)

        # Ask for at most cap + 1 rows. If we get back cap + 1, the
        # true bucket is > cap somewhere at or beyond that row, so
        # it's still correctly treated as "too broad" below -- we
        # just never had to materialize the rest of it.
        bucket = index.bucket(key_type, composed, limit=cap + 1)
        bucket_size = len(bucket)

        if bucket_size == 0:
            continue

        if bucket_size > cap:
            continue

        for suffix in bucket:

            entry = candidates.get(suffix)

            if entry is None:
                candidates[suffix] = {
                    "key_types": {key_type},
                    "min_freq": bucket_size,
                }
            else:
                entry["key_types"].add(key_type)
                entry["min_freq"] = min(entry["min_freq"], bucket_size)

    return candidates


def generate_candidate_pairs_for_row(s1_row, indexes_by_source, freq_caps=None):

    s1_id = s1_row.get("entity_id", "")
    rows = []

    for source, index in indexes_by_source.items():

        candidates = find_candidates(s1_row, index, freq_caps=freq_caps)

        for suffix, info in candidates.items():

            candidate_id = f"{source}-{suffix}"

            rows.append(
                {
                    "source1_entity_id": s1_id,
                    "candidate_entity_id": candidate_id,
                    "source": source,
                    "blocking_key_types": "|".join(sorted(info["key_types"])),
                    "blocking_num_keys": len(info["key_types"]),
                    "blocking_min_freq": info["min_freq"],
                }
            )

    return rows



####################################################################################################
# features.py
####################################################################################################
"""
features.py
============================================================
CHANGES from the original (see PHASE1_ARCHITECTURE_AUDIT.md,
sections "Existing feature set" and "Runtime optimization plan"
for the measurements behind these changes):

1. NON-LATIN FIX (correctness, not just speed):
   name_char_similarity / name_levenshtein_similarity / etc. used
   to be computed ONLY on normalize_business_name()/normalize_address(),
   which strip non-Latin scripts to "". For a true-match pair where
   both sides are in Devanagari/Telugu/Kannada/Bengali, every
   similarity feature silently became 0 or the "missing" default,
   even though the strings are genuinely very similar. This module
   now also computes the same feature suite on a script-agnostic
   normalization (normalize.normalize_unicode_preserving) and uses
   whichever normalization actually has content, so the ML model
   gets real signal on non-Latin rows instead of a constant.

2. SPEED: the original had TWO independent implementations of
   "edit-distance-based ratio" per field (text_similarity() via
   difflib.SequenceMatcher, and levenshtein_similarity() via
   rapidfuzz). difflib's SequenceMatcher is pure Python and is the
   single most expensive call in the old feature set -- at the
   ~440M-pair scale estimated for the full test set, removing one
   of the two redundant passes per field is a meaningful win.
   rapidfuzz.fuzz.ratio() is a compatible-by-design, C-accelerated
   reimplementation of the same "difflib-style" ratio, so
   name_char_similarity / address_char_similarity are now computed
   with it too. If rapidfuzz is unavailable, this falls back to the
   original difflib implementation exactly as before -- no feature
   changes shape, only which backend computes it.

3. Feature list is APPENDED to, not reordered or removed, so
   existing train_features_*.tsv files stay a strict prefix-
   compatible subset of the new schema (old columns keep the same
   name and meaning).
"""

from functools import lru_cache

from normalize import (
    normalize_business_name,
    normalize_address,
    normalize_business_name_script_agnostic,
    normalize_unicode_preserving,
    is_non_latin,
)

from similarity import token_similarity, address_number_match, country_match


# --------------------------------------------------------------
# Ratio backend: rapidfuzz preferred (C-accelerated, difflib-
# compatible ratio), pure-Python difflib as a guaranteed fallback.
# One implementation now serves BOTH "char_similarity" and
# "levenshtein_similarity" -- see change #2 above.
# --------------------------------------------------------------

try:
    from rapidfuzz.fuzz import ratio as _rapidfuzz_ratio

    def _ratio(a, b):
        if not a or not b:
            return 0.0
        return _rapidfuzz_ratio(a, b) / 100.0

except ImportError:

    from difflib import SequenceMatcher

    def _ratio(a, b):
        if not a or not b:
            return 0.0
        return SequenceMatcher(None, a, b).ratio()


levenshtein_similarity = _ratio  # kept as a public name for compatibility


@lru_cache(maxsize=2_000_000)
def cached_normalize_business_name(value):
    return normalize_business_name(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_address(value):
    return normalize_address(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_business_name_unicode(value):
    return normalize_business_name_script_agnostic(value)


@lru_cache(maxsize=2_000_000)
def cached_normalize_address_unicode(value):
    return normalize_unicode_preserving(value)


# --------------------------------------------------------------
# Character n-gram Jaccard
# --------------------------------------------------------------

def char_ngram_jaccard(a, b, n=2):

    if not a or not b:
        return 0.0

    if len(a) < n or len(b) < n:
        return 0.0

    grams_a = {a[i:i + n] for i in range(len(a) - n + 1)}
    grams_b = {b[i:i + n] for i in range(len(b) - n + 1)}

    if not grams_a or not grams_b:
        return 0.0

    return len(grams_a & grams_b) / len(grams_a | grams_b)


def prefix_similarity(a, b, k=4):

    if not a or not b:
        return 0.0

    a_p, b_p = a[:k], b[:k]
    max_len = min(len(a_p), len(b_p))

    if max_len == 0:
        return 0.0

    matched = sum(1 for x, y in zip(a_p, b_p) if x == y)
    return matched / max_len


def suffix_similarity(a, b, k=4):

    if not a or not b:
        return 0.0

    a_s, b_s = a[-k:], b[-k:]
    max_len = min(len(a_s), len(b_s))

    if max_len == 0:
        return 0.0

    matched = sum(1 for x, y in zip(reversed(a_s), reversed(b_s)) if x == y)
    return matched / max_len


def token_overlap_count(a, b):

    if not a or not b:
        return 0

    return len(set(a.split()) & set(b.split()))


# --------------------------------------------------------------
# Feature columns
# --------------------------------------------------------------
# Original columns are UNCHANGED in name, meaning and position.
# New columns are appended at the end.

FEATURE_COLUMNS = [

    # Name features (original)
    "name_exact_match",
    "name_char_similarity",
    "name_levenshtein_similarity",
    "name_token_jaccard",
    "name_token_overlap",
    "name_compact_similarity",
    "name_prefix_similarity",
    "name_suffix_similarity",
    "name_char_ngram_jaccard",

    # Address features (original)
    "address_exact_match",
    "address_char_similarity",
    "address_levenshtein_similarity",
    "address_token_jaccard",
    "address_token_overlap",
    "address_number_match",
    "address_char_ngram_jaccard",

    # Other (original)
    "country_match",
    "name_missing",
    "address_missing",
    "combined_name_address_score",

    # ---- NEW: non-Latin fallback signal ----
    "name_is_non_latin",
    "address_is_non_latin",
    "name_char_similarity_unicode",
    "name_token_jaccard_unicode",
]


def calculate_features(name1, address1, country1, name2, address2, country2):

    # -------- ASCII-folded normalization (original path) --------
    n1 = cached_normalize_business_name(name1)
    n2 = cached_normalize_business_name(name2)
    a1 = cached_normalize_address(address1)
    a2 = cached_normalize_address(address2)

    name_missing = int(not n1 or not n2)
    address_missing = int(not a1 or not a2)

    name_char_sim = _ratio(n1, n2)
    name_lev_sim = _ratio(n1, n2)  # same backend now, see module docstring #2
    name_tok_jaccard = token_similarity(n1, n2)
    name_compact_sim = _ratio(n1.replace(" ", ""), n2.replace(" ", ""))

    address_char_sim = _ratio(a1, a2)
    address_lev_sim = _ratio(a1, a2)
    address_tok_jaccard = token_similarity(a1, a2)

    combined = 0.6 * name_char_sim + 0.4 * address_char_sim

    # -------- NEW: script-agnostic fallback for non-Latin names --------
    # Only pay for the extra normalization/similarity work when the
    # ASCII-folded form actually lost content -- cheap for the
    # (majority) Latin-script rows, since is_non_latin() short-
    # circuits on the already-cached ascii_form.
    name_non_latin = is_non_latin(name1) or is_non_latin(name2)

    if name_non_latin:
        un1 = cached_normalize_business_name_unicode(name1)
        un2 = cached_normalize_business_name_unicode(name2)
        name_char_sim_unicode = _ratio(un1, un2)
        name_tok_jaccard_unicode = token_similarity(un1, un2)
    else:
        name_char_sim_unicode = name_char_sim
        name_tok_jaccard_unicode = name_tok_jaccard

    address_non_latin = is_non_latin(address1) or is_non_latin(address2)

    return {

        "name_exact_match": int(bool(n1) and n1 == n2),
        "name_char_similarity": name_char_sim,
        "name_levenshtein_similarity": name_lev_sim,
        "name_token_jaccard": name_tok_jaccard,
        "name_token_overlap": token_overlap_count(n1, n2),
        "name_compact_similarity": name_compact_sim,
        "name_prefix_similarity": prefix_similarity(n1, n2),
        "name_suffix_similarity": suffix_similarity(n1, n2),
        "name_char_ngram_jaccard": char_ngram_jaccard(n1, n2),

        "address_exact_match": int(bool(a1) and a1 == a2),
        "address_char_similarity": address_char_sim,
        "address_levenshtein_similarity": address_lev_sim,
        "address_token_jaccard": address_tok_jaccard,
        "address_token_overlap": token_overlap_count(a1, a2),
        "address_number_match": address_number_match(address1, address2),
        "address_char_ngram_jaccard": char_ngram_jaccard(a1, a2),

        "country_match": country_match(country1, country2),
        "name_missing": name_missing,
        "address_missing": address_missing,
        "combined_name_address_score": combined,

        "name_is_non_latin": int(name_non_latin),
        "address_is_non_latin": int(address_non_latin),
        "name_char_similarity_unicode": name_char_sim_unicode,
        "name_token_jaccard_unicode": name_tok_jaccard_unicode,
    }



####################################################################################################
# labels.py
####################################################################################################
"""
labels.py
============================================================
PRESERVED: load_ground_truth() / label_for() are UNCHANGED and
still correct -- keep using them for train_10k-scale work where
their extra convenience (pre-split "S2"/"S3"/"all" sets) is cheap.

ADDED: load_ground_truth_compact(), a memory-lean alternative for
the full 2.2M-row train_ground_truth.tsv.

MEASURED (this sandbox, 3.9 GB total RAM, Python 3.12):
  load_ground_truth() on the full file -> 2,206,821 entries,
  peak RSS ~2.84 GB, ~25s.

That is the ENTIRE per-S1-row ground truth structure sitting in
RAM before candidate generation, feature calculation, indexes, or
anything else has been loaded -- on a Kaggle instance with, say,
13-16 GB total RAM, this is a meaningful fixed cost, and on a
smaller instance it can be the difference between fitting in
memory and an OOM kill mid-run (which is exactly what truncated a
larger validation run attempted during this audit).

The cost comes from storing THREE Python sets per S1 row
("S2", "S3", "all") instead of one -- each empty/small set has
real fixed overhead (hash table allocation) independent of how
many ids it holds, so building three per row roughly triples the
per-row container overhead versus storing the raw id set once and
filtering by prefix on demand (which is O(len(entry)), and entries
have on average only a handful of matches).

load_ground_truth_compact() stores exactly one frozenset per row.
matches_for_source()/label_for_compact() below reconstruct the
"S2 only" / "S3 only" view on demand, at effectively no extra cost
since per-row match counts are small (median well under 10, per
analyze_ground_truth.py's own distribution check).
"""

import csv


def load_ground_truth(path):
    """
    UNCHANGED. Returns dict: source1_entity_id -> {
        "S2": set of matched S2 ids,
        "S3": set of matched S3 ids,
        "all": set of every matched id (any source),
    }
    """

    ground_truth = {}

    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:

        reader = csv.DictReader(f, delimiter="\t")

        for row in reader:

            s1_id = row["source1_entity_id"]
            raw = (row.get("matched_entity_ids") or "").strip()

            if raw:
                all_ids = {x.strip() for x in raw.split(",") if x.strip()}
            else:
                all_ids = set()

            ground_truth[s1_id] = {
                "S2": {x for x in all_ids if x.startswith("S2-")},
                "S3": {x for x in all_ids if x.startswith("S3-")},
                "all": all_ids,
            }

    return ground_truth


def label_for(s1_id, candidate_id, ground_truth):
    entry = ground_truth.get(s1_id)
    if not entry:
        return 0
    return int(candidate_id in entry["all"])


# ============================================================
# NEW: memory-lean loader for full-scale (2.2M+ row) ground truth
# ============================================================

_EMPTY_FROZENSET = frozenset()


def load_ground_truth_compact(path):
    """
    Returns dict: source1_entity_id -> frozenset of matched ids
    (mixed S2-*/S3-*). One container per row instead of three.

    frozenset (vs set) is used because these are never mutated
    after loading, and CPython's frozenset has slightly less
    per-object overhead than a mutable set for read-only use.
    """

    ground_truth = {}

    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:

        reader = csv.DictReader(f, delimiter="\t")

        for row in reader:

            s1_id = row["source1_entity_id"]
            raw = (row.get("matched_entity_ids") or "").strip()

            if raw:
                ground_truth[s1_id] = frozenset(
                    x.strip() for x in raw.split(",") if x.strip()
                )
            else:
                ground_truth[s1_id] = _EMPTY_FROZENSET

    return ground_truth


def matches_for_source(entry, source_prefix):
    """
    entry: a frozenset from load_ground_truth_compact(). Filters
    by prefix on demand -- cheap, since entry is typically only a
    handful of ids (see analyze_ground_truth.py's match_count
    distribution: median match count is small).
    """
    if not entry:
        return _EMPTY_FROZENSET
    return frozenset(x for x in entry if x.startswith(source_prefix))


def label_for_compact(s1_id, candidate_id, ground_truth):
    entry = ground_truth.get(s1_id)
    if not entry:
        return 0
    return int(candidate_id in entry)

In [56]:
# ============================================================
# STEP 3 — INSPECT ACTUAL INDEX OBJECT API
# ============================================================

import sys
import inspect

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

import indexer

print("=" * 80)
print("INDEXER CLASSES / PUBLIC METHODS")
print("=" * 80)

for name, obj in inspect.getmembers(indexer):
    if inspect.isclass(obj) and not name.startswith("_"):
        print(f"\nCLASS: {name}")
        print("-" * 60)

        for method_name, method in inspect.getmembers(obj):
            if not method_name.startswith("_"):
                try:
                    sig = inspect.signature(method)
                    print(f"{method_name}{sig}")
                except Exception:
                    pass

================================================================================
INDEXER CLASSES / PUBLIC METHODS
================================================================================

CLASS: MemoryIndex
------------------------------------------------------------
add_record(self, entity_id, name, address, country)
bucket(self, key_type, key_value, limit=None)
get_attrs(self, suffix)
num_keys(self)

CLASS: Path
------------------------------------------------------------
absolute(self)
as_posix(self)
as_uri(self)
chmod(self, mode, *, follow_symlinks=True)
cwd()
exists(self, *, follow_symlinks=True)
expanduser(self)
glob(self, pattern, *, case_sensitive=None)
group(self)
hardlink_to(self, target)
home()
is_absolute(self)
is_block_device(self)
is_char_device(self)
is_dir(self)
is_fifo(self)
is_file(self)
is_junction(self)
is_mount(self)
is_relative_to(self, other, /, *_deprecated)
is_reserved(self)
is_socket(self)
is_symlink(self)
iterdir(self)
joinpath(self, *pathsegments)
lchmod(self, mode)
lstat(self)
match(self, path_pattern, *, case_sensitive=None)
mkdir(self, mode=511, parents=False, exist_ok=False)
open(self, mode='r', buffering=-1, encoding=None, errors=None, newline=None)
owner(self)
read_bytes(self)
read_text(self, encoding=None, errors=None)
readlink(self)
relative_to(self, other, /, *_deprecated, walk_up=False)
rename(self, target)
replace(self, target)
resolve(self, strict=False)
rglob(self, pattern, *, case_sensitive=None)
rmdir(self)
samefile(self, other_path)
stat(self, *, follow_symlinks=True)
symlink_to(self, target, target_is_directory=False)
touch(self, mode=438, exist_ok=True)
unlink(self, missing_ok=False)
walk(self, top_down=True, on_error=None, follow_symlinks=False)
with_name(self, name)
with_segments(self, *pathsegments)
with_stem(self, stem)
with_suffix(self, suffix)
write_bytes(self, data)
write_text(self, data, encoding=None, errors=None, newline=None)

CLASS: SqliteIndex
------------------------------------------------------------
add_record(self, entity_id, name, address, country)
bucket(self, key_type, key_value, limit=None)
finalize(self)
get_attrs(self, suffix)
num_keys(self)
resume_point(self)

CLASS: defaultdict
------------------------------------------------------------
fromkeys(iterable, value=None, /)
get(self, key, default=None, /)
popitem(self, /)
setdefault(self, key, default=None, /)

In [57]:
# ============================================================
# STEP 4 — CHECK EXISTING INDEX FILES
# ============================================================

import os
import json

INDEX_DIR = "/kaggle/working/amazon_ml_solution/index_train"

print("=" * 80)
print("CURRENT INDEX FILES")
print("=" * 80)

for name in sorted(os.listdir(INDEX_DIR)):
    path = os.path.join(INDEX_DIR, name)

    if os.path.isfile(path):
        size_gb = os.path.getsize(path) / (1024**3)
        print(f"{name:45s} {size_gb:10.4f} GB")

print("\n" + "=" * 80)
print("MANIFESTS")
print("=" * 80)

for name in sorted(os.listdir(INDEX_DIR)):
    if name.endswith(".manifest.json"):
        path = os.path.join(INDEX_DIR, name)
        print(f"\n{name}")
        with open(path, "r") as f:
            print(json.dumps(json.load(f), indent=2))

================================================================================
CURRENT INDEX FILES
================================================================================
s2_full.sqlite                                    0.0000 GB
s2_full.sqlite-shm                                0.0045 GB
s2_full.sqlite.manifest.json                      0.0000 GB
s3_full.sqlite                                    6.5459 GB
s3_full.sqlite-shm                                0.0050 GB
s3_full.sqlite-wal                                2.5855 GB
s3_full.sqlite.manifest.json                      0.0000 GB

================================================================================
MANIFESTS
================================================================================

s2_full.sqlite.manifest.json
{
  "source_prefix": "S2",
  "rows_indexed": 5034616,
  "complete": true
}

s3_full.sqlite.manifest.json
{
  "source_prefix": "S3",
  "rows_indexed": 5285603,
  "complete": true
}

In [58]:
# ============================================================
# STEP 5 — FIND LIVE INDEX / SQLITE OBJECTS
# ============================================================

import gc
import sqlite3
import inspect

print("=" * 80)
print("LIVE INDEX-RELATED OBJECTS")
print("=" * 80)

# Check explicitly named variables first
for var_name in ["s2_conn", "s2_index", "s3_index", "index_s2", "index_s3"]:
    if var_name in globals():
        obj = globals()[var_name]
        print(
            f"{var_name:15s} -> "
            f"{type(obj).__module__}.{type(obj).__name__}"
        )

print("\n" + "=" * 80)
print("SQLITE CONNECTIONS CURRENTLY VISIBLE")
print("=" * 80)

for name, obj in globals().items():
    try:
        if isinstance(obj, sqlite3.Connection):
            print(f"{name:20s} -> sqlite3.Connection")
    except Exception:
        pass

print("\n" + "=" * 80)
print("SqliteIndex CONSTRUCTOR")
print("=" * 80)

from indexer import SqliteIndex, build_index

print("SqliteIndex:", inspect.signature(SqliteIndex))
print("build_index:", inspect.signature(build_index))

================================================================================
LIVE INDEX-RELATED OBJECTS
================================================================================
s2_conn         -> sqlite3.Connection

================================================================================
SQLITE CONNECTIONS CURRENTLY VISIBLE
================================================================================
con                  -> sqlite3.Connection
conn                 -> sqlite3.Connection
s2_conn              -> sqlite3.Connection

================================================================================
SqliteIndex CONSTRUCTOR
================================================================================
SqliteIndex: (source_prefix, db_path, manifest_path=None)
build_index: (path, source_prefix, limit=None, backend='memory', db_path=None, manifest_path=None)

In [59]:
# ============================================================
# STEP 6 — VERIFY THE LIVE S2 CONNECTION
# ============================================================

if "s2_conn" not in globals():
    raise RuntimeError(
        "CRITICAL: s2_conn is not present. "
        "STOP HERE — do NOT create a new S2 sqlite connection."
    )

s2_conn = globals()["s2_conn"]

print("=" * 80)
print("S2 LIVE CONNECTION VERIFICATION")
print("=" * 80)

print("SQLite version:", s2_conn.execute(
    "SELECT sqlite_version()"
).fetchone()[0])

print("Journal mode:", s2_conn.execute(
    "PRAGMA journal_mode"
).fetchone()[0])

print("Page count:", s2_conn.execute(
    "PRAGMA page_count"
).fetchone()[0])

print("Page size:", s2_conn.execute(
    "PRAGMA page_size"
).fetchone()[0])

attrs_count = s2_conn.execute(
    "SELECT COUNT(*) FROM attrs"
).fetchone()[0]

postings_count = s2_conn.execute(
    "SELECT COUNT(*) FROM postings"
).fetchone()[0]

keys_count = s2_conn.execute(
    "SELECT COUNT(*) FROM attrs"
).fetchone()[0]

print("attrs rows:", attrs_count)
print("postings rows:", postings_count)

print("\nExpected completed S2:")
print("attrs    ≈ 5,034,616")
print("postings ≈ 84,986,905")

if attrs_count == 5034616 and postings_count == 84986905:
    print("\n[S2] LIVE INDEX VERIFIED.")
else:
    print("\n[WARNING] Counts differ from the previously verified S2 index.")
    print("DO NOT proceed to training until we inspect this.")

================================================================================
S2 LIVE CONNECTION VERIFICATION
================================================================================
SQLite version: 3.37.2
Journal mode: wal
Page count: 1559633
Page size: 4096
attrs rows: 5034616
postings rows: 84986905

Expected completed S2:
attrs    ≈ 5,034,616
postings ≈ 84,986,905

[S2] LIVE INDEX VERIFIED.

In [60]:
# ============================================================
# STEP 7 — ATTACH PRODUCTION INDEXES
# ============================================================

import sys
import os
import sqlite3

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

from indexer import SqliteIndex

INDEX_DIR = "/kaggle/working/amazon_ml_solution/index_train"

S2_DB = os.path.join(INDEX_DIR, "s2_full.sqlite")
S2_MANIFEST = os.path.join(INDEX_DIR, "s2_full.sqlite.manifest.json")

S3_DB = os.path.join(INDEX_DIR, "s3_full.sqlite")
S3_MANIFEST = os.path.join(INDEX_DIR, "s3_full.sqlite.manifest.json")


# ------------------------------------------------------------
# S2
# ------------------------------------------------------------
# IMPORTANT:
# s2_conn is the already-live connection to the completed
# S2 WAL-backed database. DO NOT reopen s2_full.sqlite.
# ------------------------------------------------------------

if "s2_conn" not in globals():
    raise RuntimeError(
        "s2_conn is missing. STOP — do not reopen the S2 DB."
    )

print("Using existing live S2 SQLite connection.")

# The production SqliteIndex wrapper expects its own connection
# internally, so for S2 we create a lightweight wrapper object
# WITHOUT invoking its constructor.
s2_index = object.__new__(SqliteIndex)

s2_index.source_prefix = "S2"
s2_index.db_path = S2_DB
s2_index.manifest_path = S2_MANIFEST
s2_index.conn = s2_conn


# ------------------------------------------------------------
# S3
# ------------------------------------------------------------
# S3 exists as a real complete SQLite database + WAL.
# ------------------------------------------------------------

print("Opening S3 production index...")

s3_index = SqliteIndex(
    "S3",
    S3_DB,
    manifest_path=S3_MANIFEST,
)

print("S3 opened.")


# ------------------------------------------------------------
# Verify both indexes through the public API
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PRODUCTION INDEXES READY")
print("=" * 80)

print("S2 num_keys :", s2_index.num_keys())
print("S3 num_keys :", s3_index.num_keys())

indexes_by_source = {
    "S2": s2_index,
    "S3": s3_index,
}

print("\nindexes_by_source:")
print(indexes_by_source.keys())

Using existing live S2 SQLite connection.
Opening S3 production index...
S3 opened.

================================================================================
PRODUCTION INDEXES READY
================================================================================
S2 num_keys : 26696614
S3 num_keys : 28341068

indexes_by_source:
dict_keys(['S2', 'S3'])

In [64]:
# ============================================================
# STEP 8 — LOAD TRAIN S1 + COMPACT GROUND TRUTH
# FIX: read_tsv() returns a generator
# ============================================================

import os
import sys
import gc

MODULES = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULES not in sys.path:
    sys.path.insert(0, MODULES)

from data_loader import read_tsv
from labels import load_ground_truth_compact

TRAIN_DIR = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/train"
)

TRAIN_S1 = os.path.join(TRAIN_DIR, "train_source1.tsv")
TRAIN_GT = os.path.join(TRAIN_DIR, "train_ground_truth.tsv")

print("=" * 80)
print("LOADING TRAIN S1")
print("=" * 80)

# read_tsv() -> generator, so materialize it once
train_s1 = list(read_tsv(TRAIN_S1))

print("S1 rows:", len(train_s1))

print("\nS1 sample:")
for row in train_s1[:3]:
    print(row)

print("\n" + "=" * 80)
print("LOADING COMPACT GROUND TRUTH")
print("=" * 80)

ground_truth = load_ground_truth_compact(TRAIN_GT)

print("GT entries:", len(ground_truth))

print("\nGT sample:")
for k, v in list(ground_truth.items())[:3]:
    print(k, "->", list(v)[:10])

print("\n" + "=" * 80)
print("STEP 8 COMPLETE")
print("=" * 80)

================================================================================
LOADING TRAIN S1
================================================================================
S1 rows: 2206821

S1 sample:
{'entity_id': 'S1-925783039', 'business_name': "Orelee's Barbershop", 'business_address': '1795 Westchester Drive, High Point, NC', 'country': 'US'}
{'entity_id': 'S1-773889195', 'business_name': 'Prime Money', 'business_address': '17560 Ellis Road, Tahlequah, OK', 'country': 'US'}
{'entity_id': 'S1-377745466', 'business_name': 'B+ Retail Inc', 'business_address': '1712 Montebello Avenue, Phoenix, AZ', 'country': 'US'}

================================================================================
LOADING COMPACT GROUND TRUTH
================================================================================
GT entries: 2206821

GT sample:
S1-965667 -> ['S3-775321672', 'S2-743505751', 'S3-11291185', 'S2-681193310', 'S3-860443364']
S1-55344266 -> ['S2-197070651', 'S3-478195123', 'S3-384364074', 'S2-249013014']
S1-343815751 -> ['S2-479876582', 'S2-790675320', 'S3-878454467']

================================================================================
STEP 8 COMPLETE
================================================================================

In [65]:
# ============================================================
# STEP 9 — CREATE TRAIN / VALIDATION S1 SPLIT
# ============================================================

import random

SEED = 42
VAL_FRACTION = 0.20

rng = random.Random(SEED)

all_indices = list(range(len(train_s1)))
rng.shuffle(all_indices)

val_size = int(len(all_indices) * VAL_FRACTION)

val_indices = all_indices[:val_size]
train_indices = all_indices[val_size:]

print("=" * 80)
print("TRAIN / VALIDATION SPLIT")
print("=" * 80)

print("Total S1 :", len(train_s1))
print("Train S1 :", len(train_indices))
print("Val S1   :", len(val_indices))

print("\nExample validation IDs:")

for idx in val_indices[:5]:
    print(train_s1[idx].get("entity_id"))

================================================================================
TRAIN / VALIDATION SPLIT
================================================================================
Total S1 : 2206821
Train S1 : 1765457
Val S1   : 441364

Example validation IDs:
S1-192830128
S1-679331852
S1-412430032
S1-996048824
S1-505668571

In [66]:
# ============================================================
# STEP 10 — CANDIDATE GENERATION PILOT
# ============================================================

from candidates import generate_candidate_pairs_for_row
import time
import gc

PILOT_ROWS = 1000

pilot_indices = train_indices[:PILOT_ROWS]

pilot_pairs = []

t0 = time.time()

for counter, idx in enumerate(pilot_indices, start=1):

    s1_row = train_s1[idx]

    rows = generate_candidate_pairs_for_row(
        s1_row,
        indexes_by_source,
    )

    pilot_pairs.extend(rows)

    if counter % 100 == 0:
        elapsed = time.time() - t0
        rate = counter / elapsed if elapsed > 0 else 0

        print(
            f"Processed {counter:,}/{PILOT_ROWS:,} "
            f"| pairs={len(pilot_pairs):,} "
            f"| rate={rate:.1f} S1/s"
        )

elapsed = time.time() - t0

print("\n" + "=" * 80)
print("PILOT COMPLETE")
print("=" * 80)

print(f"S1 rows        : {PILOT_ROWS:,}")
print(f"Candidate pairs: {len(pilot_pairs):,}")
print(f"Time           : {elapsed:.2f} sec")
print(f"Rate           : {PILOT_ROWS / elapsed:.2f} S1/s")

if pilot_pairs:
    print("\nFirst 5 candidate rows:")
    for row in pilot_pairs[:5]:
        print(row)

Processed 100/1,000 | pairs=43,475 | rate=39.2 S1/s
Processed 200/1,000 | pairs=86,118 | rate=49.7 S1/s
Processed 300/1,000 | pairs=128,116 | rate=54.1 S1/s
Processed 400/1,000 | pairs=173,277 | rate=57.2 S1/s
Processed 500/1,000 | pairs=218,521 | rate=59.0 S1/s
Processed 600/1,000 | pairs=260,344 | rate=60.7 S1/s
Processed 700/1,000 | pairs=301,502 | rate=61.8 S1/s
Processed 800/1,000 | pairs=338,128 | rate=63.3 S1/s
Processed 900/1,000 | pairs=382,093 | rate=64.0 S1/s
Processed 1,000/1,000 | pairs=424,879 | rate=64.6 S1/s

================================================================================
PILOT COMPLETE
================================================================================
S1 rows        : 1,000
Candidate pairs: 424,879
Time           : 15.48 sec
Rate           : 64.58 S1/s

First 5 candidate rows:
{'source1_entity_id': 'S1-223467729', 'candidate_entity_id': 'S2-688425898', 'source': 'S2', 'blocking_key_types': 'NS6', 'blocking_num_keys': 1, 'blocking_min_freq': 90}
{'source1_entity_id': 'S1-223467729', 'candidate_entity_id': 'S2-843192498', 'source': 'S2', 'blocking_key_types': 'NS6', 'blocking_num_keys': 1, 'blocking_min_freq': 90}
{'source1_entity_id': 'S1-223467729', 'candidate_entity_id': 'S2-596204452', 'source': 'S2', 'blocking_key_types': 'NS6', 'blocking_num_keys': 1, 'blocking_min_freq': 90}
{'source1_entity_id': 'S1-223467729', 'candidate_entity_id': 'S2-362818786', 'source': 'S2', 'blocking_key_types': 'NS6', 'blocking_num_keys': 1, 'blocking_min_freq': 90}
{'source1_entity_id': 'S1-223467729', 'candidate_entity_id': 'S2-800357051', 'source': 'S2', 'blocking_key_types': 'NS6', 'blocking_num_keys': 1, 'blocking_min_freq': 90}

In [67]:
# ============================================================
# STEP 10B — PILOT CANDIDATE STATISTICS
# ============================================================

from collections import Counter

pairs_by_s1 = Counter(
    row["source1_entity_id"]
    for row in pilot_pairs
)

pairs_by_source = Counter(
    row["source"]
    for row in pilot_pairs
)

print("=" * 80)
print("CANDIDATE STATISTICS")
print("=" * 80)

print("Total pairs :", len(pilot_pairs))
print("Unique S1   :", len(pairs_by_s1))

print("\nPairs by source:")
for source, count in sorted(pairs_by_source.items()):
    print(f"  {source}: {count:,}")

counts = list(pairs_by_s1.values())

if counts:
    print("\nCandidates per S1:")
    print("  min    :", min(counts))
    print("  median :", sorted(counts)[len(counts)//2])
    print("  mean   :", sum(counts) / len(counts))
    print("  max    :", max(counts))

print("\nS1 rows with zero candidates:",
      PILOT_ROWS - len(pairs_by_s1))

================================================================================
CANDIDATE STATISTICS
================================================================================
Total pairs : 424879
Unique S1   : 999

Pairs by source:
  S2: 207,707
  S3: 217,172

Candidates per S1:
  min    : 1
  median : 380
  mean   : 425.3043043043043
  max    : 1712

S1 rows with zero candidates: 1

In [68]:
# ============================================================
# STEP 11 — PILOT CANDIDATE RECALL
# ============================================================

from collections import defaultdict

# Candidate IDs grouped by S1
candidate_ids_by_s1 = defaultdict(set)

for row in pilot_pairs:
    candidate_ids_by_s1[row["source1_entity_id"]].add(
        row["candidate_entity_id"]
    )

total_gt_matches = 0
found_gt_matches = 0
rows_with_gt = 0
rows_with_all_gt_found = 0
rows_with_missing_gt = 0

missing_examples = []

for idx in pilot_indices:

    s1_id = train_s1[idx]["entity_id"]

    gt = ground_truth.get(s1_id, frozenset())

    # Only matches that should be discoverable from S2/S3
    gt = set(gt)

    candidates = candidate_ids_by_s1.get(s1_id, set())

    if gt:
        rows_with_gt += 1

    total_gt_matches += len(gt)

    found = gt & candidates

    found_gt_matches += len(found)

    if gt and found == gt:
        rows_with_all_gt_found += 1

    missing = gt - candidates

    if missing:
        rows_with_missing_gt += 1

        if len(missing_examples) < 10:
            missing_examples.append(
                {
                    "s1": s1_id,
                    "missing": sorted(missing),
                    "num_candidates": len(candidates),
                }
            )

recall = (
    found_gt_matches / total_gt_matches
    if total_gt_matches
    else 0.0
)

row_recall = (
    rows_with_all_gt_found / rows_with_gt
    if rows_with_gt
    else 0.0
)

print("=" * 80)
print("PILOT CANDIDATE RECALL")
print("=" * 80)

print(f"Pilot S1 rows              : {PILOT_ROWS:,}")
print(f"S1 rows with GT matches    : {rows_with_gt:,}")
print(f"Total GT matches           : {total_gt_matches:,}")
print(f"GT matches found           : {found_gt_matches:,}")
print(f"GT matches missing         : {total_gt_matches - found_gt_matches:,}")

print(f"\nPAIR-LEVEL RECALL           : {recall:.6%}")
print(f"S1-ROW COMPLETE RECALL     : {row_recall:.6%}")

print(f"\nRows with ≥1 missing GT     : {rows_with_missing_gt:,}")

if missing_examples:
    print("\nFirst missing examples:")
    for ex in missing_examples:
        print(ex)
else:
    print("\nNo missing GT matches in the pilot.")

================================================================================
PILOT CANDIDATE RECALL
================================================================================
Pilot S1 rows              : 1,000
S1 rows with GT matches    : 934
Total GT matches           : 3,357
GT matches found           : 3,200
GT matches missing         : 157

PAIR-LEVEL RECALL           : 95.323205%
S1-ROW COMPLETE RECALL     : 86.402570%

Rows with ≥1 missing GT     : 127

First missing examples:
{'s1': 'S1-641216566', 'missing': ['S3-131085423', 'S3-56338966'], 'num_candidates': 858}
{'s1': 'S1-101171510', 'missing': ['S2-925453893', 'S3-133430367'], 'num_candidates': 954}
{'s1': 'S1-54882400', 'missing': ['S2-966298126'], 'num_candidates': 433}
{'s1': 'S1-588906422', 'missing': ['S2-228689952', 'S2-252521378', 'S2-717847741', 'S3-924363909'], 'num_candidates': 1}
{'s1': 'S1-217801541', 'missing': ['S2-486047566', 'S3-234581522', 'S3-547148581'], 'num_candidates': 329}
{'s1': 'S1-210800211', 'missing': ['S3-627029746'], 'num_candidates': 365}
{'s1': 'S1-136572517', 'missing': ['S2-127573242', 'S3-719165640', 'S3-932571654'], 'num_candidates': 1}
{'s1': 'S1-162027887', 'missing': ['S2-105870774', 'S3-966953269'], 'num_candidates': 381}
{'s1': 'S1-172380123', 'missing': ['S2-54439268'], 'num_candidates': 668}
{'s1': 'S1-814049342', 'missing': ['S3-820936546'], 'num_candidates': 18}

In [69]:
# ============================================================
# STEP 12 — LABEL PILOT CANDIDATES
# ============================================================

from labels import label_for_compact
from collections import Counter

labeled_pairs = []

for row in pilot_pairs:

    s1_id = row["source1_entity_id"]
    candidate_id = row["candidate_entity_id"]

    label = label_for_compact(
        s1_id,
        candidate_id,
        ground_truth,
    )

    labeled_pairs.append({
        **row,
        "label": label,
    })

label_counts = Counter(
    row["label"]
    for row in labeled_pairs
)

print("=" * 80)
print("PILOT LABEL DISTRIBUTION")
print("=" * 80)

print("Total pairs :", len(labeled_pairs))
print("Positive    :", label_counts.get(1, 0))
print("Negative    :", label_counts.get(0, 0))

positive_rate = (
    label_counts.get(1, 0) / len(labeled_pairs)
    if labeled_pairs
    else 0
)

print(f"Positive rate: {positive_rate:.6%}")

================================================================================
PILOT LABEL DISTRIBUTION
================================================================================
Total pairs : 424879
Positive    : 3200
Negative    : 421679
Positive rate: 0.753156%

In [70]:
# ============================================================
# STEP 13 — SAFE MISSING-PAIR DIAGNOSTIC
# ============================================================

from blocking import (
    make_name_keys,
    make_unicode_name_keys,
    make_address_keys,
    make_a4_keys,
    make_at2_keys,
)
from indexer import compose_key

# Correct mapping: name functions receive name;
# address functions receive address.

KEY_GENERATORS = [
    ("NAME", make_name_keys, "business_name"),
    ("UNICODE_NAME", make_unicode_name_keys, "business_name"),
    ("ADDRESS", make_address_keys, "business_address"),
    ("A4", make_a4_keys, "business_address"),
    ("AT2", make_at2_keys, "business_address"),
]

candidate_ids_by_s1 = {}

for row in pilot_pairs:
    candidate_ids_by_s1.setdefault(
        row["source1_entity_id"], set()
    ).add(row["candidate_entity_id"])


missing_gt_pairs = []

for idx in pilot_indices:

    s1_row = train_s1[idx]
    s1_id = s1_row["entity_id"]

    gt = ground_truth.get(s1_id, frozenset())
    candidates = candidate_ids_by_s1.get(s1_id, set())

    for candidate_id in (set(gt) - candidates):
        missing_gt_pairs.append((s1_row, candidate_id))


print("=" * 80)
print("MISSING TRUE PAIR DIAGNOSTIC")
print("=" * 80)
print("Missing pairs:", len(missing_gt_pairs))


diagnosis = []

for s1_row, candidate_id in missing_gt_pairs:

    source = candidate_id.split("-", 1)[0]

    if source == "S2":
        index = s2_index
    elif source == "S3":
        index = s3_index
    else:
        continue

    suffix = candidate_id.split("-", 1)[1]

    attrs = index.get_attrs(suffix)

    if attrs is None:
        diagnosis.append({
            "s1": s1_row["entity_id"],
            "candidate": candidate_id,
            "source": source,
            "attrs_found": False,
            "key_hits": [],
        })
        continue

    key_hits = []

    for key_name, key_func, field in KEY_GENERATORS:

        value = s1_row.get(field, "")

        for key_type, key_value in key_func(value):

            composed = compose_key(
                s1_row.get("country", "").strip(),
                key_value,
            )

            bucket = index.bucket(
                key_type,
                composed,
                limit=10001,
            )

            if suffix in bucket:
                key_hits.append(
                    (key_name, key_type, len(bucket))
                )

    diagnosis.append({
        "s1": s1_row["entity_id"],
        "candidate": candidate_id,
        "source": source,
        "attrs_found": True,
        "key_hits": key_hits,
    })


print("\nFirst 30 missing-pair diagnoses:\n")

for row in diagnosis[:30]:
    print(row)

================================================================================
MISSING TRUE PAIR DIAGNOSTIC
================================================================================
Missing pairs: 157

First 30 missing-pair diagnoses:

{'s1': 'S1-641216566', 'candidate': 'S3-131085423', 'source': 'S3', 'attrs_found': True, 'key_hits': [('AT2', 'AT2', 360)]}
{'s1': 'S1-641216566', 'candidate': 'S3-56338966', 'source': 'S3', 'attrs_found': True, 'key_hits': [('AT2', 'AT2', 360)]}
{'s1': 'S1-101171510', 'candidate': 'S2-925453893', 'source': 'S2', 'attrs_found': True, 'key_hits': [('A4', 'A4W', 1436)]}
{'s1': 'S1-101171510', 'candidate': 'S3-133430367', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-54882400', 'candidate': 'S2-966298126', 'source': 'S2', 'attrs_found': True, 'key_hits': [('ADDRESS', 'NL', 499), ('AT2', 'AT2', 535)]}
{'s1': 'S1-588906422', 'candidate': 'S2-717847741', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526), ('UNICODE_NAME', 'UFL', 1218)]}
{'s1': 'S1-588906422', 'candidate': 'S2-252521378', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526), ('UNICODE_NAME', 'UFL', 1218)]}
{'s1': 'S1-588906422', 'candidate': 'S3-924363909', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 9778), ('NAME', 'NP8', 9773), ('NAME', 'NS6', 10001), ('NAME', 'FL', 481), ('NAME', 'FL3', 479), ('NAME', 'F2', 494), ('UNICODE_NAME', 'UNP4', 9728), ('UNICODE_NAME', 'UNP6', 9557), ('UNICODE_NAME', 'UFL', 1266)]}
{'s1': 'S1-588906422', 'candidate': 'S2-228689952', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526)]}
{'s1': 'S1-217801541', 'candidate': 'S3-234581522', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 4074), ('UNICODE_NAME', 'UNP4', 4182), ('UNICODE_NAME', 'UNP6', 3986)]}
{'s1': 'S1-217801541', 'candidate': 'S3-547148581', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NS6', 6065)]}
{'s1': 'S1-217801541', 'candidate': 'S2-486047566', 'source': 'S2', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-210800211', 'candidate': 'S3-627029746', 'source': 'S3', 'attrs_found': True, 'key_hits': [('UNICODE_NAME', 'UFL', 1405), ('AT2', 'AT2', 241)]}
{'s1': 'S1-136572517', 'candidate': 'S2-127573242', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 5648), ('NAME', 'FL', 611), ('NAME', 'FL3', 868), ('NAME', 'F2', 456), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 678), ('AT2', 'AT2', 2042)]}
{'s1': 'S1-136572517', 'candidate': 'S3-719165640', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 6023), ('NAME', 'FL', 639), ('NAME', 'FL3', 899), ('NAME', 'F2', 465), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 684)]}
{'s1': 'S1-136572517', 'candidate': 'S3-932571654', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 6023), ('NAME', 'FL', 639), ('NAME', 'FL3', 899), ('NAME', 'F2', 465), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001)]}
{'s1': 'S1-162027887', 'candidate': 'S3-966953269', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-162027887', 'candidate': 'S2-105870774', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NS6', 2019), ('ADDRESS', 'NL', 4740)]}
{'s1': 'S1-172380123', 'candidate': 'S2-54439268', 'source': 'S2', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-814049342', 'candidate': 'S3-820936546', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 7180), ('NAME', 'NP8', 7126), ('NAME', 'F2', 6782), ('UNICODE_NAME', 'UNP4', 6716), ('UNICODE_NAME', 'UNP6', 6578)]}
{'s1': 'S1-309536843', 'candidate': 'S3-444425343', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 4129), ('UNICODE_NAME', 'UNP4', 4450), ('UNICODE_NAME', 'UNP6', 4021)]}
{'s1': 'S1-234422502', 'candidate': 'S2-146464105', 'source': 'S2', 'attrs_found': True, 'key_hits': [('NAME', 'NS6', 4245)]}
{'s1': 'S1-735368589', 'candidate': 'S3-197849552', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-719539555', 'candidate': 'S2-68816413', 'source': 'S2', 'attrs_found': True, 'key_hits': [('UNICODE_NAME', 'UNP4', 1907)]}
{'s1': 'S1-482487779', 'candidate': 'S3-444498360', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-850809026', 'candidate': 'S3-988917157', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-850809026', 'candidate': 'S2-544385699', 'source': 'S2', 'attrs_found': True, 'key_hits': [('ADDRESS', 'NL', 4555)]}
{'s1': 'S1-338741452', 'candidate': 'S3-481140308', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 10001), ('NAME', 'FL', 448), ('NAME', 'FL3', 444), ('NAME', 'F2', 464), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 1135)]}
{'s1': 'S1-338741452', 'candidate': 'S3-273630144', 'source': 'S3', 'attrs_found': True, 'key_hits': []}
{'s1': 'S1-338741452', 'candidate': 'S3-410540770', 'source': 'S3', 'attrs_found': True, 'key_hits': [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 10001), ('NAME', 'FL', 448), ('NAME', 'FL3', 444), ('NAME', 'F2', 464), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 1135)]}

In [71]:
# ============================================================
# STEP 14 — CLASSIFY BLOCKING MISSES
# ============================================================

from collections import Counter

cap_misses = []
no_key_misses = []
other_misses = []

for row in diagnosis:

    hits = row.get("key_hits", [])

    if not hits:
        no_key_misses.append(row)
        continue

    # A diagnostic bucket of exactly 10001 means our diagnostic
    # LIMIT was reached. Since production asks for cap+1, this
    # is evidence that the production bucket may have exceeded
    # its configured cap.
    if any(bucket_size >= 10001 for _, _, bucket_size in hits):
        cap_misses.append(row)
    else:
        other_misses.append(row)


print("=" * 80)
print("BLOCKING MISS CLASSIFICATION")
print("=" * 80)

print("Total missing true pairs :", len(diagnosis))
print("No-key misses            :", len(no_key_misses))
print("Potential cap misses     :", len(cap_misses))
print("Other                    :", len(other_misses))

print("\nBy source:")

source_counts = Counter(
    row["source"]
    for row in diagnosis
)

for source, count in sorted(source_counts.items()):
    print(f"  {source}: {count}")

print("\nExamples of no-key misses:")
for row in no_key_misses[:10]:
    print(
        row["s1"],
        "->",
        row["candidate"],
        "|",
        row["source"]
    )

print("\nExamples of potential cap misses:")
for row in cap_misses[:10]:
    print(
        row["s1"],
        "->",
        row["candidate"],
        "|",
        row["key_hits"]
    )

================================================================================
BLOCKING MISS CLASSIFICATION
================================================================================
Total missing true pairs : 157
No-key misses            : 45
Potential cap misses     : 26
Other                    : 86

By source:
  S2: 67
  S3: 90

Examples of no-key misses:
S1-101171510 -> S3-133430367 | S3
S1-217801541 -> S2-486047566 | S2
S1-162027887 -> S3-966953269 | S3
S1-172380123 -> S2-54439268 | S2
S1-735368589 -> S3-197849552 | S3
S1-482487779 -> S3-444498360 | S3
S1-850809026 -> S3-988917157 | S3
S1-338741452 -> S3-273630144 | S3
S1-593261976 -> S2-319030390 | S2
S1-54197745 -> S2-613468132 | S2

Examples of potential cap misses:
S1-588906422 -> S2-717847741 | [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526), ('UNICODE_NAME', 'UFL', 1218)]
S1-588906422 -> S2-252521378 | [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526), ('UNICODE_NAME', 'UFL', 1218)]
S1-588906422 -> S3-924363909 | [('NAME', 'NP6', 9778), ('NAME', 'NP8', 9773), ('NAME', 'NS6', 10001), ('NAME', 'FL', 481), ('NAME', 'FL3', 479), ('NAME', 'F2', 494), ('UNICODE_NAME', 'UNP4', 9728), ('UNICODE_NAME', 'UNP6', 9557), ('UNICODE_NAME', 'UFL', 1266)]
S1-588906422 -> S2-228689952 | [('NAME', 'NP6', 9764), ('NAME', 'NP8', 9741), ('NAME', 'NS6', 10001), ('NAME', 'FL', 474), ('NAME', 'FL3', 469), ('NAME', 'F2', 480), ('UNICODE_NAME', 'UNP4', 9663), ('UNICODE_NAME', 'UNP6', 9526)]
S1-136572517 -> S2-127573242 | [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 5648), ('NAME', 'FL', 611), ('NAME', 'FL3', 868), ('NAME', 'F2', 456), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 678), ('AT2', 'AT2', 2042)]
S1-136572517 -> S3-719165640 | [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 6023), ('NAME', 'FL', 639), ('NAME', 'FL3', 899), ('NAME', 'F2', 465), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 684)]
S1-136572517 -> S3-932571654 | [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 6023), ('NAME', 'FL', 639), ('NAME', 'FL3', 899), ('NAME', 'F2', 465), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001)]
S1-338741452 -> S3-481140308 | [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 10001), ('NAME', 'FL', 448), ('NAME', 'FL3', 444), ('NAME', 'F2', 464), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 1135)]
S1-338741452 -> S3-410540770 | [('NAME', 'NP6', 10001), ('NAME', 'NP8', 10001), ('NAME', 'NS6', 10001), ('NAME', 'FL', 448), ('NAME', 'FL3', 444), ('NAME', 'F2', 464), ('UNICODE_NAME', 'UNP4', 10001), ('UNICODE_NAME', 'UNP6', 10001), ('UNICODE_NAME', 'UFL', 1135)]
S1-593261976 -> S3-813756279 | [('NAME', 'NS6', 10001)]

In [72]:
# ============================================================
# STEP 15 — SHOW ACTUAL BLOCKING FREQUENCY CAPS
# ============================================================

from blocking import DEFAULT_FREQ_CAPS

print("=" * 80)
print("DEFAULT FREQUENCY CAPS")
print("=" * 80)

for key_type, cap in sorted(DEFAULT_FREQ_CAPS.items()):
    print(f"{key_type:15s} -> {cap}")

================================================================================
DEFAULT FREQUENCY CAPS
================================================================================
A2              -> 400
A4W             -> 20
AL2             -> 160
AN              -> 400
AT2             -> 40
AW2             -> 400
F2              -> 400
FL              -> 400
FL3             -> 400
FML             -> 400
NL              -> 400
NP6             -> 300
NP8             -> 300
NS6             -> 300
UFL             -> 300
UNP4            -> 300
UNP6            -> 300

In [73]:
# ============================================================
# STEP 16 — CONTROLLED HIGH-CAP RECOVERY EXPERIMENT
# ============================================================

from candidates import generate_candidate_pairs_for_row
from blocking import DEFAULT_FREQ_CAPS
from collections import defaultdict
import time

# Keep normal caps for most keys.
# Relax only the keys that are demonstrably causing misses.
RECOVERY_CAPS = dict(DEFAULT_FREQ_CAPS)

RECOVERY_CAPS.update({
    "NP6": 5000,
    "NP8": 5000,
    "NS6": 5000,
    "UNP4": 5000,
    "UNP6": 5000,
    "UFL": 2000,
    "AT2": 1000,
    "NL": 3000,
    "A4W": 1500,
})

print("=" * 80)
print("RECOVERY CAPS")
print("=" * 80)

for k in sorted(RECOVERY_CAPS):
    if RECOVERY_CAPS[k] != DEFAULT_FREQ_CAPS[k]:
        print(
            f"{k:10s}: "
            f"{DEFAULT_FREQ_CAPS[k]} -> {RECOVERY_CAPS[k]}"
        )


# ------------------------------------------------------------
# Generate recovery candidates for SAME 1,000 S1 pilot
# ------------------------------------------------------------

recovery_pairs = []

t0 = time.time()

for counter, idx in enumerate(pilot_indices, start=1):

    s1_row = train_s1[idx]

    rows = generate_candidate_pairs_for_row(
        s1_row,
        indexes_by_source,
        freq_caps=RECOVERY_CAPS,
    )

    recovery_pairs.extend(rows)

    if counter % 100 == 0:
        print(
            f"{counter:,}/{PILOT_ROWS:,} | "
            f"pairs={len(recovery_pairs):,}"
        )

elapsed = time.time() - t0

print("\n" + "=" * 80)
print("RECOVERY CANDIDATES")
print("=" * 80)

print("Pairs :", len(recovery_pairs))
print("Time  :", round(elapsed, 2), "sec")
print("Rate  :", round(PILOT_ROWS / elapsed, 2), "S1/s")

================================================================================
RECOVERY CAPS
================================================================================
A4W       : 20 -> 1500
AT2       : 40 -> 1000
NL        : 400 -> 3000
NP6       : 300 -> 5000
NP8       : 300 -> 5000
NS6       : 300 -> 5000
UFL       : 300 -> 2000
UNP4      : 300 -> 5000
UNP6      : 300 -> 5000
100/1,000 | pairs=488,111
200/1,000 | pairs=916,387
300/1,000 | pairs=1,507,741
400/1,000 | pairs=2,063,505
500/1,000 | pairs=2,558,228
600/1,000 | pairs=3,026,134
700/1,000 | pairs=3,497,338
800/1,000 | pairs=4,015,693
900/1,000 | pairs=4,494,047
1,000/1,000 | pairs=5,019,625

================================================================================
RECOVERY CANDIDATES
================================================================================
Pairs : 5019625
Time  : 114.64 sec
Rate  : 8.72 S1/s

In [74]:
# ============================================================
# STEP 16B — RECOVERY RECALL
# ============================================================

candidate_ids_recovery = defaultdict(set)

for row in recovery_pairs:
    candidate_ids_recovery[
        row["source1_entity_id"]
    ].add(
        row["candidate_entity_id"]
    )

total_gt = 0
found_gt = 0
complete_rows = 0
gt_rows = 0

for idx in pilot_indices:

    s1_id = train_s1[idx]["entity_id"]

    gt = set(
        ground_truth.get(
            s1_id,
            frozenset()
        )
    )

    if not gt:
        continue

    gt_rows += 1
    total_gt += len(gt)

    found = (
        gt &
        candidate_ids_recovery.get(
            s1_id,
            set()
        )
    )

    found_gt += len(found)

    if found == gt:
        complete_rows += 1

pair_recall = found_gt / total_gt
row_recall = complete_rows / gt_rows

print("=" * 80)
print("RECOVERY RECALL")
print("=" * 80)

print(f"GT matches       : {total_gt:,}")
print(f"Found            : {found_gt:,}")
print(f"Missing          : {total_gt - found_gt:,}")

print(f"\nPAIR RECALL      : {pair_recall:.6%}")
print(f"ROW COMPLETE    : {row_recall:.6%}")

print(f"\nCandidate pairs  : {len(recovery_pairs):,}")
print(
    f"Candidates/S1   : "
    f"{len(recovery_pairs) / PILOT_ROWS:.1f}"
)

================================================================================
RECOVERY RECALL
================================================================================
GT matches       : 3,357
Found            : 3,279
Missing          : 78

PAIR RECALL      : 97.676497%
ROW COMPLETE    : 92.719486%

Candidate pairs  : 5,019,625
Candidates/S1   : 5019.6

In [75]:
# ============================================================
# STEP 17 — NEGATIVE HARDNESS DISTRIBUTION
# ============================================================

from collections import Counter

positive_pairs = [
    row for row in labeled_pairs
    if row["label"] == 1
]

negative_pairs = [
    row for row in labeled_pairs
    if row["label"] == 0
]

print("=" * 80)
print("TRAINING PAIR DISTRIBUTION")
print("=" * 80)

print("Positive:", len(positive_pairs))
print("Negative:", len(negative_pairs))

print("\nPositive blocking_num_keys:")
print(
    Counter(
        row["blocking_num_keys"]
        for row in positive_pairs
    )
)

print("\nNegative blocking_num_keys:")
print(
    Counter(
        row["blocking_num_keys"]
        for row in negative_pairs
    ).most_common(10)
)

print("\nNegative blocking_min_freq:")
freq_counts = Counter(
    row["blocking_min_freq"]
    for row in negative_pairs
)

print(freq_counts.most_common(15))

================================================================================
TRAINING PAIR DISTRIBUTION
================================================================================
Positive: 3200
Negative: 421679

Positive blocking_num_keys:
Counter({5: 423, 4: 368, 6: 324, 1: 309, 7: 291, 3: 278, 8: 271, 2: 269, 9: 254, 10: 158, 11: 112, 12: 69, 13: 57, 14: 13, 15: 4})

Negative blocking_num_keys:
[(1, 287827), (2, 77554), (3, 32499), (4, 15915), (5, 3986), (6, 2411), (7, 1148), (8, 242), (9, 80), (10, 15)]

Negative blocking_min_freq:
[(115, 2514), (204, 2318), (283, 2255), (20, 2249), (37, 2244), (270, 2211), (84, 2178), (277, 2176), (30, 2150), (40, 2126), (237, 2107), (290, 2102), (7, 2068), (88, 2039), (239, 2018)]

In [77]:
# ============================================================
# STEP 18A — CHECK get_attrs() RETURN SHAPE
# ============================================================

test_pair = labeled_pairs[0]

source = test_pair["source"]
suffix = test_pair["candidate_entity_id"].split("-", 1)[1]

candidate_test = index_lookup[source].get_attrs(suffix)

print("=" * 80)
print("GET_ATTRS RETURN VALUE")
print("=" * 80)

print("Candidate ID:", test_pair["candidate_entity_id"])
print("Type:", type(candidate_test))
print("Value:", candidate_test)

================================================================================
GET_ATTRS RETURN VALUE
================================================================================
Candidate ID: S2-688425898
Type: <class 'tuple'>
Value: ('Physical Therapy Summit  Care LLC', '1738 RICHMOND RD, TX, WHARTON', 'US')

In [78]:
# ============================================================
# STEP 18B — FEATURE EXTRACTION — TUPLE-SAFE
# ============================================================

from features import calculate_features
import pandas as pd
import time

# ------------------------------------------------------------
# S1 lookup
# ------------------------------------------------------------

s1_lookup = {
    row["entity_id"]: row
    for row in train_s1
}

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}


# ------------------------------------------------------------
# Helper to convert get_attrs() output into a row dict
# ------------------------------------------------------------

def attrs_to_row(candidate_attrs):
    """
    Convert the project's get_attrs() return value into:
        business_name
        business_address
        country

    Handles the tuple returned by the current SqliteIndex.
    """

    if isinstance(candidate_attrs, dict):

        return {
            "business_name": candidate_attrs.get(
                "business_name", ""
            ),
            "business_address": candidate_attrs.get(
                "business_address", ""
            ),
            "country": candidate_attrs.get(
                "country", ""
            ),
        }

    if isinstance(candidate_attrs, tuple):

        if len(candidate_attrs) != 3:
            raise ValueError(
                f"Unexpected get_attrs() tuple length: "
                f"{len(candidate_attrs)} | "
                f"value={candidate_attrs}"
            )

        # The current index stores the three entity attributes.
        # We need to verify their exact order from the returned
        # tuple before processing the full matrix.
        raise RuntimeError(
            "get_attrs() returned a 3-tuple. "
            "Run STEP 18A and paste its Value."
        )

    raise TypeError(
        f"Unexpected get_attrs() type: "
        f"{type(candidate_attrs)}"
    )


print("=" * 80)
print("READY TO EXTRACT FEATURES")
print("=" * 80)

print("Labeled pairs:", len(labeled_pairs))

================================================================================
READY TO EXTRACT FEATURES
================================================================================
Labeled pairs: 424879

In [79]:
# ============================================================
# STEP 18 — FINAL FEATURE EXTRACTION
# ============================================================

from features import calculate_features
import pandas as pd
import time
import gc

# ------------------------------------------------------------
# S1 lookup
# ------------------------------------------------------------

s1_lookup = {
    row["entity_id"]: row
    for row in train_s1
}

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}


# ------------------------------------------------------------
# get_attrs() returns:
#     (business_name, business_address, country)
# ------------------------------------------------------------

def attrs_to_row(candidate_attrs):

    if isinstance(candidate_attrs, tuple):

        if len(candidate_attrs) != 3:
            raise ValueError(
                f"Unexpected tuple length: {len(candidate_attrs)}"
            )

        name, address, country = candidate_attrs

        return {
            "business_name": name or "",
            "business_address": address or "",
            "country": country or "",
        }

    elif isinstance(candidate_attrs, dict):

        return {
            "business_name": candidate_attrs.get(
                "business_name", ""
            ),
            "business_address": candidate_attrs.get(
                "business_address", ""
            ),
            "country": candidate_attrs.get(
                "country", ""
            ),
        }

    else:
        raise TypeError(
            f"Unexpected get_attrs type: "
            f"{type(candidate_attrs)}"
        )


# ------------------------------------------------------------
# Feature extraction
# ------------------------------------------------------------

FEATURE_ROWS = []

t0 = time.time()

total_pairs = len(labeled_pairs)

for i, pair in enumerate(labeled_pairs, start=1):

    s1 = s1_lookup[pair["source1_entity_id"]]

    source = pair["source"]

    candidate_suffix = pair["candidate_entity_id"].split(
        "-", 1
    )[1]

    index = index_lookup[source]

    candidate_attrs = index.get_attrs(candidate_suffix)

    if candidate_attrs is None:
        continue

    candidate = attrs_to_row(candidate_attrs)

    features = calculate_features(
        s1.get("business_name", ""),
        s1.get("business_address", ""),
        s1.get("country", ""),
        candidate["business_name"],
        candidate["business_address"],
        candidate["country"],
    )

    # --------------------------------------------------------
    # Blocking metadata
    # --------------------------------------------------------

    features["blocking_num_keys"] = (
        pair["blocking_num_keys"]
    )

    features["blocking_min_freq"] = (
        pair["blocking_min_freq"]
    )

    # --------------------------------------------------------
    # Label
    # --------------------------------------------------------

    features["label"] = pair["label"]

    FEATURE_ROWS.append(features)

    if i % 25_000 == 0:

        elapsed = time.time() - t0
        rate = i / elapsed if elapsed else 0

        print(
            f"{i:,}/{total_pairs:,} "
            f"| features={len(FEATURE_ROWS):,} "
            f"| rate={rate:.1f} pairs/s "
            f"| elapsed={elapsed/60:.1f} min"
        )


feature_df = pd.DataFrame(FEATURE_ROWS)

elapsed = time.time() - t0

print("\n" + "=" * 80)
print("FEATURE MATRIX COMPLETE")
print("=" * 80)

print("Pairs processed :", total_pairs)
print("Feature rows    :", len(feature_df))
print("Shape           :", feature_df.shape)
print("Time            :", round(elapsed / 60, 2), "minutes")

print(
    "Positive        :",
    int(feature_df["label"].sum())
)

print(
    "Negative        :",
    int((feature_df["label"] == 0).sum())
)

print("\nFeature columns:")
for col in feature_df.columns:
    print(" ", col)

25,000/424,879 | features=25,000 | rate=1337.9 pairs/s | elapsed=0.3 min
50,000/424,879 | features=50,000 | rate=1422.1 pairs/s | elapsed=0.6 min
75,000/424,879 | features=75,000 | rate=1485.5 pairs/s | elapsed=0.8 min
100,000/424,879 | features=100,000 | rate=1551.0 pairs/s | elapsed=1.1 min
125,000/424,879 | features=125,000 | rate=1624.7 pairs/s | elapsed=1.3 min
150,000/424,879 | features=150,000 | rate=1705.8 pairs/s | elapsed=1.5 min
175,000/424,879 | features=175,000 | rate=1781.8 pairs/s | elapsed=1.6 min
200,000/424,879 | features=200,000 | rate=1864.9 pairs/s | elapsed=1.8 min
225,000/424,879 | features=225,000 | rate=1945.6 pairs/s | elapsed=1.9 min
250,000/424,879 | features=250,000 | rate=2020.3 pairs/s | elapsed=2.1 min
275,000/424,879 | features=275,000 | rate=2095.7 pairs/s | elapsed=2.2 min
300,000/424,879 | features=300,000 | rate=2174.3 pairs/s | elapsed=2.3 min
325,000/424,879 | features=325,000 | rate=2248.8 pairs/s | elapsed=2.4 min
350,000/424,879 | features=350,000 | rate=2317.5 pairs/s | elapsed=2.5 min
375,000/424,879 | features=375,000 | rate=2386.9 pairs/s | elapsed=2.6 min
400,000/424,879 | features=400,000 | rate=2455.6 pairs/s | elapsed=2.7 min

================================================================================
FEATURE MATRIX COMPLETE
================================================================================
Pairs processed : 424879
Feature rows    : 424879
Shape           : (424879, 27)
Time            : 2.88 minutes
Positive        : 3200
Negative        : 421679

Feature columns:
  name_exact_match
  name_char_similarity
  name_levenshtein_similarity
  name_token_jaccard
  name_token_overlap
  name_compact_similarity
  name_prefix_similarity
  name_suffix_similarity
  name_char_ngram_jaccard
  address_exact_match
  address_char_similarity
  address_levenshtein_similarity
  address_token_jaccard
  address_token_overlap
  address_number_match
  address_char_ngram_jaccard
  country_match
  name_missing
  address_missing
  combined_name_address_score
  name_is_non_latin
  address_is_non_latin
  name_char_similarity_unicode
  name_token_jaccard_unicode
  blocking_num_keys
  blocking_min_freq
  label

In [80]:
# ============================================================
# STEP 19 — TRAIN LIGHTGBM MATCHING MODEL
# ============================================================

import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, average_precision_score

# ------------------------------------------------------------
# 1. Prepare training matrix
# ------------------------------------------------------------

BASE_FEATURES = [
    "name_exact_match",
    "name_char_similarity",
    "name_levenshtein_similarity",
    "name_token_jaccard",
    "name_token_overlap",
    "name_compact_similarity",
    "name_prefix_similarity",
    "name_suffix_similarity",
    "name_char_ngram_jaccard",
    "address_exact_match",
    "address_char_similarity",
    "address_levenshtein_similarity",
    "address_token_jaccard",
    "address_token_overlap",
    "address_number_match",
    "address_char_ngram_jaccard",
    "country_match",
    "name_missing",
    "address_missing",
    "combined_name_address_score",
    "name_is_non_latin",
    "address_is_non_latin",
    "name_char_similarity_unicode",
    "name_token_jaccard_unicode",
    "blocking_num_keys",
    "blocking_min_freq",
]

X = feature_df[BASE_FEATURES].astype(np.float32)
y = feature_df["label"].astype(np.int8)

print("=" * 70)
print("LIGHTGBM TRAINING")
print("=" * 70)
print("X shape :", X.shape)
print("Positive:", int(y.sum()))
print("Negative:", int((y == 0).sum()))
print("Positive rate:", float(y.mean()))

# ------------------------------------------------------------
# 2. Pair-level train split
# ------------------------------------------------------------

X_train, X_hold, y_train, y_hold = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTrain pairs:", len(X_train))
print("Holdout pairs:", len(X_hold))

# ------------------------------------------------------------
# 3. Class weighting
# ------------------------------------------------------------

pos = max(int(y_train.sum()), 1)
neg = int((y_train == 0).sum())

scale_pos_weight = neg / pos

print("scale_pos_weight:", scale_pos_weight)

# ------------------------------------------------------------
# 4. Model
# ------------------------------------------------------------

model = lgb.LGBMClassifier(
    objective="binary",

    n_estimators=1200,
    learning_rate=0.035,

    num_leaves=63,
    max_depth=-1,

    min_child_samples=30,

    subsample=0.85,
    colsample_bytree=0.90,

    reg_alpha=0.10,
    reg_lambda=1.00,

    scale_pos_weight=scale_pos_weight,

    random_state=42,
    n_jobs=-1,

    verbosity=-1,
)

# ------------------------------------------------------------
# 5. Train
# ------------------------------------------------------------

print("\nTraining...")

model.fit(
    X_train,
    y_train,
    eval_set=[(X_hold, y_hold)],
    eval_metric="auc",
    callbacks=[
        lgb.early_stopping(
            stopping_rounds=80,
            verbose=True
        )
    ],
)

print("\n" + "=" * 70)
print("MODEL TRAINED")
print("=" * 70)

print("Best iteration:", model.best_iteration_)

# ------------------------------------------------------------
# 6. Pair-level diagnostics
# ------------------------------------------------------------

hold_prob = model.predict_proba(
    X_hold,
    num_iteration=model.best_iteration_
)[:, 1]

print("\nPair-level diagnostics")
print("----------------------")
print("ROC-AUC :", roc_auc_score(y_hold, hold_prob))
print("PR-AUC  :", average_precision_score(y_hold, hold_prob))

======================================================================
LIGHTGBM TRAINING
======================================================================
X shape : (424879, 26)
Positive: 3200
Negative: 421679
Positive rate: 0.0075315560430146

Train pairs: 339903
Holdout pairs: 84976
scale_pos_weight: 131.774609375

Training...
Training until validation scores don't improve for 80 rounds
Early stopping, best iteration is:
[72]	valid_0's auc: 0.998978	valid_0's binary_logloss: 0.0125105

======================================================================
MODEL TRAINED
======================================================================
Best iteration: 72

Pair-level diagnostics
----------------------
ROC-AUC : 0.9989779720404098
PR-AUC  : 0.9202042535850318

In [82]:
# ============================================================
# FIX — RESTORE PRODUCTION BLOCKING CAPS
# ============================================================

CAPS = {
    "A2": 400,
    "A4W": 20,
    "AL2": 160,
    "AN": 400,
    "AT2": 40,
    "AW2": 400,
    "F2": 400,
    "FL": 400,
    "FL3": 400,
    "FML": 400,
    "NL": 400,
    "NP6": 300,
    "NP8": 300,
    "NS6": 300,
    "UFL": 300,
    "UNP4": 300,
    "UNP6": 300,
}

print("CAPS restored:")
for k, v in CAPS.items():
    print(f"  {k:5s} : {v}")

CAPS restored:
  A2    : 400
  A4W   : 20
  AL2   : 160
  AN    : 400
  AT2   : 40
  AW2   : 400
  F2    : 400
  FL    : 400
  FL3   : 400
  FML   : 400
  NL    : 400
  NP6   : 300
  NP8   : 300
  NS6   : 300
  UFL   : 300
  UNP4  : 300
  UNP6  : 300

In [84]:
# ============================================================
# STEP 20A — FIX VALIDATION S1 LOOKUP
# Reuses the already-generated 842,159 candidates.
# DO NOT regenerate candidates.
# ============================================================

import time
import pandas as pd

print("=" * 70)
print("STEP 20A — VALIDATION FEATURE EXTRACTION")
print("=" * 70)

# ------------------------------------------------------------
# Inspect one S1 row to identify its actual ID field
# ------------------------------------------------------------

print("S1 row keys:")
print(list(val_s1_rows[0].keys()))

print("\nFirst S1 row:")
print(val_s1_rows[0])

# ------------------------------------------------------------
# Automatically identify the S1 ID column
# ------------------------------------------------------------

possible_id_keys = [
    "source1_id",
    "source1_entity_id",
    "entity_id",
    "id",
]

S1_ID_KEY = None

for key in possible_id_keys:
    if key in val_s1_rows[0]:
        S1_ID_KEY = key
        break

if S1_ID_KEY is None:
    raise KeyError(
        "Could not identify S1 ID field. "
        f"Available keys: {list(val_s1_rows[0].keys())}"
    )

print("\nUsing S1 ID key:", S1_ID_KEY)

# ------------------------------------------------------------
# Build lookup
# ------------------------------------------------------------

s1_lookup_val = {
    str(row[S1_ID_KEY]): row
    for row in val_s1_rows
}

print("S1 lookup size:", len(s1_lookup_val))

# ------------------------------------------------------------
# Index lookup
# ------------------------------------------------------------

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}

# ------------------------------------------------------------
# Attribute conversion
# ------------------------------------------------------------

def attrs_to_row_val(attrs):

    if isinstance(attrs, dict):
        return {
            "business_name": attrs.get("business_name", ""),
            "business_address": attrs.get("business_address", ""),
            "country": attrs.get("country", ""),
        }

    if isinstance(attrs, (tuple, list)):
        return {
            "business_name": attrs[0] if len(attrs) > 0 else "",
            "business_address": attrs[1] if len(attrs) > 1 else "",
            "country": attrs[2] if len(attrs) > 2 else "",
        }

    raise TypeError(
        f"Unexpected attrs type: {type(attrs)}"
    )

# ------------------------------------------------------------
# Feature extraction
# ------------------------------------------------------------

t0 = time.time()

val_feature_rows = []

for i, pair in enumerate(val_candidate_pairs):

    s1_id = str(pair["source1_entity_id"])
    cand_id = pair["candidate_entity_id"]
    source = pair["source"]

    if s1_id not in s1_lookup_val:
        raise KeyError(
            f"S1 ID {s1_id} from candidate pairs "
            f"was not found in validation S1 lookup."
        )

    s1_row = s1_lookup_val[s1_id]

    attrs = index_lookup[source].get_attrs(cand_id)

    cand_row = attrs_to_row_val(attrs)

    feats = calculate_features(
        s1_row,
        cand_row
    )

    feats["blocking_num_keys"] = pair["blocking_num_keys"]
    feats["blocking_min_freq"] = pair["blocking_min_freq"]

    feats["source1_entity_id"] = s1_id
    feats["candidate_entity_id"] = cand_id
    feats["source"] = source

    val_feature_rows.append(feats)

    if (i + 1) % 25000 == 0:

        elapsed = time.time() - t0
        rate = (i + 1) / max(elapsed, 1e-9)

        print(
            f"{i+1:,}/{len(val_candidate_pairs):,} | "
            f"features={i+1:,} | "
            f"rate={rate:.1f} pairs/s | "
            f"elapsed={elapsed/60:.1f} min"
        )

val_feature_df = pd.DataFrame(val_feature_rows)

print("\n" + "=" * 70)
print("VALIDATION FEATURE MATRIX COMPLETE")
print("=" * 70)

print("Shape :", val_feature_df.shape)
print("Time  :", round((time.time() - t0) / 60, 2), "min")

# ------------------------------------------------------------
# Score
# ------------------------------------------------------------

val_X = val_feature_df[BASE_FEATURES].astype("float32")

val_feature_df["score"] = model.predict_proba(
    val_X,
    num_iteration=model.best_iteration_
)[:, 1]

print("\nScoring complete.")

print(
    "Score range :",
    float(val_feature_df["score"].min()),
    "→",
    float(val_feature_df["score"].max())
)

print(
    "Score median:",
    float(val_feature_df["score"].median())
)

print("\nValidation feature columns:")
print(val_feature_df.columns.tolist())

======================================================================
STEP 20A — VALIDATION FEATURE EXTRACTION
======================================================================
S1 row keys:
['entity_id', 'business_name', 'business_address', 'country']

First S1 row:
{'entity_id': 'S1-855856142', 'business_name': 'Veekay India Private Limited', 'business_address': '2 Dharam Palace Chs Ltd Ambewadi Opp Kurar Police Station Malad East, Mumbai, Mumbai City, Maharashtra', 'country': 'India'}

Using S1 ID key: entity_id
S1 lookup size: 2000

TypeError: Unexpected attrs type: <class 'NoneType'>

In [85]:
# ============================================================
# STEP 20B — DIAGNOSE MISSING INDEX ATTR
# ============================================================

print("=" * 70)
print("STEP 20B — CHECK CANDIDATE INDEX LOOKUPS")
print("=" * 70)

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}

missing_count = 0

for i, pair in enumerate(val_candidate_pairs):

    source = pair["source"]
    cand_id = pair["candidate_entity_id"]

    attrs = index_lookup[source].get_attrs(cand_id)

    if attrs is None:
        missing_count += 1

        print("\nMISSING INDEX RECORD")
        print("-" * 50)
        print("Pair position :", i)
        print("S1 ID         :", pair["source1_entity_id"])
        print("Candidate ID  :", cand_id)
        print("Source        :", source)
        print("Pair metadata :", pair)

        # Direct existence check
        try:
            exists = index_lookup[source].contains(cand_id)
            print("Index contains:", exists)
        except Exception as e:
            print("contains() check failed:", repr(e))

        if missing_count >= 10:
            break

print("\nMissing records found in first scan:", missing_count)

======================================================================
STEP 20B — CHECK CANDIDATE INDEX LOOKUPS
======================================================================

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 0
S1 ID         : S1-855856142
Candidate ID  : S2-772792384
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-772792384', 'source': 'S2', 'blocking_key_types': 'NP6|UNP4|UNP6', 'blocking_num_keys': 3, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 1
S1 ID         : S1-855856142
Candidate ID  : S2-620931722
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-620931722', 'source': 'S2', 'blocking_key_types': 'NP6|UFL|UNP4|UNP6', 'blocking_num_keys': 4, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 2
S1 ID         : S1-855856142
Candidate ID  : S2-449978429
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-449978429', 'source': 'S2', 'blocking_key_types': 'NP6|NP8|UNP4|UNP6', 'blocking_num_keys': 4, 'blocking_min_freq': 8}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 3
S1 ID         : S1-855856142
Candidate ID  : S2-991618028
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-991618028', 'source': 'S2', 'blocking_key_types': 'NP6|NP8|UFL|UNP4|UNP6', 'blocking_num_keys': 5, 'blocking_min_freq': 8}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 4
S1 ID         : S1-855856142
Candidate ID  : S2-914313248
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-914313248', 'source': 'S2', 'blocking_key_types': 'NP6|UFL|UNP4|UNP6', 'blocking_num_keys': 4, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 5
S1 ID         : S1-855856142
Candidate ID  : S2-548372577
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-548372577', 'source': 'S2', 'blocking_key_types': 'NP6|UNP4|UNP6', 'blocking_num_keys': 3, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 6
S1 ID         : S1-855856142
Candidate ID  : S2-997049274
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-997049274', 'source': 'S2', 'blocking_key_types': 'NP6|UFL|UNP4|UNP6', 'blocking_num_keys': 4, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 7
S1 ID         : S1-855856142
Candidate ID  : S2-62525629
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-62525629', 'source': 'S2', 'blocking_key_types': 'NP6|NP8|UFL|UNP4|UNP6', 'blocking_num_keys': 5, 'blocking_min_freq': 8}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 8
S1 ID         : S1-855856142
Candidate ID  : S2-563423403
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-563423403', 'source': 'S2', 'blocking_key_types': 'NP6|UNP4|UNP6', 'blocking_num_keys': 3, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

MISSING INDEX RECORD
--------------------------------------------------
Pair position : 9
S1 ID         : S1-855856142
Candidate ID  : S2-217848827
Source        : S2
Pair metadata : {'source1_entity_id': 'S1-855856142', 'candidate_entity_id': 'S2-217848827', 'source': 'S2', 'blocking_key_types': 'NP6|UNP4|UNP6', 'blocking_num_keys': 3, 'blocking_min_freq': 73}
contains() check failed: AttributeError("'SqliteIndex' object has no attribute 'contains'")

Missing records found in first scan: 10

In [86]:
# ============================================================
# STEP 20C — FIX FULL ENTITY ID -> INDEX SUFFIX
# ============================================================

import time
import pandas as pd

print("=" * 70)
print("STEP 20C — VALIDATION FEATURE EXTRACTION")
print("=" * 70)

# ------------------------------------------------------------
# S1 lookup
# ------------------------------------------------------------

S1_ID_KEY = "entity_id"

s1_lookup_val = {
    str(row[S1_ID_KEY]): row
    for row in val_s1_rows
}

print("Validation S1 rows :", len(s1_lookup_val))
print("Candidate pairs    :", len(val_candidate_pairs))

# ------------------------------------------------------------
# Index lookup
# ------------------------------------------------------------

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}

# ------------------------------------------------------------
# Full entity ID -> suffix
# ------------------------------------------------------------

def get_suffix(entity_id):
    """
    S2-772792384 -> 772792384
    S3-123456789 -> 123456789
    """
    entity_id = str(entity_id)

    if "-" not in entity_id:
        return entity_id

    return entity_id.split("-", 1)[1]


# ------------------------------------------------------------
# Attribute conversion
# ------------------------------------------------------------

def attrs_to_row_val(attrs):

    if attrs is None:
        raise RuntimeError(
            "Index lookup returned None."
        )

    if isinstance(attrs, dict):
        return {
            "business_name": attrs.get("business_name", ""),
            "business_address": attrs.get("business_address", ""),
            "country": attrs.get("country", ""),
        }

    if isinstance(attrs, (tuple, list)):
        return {
            "business_name": attrs[0] if len(attrs) > 0 else "",
            "business_address": attrs[1] if len(attrs) > 1 else "",
            "country": attrs[2] if len(attrs) > 2 else "",
        }

    raise TypeError(
        f"Unexpected attrs type: {type(attrs)}"
    )


# ------------------------------------------------------------
# Feature extraction
# ------------------------------------------------------------

t0 = time.time()

val_feature_rows = []

missing_attrs = 0

for i, pair in enumerate(val_candidate_pairs):

    s1_id = str(pair["source1_entity_id"])
    cand_id = str(pair["candidate_entity_id"])
    source = pair["source"]

    # ----------------------------
    # S1
    # ----------------------------

    s1_row = s1_lookup_val[s1_id]

    # ----------------------------
    # Candidate suffix
    # ----------------------------

    suffix = get_suffix(cand_id)

    # ----------------------------
    # Index lookup
    # ----------------------------

    attrs = index_lookup[source].get_attrs(suffix)

    if attrs is None:
        missing_attrs += 1

        raise RuntimeError(
            f"Candidate exists in postings but attrs lookup failed:\n"
            f"  pair position = {i}\n"
            f"  S1            = {s1_id}\n"
            f"  candidate     = {cand_id}\n"
            f"  source        = {source}\n"
            f"  suffix        = {suffix}"
        )

    cand_row = attrs_to_row_val(attrs)

    # ----------------------------
    # Features
    # ----------------------------

    feats = calculate_features(
        s1_row,
        cand_row
    )

    feats["blocking_num_keys"] = pair["blocking_num_keys"]
    feats["blocking_min_freq"] = pair["blocking_min_freq"]

    feats["source1_entity_id"] = s1_id
    feats["candidate_entity_id"] = cand_id
    feats["source"] = source

    val_feature_rows.append(feats)

    # ----------------------------
    # Progress
    # ----------------------------

    if (i + 1) % 25000 == 0:

        elapsed = time.time() - t0
        rate = (i + 1) / max(elapsed, 1e-9)

        print(
            f"{i+1:,}/{len(val_candidate_pairs):,} | "
            f"features={i+1:,} | "
            f"rate={rate:.1f} pairs/s | "
            f"elapsed={elapsed/60:.1f} min"
        )


# ------------------------------------------------------------
# DataFrame
# ------------------------------------------------------------

val_feature_df = pd.DataFrame(val_feature_rows)

print("\n" + "=" * 70)
print("VALIDATION FEATURE MATRIX COMPLETE")
print("=" * 70)

print("Feature rows :", len(val_feature_df))
print("Shape        :", val_feature_df.shape)
print("Time         :", round((time.time() - t0) / 60, 2), "min")
print("Missing attrs:", missing_attrs)

# ------------------------------------------------------------
# Score with trained model
# ------------------------------------------------------------

val_X = val_feature_df[BASE_FEATURES].astype("float32")

val_feature_df["score"] = model.predict_proba(
    val_X,
    num_iteration=model.best_iteration_
)[:, 1]

print("\n" + "=" * 70)
print("VALIDATION SCORING COMPLETE")
print("=" * 70)

print(
    "Score range :",
    float(val_feature_df["score"].min()),
    "→",
    float(val_feature_df["score"].max())
)

print(
    "Score median:",
    float(val_feature_df["score"].median())
)

======================================================================
STEP 20C — VALIDATION FEATURE EXTRACTION
======================================================================
Validation S1 rows : 2000
Candidate pairs    : 842159

TypeError: calculate_features() missing 4 required positional arguments: 'country1', 'name2', 'address2', and 'country2'

In [87]:
# ============================================================
# STEP 20D — CORRECT VALIDATION FEATURE EXTRACTION
# ============================================================

import time
import pandas as pd

print("=" * 70)
print("STEP 20D — VALIDATION FEATURE EXTRACTION")
print("=" * 70)

# ------------------------------------------------------------
# S1 lookup
# ------------------------------------------------------------

s1_lookup_val = {
    str(row["entity_id"]): row
    for row in val_s1_rows
}

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}

def get_suffix(entity_id):
    entity_id = str(entity_id)

    if "-" in entity_id:
        return entity_id.split("-", 1)[1]

    return entity_id


# ------------------------------------------------------------
# Feature extraction
# ------------------------------------------------------------

t0 = time.time()

val_feature_rows = []

for i, pair in enumerate(val_candidate_pairs):

    s1_id = str(pair["source1_entity_id"])
    cand_id = str(pair["candidate_entity_id"])
    source = pair["source"]

    # ----------------------------
    # S1
    # ----------------------------

    s1_row = s1_lookup_val[s1_id]

    name1 = s1_row["business_name"]
    address1 = s1_row["business_address"]
    country1 = s1_row["country"]

    # ----------------------------
    # Candidate
    # ----------------------------

    suffix = get_suffix(cand_id)

    attrs = index_lookup[source].get_attrs(suffix)

    if attrs is None:
        raise RuntimeError(
            f"Missing attrs for candidate:\n"
            f"  position = {i}\n"
            f"  S1       = {s1_id}\n"
            f"  candidate= {cand_id}\n"
            f"  source   = {source}\n"
            f"  suffix   = {suffix}"
        )

    name2 = attrs[0]
    address2 = attrs[1]
    country2 = attrs[2]

    # ----------------------------
    # CORRECT feature call
    # ----------------------------

    feats = calculate_features(
        name1,
        address1,
        country1,
        name2,
        address2,
        country2
    )

    # ----------------------------
    # Blocking metadata
    # ----------------------------

    feats["blocking_num_keys"] = pair["blocking_num_keys"]
    feats["blocking_min_freq"] = pair["blocking_min_freq"]

    # ----------------------------
    # IDs
    # ----------------------------

    feats["source1_entity_id"] = s1_id
    feats["candidate_entity_id"] = cand_id
    feats["source"] = source

    val_feature_rows.append(feats)

    # ----------------------------
    # Progress
    # ----------------------------

    if (i + 1) % 25000 == 0:

        elapsed = time.time() - t0
        rate = (i + 1) / max(elapsed, 1e-9)

        print(
            f"{i+1:,}/{len(val_candidate_pairs):,} | "
            f"features={i+1:,} | "
            f"rate={rate:.1f} pairs/s | "
            f"elapsed={elapsed/60:.1f} min"
        )


# ------------------------------------------------------------
# DataFrame
# ------------------------------------------------------------

val_feature_df = pd.DataFrame(val_feature_rows)

print("\n" + "=" * 70)
print("VALIDATION FEATURE MATRIX COMPLETE")
print("=" * 70)

print("Feature rows :", len(val_feature_df))
print("Shape        :", val_feature_df.shape)
print("Time         :", round((time.time() - t0) / 60, 2), "min")

# ------------------------------------------------------------
# Score
# ------------------------------------------------------------

val_X = val_feature_df[BASE_FEATURES].astype("float32")

val_feature_df["score"] = model.predict_proba(
    val_X,
    num_iteration=model.best_iteration_
)[:, 1]

print("\n" + "=" * 70)
print("VALIDATION SCORING COMPLETE")
print("=" * 70)

print(
    "Score range :",
    float(val_feature_df["score"].min()),
    "→",
    float(val_feature_df["score"].max())
)

print(
    "Score median:",
    float(val_feature_df["score"].median())
)

======================================================================
STEP 20D — VALIDATION FEATURE EXTRACTION
======================================================================
25,000/842,159 | features=25,000 | rate=3952.0 pairs/s | elapsed=0.1 min
50,000/842,159 | features=50,000 | rate=4287.7 pairs/s | elapsed=0.2 min
75,000/842,159 | features=75,000 | rate=4334.4 pairs/s | elapsed=0.3 min
100,000/842,159 | features=100,000 | rate=4327.5 pairs/s | elapsed=0.4 min
125,000/842,159 | features=125,000 | rate=4307.1 pairs/s | elapsed=0.5 min
150,000/842,159 | features=150,000 | rate=4298.4 pairs/s | elapsed=0.6 min
175,000/842,159 | features=175,000 | rate=4325.4 pairs/s | elapsed=0.7 min
200,000/842,159 | features=200,000 | rate=4355.2 pairs/s | elapsed=0.8 min
225,000/842,159 | features=225,000 | rate=4375.7 pairs/s | elapsed=0.9 min
250,000/842,159 | features=250,000 | rate=4370.4 pairs/s | elapsed=1.0 min
275,000/842,159 | features=275,000 | rate=4385.7 pairs/s | elapsed=1.0 min
300,000/842,159 | features=300,000 | rate=4371.4 pairs/s | elapsed=1.1 min
325,000/842,159 | features=325,000 | rate=4372.0 pairs/s | elapsed=1.2 min
350,000/842,159 | features=350,000 | rate=4364.3 pairs/s | elapsed=1.3 min
375,000/842,159 | features=375,000 | rate=4369.9 pairs/s | elapsed=1.4 min
400,000/842,159 | features=400,000 | rate=4374.7 pairs/s | elapsed=1.5 min
425,000/842,159 | features=425,000 | rate=4374.8 pairs/s | elapsed=1.6 min
450,000/842,159 | features=450,000 | rate=4361.4 pairs/s | elapsed=1.7 min
475,000/842,159 | features=475,000 | rate=4377.5 pairs/s | elapsed=1.8 min
500,000/842,159 | features=500,000 | rate=4391.9 pairs/s | elapsed=1.9 min
525,000/842,159 | features=525,000 | rate=4391.5 pairs/s | elapsed=2.0 min
550,000/842,159 | features=550,000 | rate=4398.9 pairs/s | elapsed=2.1 min
575,000/842,159 | features=575,000 | rate=4412.9 pairs/s | elapsed=2.2 min
600,000/842,159 | features=600,000 | rate=4416.1 pairs/s | elapsed=2.3 min
625,000/842,159 | features=625,000 | rate=4417.4 pairs/s | elapsed=2.4 min
650,000/842,159 | features=650,000 | rate=4422.2 pairs/s | elapsed=2.4 min
675,000/842,159 | features=675,000 | rate=4418.8 pairs/s | elapsed=2.5 min
700,000/842,159 | features=700,000 | rate=4423.4 pairs/s | elapsed=2.6 min
725,000/842,159 | features=725,000 | rate=4429.6 pairs/s | elapsed=2.7 min
750,000/842,159 | features=750,000 | rate=4432.2 pairs/s | elapsed=2.8 min
775,000/842,159 | features=775,000 | rate=4432.5 pairs/s | elapsed=2.9 min
800,000/842,159 | features=800,000 | rate=4442.6 pairs/s | elapsed=3.0 min
825,000/842,159 | features=825,000 | rate=4443.4 pairs/s | elapsed=3.1 min

======================================================================
VALIDATION FEATURE MATRIX COMPLETE
======================================================================
Feature rows : 842159
Shape        : (842159, 29)
Time         : 3.27 min

======================================================================
VALIDATION SCORING COMPLETE
======================================================================
Score range : 0.00021110787104476237 → 0.9579864972849627
Score median: 0.0006080407086636545

In [89]:
# ============================================================
# STEP 21 — EXACT S1-LEVEL MACRO F0.5
# FIXED FOR YOUR LOADED GT OBJECT
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 21 — S1-LEVEL MACRO F0.5")
print("=" * 70)

# ------------------------------------------------------------
# 1. Identify the actual ground-truth dictionary
# ------------------------------------------------------------

# The project loader returns:
#   dict[source1_entity_id -> frozenset(matched_entity_ids)]
#
# We deliberately do NOT use `gt` because your current `gt`
# variable is a set.

print("Checking available GT objects...")

candidate_gt_names = [
    "ground_truth",
    "ground_truth_compact",
    "train_ground_truth",
    "gt_dict",
]

ground_truth_dict = None
ground_truth_name = None

for name in candidate_gt_names:

    if name in globals():

        obj = globals()[name]

        if isinstance(obj, dict):

            # Verify it looks like S1 -> matched IDs
            if len(obj) > 0:

                first_key = next(iter(obj))
                first_value = obj[first_key]

                if (
                    isinstance(first_key, str)
                    and (
                        isinstance(first_value, (set, frozenset, list, tuple))
                        or first_value is None
                    )
                ):
                    ground_truth_dict = obj
                    ground_truth_name = name
                    break

if ground_truth_dict is None:
    raise RuntimeError(
        "Could not find the loaded ground-truth dictionary.\n"
        "Expected one of:\n"
        "  ground_truth\n"
        "  ground_truth_compact\n"
        "  train_ground_truth\n"
        "  gt_dict\n"
    )

print(
    f"Using GT dictionary: {ground_truth_name}"
)

print(
    f"GT entries: {len(ground_truth_dict):,}"
)

# ------------------------------------------------------------
# 2. Normalize GT
# ------------------------------------------------------------

ground_truth_val = {}

for s1_id, matches in ground_truth_dict.items():

    if matches is None:
        matches = set()

    ground_truth_val[str(s1_id)] = set(
        str(x) for x in matches
    )

print(
    "Normalized GT entries:",
    f"{len(ground_truth_val):,}"
)

# ------------------------------------------------------------
# 3. Group validation candidates by S1
# ------------------------------------------------------------

val_groups = {
    str(s1_id): group
    for s1_id, group in val_feature_df.groupby(
        "source1_entity_id",
        sort=False
    )
}

all_val_s1_ids = [
    str(row["entity_id"])
    for row in val_s1_rows
]

print(
    "Validation S1 rows:",
    f"{len(all_val_s1_ids):,}"
)

print(
    "S1 rows with candidates:",
    f"{len(val_groups):,}"
)

# ------------------------------------------------------------
# 4. Exact per-S1 F0.5
# ------------------------------------------------------------

def f05_single(pred_set, true_set):

    # True singleton: correctly predicting nothing
    if len(true_set) == 0:

        if len(pred_set) == 0:
            return 1.0

        return 0.0

    # GT exists but model predicted nothing
    if len(pred_set) == 0:
        return 0.0

    tp = len(pred_set & true_set)

    precision = tp / len(pred_set)
    recall = tp / len(true_set)

    if precision == 0.0:
        return 0.0

    return (
        1.25 * precision * recall
        / (0.25 * precision + recall)
    )


# ------------------------------------------------------------
# 5. Threshold sweep
# ------------------------------------------------------------

thresholds = np.concatenate([
    np.arange(0.05, 0.50, 0.01),
    np.arange(0.50, 0.91, 0.005),
    np.arange(0.91, 0.981, 0.001),
])

results = []

for threshold in thresholds:

    total_score = 0.0
    total_predicted = 0
    total_tp = 0
    rows_with_prediction = 0
    total_gt = 0

    for s1_id in all_val_s1_ids:

        true_set = ground_truth_val.get(
            s1_id,
            set()
        )

        total_gt += len(true_set)

        group = val_groups.get(s1_id)

        if group is None:

            pred_set = set()

        else:

            selected = group.loc[
                group["score"] >= threshold,
                "candidate_entity_id"
            ]

            pred_set = set(
                selected.astype(str)
            )

        score = f05_single(
            pred_set,
            true_set
        )

        total_score += score

        if pred_set:
            rows_with_prediction += 1

        total_predicted += len(pred_set)

        total_tp += len(
            pred_set & true_set
        )

    macro_f05 = (
        total_score / len(all_val_s1_ids)
    )

    aggregate_precision = (
        total_tp / total_predicted
        if total_predicted > 0
        else 0.0
    )

    aggregate_recall = (
        total_tp / total_gt
        if total_gt > 0
        else 0.0
    )

    results.append({
        "threshold": float(threshold),
        "macro_f05": float(macro_f05),
        "aggregate_precision": float(aggregate_precision),
        "aggregate_recall": float(aggregate_recall),
        "predicted_pairs": int(total_predicted),
        "true_positives": int(total_tp),
        "rows_with_prediction": int(rows_with_prediction),
    })


# ------------------------------------------------------------
# 6. Rank thresholds by actual macro F0.5
# ------------------------------------------------------------

threshold_df = pd.DataFrame(results)

threshold_df = threshold_df.sort_values(
    "macro_f05",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 70)
print("TOP 20 THRESHOLDS")
print("=" * 70)

print(
    threshold_df.head(20).to_string(
        index=False
    )
)

# ------------------------------------------------------------
# 7. Best validation threshold
# ------------------------------------------------------------

BEST_THRESHOLD = float(
    threshold_df.iloc[0]["threshold"]
)

BEST_F05 = float(
    threshold_df.iloc[0]["macro_f05"]
)

BEST_PRECISION = float(
    threshold_df.iloc[0]["aggregate_precision"]
)

BEST_RECALL = float(
    threshold_df.iloc[0]["aggregate_recall"]
)

BEST_PREDICTED = int(
    threshold_df.iloc[0]["predicted_pairs"]
)

BEST_TP = int(
    threshold_df.iloc[0]["true_positives"]
)

BEST_ROWS = int(
    threshold_df.iloc[0]["rows_with_prediction"]
)

print("\n" + "=" * 70)
print("BEST VALIDATION RESULT")
print("=" * 70)

print(
    f"Best threshold : {BEST_THRESHOLD:.4f}"
)

print(
    f"Macro F0.5     : {BEST_F05:.6f}"
)

print(
    f"Macro F0.5 %   : {BEST_F05 * 100:.4f}%"
)

print(
    f"Aggregate P   : {BEST_PRECISION:.6f}"
)

print(
    f"Aggregate R   : {BEST_RECALL:.6f}"
)

print(
    f"Predicted     : {BEST_PREDICTED:,}"
)

print(
    f"True positives: {BEST_TP:,}"
)

print(
    f"Rows predicted: {BEST_ROWS:,}/{len(all_val_s1_ids):,}"
)

======================================================================
STEP 21 — S1-LEVEL MACRO F0.5
======================================================================
Checking available GT objects...
Using GT dictionary: ground_truth
GT entries: 2,206,821
Normalized GT entries: 2,206,821
Validation S1 rows: 2,000
S1 rows with candidates: 2,000

======================================================================
TOP 20 THRESHOLDS
======================================================================
 threshold  macro_f05  aggregate_precision  aggregate_recall  predicted_pairs  true_positives  rows_with_prediction
     0.944   0.812059             0.886875          0.764246             5958            5284                  1878
     0.945   0.809242             0.896696          0.741973             5721            5130                  1856
     0.946   0.805024             0.899430          0.730836             5618            5053                  1847
     0.943   0.800133             0.854568          0.795487             6436            5500                  1916
     0.948   0.793971             0.907085          0.707405             5392            4891                  1810
     0.947   0.793679             0.902345          0.712323             5458            4925                  1816
     0.949   0.793025             0.908277          0.704657             5364            4872                  1807
     0.942   0.791961             0.838385          0.808071             6664            5587                  1931
     0.941   0.788504             0.830191          0.815302             6790            5637                  1936
     0.940   0.786725             0.826404          0.819352             6855            5665                  1938
     0.939   0.783819             0.820857          0.823113             6933            5691                  1940
     0.938   0.780685             0.816429          0.826584             7000            5715                  1942
     0.937   0.779896             0.815183          0.829332             7034            5734                  1943
     0.936   0.777794             0.812871          0.831212             7070            5747                  1944
     0.934   0.775990             0.808850          0.835406             7141            5776                  1945
     0.935   0.775891             0.809932          0.832658             7108            5757                  1944
     0.933   0.772936             0.805258          0.837287             7189            5789                  1948
     0.932   0.770612             0.801853          0.838733             7232            5799                  1950
     0.931   0.769897             0.800523          0.841047             7264            5815                  1950
     0.930   0.769682             0.799286          0.842060             7284            5822                  1952

======================================================================
BEST VALIDATION RESULT
======================================================================
Best threshold : 0.9440
Macro F0.5     : 0.812059
Macro F0.5 %   : 81.2059%
Aggregate P   : 0.886875
Aggregate R   : 0.764246
Predicted     : 5,958
True positives: 5,284
Rows predicted: 1,878/2,000

In [90]:
# ============================================================
# STEP 22 — EXPANDED TRAINING DATA
# 5,000 TRAIN S1 ROWS
# ============================================================

import time
import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 22 — EXPANDED TRAINING SET")
print("=" * 70)

TRAIN_PILOT_N = 5000

rng_train = np.random.default_rng(123)

if len(train_indices) > TRAIN_PILOT_N:
    train_pilot_indices = rng_train.choice(
        train_indices,
        size=TRAIN_PILOT_N,
        replace=False
    )
else:
    train_pilot_indices = np.asarray(train_indices)

train_pilot_indices = np.asarray(train_pilot_indices)

train_pilot_rows = [
    train_s1[i]
    for i in train_pilot_indices
]

print("Training S1 rows:", len(train_pilot_rows))

# ------------------------------------------------------------
# Candidate generation
# ------------------------------------------------------------

print("\nGenerating training candidates...")

t0 = time.time()

expanded_train_pairs = []

for j, s1_row in enumerate(train_pilot_rows):

    pairs = generate_candidate_pairs_for_row(
        s1_row,
        {
            "S2": s2_index,
            "S3": s3_index
        },
        CAPS
    )

    expanded_train_pairs.extend(pairs)

    if (j + 1) % 500 == 0:

        elapsed = time.time() - t0
        rate = (j + 1) / max(elapsed, 1e-9)

        print(
            f"{j+1:,}/{len(train_pilot_rows):,} S1 | "
            f"pairs={len(expanded_train_pairs):,} | "
            f"rate={rate:.1f} S1/s | "
            f"elapsed={elapsed/60:.1f} min"
        )

print("\n" + "=" * 70)
print("TRAINING CANDIDATES COMPLETE")
print("=" * 70)

print(
    "Training S1:",
    f"{len(train_pilot_rows):,}"
)

print(
    "Candidate pairs:",
    f"{len(expanded_train_pairs):,}"
)

print(
    "Time:",
    round((time.time() - t0) / 60, 2),
    "min"
)

# ------------------------------------------------------------
# S1 lookup
# ------------------------------------------------------------

train_s1_lookup = {
    str(row["entity_id"]): row
    for row in train_pilot_rows
}

index_lookup = {
    "S2": s2_index,
    "S3": s3_index,
}

# ------------------------------------------------------------
# Feature extraction + labels
# ------------------------------------------------------------

print("\nExtracting training features...")

t0 = time.time()

expanded_feature_rows = []

for i, pair in enumerate(expanded_train_pairs):

    s1_id = str(pair["source1_entity_id"])
    cand_id = str(pair["candidate_entity_id"])
    source = pair["source"]

    s1_row = train_s1_lookup[s1_id]

    name1 = s1_row["business_name"]
    address1 = s1_row["business_address"]
    country1 = s1_row["country"]

    suffix = (
        cand_id.split("-", 1)[1]
        if "-" in cand_id
        else cand_id
    )

    attrs = index_lookup[source].get_attrs(suffix)

    if attrs is None:
        raise RuntimeError(
            f"Missing attrs:\n"
            f"S1={s1_id}\n"
            f"candidate={cand_id}\n"
            f"source={source}\n"
            f"suffix={suffix}"
        )

    name2 = attrs[0]
    address2 = attrs[1]
    country2 = attrs[2]

    feats = calculate_features(
        name1,
        address1,
        country1,
        name2,
        address2,
        country2
    )

    feats["blocking_num_keys"] = pair["blocking_num_keys"]
    feats["blocking_min_freq"] = pair["blocking_min_freq"]

    feats["source1_entity_id"] = s1_id
    feats["candidate_entity_id"] = cand_id
    feats["source"] = source

    # Ground-truth label
    true_matches = ground_truth_dict.get(
        s1_id,
        set()
    )

    feats["label"] = int(
        cand_id in true_matches
    )

    expanded_feature_rows.append(feats)

    if (i + 1) % 100000 == 0:

        elapsed = time.time() - t0
        rate = (i + 1) / max(elapsed, 1e-9)

        print(
            f"{i+1:,}/{len(expanded_train_pairs):,} | "
            f"features={i+1:,} | "
            f"rate={rate:.1f} pairs/s | "
            f"elapsed={elapsed/60:.1f} min"
        )

expanded_feature_df = pd.DataFrame(
    expanded_feature_rows
)

print("\n" + "=" * 70)
print("EXPANDED TRAINING MATRIX COMPLETE")
print("=" * 70)

print(
    "Shape:",
    expanded_feature_df.shape
)

print(
    "Time:",
    round((time.time() - t0) / 60, 2),
    "min"
)

print(
    "Positive:",
    int(expanded_feature_df["label"].sum())
)

print(
    "Negative:",
    int(
        (expanded_feature_df["label"] == 0).sum()
    )
)

print(
    "Positive rate:",
    expanded_feature_df["label"].mean()
)

======================================================================
STEP 22 — EXPANDED TRAINING SET
======================================================================
Training S1 rows: 5000

Generating training candidates...
500/5,000 S1 | pairs=199,824 | rate=72.8 S1/s | elapsed=0.1 min
1,000/5,000 S1 | pairs=405,274 | rate=73.2 S1/s | elapsed=0.2 min
1,500/5,000 S1 | pairs=610,295 | rate=73.6 S1/s | elapsed=0.3 min
2,000/5,000 S1 | pairs=809,983 | rate=73.0 S1/s | elapsed=0.5 min
2,500/5,000 S1 | pairs=1,016,904 | rate=72.9 S1/s | elapsed=0.6 min
3,000/5,000 S1 | pairs=1,234,710 | rate=72.8 S1/s | elapsed=0.7 min
3,500/5,000 S1 | pairs=1,452,341 | rate=72.6 S1/s | elapsed=0.8 min
4,000/5,000 S1 | pairs=1,681,310 | rate=72.1 S1/s | elapsed=0.9 min
4,500/5,000 S1 | pairs=1,894,925 | rate=68.9 S1/s | elapsed=1.1 min
5,000/5,000 S1 | pairs=2,110,212 | rate=68.8 S1/s | elapsed=1.2 min

======================================================================
TRAINING CANDIDATES COMPLETE
======================================================================
Training S1: 5,000
Candidate pairs: 2,110,212
Time: 1.21 min

Extracting training features...
100,000/2,110,212 | features=100,000 | rate=4440.4 pairs/s | elapsed=0.4 min
200,000/2,110,212 | features=200,000 | rate=4485.4 pairs/s | elapsed=0.7 min
300,000/2,110,212 | features=300,000 | rate=4499.3 pairs/s | elapsed=1.1 min
400,000/2,110,212 | features=400,000 | rate=4485.3 pairs/s | elapsed=1.5 min
500,000/2,110,212 | features=500,000 | rate=4493.3 pairs/s | elapsed=1.9 min
600,000/2,110,212 | features=600,000 | rate=4506.3 pairs/s | elapsed=2.2 min
700,000/2,110,212 | features=700,000 | rate=4494.7 pairs/s | elapsed=2.6 min
800,000/2,110,212 | features=800,000 | rate=4506.5 pairs/s | elapsed=3.0 min
900,000/2,110,212 | features=900,000 | rate=4516.6 pairs/s | elapsed=3.3 min
1,000,000/2,110,212 | features=1,000,000 | rate=4515.8 pairs/s | elapsed=3.7 min
1,100,000/2,110,212 | features=1,100,000 | rate=4528.4 pairs/s | elapsed=4.0 min
1,200,000/2,110,212 | features=1,200,000 | rate=4554.1 pairs/s | elapsed=4.4 min
1,300,000/2,110,212 | features=1,300,000 | rate=4560.2 pairs/s | elapsed=4.8 min
1,400,000/2,110,212 | features=1,400,000 | rate=4565.8 pairs/s | elapsed=5.1 min
1,500,000/2,110,212 | features=1,500,000 | rate=4563.8 pairs/s | elapsed=5.5 min
1,600,000/2,110,212 | features=1,600,000 | rate=4558.4 pairs/s | elapsed=5.8 min
1,700,000/2,110,212 | features=1,700,000 | rate=4564.6 pairs/s | elapsed=6.2 min
1,800,000/2,110,212 | features=1,800,000 | rate=4563.4 pairs/s | elapsed=6.6 min
1,900,000/2,110,212 | features=1,900,000 | rate=4566.0 pairs/s | elapsed=6.9 min
2,000,000/2,110,212 | features=2,000,000 | rate=4557.1 pairs/s | elapsed=7.3 min
2,100,000/2,110,212 | features=2,100,000 | rate=4555.4 pairs/s | elapsed=7.7 min

======================================================================
EXPANDED TRAINING MATRIX COMPLETE
======================================================================
Shape: (2110212, 30)
Time: 8.03 min
Positive: 16465
Negative: 2093747
Positive rate: 0.007802533584303378

In [91]:
# ============================================================
# STEP 23 — TRAIN EXPANDED LIGHTGBM
# ============================================================

import numpy as np
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, average_precision_score

print("=" * 70)
print("STEP 23 — EXPANDED LIGHTGBM")
print("=" * 70)

# ------------------------------------------------------------
# Features
# ------------------------------------------------------------

X_expanded = expanded_feature_df[BASE_FEATURES].astype(
    np.float32
)

y_expanded = expanded_feature_df["label"].astype(
    np.int8
)

print("X shape :", X_expanded.shape)
print("Positive:", int(y_expanded.sum()))
print("Negative:", int((y_expanded == 0).sum()))
print("Positive rate:", float(y_expanded.mean()))

# ------------------------------------------------------------
# Pair-level split
# ------------------------------------------------------------

X_tr, X_ho, y_tr, y_ho = train_test_split(
    X_expanded,
    y_expanded,
    test_size=0.20,
    random_state=42,
    stratify=y_expanded
)

print("\nTrain pairs  :", len(X_tr))
print("Holdout pairs:", len(X_ho))

# ------------------------------------------------------------
# Class weighting
# ------------------------------------------------------------

pos = max(int(y_tr.sum()), 1)
neg = int((y_tr == 0).sum())

scale_pos_weight_expanded = neg / pos

print(
    "scale_pos_weight:",
    scale_pos_weight_expanded
)

# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

model_expanded = lgb.LGBMClassifier(
    objective="binary",

    n_estimators=1500,
    learning_rate=0.035,

    num_leaves=63,
    max_depth=-1,

    min_child_samples=30,

    subsample=0.85,
    colsample_bytree=0.90,

    reg_alpha=0.10,
    reg_lambda=1.00,

    scale_pos_weight=scale_pos_weight_expanded,

    random_state=42,
    n_jobs=-1,

    verbosity=-1,
)

# ------------------------------------------------------------
# Train
# ------------------------------------------------------------

print("\nTraining expanded model...")

model_expanded.fit(
    X_tr,
    y_tr,
    eval_set=[(X_ho, y_ho)],
    eval_metric="auc",
    callbacks=[
        lgb.early_stopping(
            stopping_rounds=80,
            verbose=True
        )
    ],
)

print("\n" + "=" * 70)
print("EXPANDED MODEL TRAINED")
print("=" * 70)

print(
    "Best iteration:",
    model_expanded.best_iteration_
)

# ------------------------------------------------------------
# Pair diagnostics
# ------------------------------------------------------------

hold_prob_expanded = model_expanded.predict_proba(
    X_ho,
    num_iteration=model_expanded.best_iteration_
)[:, 1]

print("\nPair-level diagnostics")
print("----------------------")

print(
    "ROC-AUC:",
    roc_auc_score(y_ho, hold_prob_expanded)
)

print(
    "PR-AUC :",
    average_precision_score(y_ho, hold_prob_expanded)
)

======================================================================
STEP 23 — EXPANDED LIGHTGBM
======================================================================
X shape : (2110212, 26)
Positive: 16465
Negative: 2093747
Positive rate: 0.007802533584303378

Train pairs  : 1688169
Holdout pairs: 422043
scale_pos_weight: 127.16345277862132

Training expanded model...
Training until validation scores don't improve for 80 rounds
Early stopping, best iteration is:
[22]	valid_0's auc: 0.998502	valid_0's binary_logloss: 0.0186334

======================================================================
EXPANDED MODEL TRAINED
======================================================================
Best iteration: 22

Pair-level diagnostics
----------------------
ROC-AUC: 0.9985024769864617
PR-AUC : 0.8501745413107846

In [92]:
# ============================================================
# STEP 24 — SCORE EXISTING VALIDATION SET
# ============================================================

print("=" * 70)
print("STEP 24 — EXPANDED MODEL VALIDATION SCORING")
print("=" * 70)

val_X_expanded = val_feature_df[
    BASE_FEATURES
].astype(np.float32)

val_feature_df["score_expanded"] = model_expanded.predict_proba(
    val_X_expanded,
    num_iteration=model_expanded.best_iteration_
)[:, 1]

print("Validation candidate rows:", len(val_feature_df))

print(
    "Score range:",
    float(val_feature_df["score_expanded"].min()),
    "→",
    float(val_feature_df["score_expanded"].max())
)

print(
    "Score median:",
    float(val_feature_df["score_expanded"].median())
)

print("Scoring complete.")

======================================================================
STEP 24 — EXPANDED MODEL VALIDATION SCORING
======================================================================
Validation candidate rows: 842159
Score range: 0.0032699565452057825 → 0.9191261799225074
Score median: 0.003714354278314823
Scoring complete.

In [94]:
# ============================================================
# STEP 25 — EXPANDED MODEL MACRO F0.5
# ============================================================

print("=" * 70)
print("STEP 25 — EXPANDED MODEL S1-LEVEL MACRO F0.5")
print("=" * 70)

# ------------------------------------------------------------
# Group candidates by S1
# ------------------------------------------------------------

val_groups_expanded = {
    str(s1_id): group
    for s1_id, group in val_feature_df.groupby(
        "source1_entity_id",
        sort=False
    )
}

all_val_s1_ids = [
    str(row["entity_id"])
    for row in val_s1_rows
]

# ------------------------------------------------------------
# Threshold sweep
# ------------------------------------------------------------

thresholds = np.concatenate([
    np.arange(0.50, 0.90, 0.005),
    np.arange(0.90, 0.950, 0.001),
    np.arange(0.950, 0.991, 0.001),
])

results_expanded = []

for threshold in thresholds:

    total_score = 0.0
    total_predicted = 0
    total_tp = 0
    total_gt = 0
    rows_with_prediction = 0

    for s1_id in all_val_s1_ids:

        true_set = ground_truth_val.get(
            s1_id,
            set()
        )

        total_gt += len(true_set)

        group = val_groups_expanded.get(s1_id)

        if group is None:

            pred_set = set()

        else:

            pred_set = set(
                group.loc[
                    group["score_expanded"] >= threshold,
                    "candidate_entity_id"
                ].astype(str)
            )

        score = f05_single(
            pred_set,
            true_set
        )

        total_score += score

        if pred_set:
            rows_with_prediction += 1

        total_predicted += len(pred_set)

        total_tp += len(
            pred_set & true_set
        )

    macro_f05 = (
        total_score / len(all_val_s1_ids)
    )

    aggregate_precision = (
        total_tp / total_predicted
        if total_predicted
        else 0.0
    )

    aggregate_recall = (
        total_tp / total_gt
        if total_gt
        else 0.0
    )

    results_expanded.append({
        "threshold": float(threshold),
        "macro_f05": float(macro_f05),
        "aggregate_precision": float(aggregate_precision),
        "aggregate_recall": float(aggregate_recall),
        "predicted_pairs": int(total_predicted),
        "true_positives": int(total_tp),
        "rows_with_prediction": int(rows_with_prediction),
    })

threshold_df_expanded = (
    pd.DataFrame(results_expanded)
    .sort_values("macro_f05", ascending=False)
    .reset_index(drop=True)
)

print("\n" + "=" * 70)
print("TOP 20 EXPANDED-MODEL THRESHOLDS")
print("=" * 70)

print(
    threshold_df_expanded.head(20).to_string(index=False)
)

# ------------------------------------------------------------
# Best
# ------------------------------------------------------------

best_exp = threshold_df_expanded.iloc[0]

BEST_THRESHOLD_EXPANDED = float(best_exp["threshold"])
BEST_F05_EXPANDED = float(best_exp["macro_f05"])

print("\n" + "=" * 70)
print("EXPANDED MODEL — BEST VALIDATION RESULT")
print("=" * 70)

print(f"Best threshold : {BEST_THRESHOLD_EXPANDED:.4f}")
print(f"Macro F0.5     : {BEST_F05_EXPANDED:.6f}")
print(f"Macro F0.5 %   : {BEST_F05_EXPANDED * 100:.4f}%")
print(f"Aggregate P    : {best_exp['aggregate_precision']:.6f}")
print(f"Aggregate R    : {best_exp['aggregate_recall']:.6f}")
print(f"Predicted      : {int(best_exp['predicted_pairs']):,}")
print(f"True positives : {int(best_exp['true_positives']):,}")
print(
    f"Rows predicted : "
    f"{int(best_exp['rows_with_prediction']):,}"
    f"/{len(all_val_s1_ids):,}"
)

print("\nBASELINE MODEL")
print("Macro F0.5     : 0.812059")

print("\nCHANGE")
print(
    f"{BEST_F05_EXPANDED - 0.812059:+.6f}"
)

======================================================================
STEP 25 — EXPANDED MODEL S1-LEVEL MACRO F0.5
======================================================================

======================================================================
TOP 20 EXPANDED-MODEL THRESHOLDS
======================================================================
 threshold  macro_f05  aggregate_precision  aggregate_recall  predicted_pairs  true_positives  rows_with_prediction
     0.710   0.729557             0.766676          0.807926             7286            5586                  1932
     0.705   0.726436             0.755034          0.824270             7548            5699                  1956
     0.700   0.721451             0.744746          0.840613             7804            5812                  1975
     0.695   0.721143             0.738080          0.862019             8075            5960                  1976
     0.685   0.720722             0.732256          0.871420             8228            6025                  1980
     0.690   0.720580             0.737134          0.863899             8103            5973                  1977
     0.715   0.715776             0.779019          0.766850             6806            5302                  1908
     0.680   0.708795             0.712617          0.882268             8560            6100                  1985
     0.675   0.705270             0.707112          0.885884             8662            6125                  1987
     0.670   0.703847             0.704517          0.886607             8701            6130                  1987
     0.665   0.702925             0.703003          0.887041             8724            6133                  1987
     0.660   0.701698             0.701005          0.887764             8756            6138                  1987
     0.655   0.700102             0.698081          0.889210             8807            6148                  1987
     0.650   0.697944             0.693354          0.891814             8893            6166                  1987
     0.645   0.695475             0.687646          0.894417             8993            6184                  1987
     0.640   0.692291             0.682279          0.895430             9074            6191                  1990
     0.635   0.690762             0.679115          0.896876             9131            6201                  1990
     0.630   0.682413             0.663764          0.903963             9416            6250                  1990
     0.625   0.678134             0.654055          0.907579             9594            6275                  1990
     0.620   0.675987             0.651209          0.907868             9639            6277                  1990

======================================================================
EXPANDED MODEL — BEST VALIDATION RESULT
======================================================================
Best threshold : 0.7100
Macro F0.5     : 0.729557
Macro F0.5 %   : 72.9557%
Aggregate P    : 0.766676
Aggregate R    : 0.807926
Predicted      : 7,286
True positives : 5,586
Rows predicted : 1,932/2,000

BASELINE MODEL
Macro F0.5     : 0.812059

CHANGE
-0.082502

In [95]:
# ============================================================
# STEP 26 — EXPANDED DATA, FIXED 72 ITERATIONS
# ============================================================

print("=" * 70)
print("STEP 26 — FIXED-ITERATION EXPANDED MODEL")
print("=" * 70)

import lightgbm as lgb
import numpy as np

# Reuse the already-created X_tr / y_tr from Step 23.
# DO NOT regenerate anything.

model_expanded_72 = lgb.LGBMClassifier(
    objective="binary",

    n_estimators=72,
    learning_rate=0.035,

    num_leaves=63,
    max_depth=-1,

    min_child_samples=30,

    subsample=0.85,
    colsample_bytree=0.90,

    reg_alpha=0.10,
    reg_lambda=1.00,

    scale_pos_weight=scale_pos_weight_expanded,

    random_state=42,
    n_jobs=-1,

    verbosity=-1,
)

print("Training with fixed 72 iterations...")

model_expanded_72.fit(
    X_tr,
    y_tr
)

print("\n" + "=" * 70)
print("FIXED-72 MODEL TRAINED")
print("=" * 70)

print("Iterations:", 72)

======================================================================
STEP 26 — FIXED-ITERATION EXPANDED MODEL
======================================================================
Training with fixed 72 iterations...

======================================================================
FIXED-72 MODEL TRAINED
======================================================================
Iterations: 72

In [96]:
# ============================================================
# STEP 27 — SCORE VALIDATION WITH FIXED-72 MODEL
# ============================================================

print("=" * 70)
print("STEP 27 — FIXED-72 VALIDATION SCORING")
print("=" * 70)

val_feature_df["score_expanded_72"] = model_expanded_72.predict_proba(
    val_feature_df[BASE_FEATURES].astype(np.float32)
)[:, 1]

print(
    "Score range:",
    float(val_feature_df["score_expanded_72"].min()),
    "→",
    float(val_feature_df["score_expanded_72"].max())
)

print(
    "Score median:",
    float(val_feature_df["score_expanded_72"].median())
)

print("Scoring complete.")

======================================================================
STEP 27 — FIXED-72 VALIDATION SCORING
======================================================================
Score range: 0.0003062512834527343 → 0.9750566699460197
Score median: 0.0007518474723934448
Scoring complete.

In [98]:
# ============================================================
# STEP 28 — FIXED-72 MACRO F0.5
# FIX: rebuild groups AFTER adding score_expanded_72
# ============================================================

print("=" * 70)
print("STEP 28 — FIXED-72 MACRO F0.5")
print("=" * 70)

# ------------------------------------------------------------
# Rebuild validation groups using the CURRENT dataframe
# ------------------------------------------------------------

val_groups_72 = {
    str(s1_id): group
    for s1_id, group in val_feature_df.groupby(
        "source1_entity_id",
        sort=False
    )
}

print(
    "Validation S1 groups:",
    len(val_groups_72)
)

print(
    "Score column exists:",
    "score_expanded_72" in val_feature_df.columns
)

# ------------------------------------------------------------
# Validation S1 IDs
# ------------------------------------------------------------

all_val_s1_ids = [
    str(row["entity_id"])
    for row in val_s1_rows
]

# ------------------------------------------------------------
# Threshold sweep
# ------------------------------------------------------------

thresholds_72 = np.arange(
    0.50,
    0.991,
    0.002
)

results_72 = []

for threshold in thresholds_72:

    total_score = 0.0
    total_predicted = 0
    total_tp = 0
    total_gt = 0
    rows_with_prediction = 0

    for s1_id in all_val_s1_ids:

        true_set = ground_truth_val.get(
            s1_id,
            set()
        )

        total_gt += len(true_set)

        group = val_groups_72.get(s1_id)

        if group is None:

            pred_set = set()

        else:

            pred_set = set(
                group.loc[
                    group["score_expanded_72"] >= threshold,
                    "candidate_entity_id"
                ].astype(str)
            )

        score = f05_single(
            pred_set,
            true_set
        )

        total_score += score

        total_predicted += len(pred_set)

        total_tp += len(
            pred_set & true_set
        )

        if pred_set:
            rows_with_prediction += 1

    macro_f05 = (
        total_score / len(all_val_s1_ids)
    )

    results_72.append({
        "threshold": float(threshold),
        "macro_f05": float(macro_f05),
        "predicted_pairs": int(total_predicted),
        "true_positives": int(total_tp),
        "precision": (
            total_tp / total_predicted
            if total_predicted
            else 0.0
        ),
        "recall": (
            total_tp / total_gt
            if total_gt
            else 0.0
        ),
        "rows_with_prediction": int(
            rows_with_prediction
        )
    })


# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

results_72_df = (
    pd.DataFrame(results_72)
    .sort_values(
        "macro_f05",
        ascending=False
    )
    .reset_index(drop=True)
)

print("\n" + "=" * 70)
print("TOP 20 FIXED-72 THRESHOLDS")
print("=" * 70)

print(
    results_72_df.head(20).to_string(
        index=False
    )
)

# ------------------------------------------------------------
# Best
# ------------------------------------------------------------

best72 = results_72_df.iloc[0]

BEST_THRESHOLD_72 = float(
    best72["threshold"]
)

BEST_F05_72 = float(
    best72["macro_f05"]
)

print("\n" + "=" * 70)
print("FIXED-72 BEST RESULT")
print("=" * 70)

print(
    f"Threshold      : {BEST_THRESHOLD_72:.4f}"
)

print(
    f"Macro F0.5     : {BEST_F05_72:.6f}"
)

print(
    f"Macro F0.5 %   : {BEST_F05_72 * 100:.4f}%"
)

print(
    f"Precision      : {best72['precision']:.6f}"
)

print(
    f"Recall         : {best72['recall']:.6f}"
)

print(
    f"Predicted      : "
    f"{int(best72['predicted_pairs']):,}"
)

print(
    f"True positives : "
    f"{int(best72['true_positives']):,}"
)

print(
    f"Rows predicted : "
    f"{int(best72['rows_with_prediction']):,}"
    f"/{len(all_val_s1_ids):,}"
)

print("\nBASELINE MODEL")
print("Macro F0.5     : 81.2059%")

print(
    f"\nCHANGE         : "
    f"{(BEST_F05_72 - 0.812059) * 100:+.4f} percentage points"
)

======================================================================
STEP 28 — FIXED-72 MACRO F0.5
======================================================================
Validation S1 groups: 2000
Score column exists: True

======================================================================
TOP 20 FIXED-72 THRESHOLDS
======================================================================
 threshold  macro_f05  predicted_pairs  true_positives  precision   recall  rows_with_prediction
     0.944   0.807713             5477            4969   0.907248 0.718687                  1837
     0.946   0.802445             5393            4905   0.909512 0.709430                  1826
     0.942   0.800580             6007            5249   0.873814 0.759184                  1880
     0.940   0.752434             7315            5779   0.790021 0.835840                  1954
     0.938   0.743625             7576            5886   0.776927 0.851316                  1972
     0.936   0.740205             7690            5931   0.771261 0.857825                  1976
     0.934   0.739629             7775            5969   0.767717 0.863321                  1979
     0.932   0.735984             7862            5992   0.762147 0.866647                  1983
     0.930   0.735457             7905            6012   0.760531 0.869540                  1983
     0.926   0.734105             8000            6053   0.756625 0.875470                  1983
     0.928   0.734033             7951            6027   0.758018 0.871710                  1983
     0.924   0.733762             8028            6064   0.755356 0.877061                  1983
     0.920   0.731871             8153            6116   0.750153 0.884582                  1987
     0.922   0.731451             8119            6098   0.751078 0.881979                  1986
     0.918   0.730471             8222            6142   0.747020 0.888342                  1987
     0.916   0.728108             8300            6162   0.742410 0.891235                  1987
     0.948   0.727124             3961            3857   0.973744 0.557854                  1588
     0.914   0.726021             8359            6175   0.738725 0.893115                  1987
     0.912   0.724663             8392            6183   0.736773 0.894272                  1987
     0.910   0.723365             8429            6189   0.734251 0.895140                  1987

======================================================================
FIXED-72 BEST RESULT
======================================================================
Threshold      : 0.9440
Macro F0.5     : 0.807713
Macro F0.5 %   : 80.7713%
Precision      : 0.907248
Recall         : 0.718687
Predicted      : 5,477
True positives : 4,969
Rows predicted : 1,837/2,000

BASELINE MODEL
Macro F0.5     : 81.2059%

CHANGE         : -0.4346 percentage points

In [99]:
# ============================================================
# STEP 29 — BASELINE ERROR + CANDIDATE RECALL DIAGNOSTIC
# ============================================================

print("=" * 70)
print("STEP 29 — VALIDATION BOTTLENECK DIAGNOSTIC")
print("=" * 70)

BASE_THRESHOLD = 0.944

# ------------------------------------------------------------
# 1. Candidate recall on the 2,000 validation S1
# ------------------------------------------------------------

candidate_sets = {}

for s1_id, group in val_feature_df.groupby("source1_entity_id", sort=False):
    candidate_sets[str(s1_id)] = set(group["candidate_entity_id"].astype(str))

total_gt_pairs = 0
found_gt_pairs = 0
rows_with_missing_gt = 0
rows_with_zero_candidates = 0

missing_examples = []

for s1_id, gt_ids in ground_truth_val.items():
    s1_id = str(s1_id)

    gt_set = set(map(str, gt_ids))
    cand_set = candidate_sets.get(s1_id, set())

    total_gt_pairs += len(gt_set)
    found = gt_set & cand_set
    found_gt_pairs += len(found)

    if len(gt_set - cand_set) > 0:
        rows_with_missing_gt += 1

        if len(missing_examples) < 20:
            missing_examples.append({
                "source1_entity_id": s1_id,
                "gt_count": len(gt_set),
                "found": len(found),
                "missing": len(gt_set - cand_set),
                "missing_ids": list(gt_set - cand_set)[:5]
            })

    if len(cand_set) == 0:
        rows_with_zero_candidates += 1

pair_recall = (
    found_gt_pairs / total_gt_pairs
    if total_gt_pairs else 0
)

print("\n" + "=" * 70)
print("CANDIDATE RECALL")
print("=" * 70)

print(f"GT pairs             : {total_gt_pairs:,}")
print(f"GT pairs found       : {found_gt_pairs:,}")
print(f"GT pairs missing     : {total_gt_pairs - found_gt_pairs:,}")
print(f"Pair recall          : {pair_recall:.6%}")
print(f"Rows with missing GT : {rows_with_missing_gt:,}")
print(f"Rows with zero cand. : {rows_with_zero_candidates:,}")


# ------------------------------------------------------------
# 2. Baseline prediction statistics
# ------------------------------------------------------------

predicted_pairs = 0
true_positive_pairs = 0
false_positive_pairs = 0
rows_with_prediction = 0
rows_with_gt = 0
rows_correct_exact = 0

row_diagnostics = []

for s1_id, group in val_feature_df.groupby(
    "source1_entity_id", sort=False
):
    s1_id = str(s1_id)

    gt_set = set(map(str, ground_truth_val.get(s1_id, [])))

    pred = set(
        group.loc[
            group["score"] >= BASE_THRESHOLD,
            "candidate_entity_id"
        ].astype(str)
    )

    tp = len(pred & gt_set)
    fp = len(pred - gt_set)
    fn = len(gt_set - pred)

    predicted_pairs += len(pred)
    true_positive_pairs += tp
    false_positive_pairs += fp

    if len(pred) > 0:
        rows_with_prediction += 1

    if len(gt_set) > 0:
        rows_with_gt += 1

    # Exact set match for this S1
    if pred == gt_set:
        rows_correct_exact += 1

    row_diagnostics.append({
        "source1_entity_id": s1_id,
        "gt_count": len(gt_set),
        "candidate_count": len(group),
        "pred_count": len(pred),
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "candidate_recall": (
            len(gt_set & set(group["candidate_entity_id"].astype(str)))
            / len(gt_set)
            if gt_set else 1.0
        ),
        "has_missing_candidate_gt": (
            len(gt_set - set(group["candidate_entity_id"].astype(str))) > 0
        ),
    })

diag_df = pd.DataFrame(row_diagnostics)

print("\n" + "=" * 70)
print("BASELINE ERROR BREAKDOWN")
print("=" * 70)

print(f"Predicted pairs      : {predicted_pairs:,}")
print(f"True positives       : {true_positive_pairs:,}")
print(f"False positives      : {false_positive_pairs:,}")
print(f"Rows predicted       : {rows_with_prediction:,}/{len(diag_df):,}")
print(f"Rows with GT         : {rows_with_gt:,}")
print(f"Exact-set rows       : {rows_correct_exact:,}")

print("\n" + "=" * 70)
print("ROW-LEVEL DIAGNOSTICS")
print("=" * 70)

print(
    f"Rows with candidate recall < 100% : "
    f"{diag_df['has_missing_candidate_gt'].sum():,}"
)

print(
    f"Mean candidate recall             : "
    f"{diag_df['candidate_recall'].mean():.6%}"
)

print(
    f"Median candidate recall           : "
    f"{diag_df['candidate_recall'].median():.6%}"
)

print(
    f"Rows with FN at threshold         : "
    f"{(diag_df['fn'] > 0).sum():,}"
)

print(
    f"Rows with FP at threshold         : "
    f"{(diag_df['fp'] > 0).sum():,}"
)


# ------------------------------------------------------------
# 3. Separate MODEL errors from BLOCKING errors
# ------------------------------------------------------------

blocking_loss = diag_df["has_missing_candidate_gt"].sum()

model_loss = (
    (diag_df["fn"] > 0) &
    (~diag_df["has_missing_candidate_gt"])
).sum()

mixed_loss = (
    (diag_df["fn"] > 0) &
    (diag_df["has_missing_candidate_gt"])
).sum()

print("\n" + "=" * 70)
print("BOTTLENECK SPLIT")
print("=" * 70)

print(f"Rows affected by blocking : {blocking_loss:,}")
print(f"Pure model FN rows        : {model_loss:,}")
print(f"Mixed blocking/model rows : {mixed_loss:,}")


# ------------------------------------------------------------
# 4. Show worst rows
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TOP 20 ROWS WITH MISSING GT CANDIDATES")
print("=" * 70)

display(
    diag_df[
        diag_df["has_missing_candidate_gt"]
    ]
    .sort_values(
        ["fn", "candidate_count"],
        ascending=[False, False]
    )
    .head(20)
)


print("\n" + "=" * 70)
print("TOP 20 MODEL FN ROWS WITH 100% CANDIDATE RECALL")
print("=" * 70)

display(
    diag_df[
        (~diag_df["has_missing_candidate_gt"]) &
        (diag_df["fn"] > 0)
    ]
    .sort_values(
        ["fn", "candidate_count"],
        ascending=[False, False]
    )
    .head(20)
)

print("\n" + "=" * 70)
print("FIRST 20 BLOCKING MISS EXAMPLES")
print("=" * 70)

display(pd.DataFrame(missing_examples))

======================================================================
STEP 29 — VALIDATION BOTTLENECK DIAGNOSTIC
======================================================================

======================================================================
CANDIDATE RECALL
======================================================================
GT pairs             : 7,638,365
GT pairs found       : 6,563
GT pairs missing     : 7,631,802
Pair recall          : 0.085922%
Rows with missing GT : 2,081,946
Rows with zero cand. : 2,204,821

======================================================================
BASELINE ERROR BREAKDOWN
======================================================================
Predicted pairs      : 5,958
True positives       : 5,284
False positives      : 674
Rows predicted       : 1,878/2,000
Rows with GT         : 1,900
Exact-set rows       : 635

======================================================================
ROW-LEVEL DIAGNOSTICS
======================================================================
Rows with candidate recall < 100% : 272
Mean candidate recall             : 95.286290%
Median candidate recall           : 100.000000%
Rows with FN at threshold         : 1,000
Rows with FP at threshold         : 638

======================================================================
BOTTLENECK SPLIT
======================================================================
Rows affected by blocking : 272
Pure model FN rows        : 728
Mixed blocking/model rows : 272

======================================================================
TOP 20 ROWS WITH MISSING GT CANDIDATES
======================================================================

,source1_entity_id,gt_count,candidate_count,pred_count,tp,fp,fn,candidate_recall,has_missing_candidate_gt
630,S1-163567186,7,908,0,0,0,7,0.000000,True
898,S1-914622541,7,1002,1,1,0,6,0.571429,True
153,S1-341097791,8,885,2,2,0,6,0.750000,True
1412,S1-596058354,7,797,1,1,0,6,0.857143,True
224,S1-570692468,7,547,1,1,0,6,0.714286,True
1404,S1-635390945,7,465,1,1,0,6,0.428571,True
1924,S1-960478188,5,1410,0,0,0,5,0.800000,True
249,S1-308960965,6,1023,1,1,0,5,0.833333,True
692,S1-140223936,8,532,3,3,0,5,0.750000,True
1123,S1-300435055,5,252,0,0,0,5,0.600000,True
963,S1-654117873,7,4,2,2,0,5,0.285714,True
1877,S1-249493462,6,1753,2,2,0,4,0.833333,True
1635,S1-127491881,5,1353,1,1,0,4,0.400000,True
782,S1-205860416,6,1192,2,2,0,4,0.666667,True
1401,S1-468961522,6,998,2,2,0,4,0.833333,True
605,S1-860397041,8,937,4,4,0,4,0.750000,True
1646,S1-258724443,6,934,2,2,0,4,0.833333,True
982,S1-500020440,4,902,1,0,1,4,0.500000,True
1844,S1-743790598,5,889,1,1,0,4,0.800000,True
1028,S1-992051878,7,868,3,3,0,4,0.857143,True

======================================================================
TOP 20 MODEL FN ROWS WITH 100% CANDIDATE RECALL
======================================================================

,source1_entity_id,gt_count,candidate_count,pred_count,tp,fp,fn,candidate_recall,has_missing_candidate_gt
1198,S1-771626801,5,880,0,0,0,5,1.0,False
49,S1-203869872,4,980,1,0,1,4,1.0,False
307,S1-454568439,4,841,0,0,0,4,1.0,False
600,S1-157307694,9,781,5,5,0,4,1.0,False
850,S1-263890732,6,753,3,2,1,4,1.0,False
1761,S1-875685290,5,734,1,1,0,4,1.0,False
648,S1-601003140,4,611,0,0,0,4,1.0,False
1513,S1-873149130,6,606,2,2,0,4,1.0,False
632,S1-39270424,7,600,4,3,1,4,1.0,False
895,S1-17600046,4,597,0,0,0,4,1.0,False
386,S1-142430520,6,587,2,2,0,4,1.0,False
1584,S1-649870864,7,575,3,3,0,4,1.0,False
1848,S1-26557495,6,543,2,2,0,4,1.0,False
1953,S1-231433710,5,535,1,1,0,4,1.0,False
1197,S1-939270751,5,500,1,1,0,4,1.0,False
72,S1-932419905,4,395,0,0,0,4,1.0,False
1193,S1-454216444,6,391,2,2,0,4,1.0,False
1995,S1-465216093,4,297,0,0,0,4,1.0,False
924,S1-885349481,5,253,1,1,0,4,1.0,False
181,S1-892736187,6,219,2,2,0,4,1.0,False

======================================================================
FIRST 20 BLOCKING MISS EXAMPLES
======================================================================

,source1_entity_id,gt_count,found,missing,missing_ids
0,S1-965667,5,0,5,"[S3-11291185, S2-681193310, S3-860443364, S3-7..."
1,S1-55344266,4,0,4,"[S3-384364074, S3-478195123, S2-197070651, S2-..."
2,S1-343815751,3,0,3,"[S2-479876582, S2-790675320, S3-878454467]"
3,S1-656753428,3,0,3,"[S3-679606215, S2-24659151, S2-153058913]"
4,S1-102811957,6,0,6,"[S2-553508714, S2-625774905, S3-728090388, S3-..."
5,S1-18727616,4,0,4,"[S3-476250621, S3-187831601, S3-641489370, S2-..."
6,S1-318373630,2,0,2,"[S3-804600254, S2-660036492]"
7,S1-86989137,2,0,2,"[S3-274817120, S3-312496301]"
8,S1-29845983,2,0,2,"[S3-588502663, S2-648035184]"
9,S1-789009573,3,0,3,"[S2-383871912, S3-74481402, S3-576451439]"
10,S1-730934468,2,0,2,"[S3-352439310, S2-356983532]"
11,S1-7293388,4,0,4,"[S2-157073701, S2-7028416, S2-442723188, S3-52..."
12,S1-546142636,6,0,6,"[S3-249331830, S2-487600131, S3-729771680, S2-..."
13,S1-274126313,6,0,6,"[S2-51486805, S3-925631694, S2-736616474, S3-8..."
14,S1-145361722,3,0,3,"[S2-120366543, S2-939389287, S3-96572514]"
15,S1-503957000,7,0,7,"[S3-858763214, S3-33665521, S2-994658326, S2-2..."
16,S1-692000596,2,0,2,"[S3-164220452, S2-580419223]"
17,S1-561341312,2,0,2,"[S3-619529814, S2-483615364]"
18,S1-777597828,2,0,2,"[S2-836452886, S3-413669121]"
19,S1-282467635,2,0,2,"[S3-138350041, S2-938895481]"

In [101]:
# ============================================================
# STEP 30A — SAFE VALIDATION OBJECT CHECK
# ============================================================

print("=" * 70)
print("STEP 30A — SAFE VALIDATION OBJECT CHECK")
print("=" * 70)

import sys
import os
import inspect

# ------------------------------------------------------------
# 1. Check validation objects
# ------------------------------------------------------------

print("\nOBJECT TYPES / SIZES")
print("-" * 70)

print("ground_truth_val type :", type(ground_truth_val))
print("ground_truth_val len  :", len(ground_truth_val))

print("candidate_sets type   :", type(candidate_sets))
print("candidate_sets len    :", len(candidate_sets))

print("val_feature_df shape  :", val_feature_df.shape)

# ------------------------------------------------------------
# 2. Inspect first few GT entries
# ------------------------------------------------------------

print("\nFIRST 5 ground_truth_val ENTRIES")
print("-" * 70)

for i, (k, v) in enumerate(ground_truth_val.items()):
    print(
        f"{i}:",
        repr(k),
        "=> type:", type(v),
        "len:", len(v) if hasattr(v, "__len__") else "NA",
        "sample:", list(v)[:5] if hasattr(v, "__iter__") else v
    )

    if i >= 4:
        break

# ------------------------------------------------------------
# 3. Inspect candidate_sets
# ------------------------------------------------------------

print("\nFIRST 5 candidate_sets ENTRIES")
print("-" * 70)

for i, (k, v) in enumerate(candidate_sets.items()):
    print(
        f"{i}:",
        repr(k),
        "=> type:", type(v),
        "len:", len(v) if hasattr(v, "__len__") else "NA",
        "sample:", list(v)[:5] if hasattr(v, "__iter__") else v
    )

    if i >= 4:
        break

# ------------------------------------------------------------
# 4. Recompute GT pair count SAFELY
# ------------------------------------------------------------

gt_pair_count = 0

for gt_ids in ground_truth_val.values():
    gt_pair_count += len(gt_ids)

print("\nTOTAL GT PAIRS IN VALIDATION")
print("-" * 70)
print(f"GT pairs: {gt_pair_count:,}")

# ------------------------------------------------------------
# 5. Recompute candidate recall WITHOUT creating millions
#    of Python tuples/lists.
# ------------------------------------------------------------

found_pairs = 0
missing_pairs_count = 0
rows_with_missing = 0
rows_with_zero_candidates = 0

for s1_id, gt_ids in ground_truth_val.items():

    s1_id = str(s1_id)

    cand_set = candidate_sets.get(s1_id, set())

    if not cand_set:
        rows_with_zero_candidates += 1

    gt_set = set(map(str, gt_ids))

    found = gt_set.intersection(cand_set)

    found_pairs += len(found)

    if len(found) < len(gt_set):
        rows_with_missing += 1
        missing_pairs_count += len(gt_set) - len(found)

print("\nSAFE CANDIDATE RECALL")
print("-" * 70)

print(f"GT pairs             : {gt_pair_count:,}")
print(f"GT pairs found       : {found_pairs:,}")
print(f"GT pairs missing     : {missing_pairs_count:,}")
print(f"Rows with missing GT : {rows_with_missing:,}")
print(f"Rows with zero cand. : {rows_with_zero_candidates:,}")

if gt_pair_count:
    print(
        f"Pair recall          : "
        f"{found_pairs / gt_pair_count:.6%}"
    )

# ------------------------------------------------------------
# 6. FIX MODULE IMPORT PATH
# ------------------------------------------------------------

MODULE_DIR = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

print("\nMODULE PATH")
print("-" * 70)
print("Exists:", os.path.isdir(MODULE_DIR))
print("Path  :", MODULE_DIR)

if MODULE_DIR not in sys.path:
    sys.path.insert(0, MODULE_DIR)

# Import the actual blocking.py directly.
import blocking as blocking_mod

print("\nBLOCKING MODULE")
print("-" * 70)
print("Imported from:", blocking_mod.__file__)

print(
    "find_candidates signature:",
    inspect.signature(blocking_mod.find_candidates)
)

print(
    "generate_candidate_pairs_for_row signature:",
    inspect.signature(
        blocking_mod.generate_candidate_pairs_for_row
    )
)

print("\n" + "=" * 70)
print("STEP 30A COMPLETE — NO CANDIDATES REGENERATED")
print("=" * 70)

======================================================================
STEP 30A — SAFE VALIDATION OBJECT CHECK
======================================================================

OBJECT TYPES / SIZES
----------------------------------------------------------------------
ground_truth_val type : <class 'dict'>
ground_truth_val len  : 2206821
candidate_sets type   : <class 'dict'>
candidate_sets len    : 2000
val_feature_df shape  : (842159, 32)

FIRST 5 ground_truth_val ENTRIES
----------------------------------------------------------------------
0: 'S1-965667' => type: <class 'set'> len: 5 sample: ['S3-775321672', 'S2-743505751', 'S3-11291185', 'S2-681193310', 'S3-860443364']
1: 'S1-55344266' => type: <class 'set'> len: 4 sample: ['S3-384364074', 'S3-478195123', 'S2-249013014', 'S2-197070651']
2: 'S1-343815751' => type: <class 'set'> len: 3 sample: ['S2-479876582', 'S2-790675320', 'S3-878454467']
3: 'S1-656753428' => type: <class 'set'> len: 3 sample: ['S3-679606215', 'S2-24659151', 'S2-153058913']
4: 'S1-102811957' => type: <class 'set'> len: 6 sample: ['S2-553508714', 'S3-728090388', 'S3-928796641', 'S2-625774905', 'S3-449308785']

FIRST 5 candidate_sets ENTRIES
----------------------------------------------------------------------
0: 'S1-855856142' => type: <class 'set'> len: 464 sample: ['S2-627406405', 'S3-723789951', 'S2-164421145', 'S2-787042040', 'S2-75590647']
1: 'S1-994066728' => type: <class 'set'> len: 134 sample: ['S3-321190204', 'S3-489013337', 'S2-244482499', 'S3-619977537', 'S3-900556800']
2: 'S1-583653395' => type: <class 'set'> len: 309 sample: ['S2-338415458', 'S2-155099896', 'S2-807221669', 'S2-198125689', 'S3-149206028']
3: 'S1-939814352' => type: <class 'set'> len: 802 sample: ['S2-35306700', 'S2-761789563', 'S2-981638844', 'S2-918652939', 'S2-155336429']
4: 'S1-679362510' => type: <class 'set'> len: 204 sample: ['S2-477578793', 'S2-690536137', 'S3-866216629', 'S3-190089823', 'S2-994745722']

TOTAL GT PAIRS IN VALIDATION
----------------------------------------------------------------------
GT pairs: 7,638,365

SAFE CANDIDATE RECALL
----------------------------------------------------------------------
GT pairs             : 7,638,365
GT pairs found       : 6,563
GT pairs missing     : 7,631,802
Rows with missing GT : 2,081,946
Rows with zero cand. : 2,204,821
Pair recall          : 0.085922%

MODULE PATH
----------------------------------------------------------------------
Exists: True
Path  : /kaggle/input/datasets/tejasweerajput/amazon-v3/modules

BLOCKING MODULE
----------------------------------------------------------------------
Imported from: /kaggle/input/datasets/tejasweerajput/amazon-v3/modules/blocking.py

AttributeError: module 'blocking' has no attribute 'find_candidates'

In [102]:
# ============================================================
# STEP 30B — CORRECT VALIDATION-ONLY BLOCKING DIAGNOSTIC
# ============================================================

print("=" * 70)
print("STEP 30B — CORRECT VALIDATION-ONLY BLOCKING DIAGNOSTIC")
print("=" * 70)

# ------------------------------------------------------------
# 1. Use the EXACT 2,000 validation S1 IDs
# ------------------------------------------------------------

val_s1_ids = set(map(str, all_val_s1_ids))

print(f"\nValidation S1 IDs : {len(val_s1_ids):,}")

# ------------------------------------------------------------
# 2. Restrict the FULL ground truth to validation only
# ------------------------------------------------------------

ground_truth_val_correct = {
    str(s1_id): set(map(str, gt_ids))
    for s1_id, gt_ids in ground_truth.items()
    if str(s1_id) in val_s1_ids
}

print(f"Validation GT rows: {len(ground_truth_val_correct):,}")

# Safety check
assert len(ground_truth_val_correct) == len(val_s1_ids), (
    "Validation S1 IDs and ground truth do not align."
)

# ------------------------------------------------------------
# 3. Candidate sets are already exactly 2,000 rows
# ------------------------------------------------------------

assert len(candidate_sets) == 2000

candidate_s1_ids = set(map(str, candidate_sets.keys()))

print(f"Candidate S1 rows : {len(candidate_s1_ids):,}")

missing_validation_ids = val_s1_ids - candidate_s1_ids

print(
    f"Validation IDs missing from candidate_sets: "
    f"{len(missing_validation_ids):,}"
)

assert len(missing_validation_ids) == 0, (
    "candidate_sets does not contain all validation S1 IDs."
)

# ------------------------------------------------------------
# 4. Correct candidate recall calculation
# ------------------------------------------------------------

total_gt_pairs = 0
found_gt_pairs = 0
missing_gt_pairs = 0

rows_with_missing_gt = 0
rows_with_zero_candidates = 0

blocking_diagnostics = []

for s1_id in all_val_s1_ids:

    s1_id = str(s1_id)

    gt_set = ground_truth_val_correct[s1_id]
    cand_set = candidate_sets[s1_id]

    found = gt_set.intersection(cand_set)
    missing = gt_set - cand_set

    total_gt_pairs += len(gt_set)
    found_gt_pairs += len(found)
    missing_gt_pairs += len(missing)

    if len(missing) > 0:
        rows_with_missing_gt += 1

    if len(cand_set) == 0:
        rows_with_zero_candidates += 1

    blocking_diagnostics.append({
        "source1_entity_id": s1_id,
        "gt_count": len(gt_set),
        "candidate_count": len(cand_set),
        "found_gt": len(found),
        "missing_gt": len(missing),
        "candidate_recall": (
            len(found) / len(gt_set)
            if len(gt_set) > 0
            else 1.0
        ),
    })

# ------------------------------------------------------------
# 5. Results
# ------------------------------------------------------------

correct_pair_recall = (
    found_gt_pairs / total_gt_pairs
    if total_gt_pairs > 0
    else 0
)

diag_df_correct = pd.DataFrame(blocking_diagnostics)

print("\n" + "=" * 70)
print("CORRECT VALIDATION BLOCKING RECALL")
print("=" * 70)

print(f"Validation S1 rows       : {len(val_s1_ids):,}")
print(f"GT pairs                 : {total_gt_pairs:,}")
print(f"GT pairs found           : {found_gt_pairs:,}")
print(f"GT pairs missing         : {missing_gt_pairs:,}")
print(f"Pair recall              : {correct_pair_recall:.6%}")
print(f"Rows with missing GT     : {rows_with_missing_gt:,}")
print(f"Rows with zero candidates: {rows_with_zero_candidates:,}")

print("\n" + "=" * 70)
print("CANDIDATE COUNT DISTRIBUTION")
print("=" * 70)

print(
    diag_df_correct["candidate_count"]
    .describe()
    .to_string()
)

print("\n" + "=" * 70)
print("WORST BLOCKING ROWS")
print("=" * 70)

display(
    diag_df_correct
    .sort_values(
        ["missing_gt", "candidate_count"],
        ascending=[False, False]
    )
    .head(20)
)

print("\n" + "=" * 70)
print("STEP 30B COMPLETE")
print("=" * 70)

======================================================================
STEP 30B — CORRECT VALIDATION-ONLY BLOCKING DIAGNOSTIC
======================================================================

Validation S1 IDs : 2,000
Validation GT rows: 2,000
Candidate S1 rows : 2,000
Validation IDs missing from candidate_sets: 0

======================================================================
CORRECT VALIDATION BLOCKING RECALL
======================================================================
Validation S1 rows       : 2,000
GT pairs                 : 6,914
GT pairs found           : 6,563
GT pairs missing         : 351
Pair recall              : 94.923344%
Rows with missing GT     : 272
Rows with zero candidates: 0

======================================================================
CANDIDATE COUNT DISTRIBUTION
======================================================================
count    2000.000000
mean      421.079500
std       302.795041
min         3.000000
25%       175.000000
50%       386.000000
75%       590.000000
max      2022.000000

======================================================================
WORST BLOCKING ROWS
======================================================================

,source1_entity_id,gt_count,candidate_count,found_gt,missing_gt,candidate_recall
630,S1-163567186,7,908,0,7,0.000000
963,S1-654117873,7,4,2,5,0.285714
364,S1-343636643,4,715,0,4,0.000000
1404,S1-635390945,7,465,3,4,0.428571
242,S1-560290866,6,1412,3,3,0.500000
1635,S1-127491881,5,1353,2,3,0.400000
898,S1-914622541,7,1002,4,3,0.571429
1413,S1-708610889,5,778,2,3,0.400000
320,S1-426723298,3,710,0,3,0.000000
660,S1-658192036,3,695,0,3,0.000000
1486,S1-884904716,4,369,1,3,0.250000
741,S1-469535575,5,138,2,3,0.400000
1910,S1-804892516,6,135,3,3,0.500000
696,S1-682824625,3,122,0,3,0.000000
782,S1-205860416,6,1192,4,2,0.666667
581,S1-636370789,2,1099,0,2,0.000000
1362,S1-732307284,5,1025,3,2,0.600000
1206,S1-249159728,5,955,3,2,0.600000
605,S1-860397041,8,937,6,2,0.750000
982,S1-500020440,4,902,2,2,0.500000

======================================================================
STEP 30B COMPLETE
======================================================================

In [103]:
# ============================================================
# STEP 31 — INSPECT ACTUAL BLOCKING MISSES
# ============================================================

print("=" * 70)
print("STEP 31 — ACTUAL BLOCKING MISS INSPECTION")
print("=" * 70)

# ------------------------------------------------------------
# Build S1 lookup
# ------------------------------------------------------------

s1_lookup = {
    str(row["entity_id"]): row
    for row in train_s1
}

# ------------------------------------------------------------
# Collect ONLY the 351 missing GT pairs
# ------------------------------------------------------------

missing_records = []

for s1_id in all_val_s1_ids:

    s1_id = str(s1_id)

    gt_set = ground_truth_val_correct[s1_id]
    cand_set = candidate_sets[s1_id]

    missing_ids = gt_set - cand_set

    if not missing_ids:
        continue

    s1_row = s1_lookup[s1_id]

    for gt_id in missing_ids:

        if gt_id.startswith("S2-"):
            index = s2_index
            source = "S2"
        elif gt_id.startswith("S3-"):
            index = s3_index
            source = "S3"
        else:
            continue

        suffix = gt_id[3:]

        try:
            gt_name, gt_address, gt_country = index.get_attrs(suffix)
        except Exception:
            continue

        missing_records.append({
            "s1_id": s1_id,
            "gt_id": gt_id,
            "source": source,

            "s1_name": s1_row["business_name"],
            "s1_address": s1_row["business_address"],
            "s1_country": s1_row["country"],

            "gt_name": gt_name,
            "gt_address": gt_address,
            "gt_country": gt_country,
        })

missing_df = pd.DataFrame(missing_records)

print(f"\nMissing GT records inspected: {len(missing_df):,}")

# ------------------------------------------------------------
# Show examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 30 MISSING GT PAIRS")
print("=" * 70)

display(
    missing_df.head(30)
)

======================================================================
STEP 31 — ACTUAL BLOCKING MISS INSPECTION
======================================================================

Missing GT records inspected: 351

======================================================================
FIRST 30 MISSING GT PAIRS
======================================================================

,s1_id,gt_id,source,s1_name,s1_address,s1_country,gt_name,gt_address,gt_country
0,S1-301369134,S3-304200480,S3,"Sapphire, Inc","100 Chapel Court, Unit 215, Walkersville, MD",US,"Sapphire,-Inc.","Chapel Ct, # 215, Walkersville, Maryland",US
1,S1-121577413,S3-20638002,S3,Premier Foods Private Limited,"Plot No. 3, 14/1 Ambedkar Road, Lic Choraha, N...",India,Premier फूड्स प्राइवेट लिमिटेड,"No 3, Neemuch, MP",India
2,S1-319961138,S3-554626257,S3,Krishan Technology Ltd,"No.2954, Ramdass Complexmahakavi Kuvempu Road ...",India,Smt Krishan Technology [Ltd.],"#2954, Bangalore, Rajajinagar Bangalore., ಕರ್ನಾಟಕ",India
3,S1-732874695,S3-29188601,S3,White Marketing Private Limited,"33, Dholi Bawri, Udaipur, Rajasthan",India,Shri White Marketing Private Ltd,"33, Udaipur, राजस्थान",India
4,S1-84081739,S3-466428155,S3,Hari Arts Pvt. Ltd.,"Rs No 312/B Plot No 10/A, Aditya Nagar, Gokak,...",India,Pvt. Hari Arot Ltd.,"Rs No 12/B Plt No 10/A, Belgaum, KA",India
5,S1-328379638,S3-826694275,S3,Great Healthcare Private Limited,"Sawai Madhopur, Near Bus Stand, Teh-Mitrapura,...",India,Great हेल्थकेयर प्राइवेट लिमिटेड,"Near Bus Stand, Teh-mitrapura, Bonli, RJ",India
6,S1-612288482,S3-357738147,S3,Classic Trading Private Limited,"3, Haddowsrd, Chennai-63, Haddowsrd, Chennai-6...",India,கிளாசிக் டிரேடிங் பிரைவேட் லிமிடெட்,"3, Chennai-6, Chennai, TN",India
7,S1-540232781,S2-431778910,S2,Quality Asset Works,"455 Arden Road, Upper Merion Township, PA",US,wqasset.com,"PA, CONSHOHOCKEN, 455 ARDEN RD",US
8,S1-407695807,S2-168906583,S2,A+ Companies Group,"6245 Presidio Street, Mesa, AZ",US,A+ Group Companies,"AZ, MESA FALCON FIELD, 624 PRESIDIO STREET",US
9,S1-156878332,S2-148871316,S2,Good Care Private Limited,"Flat No. 8 Vasant Enclave, Palam Marg, New Del...",India,गुड केयर प्राइवेट लिमिटेड,"8 VASANT ENCLAVE, PALAM MARG, NEW DELHI, Delhi",India
10,S1-487841439,S2-313395306,S2,Apex Infra Private Limited,"C/O Smt Mani Kumari, Khata No.168 Plot No.1215...",India,एपेक्स इंफ्रा प्राइवेट लिमिटेड,"C/O SMT MANI KUMARI, GODIHA, Bihar",India
11,S1-131692277,S3-881688514,S3,Heart Program LP,"15 Riverview Street, Brattleboro, VT",US,Heart LP Service,,US
12,S1-946771116,S3-847878051,S3,South Premier Foundation Private Limited,"H No 12-2-790/153, Ayodhya Nagar Colony Dilsha...",India,సౌత్ ప్రీమియర్ ఫౌండేషన్ ప్రైవేట్ లిమిటెడ్,"#12-2-790/153, Hyderabad, Andhra Pradesh",India
13,S1-489056211,S2-397116468,S2,Forge Inc,"308 12th Street, Sac City, IA",US,Flore Inc,"Twelfth Street, SAC CITY, IA",US
14,S1-340753288,S3-16288150,S3,Chennai Design Ltd,"49, Sri Prabhu Illam, Subramanian Street Sendh...",India,ltd chennai design,"#49, Madras, Thiruvallur, TN",India
15,S1-345536929,S3-275713282,S3,Peak Assets Co,"8109 Waterside Trail, Fort Worth, TX",US,The Peak Assets Co,,US
16,S1-341097791,S2-709683238,S2,Shree Investments Private Limited,"Street No.2, Karan Park, B/H. Siyaram Dairy, N...",India,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,"RAJKOT, BLOCK G-427 STREET NO.2, Gujarat",India
17,S1-341097791,S3-790821637,S3,Shree Investments Private Limited,"Street No.2, Karan Park, B/H. Siyaram Dairy, N...",India,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,"787 Street No.2, Rajkot, GJ",India
18,S1-835179328,S3-79614433,S3,Bhubaneswar Consulting Private Limited,"Plot No. 627-1155, Chhatabar, Chandaka, Bhuban...",India,bhubaneswarconsultingprivate.com,"No 2-627-1155, Bhubaneswar, Badaraghunathpur, ...",India
19,S1-70712773,S3-229571580,S3,Behavioral Health Clinic LLC,"878 33, Waddington, NY",US,Behavioral-Health,"New York, 878 33, Waddington",US
20,S1-969611446,S3-249629497,S3,TMY Healthcare Ahmedabad,"Nirav Com Navrangpura, Ahmedabad, Gujarat",India,Ahmedabad Healthcare Tmy,"GJ, Nirav Com Navrangpura, Ahmedabad, Ahmedaba...",India
21,S1-350567233,S3-53315476,S3,Pinnacle Coastal,"3401 H Ave NW, Cedar Rapids, IA",US,Pinnacle Services Trading,,US
22,S1-1870741,S2-856224121,S2,Creative Ventures Private Limited,"C/O Sukumar Das, Banitala, (Sasaru Para), Ulub...",India,ক্রিয়েটিভ ভেঞ্চারস প্রাইভেট লিমিটেড,"C/O SUKUMAR DAS, DOMJUR, HOWRAH, West Bengal",India
23,S1-899335462,S3-488000874,S3,International Exports Limited,"3-1080, Syno 11/11To11/13, Uma Nilayam, Rd No....",India,ఇంటర్నేషనల్ ఎక్స్‌పోర్ట్స్ లిమిటెడ్,"3-1080, Hyderabad, Seri Lingampally, TG",India
24,S1-377836896,S3-364991009,S3,Counter Metal Private Limited,"Gujarat, Orchrad A 502, Ahmedabad, Ahmedabad C...",India,Limited Counter Private Services,"Orchrad A 00502, Gandhinagar, Ahmedabad, GJ",India
25,S1-254813910,S2-958799222,S2,Vijay Solutions Private Limited,"1B, Aravind Bhavanam, 7Th Street, Kuberer Naga...",India,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,"1B, MADRAS, CHENNAI, Tamil Nadu",India
26,S1-254813910,S2-250859577,S2,Vijay Solutions Private Limited,"1B, Aravind Bhavanam, 7Th Street, Kuberer Naga...",India,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,"Tamil Nadu, 1B, MADRAS",India
27,S1-95823999,S3-783312005,S3,Achilles & Brothers Pvt Ltd,"D-138, Flat No. 04, First Floo Krishna Park, K...",India,Pvt Achilles & Brnesr Ltd,"D-138, South Delhi, New Delhi, DL",India
28,S1-570692468,S3-979892181,S3,Fortune Systems Private Limited,"97, St.John'S Church Road, Bangalore-5, Bangal...",India,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"97, Bangalore-5, Bengaluru, ಕರ್ನಾಟಕ",India
29,S1-570692468,S3-869473412,S3,Fortune Systems Private Limited,"97, St.John'S Church Road, Bangalore-5, Bangal...",India,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"97, Bangalore-5, Bengaluru, KA",India

In [104]:
# ============================================================
# STEP 31B — NAME / ADDRESS SIMILARITY OF MISSES
# ============================================================

from rapidfuzz.fuzz import ratio, token_set_ratio

def safe_text(x):
    if x is None:
        return ""
    return str(x)

analysis_rows = []

for _, r in missing_df.iterrows():

    s1_name = safe_text(r["s1_name"])
    gt_name = safe_text(r["gt_name"])

    s1_addr = safe_text(r["s1_address"])
    gt_addr = safe_text(r["gt_address"])

    analysis_rows.append({
        "s1_id": r["s1_id"],
        "gt_id": r["gt_id"],
        "source": r["source"],

        "name_ratio": ratio(
            s1_name,
            gt_name
        ) / 100.0,

        "name_token_ratio": token_set_ratio(
            s1_name,
            gt_name
        ) / 100.0,

        "address_ratio": ratio(
            s1_addr,
            gt_addr
        ) / 100.0,

        "s1_country": r["s1_country"],
        "gt_country": r["gt_country"],

        "s1_name": s1_name,
        "gt_name": gt_name,

        "s1_address": s1_addr,
        "gt_address": gt_addr,
    })

miss_analysis_df = pd.DataFrame(analysis_rows)

print("=" * 70)
print("MISSING PAIR SIMILARITY DISTRIBUTION")
print("=" * 70)

display(
    miss_analysis_df[
        [
            "name_ratio",
            "name_token_ratio",
            "address_ratio"
        ]
    ].describe()
)

print("\n" + "=" * 70)
print("HIGHEST NAME-SIMILARITY MISSING PAIRS")
print("=" * 70)

display(
    miss_analysis_df
    .sort_values(
        ["name_token_ratio", "address_ratio"],
        ascending=False
    )
    .head(30)
)

======================================================================
MISSING PAIR SIMILARITY DISTRIBUTION
======================================================================

       name_ratio  name_token_ratio  address_ratio
count  351.000000        351.000000     351.000000
mean     0.479388          0.541686       0.401725
std      0.329960          0.379383       0.217259
min      0.000000          0.000000       0.000000
25%      0.105263          0.105263       0.262726
50%      0.545455          0.666667       0.390805
75%      0.781548          0.909091       0.528510
max      1.000000          1.000000       0.877551

======================================================================
HIGHEST NAME-SIMILARITY MISSING PAIRS
======================================================================

,s1_id,gt_id,source,name_ratio,name_token_ratio,address_ratio,s1_country,gt_country,s1_name,gt_name,s1_address,gt_address
217,S1-754363423,S3-12351257,S3,0.708333,1.0,0.813559,US,US,Valley Veterinary Clinic,Valley Clinic Veterinary,"212 Paloma Court, Gresham, OR","412 Paloma Ct, Gresham, Oregon"
57,S1-688640659,S3-982915915,S3,0.761905,1.0,0.794872,US,US,Strategic Blue Series,Strategic Series Blue,"4917 Amberwell Place, Henrico County, VA","Amberwell Pl, Henrico County, Virginia"
287,S1-842007149,S3-997394854,S3,0.500000,1.0,0.707692,US,US,Hunger Association,Hunger,"2119 Plaza Court, St Charles, MO","Plaza Ct, Saint Charles, Missouri"
141,S1-334424523,S3-303574153,S3,0.666667,1.0,0.701754,US,US,Lynx LLC,Lynx,"2118 74 Street, Brooklyn, NY","New York, 74 Street, Brooklyn"
134,S1-268200457,S3-810705657,S3,0.755556,1.0,0.692308,US,US,Behavioral Health Physicians,Behavioral Health,"6330 Vigo Drive, Clayton, IN","Vigo Dr, Cayton, Indiana"
201,S1-387829461,S3-950327283,S3,0.882353,1.0,0.684685,US,US,Lemus Northland,The Lemus Northland,"Unit 1, DE, 22251 Lewes Georgetown Highway, Ge...","022251 Lewes Georgetown Hwy, Unit 1, Georgetow..."
267,S1-192845076,S3-66771546,S3,0.809524,1.0,0.627451,US,US,Carter and Sheehy Inc,Carter Sheehy and Inc,"35 9P, Malta, NY","35 9P, PO Box 9662, Malta, New York"
326,S1-804892516,S3-926656803,S3,0.740741,1.0,0.561644,India,India,Consultants Udbhav Training,Consultants Training Udbhav,"2-B-14, Moxa, Sector Xi Shantinagar Co-Op. Hsg...","2-B-14, <NULL>, Mira Road East, Mumbai City, MH"
328,S1-804892516,S3-401938105,S3,0.740741,1.0,0.561644,India,India,Consultants Udbhav Training,Consultants Training Udbhav,"2-B-14, Moxa, Sector Xi Shantinagar Co-Op. Hsg...","2-B-14, <NULL>, Mira Road East, Mumbai City, MH"
263,S1-688260177,S3-358408242,S3,0.727273,1.0,0.526316,US,US,Williams Highland Connecticut LLC,Williams Connecticut Highland LLC,"6730 Purdy Parkway, City Of Appleton, WI","Appleton, 6730 Purdy Pkwy, Wisconsin"
97,S1-6692510,S3-551313219,S3,0.900000,1.0,0.519084,India,India,Shreenath & Brothers Private Limited,>> The Shreenath & Brothers Private Limited,"405, Minar Apartments, Deccantowers, Basheerba...","Plot 121 405, Hyderabad., Andhra Pradesh, TG"
138,S1-469535575,S2-609541042,S2,0.633333,1.0,0.510067,India,India,Mangal Construction Associates,Mangal Associates Construction,"Gautam Buddha Nagar, Noida, Ats Dolce, Gh-12A,...","FLAT NO. - 5GF1, ATS DOLCE, GH-12A, ZETA-I, NO..."
203,S1-983193550,S3-85515857,S3,0.867925,1.0,0.507937,US,US,Rev It Up Bike Shop LLC,Rev It Up Bike Shop LLC Center,"Shively, 1718 Youngland Ave, KY","Youngland Ave, Shively, Kentucky"
127,S1-841213363,S3-202831264,S3,0.833333,1.0,0.500000,US,US,Economic Development Council,Economic Development,"Fort Worth, TX, 5222 Village Lane","5222 Village Lane, FT. Worth, Texas"
177,S1-654117873,S2-970646673,S2,1.000000,1.0,0.500000,US,US,Pediatric Group,Pediatric Group,"3100 12th Street, Bentonville, AR","003100 12ND ST, BENTONVILLE, AR"
252,S1-884904716,S2-484513717,S2,0.933333,1.0,0.492754,US,US,Chiropractic Medicine,Chiropractic Medicine LP,"2152 Rope Maker Road, Conroe, TX","2152A ROPE MAKER RD, null, CONROE, TX"
120,S1-140223936,S3-162340681,S3,0.794118,1.0,0.438356,India,India,Jain Shakti Infrastructure Pvt Ltd,Jain Pvt Infrastructure Shakti Ltd,"C-403, Silver Birch, Vasant Gardenm, Mumbai, M...","C-403, Mumbai, MH"
327,S1-804892516,S3-5729759,S3,0.740741,1.0,0.421053,India,India,Consultants Udbhav Training,Consultants Training Udbhav,"2-B-14, Moxa, Sector Xi Shantinagar Co-Op. Hsg...","2-B-14, <NULL>, Mira Road East, MH"
180,S1-654117873,S2-686876225,S2,1.000000,1.0,0.417910,US,US,Pediatric Group,Pediatric Group,"3100 12th Street, Bentonville, AR","003100 TWELFTH ST, BENTONVILLE, AR"
136,S1-743240769,S3-969140596,S3,0.912281,1.0,0.395349,India,India,Avenue Solutions Pvt. Ltd.,M/s Avenue Solutions Pvt. Ltd.,"167, Ist Floor, Above As, Property, Pratap Nag...","166, East Delhi, DL"
156,S1-479314025,S2-479592902,S2,0.714286,1.0,0.361905,India,India,Hbm Polymers Private Limited,Private Hbm Polymers Limited,"302, Regency Palace Appt., 45-46, Shakti Nagar...","INDORE, 302, Madhya Pradesh, INDORE"
86,S1-130248916,S3-223440260,S3,0.941176,1.0,0.361702,India,India,Sharda Education Private Limited,M/s Sharda Education Private Limited,"Flat No. 1A, Mayur Milan Apt, G P Road, Nashik...","महाराष्ट्र, Door No 1A, N/A, Nashik"
344,S1-492709395,S3-134008039,S3,0.866667,1.0,0.346939,India,India,Window Clinic,Sri Window Clinic,"Bhopal, Madhya Pradesh, Alchem, Balaji Tower, ...","Alchem, Mumbai, Bhopal, MP"
261,S1-95730121,S3-481016814,S3,0.724138,1.0,0.341880,India,India,Sree Builders Private Limited,Private Sree Builders Limited,"No.1106/9, A. M. Industrial Estate, Garebhavi ...","#1106/9, Bangalore, KA"
113,S1-87161815,S2-489844343,S2,0.615385,1.0,0.333333,US,US,Salazar Patriot Hawaii Inc,Salazar Inc Hawaii Patriot,"723 2nd Street, Hopkins, MN","618 2ND STREET, PO BOX 3415, HOKINS, MN"
78,S1-488641100,S3-406598993,S3,0.724138,1.0,0.314815,India,India,Easylife & Associates,M/s Easylife & Associates Corporation,"Delhi, Ansal Vikas Deep, Laxmi Nagar Distict C...","H.no 506 801, New Delhi, Shahdara, दिल्ली"
150,S1-981078855,S3-669026485,S3,0.685714,1.0,0.306569,India,India,Csk Advisors,Mr Csk Advisors Limited,"Maharashtra, Om Shrddha Co Op Hsg Society Ltd....","#6, Mumbai City, Mumbai, MH"
36,S1-842551982,S2-521081010,S2,0.666667,1.0,0.305556,US,US,Nowak Ventures L.L.C.,L.L.C. Nowak Ventures,"NC, Charlotte, 11511 Ridge Oak Drive","11511 RIDGE OAK DRIVE, NC, CHARLOTTE"
124,S1-291812801,S2-56990795,S2,0.790698,1.0,0.262295,India,India,Skytouch & Partners,Shri Skytouch Partners &,"Ghaziabad, Uttar Pradesh, 328/S-3, Ghaziabad, ...","328/S-3, SMG-I SHALIMAR GARDEN, GHAZIABAD, उत्..."
200,S1-339174188,S2-663473454,S2,0.482759,1.0,0.258065,India,India,South Tukoganj Laundry Limited,Laundry South South Tukoganj,"112, The Horizon 11/5, South Tukoganj, Indore,...","112, SOUTH TUKOGANJ, मध्य प्रदेश"

In [105]:
# ============================================================
# STEP 32 — INSPECT ACTUAL BLOCKING IMPLEMENTATION
# ============================================================

print("=" * 70)
print("STEP 32 — ACTUAL BLOCKING.PY INSPECTION")
print("=" * 70)

import os
import ast

BLOCKING_FILE = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-v3/modules/blocking.py"
)

print("\nFile exists:", os.path.isfile(BLOCKING_FILE))
print("Path:", BLOCKING_FILE)

with open(BLOCKING_FILE, "r", encoding="utf-8") as f:
    blocking_source = f.read()

print("\nFile size:", len(blocking_source), "characters")

# ------------------------------------------------------------
# Parse function/class names WITHOUT importing anything
# ------------------------------------------------------------

tree = ast.parse(blocking_source)

functions = []
classes = []

for node in tree.body:

    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        functions.append(node.name)

    elif isinstance(node, ast.ClassDef):
        classes.append(node.name)

print("\nTOP-LEVEL FUNCTIONS")
print("-" * 70)

for name in functions:
    print(name)

print("\nTOP-LEVEL CLASSES")
print("-" * 70)

for name in classes:
    print(name)

# ------------------------------------------------------------
# Print relevant source
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FULL blocking.py")
print("=" * 70)

print(blocking_source)

======================================================================
STEP 32 — ACTUAL BLOCKING.PY INSPECTION
======================================================================

File exists: True
Path: /kaggle/input/datasets/tejasweerajput/amazon-v3/modules/blocking.py

File size: 10465 characters

TOP-LEVEL FUNCTIONS
----------------------------------------------------------------------
make_unicode_name_keys
make_name_keys
make_address_keys
make_at2_keys
make_a4_keys
make_all_keys

TOP-LEVEL CLASSES
----------------------------------------------------------------------

======================================================================
FULL blocking.py
======================================================================
"""
blocking.py
============================================================
Blocking-key generation for Business Entity Resolution.

This module is SOURCE-INDEPENDENT: the same functions are used
for Source 1, Source 2 and Source 3, and for both the 10K
development data and the full 5M+ record production data.

Nothing in this file is hard-coded to any dataset size. Frequency
thresholds are NOT computed here -- they are computed by indexer.py
against whatever data was actually indexed (10K or full), which is
what makes this pipeline safe to move from lab -> production.

Key types produced:

  Name keys   : NP6, NP8, NS6, FL, FL3, F2, FML
  Address keys: AN, A2, AW2, AL2, NL
  A4 keys     : A4W (numeric address component + nearby address word,
                windowed so cost is O(n) in the number of address
                tokens, not O(n^2))
"""

import re

from normalize import normalize_business_name, normalize_address



# ============================================================
# UNICODE NAME BLOCKING
# ============================================================

def make_unicode_name_keys(name):
    """
    Unicode-preserving name keys.

    Keeps Hindi, Kannada, Gujarati, etc. instead of deleting
    non-ASCII characters.
    """
    if not name:
        return []

    import unicodedata

    n = unicodedata.normalize("NFKC", str(name)).casefold()
    n = " ".join(n.split())

    if not n:
        return []

    keys = []

    compact = "".join(ch for ch in n if not ch.isspace())

    if len(compact) >= 4:
        keys.append(("UNP4", compact[:4]))

    if len(compact) >= 6:
        keys.append(("UNP6", compact[:6]))

    words = n.split()

    if len(words) >= 2:
        first = words[0]
        last = words[-1]

        if len(first) >= 2 and len(last) >= 2:
            keys.append(("UFL", first[:3] + "|" + last[:3]))

    return keys


# ============================================================
# NAME BLOCKING
# ============================================================

def make_name_keys(name):
    """
    Generate selective name-blocking keys.

    We avoid generic single-word keys because they create
    enormous candidate buckets. Logic preserved from the
    original candidate_generator.py (already measured at
    ~92% S2 recall on the 1,000-row dev sample).
    """

    n = normalize_business_name(name)

    if not n:
        return []

    keys = []
    compact = n.replace(" ", "")

    if len(compact) >= 6:
        keys.append(("NP6", compact[:6]))

    if len(compact) >= 8:
        keys.append(("NP8", compact[:8]))

    if len(compact) >= 6:
        keys.append(("NS6", compact[-6:]))

    words = n.split()

    if len(words) >= 2:
        first, last = words[0], words[-1]

        if len(first) >= 3 and len(last) >= 3:
            keys.append(("FL", first[:4] + "|" + last[:4]))
            keys.append(("FL3", first[:3] + "|" + last[:5]))

        w1, w2 = words[0], words[1]

        if len(w1) >= 3 and len(w2) >= 3:
            keys.append(("F2", w1[:5] + "|" + w2[:5]))

    if len(words) >= 3:
        first, middle, last = words[0], words[-2], words[-1]

        if len(first) >= 3 and len(last) >= 3:
            keys.append(
                ("FML", first[:3] + "|" + middle[:3] + "|" + last[:3])
            )

    return keys


# ============================================================
# ADDRESS BLOCKING (original key set)
# ============================================================

def make_address_keys(address):
    """
    Generate selective address-blocking keys.

    We deliberately do NOT use a bare number as a key -- logic
    preserved from the original candidate_generator.py.
    """

    a = normalize_address(address)

    if not a:
        return []

    keys = []
    words = a.split()

    if not words:
        return []

    numbers = [w for w in words if w.isdigit()]
    non_numeric = [w for w in words if not w.isdigit()]

    if numbers:
        number = numbers[0]

        for word in words:
            if not word.isdigit() and len(word) >= 3:
                keys.append(("AN", number + "|" + word[:6]))
                break

        if len(non_numeric) >= 2:
            keys.append(
                (
                    "A2",
                    number + "|" + non_numeric[0][:4] + "|" + non_numeric[1][:4],
                )
            )

    if len(non_numeric) >= 2:
        w1, w2 = non_numeric[0], non_numeric[1]

        if len(w1) >= 3 and len(w2) >= 3:
            keys.append(("AW2", w1[:5] + "|" + w2[:5]))

        w1, w2 = non_numeric[-2], non_numeric[-1]

        if len(w1) >= 3 and len(w2) >= 3:
            keys.append(("AL2", w1[:5] + "|" + w2[:5]))

    if numbers and non_numeric:
        number = numbers[0]
        last_word = non_numeric[-1]

        if len(last_word) >= 3:
            keys.append(("NL", number + "|" + last_word[:6]))

    return keys



# ============================================================
# AT2 BLOCKING (informative address-token pairs)
# ============================================================

# Very common address words are poor blocking signals.
# Keep this list deliberately small.
GENERIC_ADDRESS_WORDS = {
    "street", "st", "road", "rd", "avenue", "ave",
    "lane", "ln", "drive", "dr", "boulevard", "blvd",
    "highway", "hwy", "near", "opposite", "opp",
    "building", "bldg", "floor", "fl", "block",
    "district", "city", "state", "india",
    "private", "limited", "ltd", "pvt",
}

def make_at2_keys(address):
    """
    Generate a small number of informative address-token-pair keys.

    Unlike AW2/AL2, this does not depend on token position.
    It selects informative tokens and creates only adjacent pairs
    after sorting by their original position.

    The goal is to recover matches where the business name is in
    another script but the address is shared.
    """
    a = normalize_address(address)

    if not a:
        return []

    tokens = a.split()

    informative = []

    for tok in tokens:
        if tok.isdigit():
            continue

        if len(tok) < 4:
            continue

        if tok in GENERIC_ADDRESS_WORDS:
            continue

        informative.append(tok)

    if len(informative) < 2:
        return []

    # Keep at most 6 informative tokens per address.
    # Prefer longer tokens because they are generally more distinctive.
    informative = sorted(
        informative,
        key=lambda x: (-len(x), x)
    )[:6]

    keys = []
    seen = set()

    # Only 5-6 pairs, rather than O(n^2) over the whole address.
    for i in range(len(informative) - 1):
        w1 = informative[i][:8]
        w2 = informative[i + 1][:8]

        if w1 == w2:
            continue

        a1, a2 = sorted((w1, w2))
        key_value = a1 + "|" + a2

        if key_value not in seen:
            seen.add(key_value)
            keys.append(("AT2", key_value))

    return keys


# ============================================================
# A4 BLOCKING (numeric address component + NEARBY words)
# ============================================================
#
# The original A4 experiment (test_a4_overhead_fast.py) paired every
# number in the address with EVERY pair of words (O(n^2) per record).
# That is fine for a one-off 1,000-row experiment but is not safe to
# run unmodified against 5M+ records: addresses with many tokens
# would generate a large number of keys per record.
#
# This production version keeps the same idea -- "numeric address
# component + nearby normalized address words" -- but only looks at
# a small window of words around each number (WINDOW on each side),
# making key generation O(n) per record instead of O(n^2). Recall
# on the dev set should stay close to the original experiment
# because true matches almost always keep numbers and street words
# adjacent to one another.

A4_WINDOW = 3  # words examined on each side of a number


def make_a4_keys(address, window=A4_WINDOW):

    a = normalize_address(address)

    if not a:
        return []

    tokens = a.split()

    number_positions = [i for i, t in enumerate(tokens) if t.isdigit()]

    if not number_positions:
        return []

    keys = []
    seen = set()

    for pos in number_positions:

        number = tokens[pos]

        nearby = []

        for offset in range(1, window + 1):

            for idx in (pos - offset, pos + offset):

                if 0 <= idx < len(tokens):

                    tok = tokens[idx]

                    if not tok.isdigit() and len(tok) >= 2:
                        nearby.append(tok)

        # de-dup while preserving order, cap to the 3 closest words
        nearby = list(dict.fromkeys(nearby))[:3]

        for i in range(len(nearby)):
            for j in range(i + 1, len(nearby)):

                w1, w2 = sorted((nearby[i][:6], nearby[j][:6]))
                key_value = number + "|" + w1 + "|" + w2

                if key_value not in seen:
                    seen.add(key_value)
                    keys.append(("A4W", key_value))

    return keys


# ============================================================
# COMBINED
# ============================================================

def make_all_keys(name, address):
    """
    Convenience helper returning every (key_type, key_value) pair
    for a record's name + address, used by indexer.py.
    """

    return make_name_keys(name) + make_unicode_name_keys(name) + make_address_keys(address) + make_a4_keys(address)


NAME_KEY_TYPES = {"NP6", "NP8", "NS6", "FL", "FL3", "F2", "FML", "UNP4", "UNP6", "UFL"}
ADDRESS_KEY_TYPES = {"AN", "A2", "AW2", "AL2", "NL", "A4W", "AT2"}
ALL_KEY_TYPES = NAME_KEY_TYPES | ADDRESS_KEY_TYPES


# Default per-key-type maximum bucket size ("frequency cap").
# If a specific key's bucket (for the dataset actually indexed --
# 10K dev OR full production) grows past this size, that key is
# treated as too broad and skipped for that record. This is what
# keeps AL2 / NS6 usable without deleting them outright, and is
# recomputed fresh every time build_index() runs, so it is always
# evaluated against the CURRENT index, never against stale 10K
# statistics.
DEFAULT_FREQ_CAPS = {
    "NP6": 300,
    "NP8": 300,
    "NS6": 300,
    "FL": 400,
    "FL3": 400,
    "F2": 400,
    "FML": 400,
    "AN": 400,
    "A2": 400,
    "AW2": 400,
    "AL2": 160,
    "NL": 400,
    "A4W": 20,
    "AT2": 40,
    "UNP4": 300,
    "UNP6": 300,
    "UFL": 300,
}

In [106]:
# ============================================================
# STEP 33 — FAST ORDER-INVARIANT NAME BLOCKING TEST
# ============================================================

print("=" * 70)
print("STEP 33 — ORDER-INVARIANT NAME KEY RECOVERY TEST")
print("=" * 70)

import unicodedata
import re

def make_order_invariant_name_key(name):
    """
    Unicode-preserving, token-order-independent name key.

    Important:
    - Does NOT translate languages.
    - Preserves Unicode.
    - Removes punctuation through token extraction.
    - Sorts tokens so token order does not matter.
    - Requires at least 2 useful tokens.
    """

    if not name:
        return None

    n = unicodedata.normalize("NFKC", str(name)).casefold()

    # Keep Unicode word characters.
    tokens = re.findall(r"\w+", n, flags=re.UNICODE)

    # Remove extremely short/noisy tokens.
    tokens = [
        t for t in tokens
        if len(t) >= 2
    ]

    if len(tokens) < 2:
        return None

    # Sort => order invariant
    tokens = sorted(set(tokens))

    # Keep enough information without creating huge keys.
    return "|".join(tokens)


# ------------------------------------------------------------
# 1. Build lookup of ALL 351 GT missing names
# ------------------------------------------------------------

missing_name_tests = []

for _, r in missing_df.iterrows():

    s1_key = make_order_invariant_name_key(r["s1_name"])
    gt_key = make_order_invariant_name_key(r["gt_name"])

    missing_name_tests.append({
        "s1_id": r["s1_id"],
        "gt_id": r["gt_id"],
        "s1_name": r["s1_name"],
        "gt_name": r["gt_name"],
        "s1_order_key": s1_key,
        "gt_order_key": gt_key,
        "exact_order_key_match": (
            s1_key is not None
            and gt_key is not None
            and s1_key == gt_key
        ),
    })

order_test_df = pd.DataFrame(missing_name_tests)

# ------------------------------------------------------------
# 2. Results
# ------------------------------------------------------------

exact_recoveries = int(
    order_test_df["exact_order_key_match"].sum()
)

total_missing = len(order_test_df)

print(f"\nMissing GT pairs tested : {total_missing:,}")
print(f"Recovered by new key    : {exact_recoveries:,}")

if total_missing:
    print(
        f"Recovery rate           : "
        f"{exact_recoveries / total_missing:.6%}"
    )

# ------------------------------------------------------------
# 3. Show recovered examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RECOVERABLE EXAMPLES")
print("=" * 70)

display(
    order_test_df[
        order_test_df["exact_order_key_match"]
    ][
        [
            "s1_id",
            "gt_id",
            "s1_name",
            "gt_name",
            "s1_order_key",
        ]
    ].head(30)
)

# ------------------------------------------------------------
# 4. Show multilingual / non-Latin cases
# ------------------------------------------------------------

def contains_non_latin(text):
    if not text:
        return False

    return any(
        ord(ch) > 127
        for ch in str(text)
    )

order_test_df["non_latin"] = (
    order_test_df["s1_name"].apply(contains_non_latin) |
    order_test_df["gt_name"].apply(contains_non_latin)
)

print("\n" + "=" * 70)
print("MULTILINGUAL / NON-LATIN MISSES")
print("=" * 70)

multi_df = order_test_df[
    order_test_df["non_latin"]
]

print(f"Non-Latin missing pairs: {len(multi_df):,}")
print(
    f"Recovered by this key  : "
    f"{multi_df['exact_order_key_match'].sum():,}"
)

display(
    multi_df[
        [
            "s1_id",
            "gt_id",
            "s1_name",
            "gt_name",
            "exact_order_key_match",
        ]
    ].head(30)
)

print("\n" + "=" * 70)
print("STEP 33 COMPLETE")
print("=" * 70)

======================================================================
STEP 33 — ORDER-INVARIANT NAME KEY RECOVERY TEST
======================================================================

Missing GT pairs tested : 351
Recovered by new key    : 42
Recovery rate           : 11.965812%

======================================================================
RECOVERABLE EXAMPLES
======================================================================

,s1_id,gt_id,s1_name,gt_name,s1_order_key
0,S1-301369134,S3-304200480,"Sapphire, Inc","Sapphire,-Inc.",inc|sapphire
8,S1-407695807,S2-168906583,A+ Companies Group,A+ Group Companies,companies|group
14,S1-340753288,S3-16288150,Chennai Design Ltd,ltd chennai design,chennai|design|ltd
20,S1-969611446,S3-249629497,TMY Healthcare Ahmedabad,Ahmedabad Healthcare Tmy,ahmedabad|healthcare|tmy
36,S1-842551982,S2-521081010,Nowak Ventures L.L.C.,L.L.C. Nowak Ventures,nowak|ventures
42,S1-854218309,S3-50839267,Dermatology Health LLC,Dermatology Health [LLC],dermatology|health|llc
44,S1-24929964,S3-52017215,Kokomo Cancer Ridge Center Inc.,Inc Kokomo Cancer Ridge Center,cancer|center|inc|kokomo|ridge
50,S1-209491128,S3-817621735,Goldy Rosales Nexpoint LLC,"Rosales, Goldy Nexpoint LLC",goldy|llc|nexpoint|rosales
57,S1-688640659,S3-982915915,Strategic Blue Series,Strategic Series Blue,blue|series|strategic
77,S1-741535013,S3-618079518,Palmer Select Associates,Palmer Associates Select,associates|palmer|select
86,S1-130248916,S3-223440260,Sharda Education Private Limited,M/s Sharda Education Private Limited,education|limited|private|sharda
110,S1-658192036,S3-346148845,Cardiology Medicine P.C.,Cardiology-Medicine,cardiology|medicine
113,S1-87161815,S2-489844343,Salazar Patriot Hawaii Inc,Salazar Inc Hawaii Patriot,hawaii|inc|patriot|salazar
115,S1-88729605,S3-445105822,Rebekkah Byers Water,"Byers, Rebekkah Water",byers|rebekkah|water
120,S1-140223936,S3-162340681,Jain Shakti Infrastructure Pvt Ltd,Jain Pvt Infrastructure Shakti Ltd,infrastructure|jain|ltd|pvt|shakti
136,S1-743240769,S3-969140596,Avenue Solutions Pvt. Ltd.,M/s Avenue Solutions Pvt. Ltd.,avenue|ltd|pvt|solutions
138,S1-469535575,S2-609541042,Mangal Construction Associates,Mangal Associates Construction,associates|construction|mangal
142,S1-334424523,S3-193474336,Lynx LLC,Lynx [LLC],llc|lynx
156,S1-479314025,S2-479592902,Hbm Polymers Private Limited,Private Hbm Polymers Limited,hbm|limited|polymers|private
159,S1-698473845,S3-890945141,Harbor Blue Israel LLC,[LLC] Harbor Blue Israel,blue|harbor|israel|llc
165,S1-77762972,S2-419513046,Orthopedic Center,Orthopedic (Center),center|orthopedic
177,S1-654117873,S2-970646673,Pediatric Group,Pediatric Group,group|pediatric
178,S1-654117873,S2-120514344,Pediatric Group,PEDIATRIC GROUP,group|pediatric
180,S1-654117873,S2-686876225,Pediatric Group,Pediatric Group,group|pediatric
181,S1-654117873,S3-856717455,Pediatric Group,Pediatric [Group],group|pediatric
194,S1-804108270,S3-272130825,Darrelle Matthews Renewable Inc,"Matthews, Darrelle Renewable Inc.",darrelle|inc|matthews|renewable
217,S1-754363423,S3-12351257,Valley Veterinary Clinic,Valley Clinic Veterinary,clinic|valley|veterinary
258,S1-965462149,S3-74546218,Ailyn Morales Keystone Defense,"Morales, Ailyn Keystone Defense",ailyn|defense|keystone|morales
261,S1-95730121,S3-481016814,Sree Builders Private Limited,Private Sree Builders Limited,builders|limited|private|sree
263,S1-688260177,S3-358408242,Williams Highland Connecticut LLC,Williams Connecticut Highland LLC,connecticut|highland|llc|williams

======================================================================
MULTILINGUAL / NON-LATIN MISSES
======================================================================
Non-Latin missing pairs: 133
Recovered by this key  : 0

,s1_id,gt_id,s1_name,gt_name,exact_order_key_match
1,S1-121577413,S3-20638002,Premier Foods Private Limited,Premier फूड्स प्राइवेट लिमिटेड,False
5,S1-328379638,S3-826694275,Great Healthcare Private Limited,Great हेल्थकेयर प्राइवेट लिमिटेड,False
6,S1-612288482,S3-357738147,Classic Trading Private Limited,கிளாசிக் டிரேடிங் பிரைவேட் லிமிடெட்,False
9,S1-156878332,S2-148871316,Good Care Private Limited,गुड केयर प्राइवेट लिमिटेड,False
10,S1-487841439,S2-313395306,Apex Infra Private Limited,एपेक्स इंफ्रा प्राइवेट लिमिटेड,False
12,S1-946771116,S3-847878051,South Premier Foundation Private Limited,సౌత్ ప్రీమియర్ ఫౌండేషన్ ప్రైవేట్ లిమిటెడ్,False
16,S1-341097791,S2-709683238,Shree Investments Private Limited,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,False
17,S1-341097791,S3-790821637,Shree Investments Private Limited,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,False
22,S1-1870741,S2-856224121,Creative Ventures Private Limited,ক্রিয়েটিভ ভেঞ্চারস প্রাইভেট লিমিটেড,False
23,S1-899335462,S3-488000874,International Exports Limited,ఇంటర్నేషనల్ ఎక్స్‌పోర్ట్స్ లిమిటెడ్,False
25,S1-254813910,S2-958799222,Vijay Solutions Private Limited,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,False
26,S1-254813910,S2-250859577,Vijay Solutions Private Limited,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,False
28,S1-570692468,S3-979892181,Fortune Systems Private Limited,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,False
29,S1-570692468,S3-869473412,Fortune Systems Private Limited,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,False
30,S1-990342798,S2-436803520,Gujarat Infotech,গুজরাট ইনফোটেক,False
34,S1-308960965,S2-475108026,Alpha Products Private Limited,ആൽഫ പ്രൊഡക്ട്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്,False
38,S1-421560528,S2-244632256,Tarai Management Pvt. Ltd.,Pvt. Tarai Mánagement Ltd.,False
39,S1-560786353,S3-5382926,Surya Healthcare Limited,सूर्य हेल्थकेयर लिमिटेड,False
40,S1-560786353,S3-97751317,Surya Healthcare Limited,सूर्या हेल्थकेयर लिमिटेड,False
46,S1-34018933,S2-73007223,Blue Marketing Private Limited,ब्लू मार्केटिंग प्राइवेट लिमिटेड,False
47,S1-426723298,S3-556262584,One Services Private Limited,वन सर्विसेज प्राइवेट लिमिटेड,False
48,S1-426723298,S3-991847287,One Services Private Limited,वन सर्विसेज प्राइवेट लिमिटेड,False
53,S1-953200585,S2-56875010,East Trading Private Limited,ईस्ट ट्रेडिंग प्राइवेट लिमिटेड,False
54,S1-715240062,S2-925257377,Dynamic Energy Private Limited,ଡାଇନାମିକ୍ ଏନର୍ଜି ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,False
55,S1-715240062,S3-992776958,Dynamic Energy Private Limited,ଡାଇନାମିକ୍ Energy ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,False
59,S1-343636643,S3-796126112,Vibrant Enterprises Private Limited,Pyrálum,False
63,S1-68472642,S2-863931323,United Sai Technology Private Limited,यूनाइटेड साई टेक्नोलॉजी प्राइवेट लिमिटेड,False
64,S1-68472642,S2-724841405,United Sai Technology Private Limited,यूनाइटेड साईं टेक्नोलॉजी प्राइवेट लिमिटेड,False
65,S1-863356031,S3-151375842,Lakshmi Estate Private Limited,Smt Lakshmi Lakshmi Étsote Private Limited,False
69,S1-303373410,S2-341528433,Om Infotech Private Limited,ओम इंफोटेक प्राइवेट लिमिटेड,False

======================================================================
STEP 33 COMPLETE
======================================================================

In [107]:
# ============================================================
# STEP 34 — MULTILINGUAL MISS: ADDRESS RECOVERY TEST
# ============================================================

print("=" * 70)
print("STEP 34 — MULTILINGUAL ADDRESS RECOVERY TEST")
print("=" * 70)

# ------------------------------------------------------------
# We already have:
#   missing_df
#   s1_lookup
#   s2_index
#   s3_index
#
# We will inspect the actual existing address keys.
# ------------------------------------------------------------

import sys

MODULE_DIR = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"

if MODULE_DIR not in sys.path:
    sys.path.insert(0, MODULE_DIR)

import blocking
from normalize import normalize_address


# ------------------------------------------------------------
# Existing blocker functions
# ------------------------------------------------------------

print("Blocking module:", blocking.__file__)

print(
    "\nAvailable address functions:",
    [
        x for x in dir(blocking)
        if "address" in x.lower() or "at2" in x.lower()
    ]
)


# ------------------------------------------------------------
# Test ONLY the 133 multilingual misses
# ------------------------------------------------------------

multi_missing = missing_df[
    missing_df["s1_name"].apply(
        lambda x: any(ord(ch) > 127 for ch in str(x))
    )
    |
    missing_df["gt_name"].apply(
        lambda x: any(ord(ch) > 127 for ch in str(x))
    )
].copy()

print(f"\nMultilingual missing pairs: {len(multi_missing):,}")


results = []

for _, r in multi_missing.iterrows():

    s1_address = r["s1_address"]
    gt_address = r["gt_address"]

    s1_keys = set()
    gt_keys = set()

    # Existing address keys
    for key_fn in [
        blocking.make_address_keys,
        blocking.make_at2_keys,
        blocking.make_a4_keys,
    ]:

        try:
            s1_keys.update(key_fn(s1_address))
            gt_keys.update(key_fn(gt_address))
        except Exception:
            pass

    shared = s1_keys.intersection(gt_keys)

    results.append({
        "s1_id": r["s1_id"],
        "gt_id": r["gt_id"],
        "s1_name": r["s1_name"],
        "gt_name": r["gt_name"],
        "shared_address_keys": len(shared),
        "shared_keys": list(shared)[:5],
        "s1_key_count": len(s1_keys),
        "gt_key_count": len(gt_keys),
    })


multi_address_df = pd.DataFrame(results)

recoverable = (
    multi_address_df["shared_address_keys"] > 0
)

print("\n" + "=" * 70)
print("RESULT")
print("=" * 70)

print(
    f"Multilingual misses tested : "
    f"{len(multi_address_df):,}"
)

print(
    f"Address-key recoverable     : "
    f"{recoverable.sum():,}"
)

print(
    f"Recovery rate               : "
    f"{recoverable.mean():.6%}"
)

print("\n" + "=" * 70)
print("RECOVERABLE MULTILINGUAL EXAMPLES")
print("=" * 70)

display(
    multi_address_df[
        recoverable
    ].head(30)
)

print("\n" + "=" * 70)
print("UNRECOVERABLE MULTILINGUAL EXAMPLES")
print("=" * 70)

display(
    multi_address_df[
        ~recoverable
    ].head(30)
)

print("\n" + "=" * 70)
print("STEP 34 COMPLETE")
print("=" * 70)

======================================================================
STEP 34 — MULTILINGUAL ADDRESS RECOVERY TEST
======================================================================
Blocking module: /kaggle/input/datasets/tejasweerajput/amazon-v3/modules/blocking.py

Available address functions: ['ADDRESS_KEY_TYPES', 'GENERIC_ADDRESS_WORDS', 'make_address_keys', 'make_at2_keys', 'normalize_address']

Multilingual missing pairs: 133

======================================================================
RESULT
======================================================================
Multilingual misses tested : 133
Address-key recoverable     : 71
Recovery rate               : 53.383459%

======================================================================
RECOVERABLE MULTILINGUAL EXAMPLES
======================================================================

,s1_id,gt_id,s1_name,gt_name,shared_address_keys,shared_keys,s1_key_count,gt_key_count
3,S1-156878332,S2-148871316,Good Care Private Limited,गुड केयर प्राइवेट लिमिटेड,5,"[(AL2, delhi|delhi), (AT2, enclave|vasant), (A...",11,12
4,S1-487841439,S2-313395306,Apex Infra Private Limited,एपेक्स इंफ्रा प्राइवेट लिमिटेड,1,"[(AT2, bihar|kumari)]",15,4
6,S1-341097791,S2-709683238,Shree Investments Private Limited,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,1,"[(A4W, 2|no|st)]",12,11
7,S1-341097791,S3-790821637,Shree Investments Private Limited,શ્રી ઇન્વેસ્ટમેન્ટ્સ પ્રાઇવેટ લિમિટેડ,1,"[(A4W, 2|no|st)]",12,6
8,S1-1870741,S2-856224121,Creative Ventures Private Limited,ক্রিয়েটিভ ভেঞ্চারস প্রাইভেট লিমিটেড,4,"[(AT2, bengal|sukumar), (AT2, domjur|howrah), ...",6,5
10,S1-254813910,S2-958799222,Vijay Solutions Private Limited,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,1,"[(AL2, tamil|nadu)]",6,4
15,S1-308960965,S2-475108026,Alpha Products Private Limited,ആൽഫ പ്രൊഡക്ട്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്,2,"[(AT2, chambers|kerala), (AT2, chambers|ernaku...",9,7
16,S1-421560528,S2-244632256,Tarai Management Pvt. Ltd.,Pvt. Tarai Mánagement Ltd.,3,"[(AL2, patna|bihar), (AT2, patna|south), (AT2,...",6,9
17,S1-560786353,S3-5382926,Surya Healthcare Limited,सूर्य हेल्थकेयर लिमिटेड,1,"[(AT2, delhi|north)]",11,10
18,S1-560786353,S3-97751317,Surya Healthcare Limited,सूर्या हेल्थकेयर लिमिटेड,3,"[(AT2, darya|delhi), (AT2, ansari|darya), (AT2...",11,15
23,S1-715240062,S2-925257377,Dynamic Energy Private Limited,ଡାଇନାମିକ୍ ଏନର୍ଜି ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,1,"[(AT2, bhubanes|khordha)]",11,8
24,S1-715240062,S3-992776958,Dynamic Energy Private Limited,ଡାଇନାମିକ୍ Energy ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍,1,"[(AT2, bhubanes|chandras)]",11,10
25,S1-343636643,S3-796126112,Vibrant Enterprises Private Limited,Pyrálum,1,"[(AT2, chennai|nagar)]",13,13
31,S1-791268226,S2-941436042,Sai Global,ସାଇ ଗ୍ଲୋବାଲ୍,2,"[(A4W, 174|no|plot), (A4W, 569|no|plot)]",19,10
32,S1-868344892,S2-341135091,Indo Services (India) Ltd,Ltd Indo Services (Índia),4,"[(AT2, jaipur|nagar), (AT2, govind|jaipur), (A...",13,12
33,S1-719428038,S2-181684681,Creative Developers Private Limited,क्रिएटिव डेवलपर्स प्राइवेट लिमिटेड,10,"[(A4W, 2|first|no), (A2, 2|h|no), (A4W, 23|fir...",14,13
35,S1-337747814,S2-843673673,Dream Investments Private Limited,ड्रीम इन्वेस्टमेंट्स प्राइवेट लिमिटेड,2,"[(AL2, delhi|delhi), (NL, 14|delhi)]",14,8
36,S1-879955092,S2-618612678,Maa Great Software Pvt Ltd,મા ગ્રેટ સોફ્ટવેર પ્રા. લિ.,9,"[(AT2, gandhina|signatur), (AL2, nagar|gujar),...",15,15
37,S1-52243626,S3-898117247,Om Solutions Private Limited,ओम सॉल्यूशंस प्राइवेट लिमिटेड,2,"[(AT2, delhi|okhla), (AT2, okhla|phase)]",9,9
38,S1-860397041,S2-382696045,Lotus International Private Limited,লোটাস ইন্টারন্যাশনাল প্রাইভেট লিমিটেড,2,"[(NL, 29|bengal), (AL2, west|benga)]",16,11
39,S1-860397041,S2-750747352,Lotus International Private Limited,লোটাস ইন্টারন্যাশনাল প্রাইভেট লিমিটেড,2,"[(NL, 29|bengal), (AL2, west|benga)]",16,11
40,S1-215670629,S2-400140171,Guru Unique Builders Private Limited,गुरु यूनिक बिल्डर्स प्राइवेट लिमिटेड,4,"[(AT2, delhi|house), (A4W, 21|house|nauran), (...",12,16
41,S1-839071518,S2-794423982,Dynamic Infrastructure Pvt Ltd,डायनामिक इंफ्रास्ट्रक्चर प्रा. लि.,1,"[(AT2, gurgaon|gurugram)]",11,6
46,S1-163567186,S2-464862552,Blue Services Private Limited,புளூ Services Private Limited,4,"[(AT2, tamil|vellore), (AT2, nadu|tamil), (AL2...",11,11
47,S1-163567186,S2-685844115,Blue Services Private Limited,புளூ சர்வீசஸ் Private Limited,4,"[(AT2, tamil|vellore), (AT2, nadu|tamil), (AL2...",11,11
49,S1-459471626,S2-982965103,Hari Marketing Private Limited,हरि मार्केटिंग प्राइवेट लिमिटेड,7,"[(AT2, buddha|gautam), (A4W, 2|floor|sector), ...",15,11
50,S1-523700320,S2-269175510,Guru Anand Services Private Limited,குரு ஆனந்த் சர்வீசஸ் பிரைவேட் லிமிடெட்,2,"[(NL, 29|nadu), (AL2, tamil|nadu)]",11,10
56,S1-440205957,S3-273552496,Perfect Technology LLP,परफेक्ट टेक्नोलॉजी एलएलपी,1,"[(AT2, bhagalpu|jagdishp)]",6,6
57,S1-203888800,S2-272405867,All Management Private Limited,ஆல் மேனேஜ்மெண்ட் பிரைவேட் லிமிடெட்,1,"[(AT2, adyar|madras)]",5,5
58,S1-205860416,S2-704814902,Green Jay Consulting Pvt Ltd,గ్రీన్ జై కన్సల్టింగ్ ప్రైవేట్ లిమిటెడ్,1,"[(AT2, hyderaba|telangan)]",11,6

======================================================================
UNRECOVERABLE MULTILINGUAL EXAMPLES
======================================================================

,s1_id,gt_id,s1_name,gt_name,shared_address_keys,shared_keys,s1_key_count,gt_key_count
0,S1-121577413,S3-20638002,Premier Foods Private Limited,Premier फूड्स प्राइवेट लिमिटेड,0,[],18,5
1,S1-328379638,S3-826694275,Great Healthcare Private Limited,Great हेल्थकेयर प्राइवेट लिमिटेड,0,[],7,3
2,S1-612288482,S3-357738147,Classic Trading Private Limited,கிளாசிக் டிரேடிங் பிரைவேட் லிமிடெட்,0,[],11,4
5,S1-946771116,S3-847878051,South Premier Foundation Private Limited,సౌత్ ప్రీమియర్ ఫౌండేషన్ ప్రైవేట్ లిమిటెడ్,0,[],19,11
9,S1-899335462,S3-488000874,International Exports Limited,ఇంటర్నేషనల్ ఎక్స్‌పోర్ట్స్ లిమిటెడ్,0,[],20,9
11,S1-254813910,S2-250859577,Vijay Solutions Private Limited,விஜய் சொல்யூஷன்ஸ் பிரைவேட் லிமிடெட்,0,[],6,3
12,S1-570692468,S3-979892181,Fortune Systems Private Limited,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0,[],11,8
13,S1-570692468,S3-869473412,Fortune Systems Private Limited,ಫಾರ್ಚೂನ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0,[],11,8
14,S1-990342798,S2-436803520,Gujarat Infotech,গুজরাট ইনফোটেক,0,[],12,3
19,S1-34018933,S2-73007223,Blue Marketing Private Limited,ब्लू मार्केटिंग प्राइवेट लिमिटेड,0,[],13,6
20,S1-426723298,S3-556262584,One Services Private Limited,वन सर्विसेज प्राइवेट लिमिटेड,0,[],12,3
21,S1-426723298,S3-991847287,One Services Private Limited,वन सर्विसेज प्राइवेट लिमिटेड,0,[],12,4
22,S1-953200585,S2-56875010,East Trading Private Limited,ईस्ट ट्रेडिंग प्राइवेट लिमिटेड,0,[],13,2
26,S1-68472642,S2-863931323,United Sai Technology Private Limited,यूनाइटेड साई टेक्नोलॉजी प्राइवेट लिमिटेड,0,[],15,11
27,S1-68472642,S2-724841405,United Sai Technology Private Limited,यूनाइटेड साईं टेक्नोलॉजी प्राइवेट लिमिटेड,0,[],15,12
28,S1-863356031,S3-151375842,Lakshmi Estate Private Limited,Smt Lakshmi Lakshmi Étsote Private Limited,0,[],16,0
29,S1-303373410,S2-341528433,Om Infotech Private Limited,ओम इंफोटेक प्राइवेट लिमिटेड,0,[],12,4
30,S1-428899490,S3-917430294,Bright International Private Limited,ಬ್ರೈಟ್ ಇಂಟರ್‌ನ್ಯಾಷನಲ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0,[],13,3
34,S1-337747814,S3-862994084,Dream Investments Private Limited,ड्रीम इन्वेस्टमेंट्स प्राइवेट लिमिटेड,0,[],14,5
42,S1-163567186,S3-990670242,Blue Services Private Limited,புளூ சர்வீசஸ் பிரைவேட் லிமிடெட்,0,[],11,4
43,S1-163567186,S3-46382528,Blue Services Private Limited,புளூ சர்வீசஸ் பிரைவேட் லிமிடெட்,0,[],11,2
44,S1-163567186,S3-124327434,Blue Services Private Limited,புளூ சர்வீசஸ் பிரைவேட் லிமிடெட்,0,[],11,4
45,S1-163567186,S2-740357090,Blue Services Private Limited,புளூ சர்வீசஸ் பிரைவேட் லிமிடெட்,0,[],11,2
48,S1-331812776,S3-802804919,United Logistics Private Limited,யுனைடெட் லாஜிஸ்டிக்ஸ் பிரைவேட் லிமிடெட்,0,[],6,2
51,S1-956523004,S2-457596427,Bombay Systems,বোম্বে Systems,0,[],14,12
52,S1-567541236,S3-648073614,Sree Foods Private Limited,श्री फूड्स प्राइवेट लिमिटेड,0,[],13,8
53,S1-140223936,S2-202794340,Jain Shakti Infrastructure Pvt Ltd,जैन शक्ति इंफ्रास्ट्रक्चर प्रा. लि.,0,[],12,3
54,S1-682824625,S2-654391950,Southern Lotus Projects Private Limited,சதர்ன் லோட்டஸ் புராஜெக்ட்ஸ் பிரைவேட் லிமிடெட்,0,[],5,2
55,S1-682824625,S3-785849535,Southern Lotus Projects Private Limited,சதர்ன் லோட்டஸ் புராஜெக்ட்ஸ் பிரைவேட் லிமிடெட்,0,[],5,3
65,S1-324545942,S3-248112465,Bright Hari Business Private Limited,ബ്രൈറ്റ് ഹരി ബിസിനസ് പ്രൈവറ്റ് ലിമിറ്റഡ്,0,[],14,8

======================================================================
STEP 34 COMPLETE
======================================================================

In [108]:
# ============================================================
# STEP 35 — ENHANCED CANDIDATE GENERATION
# Uses:
#   1. Existing blocking keys
#   2. AT2 address-token-pair keys
#   3. A4W address-number/window keys
#   4. Order-invariant name token key
# ============================================================

import sys
import os
import pandas as pd

MODULE_DIR = "/kaggle/input/datasets/tejasweerajput/amazon-v3/modules"
if MODULE_DIR not in sys.path:
    sys.path.insert(0, MODULE_DIR)

import blocking
from candidates import generate_candidate_pairs_for_row

# ------------------------------------------------------------
# Extra keys ONLY for candidate retrieval.
# We are NOT modifying the SQLite indexes.
# ------------------------------------------------------------

def enhanced_keys(row):
    name = str(row["business_name"])
    address = str(row["business_address"])

    keys = set(blocking.make_all_keys(name, address))

    # Proven multilingual/address recovery
    keys.update(blocking.make_at2_keys(address))
    keys.update(blocking.make_a4_keys(address))

    # Order-invariant normalized name key
    try:
        norm = blocking.normalize_business_name(name)
        toks = [x for x in norm.split() if x]
        if len(toks) >= 2:
            ordered = "|".join(sorted(set(toks)))
            keys.add(("NORD", ordered))
    except Exception:
        pass

    return keys


print("STEP 35 READY")
print("Existing S2 keys :", s2_index.num_keys)
print("Existing S3 keys :", s3_index.num_keys)
print("No index rebuild.")

STEP 35 READY
Existing S2 keys : <bound method SqliteIndex.num_keys of <indexer.SqliteIndex object at 0x78093dd1f7a0>>
Existing S3 keys : <bound method SqliteIndex.num_keys of <indexer.SqliteIndex object at 0x78093dd1ee40>>
No index rebuild.

In [109]:
# ============================================================
# STEP 35B — CHECK WHICH EXTRA KEY TYPES ARE ACTUALLY INDEXED
# ============================================================

sample_row = train_s1[0]

base_keys = set(
    blocking.make_all_keys(
        sample_row["business_name"],
        sample_row["business_address"]
    )
)

extra_at2 = set(blocking.make_at2_keys(sample_row["business_address"]))
extra_a4  = set(blocking.make_a4_keys(sample_row["business_address"]))

print("Base keys :", len(base_keys))
print("AT2 keys  :", len(extra_at2))
print("A4W keys :", len(extra_a4))

print("\nBase key types:", sorted(set(k[0] for k in base_keys)))
print("AT2 key types:", sorted(set(k[0] for k in extra_at2)))
print("A4W key types:", sorted(set(k[0] for k in extra_a4)))

# Test actual index retrieval
for key in list(extra_at2)[:3]:
    kt, val = key
    try:
        s2_hits = s2_index.bucket(kt, val, limit=41)
        s3_hits = s3_index.bucket(kt, val, limit=41)
        print(
            f"{key} -> "
            f"S2={len(s2_hits)} S3={len(s3_hits)}"
        )
    except Exception as e:
        print("ERROR:", key, repr(e))

Base keys : 14
AT2 keys  : 2
A4W keys : 3

Base key types: ['A2', 'A4W', 'AN', 'FL', 'FL3', 'FML', 'NP6', 'NP8', 'NS6', 'UFL', 'UNP4', 'UNP6']
AT2 key types: ['AT2']
A4W key types: ['A4W']
('AT2', 'point|westches') -> S2=0 S3=0
('AT2', 'high|point') -> S2=0 S3=0

In [110]:
# ============================================================
# STEP 35C — VERIFY AT2 / A4W INDEX COVERAGE
# ============================================================

for name, idx in [("S2", s2_index), ("S3", s3_index)]:
    print(f"\n{name}")

    for key_type in ["AT2", "A4W", "A2", "AN", "NP6", "UNP4"]:
        try:
            result = idx.bucket(key_type, "__NONEXISTENT_TEST_KEY__", limit=1)
            print(f"{key_type:5s} -> bucket() works, hits={len(result)}")
        except Exception as e:
            print(f"{key_type:5s} -> ERROR: {type(e).__name__}: {e}")

    try:
        print("num_keys:", idx.num_keys())
    except Exception as e:
        print("num_keys error:", e)

S2
AT2   -> bucket() works, hits=0
A4W   -> bucket() works, hits=0
A2    -> bucket() works, hits=0
AN    -> bucket() works, hits=0
NP6   -> bucket() works, hits=0
UNP4  -> bucket() works, hits=0
num_keys: 26696614

S3
AT2   -> bucket() works, hits=0
A4W   -> bucket() works, hits=0
A2    -> bucket() works, hits=0
AN    -> bucket() works, hits=0
NP6   -> bucket() works, hits=0
UNP4  -> bucket() works, hits=0
num_keys: 28341068

In [111]:
# ============================================================
# STEP 36 — PER-S1 THRESHOLD / TOP-K OPTIMIZATION
# ============================================================

import numpy as np
import pandas as pd

df = val_feature_df.copy()
df["score"] = score

# Correct validation GT
val_s1_ids = set(str(x) for x in all_val_s1_ids)

gt_val = {
    str(k): set(str(x) for x in v)
    for k, v in ground_truth.items()
    if str(k) in val_s1_ids
}

# Candidate IDs
cand_col = "candidate_entity_id"
s1_col = "source1_entity_id"

# Group once
groups = {
    str(s1): g.sort_values("score", ascending=False)
    for s1, g in df.groupby(s1_col, sort=False)
}

def f05(p, r):
    if p == 0 and r == 0:
        return 0.0
    return (1.25 * p * r) / (0.25 * p + r)

# ------------------------------------------------------------
# Evaluate top-K rules
# ------------------------------------------------------------

results = []

for k in [1, 2, 3, 4, 5, 6, 8, 10, 15, 20]:
    row_scores = []

    for s1, g in groups.items():
        truth = gt_val.get(s1, set())
        if not truth:
            continue

        pred = set(g.head(k)[cand_col].astype(str))

        if len(truth) == 0 and len(pred) == 0:
            row_scores.append(1.0)
            continue

        tp = len(pred & truth)
        precision = tp / len(pred) if pred else 0.0
        recall = tp / len(truth) if truth else 0.0

        row_scores.append(f05(precision, recall))

    results.append({
        "rule": f"top_{k}",
        "macro_f05": np.mean(row_scores),
    })

# ------------------------------------------------------------
# Threshold rules
# ------------------------------------------------------------

for t in np.arange(0.50, 0.991, 0.01):
    row_scores = []

    for s1, g in groups.items():
        truth = gt_val.get(s1, set())

        pred = set(
            g.loc[g["score"] >= t, cand_col].astype(str)
        )

        # singleton correctness
        if not truth:
            row_scores.append(1.0 if not pred else 0.0)
            continue

        tp = len(pred & truth)
        precision = tp / len(pred) if pred else 0.0
        recall = tp / len(truth)

        row_scores.append(f05(precision, recall))

    results.append({
        "rule": f"threshold_{t:.2f}",
        "macro_f05": np.mean(row_scores),
    })

result_df = pd.DataFrame(results).sort_values(
    "macro_f05",
    ascending=False
)

print("=" * 70)
print("STEP 36 RESULTS")
print("=" * 70)

display(result_df.head(20))

======================================================================
STEP 36 RESULTS
======================================================================

              rule  macro_f05
2            top_3   0.110109
3            top_4   0.105695
1            top_2   0.105542
4            top_5   0.099195
5            top_6   0.092784
6            top_8   0.085052
0            top_1   0.078680
7           top_10   0.078093
8           top_15   0.066051
9           top_20   0.058371
10  threshold_0.50   0.050000
11  threshold_0.51   0.050000
12  threshold_0.52   0.050000
13  threshold_0.53   0.050000
14  threshold_0.54   0.050000
15  threshold_0.55   0.050000
16  threshold_0.56   0.050000
17  threshold_0.57   0.050000
18  threshold_0.58   0.050000
19  threshold_0.59   0.050000

In [112]:
# ============================================================
# STEP 37 — SHOW ACTUAL CANDIDATE GENERATOR
# ============================================================

import inspect
import candidates

print(inspect.getsource(candidates.generate_candidate_pairs_for_row))

def generate_candidate_pairs_for_row(s1_row, indexes_by_source, freq_caps=None):

    s1_id = s1_row.get("entity_id", "")
    rows = []

    for source, index in indexes_by_source.items():

        candidates = find_candidates(s1_row, index, freq_caps=freq_caps)

        for suffix, info in candidates.items():

            candidate_id = f"{source}-{suffix}"

            rows.append(
                {
                    "source1_entity_id": s1_id,
                    "candidate_entity_id": candidate_id,
                    "source": source,
                    "blocking_key_types": "|".join(sorted(info["key_types"])),
                    "blocking_num_keys": len(info["key_types"]),
                    "blocking_min_freq": info["min_freq"],
                }
            )

    return rows

In [113]:
import inspect
from candidates import find_candidates

print(inspect.getsource(find_candidates))

def find_candidates(s1_row, index, freq_caps=None):

    freq_caps = freq_caps or DEFAULT_FREQ_CAPS

    country = s1_row.get("country", "").strip()
    name = s1_row.get("business_name", "")
    address = s1_row.get("business_address", "")

    all_keys = (
        make_name_keys(name)
        + make_unicode_name_keys(name)
        + make_address_keys(address)
        + make_a4_keys(address)
        + make_at2_keys(address)
    )

    candidates = {}

    for key_type, key_value in all_keys:

        cap = freq_caps.get(key_type, DEFAULT_FREQ_CAPS.get(key_type, 500))

        composed = compose_key(country, key_value)

        # Ask for at most cap + 1 rows. If we get back cap + 1, the
        # true bucket is > cap somewhere at or beyond that row, so
        # it's still correctly treated as "too broad" below -- we
        # just never had to materialize the rest of it.
        bucket = index.bucket(key_type, composed, limit=cap + 1)
        bucket_size = len(bucket)

        if bucket_size == 0:
            continue

        if bucket_size > cap:
            continue

        for suffix in bucket:

            entry = candidates.get(suffix)

            if entry is None:
                candidates[suffix] = {
                    "key_types": {key_type},
                    "min_freq": bucket_size,
                }
            else:
                entry["key_types"].add(key_type)
                entry["min_freq"] = min(entry["min_freq"], bucket_size)

    return candidates

In [114]:
# ============================================================
# STEP 38 — REPRODUCE VERIFIED BASELINE
# ============================================================

import numpy as np
import pandas as pd

df = val_feature_df.copy()
df["model_score"] = np.asarray(score)

# ------------------------------------------------------------
# Correct validation GT
# ------------------------------------------------------------

val_s1_ids = set(str(x) for x in all_val_s1_ids)

gt_val = {
    str(s1_id): set(map(str, gt_ids))
    for s1_id, gt_ids in ground_truth.items()
    if str(s1_id) in val_s1_ids
}

# ------------------------------------------------------------
# EXACT previous evaluation logic
# ------------------------------------------------------------

def evaluate_threshold(df, threshold):

    macro_scores = []
    total_tp = 0
    total_pred = 0
    total_gt = 0
    rows_predicted = 0

    for s1_id, g in df.groupby("source1_entity_id", sort=False):

        s1_id = str(s1_id)
        truth = gt_val.get(s1_id, set())

        pred = set(
            g.loc[
                g["model_score"] >= threshold,
                "candidate_entity_id"
            ].astype(str)
        )

        # singleton
        if len(truth) == 0:
            macro_scores.append(1.0 if len(pred) == 0 else 0.0)
            continue

        if len(pred) > 0:
            rows_predicted += 1

        tp = len(pred & truth)

        precision = tp / len(pred) if pred else 0.0
        recall = tp / len(truth)

        f05 = (
            (1.25 * precision * recall) /
            (0.25 * precision + recall)
            if (precision > 0 or recall > 0)
            else 0.0
        )

        macro_scores.append(f05)

        total_tp += tp
        total_pred += len(pred)
        total_gt += len(truth)

    return {
        "threshold": threshold,
        "macro_f05": np.mean(macro_scores),
        "precision": total_tp / total_pred if total_pred else 0,
        "recall": total_tp / total_gt if total_gt else 0,
        "predicted_pairs": total_pred,
        "tp": total_tp,
        "rows_predicted": rows_predicted,
    }


baseline_check = evaluate_threshold(df, 0.944)

print("=" * 70)
print("STEP 38 — VERIFIED BASELINE CHECK")
print("=" * 70)

for k, v in baseline_check.items():
    print(f"{k:20s}: {v}")

======================================================================
STEP 38 — VERIFIED BASELINE CHECK
======================================================================
threshold           : 0.944
macro_f05           : 0.05
precision           : 0
recall              : 0.0
predicted_pairs     : 0
tp                  : 0
rows_predicted      : 0

In [117]:
# ============================================================
# STEP 39B — SAFE SCORE VARIABLE CHECK
# ============================================================

import numpy as np

for name in ["score", "score_expanded", "score_expanded_72"]:
    if name not in globals():
        print(f"{name:20s} NOT DEFINED")
        continue

    obj = globals()[name]

    print(f"\n{name}")
    print("  type :", type(obj))
    print("  shape:", getattr(obj, "shape", None))

    try:
        arr = np.asarray(obj)

        if arr.ndim == 0:
            print("  scalar/object ->", repr(obj))
        else:
            print("  len    :", arr.size)
            print("  min    :", float(np.min(arr)))
            print("  max    :", float(np.max(arr)))
            print("  median :", float(np.median(arr)))

    except Exception as e:
        print("  inspection error:", repr(e))

score
  type : <class 'float'>
  shape: None
  scalar/object -> 0.0
score_expanded       NOT DEFINED
score_expanded_72    NOT DEFINED

In [118]:
# ============================================================
# STEP 40 — RECOVER BASELINE SCORES FROM ORIGINAL MODEL
# ============================================================

import numpy as np

print("model exists :", "model" in globals())
print("val_feature_df exists :", "val_feature_df" in globals())

print("val_feature_df shape :", val_feature_df.shape)

# Original model used these 26 columns:
# 25 feature columns + blocking_num_keys + blocking_min_freq

feature_cols = [
    c for c in val_feature_df.columns
    if c not in [
        "source1_entity_id",
        "candidate_entity_id",
        "source",
        "label",
        "blocking_key_types"
    ]
]

print("Feature columns:", len(feature_cols))

X_val_recovered = val_feature_df[feature_cols]

print("X shape:", X_val_recovered.shape)

# Recover predictions from the ORIGINAL baseline model
score_recovered = model.predict(
    X_val_recovered,
    num_iteration=getattr(model, "best_iteration_", None)
)

score_recovered = np.asarray(score_recovered)

print("\nRecovered scores")
print("length :", len(score_recovered))
print("min    :", float(score_recovered.min()))
print("max    :", float(score_recovered.max()))
print("median :", float(np.median(score_recovered)))

model exists : True
val_feature_df exists : True
val_feature_df shape : (842159, 32)
Feature columns: 29
X shape: (842159, 29)

[LightGBM] [Fatal] The number of features in data (29) is not the same as it was in training data (26).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.

LightGBMError: The number of features in data (29) is not the same as it was in training data (26).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.

In [119]:
# ============================================================
# STEP 40B — GET EXACT TRAINING FEATURES
# ============================================================

print("MODEL FEATURE COUNT:", model.n_features_in_)

try:
    print("\nMODEL FEATURE NAMES:")
    for i, c in enumerate(model.feature_name_):
        print(i, c)
except Exception as e:
    print("feature_name_ unavailable:", repr(e))

print("\nVAL FEATURE COLUMNS:")
for i, c in enumerate(val_feature_df.columns):
    print(i, c)

MODEL FEATURE COUNT: 26

MODEL FEATURE NAMES:
0 name_exact_match
1 name_char_similarity
2 name_levenshtein_similarity
3 name_token_jaccard
4 name_token_overlap
5 name_compact_similarity
6 name_prefix_similarity
7 name_suffix_similarity
8 name_char_ngram_jaccard
9 address_exact_match
10 address_char_similarity
11 address_levenshtein_similarity
12 address_token_jaccard
13 address_token_overlap
14 address_number_match
15 address_char_ngram_jaccard
16 country_match
17 name_missing
18 address_missing
19 combined_name_address_score
20 name_is_non_latin
21 address_is_non_latin
22 name_char_similarity_unicode
23 name_token_jaccard_unicode
24 blocking_num_keys
25 blocking_min_freq

VAL FEATURE COLUMNS:
0 name_exact_match
1 name_char_similarity
2 name_levenshtein_similarity
3 name_token_jaccard
4 name_token_overlap
5 name_compact_similarity
6 name_prefix_similarity
7 name_suffix_similarity
8 name_char_ngram_jaccard
9 address_exact_match
10 address_char_similarity
11 address_levenshtein_similarity
12 address_token_jaccard
13 address_token_overlap
14 address_number_match
15 address_char_ngram_jaccard
16 country_match
17 name_missing
18 address_missing
19 combined_name_address_score
20 name_is_non_latin
21 address_is_non_latin
22 name_char_similarity_unicode
23 name_token_jaccard_unicode
24 blocking_num_keys
25 blocking_min_freq
26 source1_entity_id
27 candidate_entity_id
28 source
29 score
30 score_expanded
31 score_expanded_72

In [120]:
# ============================================================
# STEP 40C — RECOVER ORIGINAL BASELINE MODEL SCORES
# ============================================================

model_features = list(model.feature_name_)

X_val_recovered = val_feature_df[model_features]

print("X shape:", X_val_recovered.shape)
print("Expected:", (len(val_feature_df), 26))

score_recovered = model.predict(
    X_val_recovered,
    num_iteration=model.best_iteration_
)

score_recovered = np.asarray(score_recovered)

print("\nRECOVERED SCORE DISTRIBUTION")
print("length :", len(score_recovered))
print("min    :", float(score_recovered.min()))
print("max    :", float(score_recovered.max()))
print("median :", float(np.median(score_recovered)))

X shape: (842159, 26)
Expected: (842159, 26)

RECOVERED SCORE DISTRIBUTION
length : 842159
min    : 0.0
max    : 1.0
median : 0.0

In [122]:
# ============================================================
# STEP 40D — RESTORE SCORE COLUMN
# ============================================================

val_eval = val_feature_df[
    [
        "source1_entity_id",
        "candidate_entity_id",
    ]
].copy()

val_eval["model_score"] = score_recovered

print(val_eval.shape)
print(val_eval["model_score"].describe())

(842159, 3)
count    842159.000000
mean          0.012109
std           0.109374
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: model_score, dtype: float64

In [123]:
print("model.best_iteration_ =", model.best_iteration_)
print("model.n_estimators_   =", getattr(model, "n_estimators_", None))
print("model objective       =", model.get_params().get("objective"))
print("model learning_rate   =", model.get_params().get("learning_rate"))
print("model num_leaves       =", model.get_params().get("num_leaves"))

model.best_iteration_ = 72
model.n_estimators_   = 72
model objective       = binary
model learning_rate   = 0.035
model num_leaves       = 63

In [124]:
# ============================================================
# STEP 41 — RECOVER ORIGINAL CONTINUOUS PROBABILITIES
# ============================================================

import numpy as np

model_features = list(model.feature_name_)
X_val_recovered = val_feature_df[model_features]

booster = model.booster_

print("Booster:", type(booster))
print("Trees :", booster.num_trees())
print("Features:", booster.num_feature())

# Direct Booster prediction = probability for binary objective
score_recovered = booster.predict(
    X_val_recovered,
    num_iteration=72
)

score_recovered = np.asarray(score_recovered)

print("\nRECOVERED PROBABILITY DISTRIBUTION")
print("length :", len(score_recovered))
print("min    :", float(score_recovered.min()))
print("max    :", float(score_recovered.max()))
print("median :", float(np.median(score_recovered)))
print("mean   :", float(score_recovered.mean()))

print("\nPercentiles:")
for p in [50, 90, 95, 99, 99.5, 99.9, 99.99]:
    print(f"{p:6.2f}% :", float(np.percentile(score_recovered, p)))

Booster: <class 'lightgbm.basic.Booster'>
Trees : 72
Features: 26

RECOVERED PROBABILITY DISTRIBUTION
length : 842159
min    : 0.00021110787104476237
max    : 0.9579864972849627
median : 0.0006080407086636545
mean   : 0.012912612638270073

Percentiles:
 50.00% : 0.0006080407086636545
 90.00% : 0.0010296458669787594
 95.00% : 0.0025764791083493434
 99.00% : 0.8447415090151832
 99.50% : 0.9497985183338613
 99.90% : 0.9535422879407986
 99.99% : 0.9535491733803816

In [125]:
# ============================================================
# STEP 42 — REAL BASELINE + HARD-ROW IDENTIFICATION
# ============================================================

import numpy as np
import pandas as pd

df = val_feature_df[
    ["source1_entity_id", "candidate_entity_id"]
].copy()

df["model_score"] = score_recovered

# GT ONLY for S1s actually present in this validation candidate set
val_ids = set(df["source1_entity_id"].astype(str))

gt_val = {
    str(s1): set(map(str, gt_ids))
    for s1, gt_ids in ground_truth.items()
    if str(s1) in val_ids
}

def f05(tp, pred_n, gt_n):
    if pred_n == 0:
        return 1.0 if gt_n == 0 else 0.0

    p = tp / pred_n
    r = tp / gt_n if gt_n else 0.0

    if p == 0 and r == 0:
        return 0.0

    return (1.25 * p * r) / (0.25 * p + r)

# ------------------------------------------------------------
# Threshold sweep
# ------------------------------------------------------------

threshold_results = []

for t in np.arange(0.80, 0.971, 0.002):

    row_scores = []
    total_tp = 0
    total_pred = 0
    total_gt = 0

    for s1, g in df.groupby("source1_entity_id", sort=False):

        s1 = str(s1)
        truth = gt_val.get(s1, set())

        pred = set(
            g.loc[g["model_score"] >= t,
                  "candidate_entity_id"].astype(str)
        )

        tp = len(pred & truth)

        row_scores.append(
            f05(tp, len(pred), len(truth))
        )

        total_tp += tp
        total_pred += len(pred)
        total_gt += len(truth)

    threshold_results.append({
        "threshold": t,
        "macro_f05": np.mean(row_scores),
        "precision": total_tp / total_pred if total_pred else 0,
        "recall": total_tp / total_gt if total_gt else 0,
        "predicted_pairs": total_pred,
        "tp": total_tp
    })

thr_df = pd.DataFrame(threshold_results).sort_values(
    "macro_f05",
    ascending=False
)

print("=" * 70)
print("REAL BASELINE / THRESHOLD SEARCH")
print("=" * 70)

display(thr_df.head(10))

# ------------------------------------------------------------
# Hard rows
# ------------------------------------------------------------

best_t = float(thr_df.iloc[0]["threshold"])

hard_rows = []

for s1, g in df.groupby("source1_entity_id", sort=False):

    s1 = str(s1)
    truth = gt_val.get(s1, set())

    scores = g["model_score"].to_numpy()

    pred = set(
        g.loc[g["model_score"] >= best_t,
              "candidate_entity_id"].astype(str)
    )

    found = pred & truth
    missing = truth - set(g["candidate_entity_id"].astype(str))

    hard_rows.append({
        "s1": s1,
        "gt_count": len(truth),
        "candidate_count": len(g),
        "max_score": float(scores.max()),
        "second_score": float(
            np.sort(scores)[-2]
        ) if len(scores) > 1 else 0.0,
        "pred_count": len(pred),
        "tp": len(found),
        "missing_gt": len(missing),
        "all_gt_found_in_candidates": len(missing) == 0
    })

hard_df = pd.DataFrame(hard_rows)

print("\nBEST THRESHOLD:", best_t)

print("\nRows with missing candidate GT:")
display(
    hard_df[
        ~hard_df["all_gt_found_in_candidates"]
    ].sort_values(
        ["missing_gt", "max_score"],
        ascending=[False, True]
    ).head(30)
)

print(
    "\nRows with GT missing:",
    (~hard_df["all_gt_found_in_candidates"]).sum()
)

======================================================================
REAL BASELINE / THRESHOLD SEARCH
======================================================================

    threshold  macro_f05  precision    recall  predicted_pairs    tp
72      0.944   0.812059   0.886875  0.764246             5958  5284
73      0.946   0.805024   0.899430  0.730836             5618  5053
74      0.948   0.793971   0.907085  0.707405             5392  4891
71      0.942   0.791961   0.838385  0.808071             6664  5587
70      0.940   0.786725   0.826404  0.819352             6855  5665
69      0.938   0.780685   0.816429  0.826584             7000  5715
68      0.936   0.777794   0.812871  0.831212             7070  5747
67      0.934   0.775990   0.808850  0.835406             7141  5776
66      0.932   0.770612   0.801853  0.838733             7232  5799
65      0.930   0.769682   0.799286  0.842060             7284  5822

BEST THRESHOLD: 0.9440000000000002

Rows with missing candidate GT:

,s1,gt_count,candidate_count,max_score,second_score,pred_count,tp,missing_gt,all_gt_found_in_candidates
630,S1-163567186,7,908,0.275197,0.219225,0,0,7,False
963,S1-654117873,7,4,0.953549,0.953549,2,2,5,False
364,S1-343636643,4,715,0.949782,0.943226,1,0,4,False
1404,S1-635390945,7,465,0.953542,0.942106,1,1,4,False
696,S1-682824625,3,122,0.169539,0.156715,0,0,3,False
660,S1-658192036,3,695,0.943301,0.626755,0,0,3,False
320,S1-426723298,3,710,0.943848,0.943848,0,0,3,False
1413,S1-708610889,5,778,0.946351,0.946351,3,2,3,False
741,S1-469535575,5,138,0.949817,0.949782,2,2,3,False
1486,S1-884904716,4,369,0.953441,0.942777,1,1,3,False
1910,S1-804892516,6,135,0.953510,0.949817,3,2,3,False
898,S1-914622541,7,1002,0.953542,0.943512,1,1,3,False
1635,S1-127491881,5,1353,0.953542,0.627131,1,1,3,False
242,S1-560290866,6,1412,0.956562,0.953542,4,3,3,False
500,S1-719428038,2,488,0.877107,0.877107,0,0,2,False
706,S1-841213363,3,145,0.904121,0.296506,0,0,2,False
527,S1-337747814,3,431,0.934275,0.849783,0,0,2,False
801,S1-991022122,3,523,0.939472,0.524033,0,0,2,False
1663,S1-122974528,3,477,0.942111,0.898291,0,0,2,False
842,S1-479314025,3,492,0.943512,0.852654,0,0,2,False
1123,S1-300435055,5,252,0.943874,0.811952,0,0,2,False
982,S1-500020440,4,902,0.944420,0.800744,1,0,2,False
1884,S1-306092916,3,159,0.944420,0.942075,1,0,2,False
1934,S1-6361374,5,539,0.945324,0.754538,1,1,2,False
1509,S1-95730121,3,228,0.946351,0.921899,1,1,2,False
837,S1-81143467,3,749,0.946502,0.861302,1,1,2,False
350,S1-715240062,5,412,0.946731,0.942527,1,1,2,False
1673,S1-560974101,3,566,0.947076,0.191047,1,1,2,False
581,S1-636370789,2,1099,0.949782,0.386566,1,0,2,False
371,S1-68472642,3,768,0.949799,0.927064,1,1,2,False

Rows with GT missing: 272

In [127]:
# ============================================================
# STEP 43 — TARGETED ADAPTIVE BLOCKING
# CORRECTED: uses existing train_s1, no val_s1 variable
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 43 — TARGETED ADAPTIVE BLOCKING")
print("=" * 70)

# ------------------------------------------------------------
# 1. Identify hard validation S1 IDs
# ------------------------------------------------------------

hard_ids = set(
    hard_df.loc[
        ~hard_df["all_gt_found_in_candidates"],
        "s1"
    ].astype(str)
)

print("Hard S1 IDs:", len(hard_ids))

# ------------------------------------------------------------
# 2. Retrieve their actual S1 rows from EXISTING train_s1
# ------------------------------------------------------------

hard_rows = [
    row for row in train_s1
    if str(row.get("entity_id", "")) in hard_ids
]

print("Retrieved S1 rows:", len(hard_rows))

if len(hard_rows) != len(hard_ids):
    missing_rows = hard_ids - {
        str(row.get("entity_id", ""))
        for row in hard_rows
    }
    print("WARNING — missing S1 rows:", len(missing_rows))
    print(list(missing_rows)[:10])

# ------------------------------------------------------------
# 3. Existing caps
# ------------------------------------------------------------

base_caps = CAPS.copy()

# Only hard rows get expanded caps
cap_multipliers = [2, 4, 8]

# ------------------------------------------------------------
# 4. Existing candidate sets
# ------------------------------------------------------------

existing_by_s1 = {
    str(s1): set(
        g["candidate_entity_id"].astype(str)
    )
    for s1, g in val_candidate_pairs.groupby(
        "source1_entity_id",
        sort=False
    )
}

print("Existing candidate groups:", len(existing_by_s1))

# ------------------------------------------------------------
# 5. Validation ground truth
# ------------------------------------------------------------

gt_hard = {
    str(s1): set(map(str, gt_ids))
    for s1, gt_ids in ground_truth.items()
    if str(s1) in hard_ids
}

# ------------------------------------------------------------
# 6. Candidate retrieval helper
# ------------------------------------------------------------

def get_candidates_with_caps(row, caps):

    result = set()

    for source, index in [
        ("S2", s2_index),
        ("S3", s3_index)
    ]:

        found = find_candidates(
            row,
            index,
            freq_caps=caps
        )

        for suffix in found.keys():
            result.add(f"{source}-{suffix}")

    return result


# ------------------------------------------------------------
# 7. Test increasingly relaxed caps
# ------------------------------------------------------------

summary = []

for mult in cap_multipliers:

    print(f"\nTesting {mult}x caps...")

    caps = {
        key: int(value * mult)
        for key, value in base_caps.items()
    }

    total_missing = 0
    recovered = 0
    extra_candidates = 0
    rows_recovered = 0

    for row in hard_rows:

        s1 = str(row["entity_id"])

        truth = gt_hard.get(s1, set())
        existing = existing_by_s1.get(s1, set())

        missing = truth - existing

        if not missing:
            continue

        expanded = get_candidates_with_caps(
            row,
            caps
        )

        newly_found = missing & expanded

        total_missing += len(missing)
        recovered += len(newly_found)

        if newly_found:
            rows_recovered += 1

        extra_candidates += len(
            expanded - existing
        )

    recovery_pct = (
        100.0 * recovered / total_missing
        if total_missing
        else 0.0
    )

    summary.append({
        "cap_multiplier": mult,
        "missing_gt": total_missing,
        "recovered_gt": recovered,
        "recovery_pct": recovery_pct,
        "rows_recovered": rows_recovered,
        "extra_candidates": extra_candidates
    })

    print(
        f"  recovered: {recovered}/{total_missing} "
        f"({recovery_pct:.2f}%)"
    )
    print(
        f"  rows recovered: {rows_recovered}"
    )
    print(
        f"  extra candidates: {extra_candidates}"
    )

summary_df = pd.DataFrame(summary)

print("\n" + "=" * 70)
print("STEP 43 RESULT")
print("=" * 70)

display(summary_df)

======================================================================
STEP 43 — TARGETED ADAPTIVE BLOCKING
======================================================================
Hard S1 IDs: 272
Retrieved S1 rows: 272

AttributeError: 'list' object has no attribute 'groupby'

In [128]:
# ============================================================
# STEP 43 — TARGETED ADAPTIVE BLOCKING
# CORRECTED FOR val_candidate_pairs = list[dict]
# ============================================================

import pandas as pd

print("=" * 70)
print("STEP 43 — TARGETED ADAPTIVE BLOCKING")
print("=" * 70)

# ------------------------------------------------------------
# Existing candidate sets from LIST of dictionaries
# ------------------------------------------------------------

existing_by_s1 = {}

for item in val_candidate_pairs:
    s1 = str(item["source1_entity_id"])
    cid = str(item["candidate_entity_id"])

    if s1 not in existing_by_s1:
        existing_by_s1[s1] = set()

    existing_by_s1[s1].add(cid)

print("Existing candidate groups:", len(existing_by_s1))

# ------------------------------------------------------------
# Ground truth for hard rows
# ------------------------------------------------------------

gt_hard = {
    str(s1): set(map(str, gt_ids))
    for s1, gt_ids in ground_truth.items()
    if str(s1) in hard_ids
}

print("GT hard rows:", len(gt_hard))

# ------------------------------------------------------------
# Candidate retrieval
# ------------------------------------------------------------

def get_candidates_with_caps(row, caps):

    result = set()

    for source, index in [
        ("S2", s2_index),
        ("S3", s3_index)
    ]:

        found = find_candidates(
            row,
            index,
            freq_caps=caps
        )

        for suffix in found.keys():
            result.add(f"{source}-{suffix}")

    return result


# ------------------------------------------------------------
# Test relaxed caps
# ------------------------------------------------------------

base_caps = CAPS.copy()

# Keep this targeted. Only 272 difficult rows.
cap_multipliers = [2, 4, 8]

summary = []

for mult in cap_multipliers:

    print(f"\nTesting {mult}x caps...")

    caps = {
        key: int(value * mult)
        for key, value in base_caps.items()
    }

    total_missing = 0
    recovered = 0
    rows_recovered = 0
    extra_candidates = 0

    for row in hard_rows:

        s1 = str(row["entity_id"])

        truth = gt_hard.get(s1, set())
        existing = existing_by_s1.get(s1, set())

        missing = truth - existing

        if not missing:
            continue

        expanded = get_candidates_with_caps(
            row,
            caps
        )

        newly_found = missing & expanded

        total_missing += len(missing)
        recovered += len(newly_found)

        if newly_found:
            rows_recovered += 1

        extra_candidates += len(expanded - existing)

    recovery_pct = (
        100.0 * recovered / total_missing
        if total_missing
        else 0.0
    )

    summary.append({
        "cap_multiplier": mult,
        "missing_gt": total_missing,
        "recovered_gt": recovered,
        "recovery_pct": recovery_pct,
        "rows_recovered": rows_recovered,
        "extra_candidates": extra_candidates
    })

    print(
        f"Recovered {recovered}/{total_missing} "
        f"({recovery_pct:.2f}%)"
    )
    print(f"Rows recovered: {rows_recovered}")
    print(f"Extra candidates: {extra_candidates}")

summary_df = pd.DataFrame(summary)

print("\n" + "=" * 70)
print("STEP 43 RESULT")
print("=" * 70)

display(summary_df)

======================================================================
STEP 43 — TARGETED ADAPTIVE BLOCKING
======================================================================
Existing candidate groups: 2000
GT hard rows: 272

Testing 2x caps...
Recovered 70/351 (19.94%)
Rows recovered: 56
Extra candidates: 134068

Testing 4x caps...
Recovered 107/351 (30.48%)
Rows recovered: 88
Extra candidates: 385025

Testing 8x caps...
Recovered 141/351 (40.17%)
Rows recovered: 115
Extra candidates: 821334

======================================================================
STEP 43 RESULT
======================================================================

,cap_multiplier,missing_gt,recovered_gt,recovery_pct,rows_recovered,extra_candidates
0,2,351,70,19.94302,56,134068
1,4,351,107,30.48433,88,385025
2,8,351,141,40.17094,115,821334

In [129]:
# ============================================================
# STEP 44 — FUZZY RECOVERY POTENTIAL OF REMAINING GT MISSES
# ============================================================

from rapidfuzz.fuzz import ratio, token_set_ratio, WRatio

# Reconstruct the 351 missing GT pairs from our previous diagnostic
remaining_records = []

for _, r in missing_df.iterrows():

    s1_name = str(r["s1_name"])
    gt_name = str(r["gt_name"])
    s1_addr = str(r["s1_address"])
    gt_addr = str(r["gt_address"])

    name_ratio = ratio(s1_name, gt_name) / 100.0
    name_token = token_set_ratio(s1_name, gt_name) / 100.0
    name_wratio = WRatio(s1_name, gt_name) / 100.0

    addr_ratio = ratio(s1_addr, gt_addr) / 100.0
    addr_token = token_set_ratio(s1_addr, gt_addr) / 100.0

    remaining_records.append({
        "s1": str(r["s1_id"]),
        "gt": str(r["gt_id"]),
        "name_ratio": name_ratio,
        "name_token": name_token,
        "name_wratio": name_wratio,
        "addr_ratio": addr_ratio,
        "addr_token": addr_token,
        "combined": (
            0.60 * max(name_ratio, name_token, name_wratio)
            + 0.40 * max(addr_ratio, addr_token)
        )
    })

fuzzy_missing_df = pd.DataFrame(remaining_records)

print("=" * 70)
print("STEP 44 — FUZZY RECOVERY POTENTIAL")
print("=" * 70)

for col in [
    "name_ratio",
    "name_token",
    "name_wratio",
    "addr_ratio",
    "addr_token",
    "combined"
]:
    print(
        f"{col:15s} "
        f"mean={fuzzy_missing_df[col].mean():.3f}  "
        f"median={fuzzy_missing_df[col].median():.3f}  "
        f"max={fuzzy_missing_df[col].max():.3f}"
    )

print("\nPotentially strong missing pairs:")

display(
    fuzzy_missing_df
    .sort_values("combined", ascending=False)
    .head(30)
)

======================================================================
STEP 44 — FUZZY RECOVERY POTENTIAL
======================================================================
name_ratio      mean=0.479  median=0.545  max=1.000
name_token      mean=0.542  median=0.667  max=1.000
name_wratio     mean=0.542  median=0.696  max=1.000
addr_ratio      mean=0.402  median=0.391  max=0.878
addr_token      mean=0.548  median=0.577  max=0.978
combined        mean=0.555  median=0.562  max=0.961

Potentially strong missing pairs:

,s1,gt,name_ratio,name_token,name_wratio,addr_ratio,addr_token,combined
120,S1-140223936,S3-162340681,0.794118,1.000000,0.950000,0.438356,0.903226,0.961290
267,S1-192845076,S3-66771546,0.809524,1.000000,0.950000,0.627451,0.896552,0.958621
326,S1-804892516,S3-926656803,0.740741,1.000000,0.950000,0.561644,0.867470,0.946988
328,S1-804892516,S3-401938105,0.740741,1.000000,0.950000,0.561644,0.867470,0.946988
203,S1-983193550,S3-85515857,0.867925,1.000000,0.950000,0.507937,0.851852,0.940741
97,S1-6692510,S3-551313219,0.900000,1.000000,0.950000,0.519084,0.842105,0.936842
188,S1-702641290,S3-740374896,0.915254,0.931034,0.915254,0.317881,0.936170,0.933089
258,S1-965462149,S3-74546218,0.786885,0.983607,0.934426,0.852941,0.852941,0.931340
127,S1-841213363,S3-202831264,0.833333,1.000000,0.950000,0.500000,0.823529,0.929412
217,S1-754363423,S3-12351257,0.708333,1.000000,0.950000,0.813559,0.813559,0.925424
159,S1-698473845,S3-890945141,0.782609,0.956522,0.908696,0.877551,0.877551,0.924933
339,S1-456544362,S3-685079530,0.784314,0.941176,0.894118,0.871287,0.900000,0.924706
327,S1-804892516,S3-5729759,0.740741,1.000000,0.950000,0.421053,0.807018,0.922807
277,S1-186639306,S3-318251156,0.784314,0.930233,0.883721,0.435897,0.909091,0.921776
220,S1-387148230,S3-522320221,0.950000,0.950000,0.950000,0.645161,0.875000,0.920000
57,S1-688640659,S3-982915915,0.761905,1.000000,0.950000,0.794872,0.794872,0.917949
271,S1-61397406,S3-404739324,0.918033,0.918033,0.918033,0.506667,0.914286,0.916534
115,S1-88729605,S3-445105822,0.682927,0.975610,0.926829,0.757576,0.818182,0.912639
319,S1-249493462,S3-813060496,0.727273,0.888889,0.844444,0.440000,0.947368,0.912281
79,S1-117173327,S3-795468483,0.846154,0.923077,0.876923,0.350877,0.892308,0.910769
333,S1-177253144,S3-868077821,0.965517,0.827586,0.965517,0.652174,0.828571,0.910739
141,S1-334424523,S3-303574153,0.666667,1.000000,0.900000,0.701754,0.771930,0.908772
294,S1-560974101,S3-366698742,0.894737,0.894737,0.894737,0.834225,0.929412,0.908607
31,S1-560290866,S3-986229253,0.800000,0.923077,0.876923,0.724490,0.885714,0.908132
20,S1-969611446,S3-249629497,0.541667,0.916667,0.870833,0.795699,0.891892,0.906757
27,S1-95823999,S3-783312005,0.730769,0.884615,0.840385,0.465517,0.938776,0.906279
201,S1-387829461,S3-950327283,0.882353,1.000000,0.950000,0.684685,0.760000,0.904000
125,S1-291812801,S3-921459018,0.723404,0.944444,0.897222,0.513274,0.843137,0.903922
263,S1-688260177,S3-358408242,0.727273,1.000000,0.950000,0.526316,0.736842,0.894737
136,S1-743240769,S3-969140596,0.912281,1.000000,0.950000,0.395349,0.733333,0.893333

In [130]:
# ============================================================
# STEP 45 — FUZZY THRESHOLD COVERAGE
# ============================================================

print("=" * 70)
print("STEP 45 — FUZZY THRESHOLD COVERAGE")
print("=" * 70)

for t in [0.70, 0.75, 0.80, 0.85, 0.88, 0.90, 0.92, 0.94]:

    hit = (
        fuzzy_missing_df["combined"] >= t
    ).sum()

    print(
        f"combined >= {t:.2f} : "
        f"{hit:3d}/351 "
        f"({100*hit/351:.2f}%)"
    )

======================================================================
STEP 45 — FUZZY THRESHOLD COVERAGE
======================================================================
combined >= 0.70 : 137/351 (39.03%)
combined >= 0.75 : 109/351 (31.05%)
combined >= 0.80 :  82/351 (23.36%)
combined >= 0.85 :  55/351 (15.67%)
combined >= 0.88 :  36/351 (10.26%)
combined >= 0.90 :  28/351 (7.98%)
combined >= 0.92 :  14/351 (3.99%)
combined >= 0.94 :   5/351 (1.42%)

In [131]:
# ============================================================
# CELL 46 — TRANSLITERATED NAME RETRIEVAL INDEX
# ============================================================
#
# PURPOSE
# -------
# Recover cross-script matches such as:
#
#   Premier Foods Private Limited
#       ↔
#   Premier फूड्स प्राइवेट लिमिटेड
#
#   Great Healthcare Private Limited
#       ↔
#   Great हेल्थकेयर प्राइवेट लिमिटेड
#
# without rebuilding the existing 5M-row blocking indexes.
#
# IMPORTANT:
# - Does NOT modify s2_index
# - Does NOT modify s3_index
# - Does NOT close s2_conn
# - Does NOT rebuild SQLite production indexes
# - Uses ONLY training S2/S3 data
# - No validation/test ground truth is used
# ============================================================

import os
import re
import gc
import sqlite3
import shutil
import unicodedata

print("=" * 80)
print("CELL 46 — TRANSLITERATED NAME RETRIEVAL INDEX")
print("=" * 80)

# ------------------------------------------------------------
# 0. Verify critical live state
# ------------------------------------------------------------

assert "s2_index" in globals(), "s2_index is missing."
assert "s3_index" in globals(), "s3_index is missing."
assert "train_s1" in globals(), "train_s1 is missing."
assert "val_feature_df" in globals(), "Validation data is missing."

# We deliberately require the live SQLite objects.
assert hasattr(s2_index, "conn"), "S2 SQLite connection unavailable."
assert hasattr(s3_index, "conn"), "S3 SQLite connection unavailable."

# ------------------------------------------------------------
# 1. Transliteration backend
# ------------------------------------------------------------

try:
    from unidecode import unidecode

    print("Transliteration backend: unidecode")

except ImportError:

    try:
        from text_unidecode import unidecode

        print("Transliteration backend: text_unidecode")

    except ImportError as e:
        raise RuntimeError(
            "No transliteration backend is installed. "
            "Do NOT install packages or restart the kernel. "
            "Stop here."
        ) from e


# ------------------------------------------------------------
# 2. Compact transliterated-name key
# ------------------------------------------------------------

def translit_name_keys_46(name):
    """
    Produce selective transliterated keys.

    The goal is NOT to create a fuzzy index.
    The goal is deterministic retrieval across scripts.

    Examples:
        English <-> Hindi
        English <-> Tamil
        English <-> Gujarati
        English <-> Bengali
        English <-> Malayalam

    Multiple keys increase recall while keeping buckets bounded.
    """

    if name is None:
        return ()

    raw = str(name).strip()

    if not raw:
        return ()

    # Unicode -> Latin transliteration.
    text = unidecode(raw)

    # Normalize punctuation/whitespace.
    text = unicodedata.normalize("NFKC", text).casefold()

    text = re.sub(
        r"[^a-z0-9]+",
        " ",
        text,
    )

    text = " ".join(text.split())

    if not text:
        return ()

    compact = text.replace(" ", "")
    words = text.split()

    keys = set()

    # --------------------------------------------------------
    # Prefix keys
    # --------------------------------------------------------

    if len(compact) >= 6:
        keys.add(("TNP6", compact[:6]))

    if len(compact) >= 8:
        keys.add(("TNP8", compact[:8]))

    # --------------------------------------------------------
    # Suffix key
    # --------------------------------------------------------

    if len(compact) >= 6:
        keys.add(("TNS6", compact[-6:]))

    # --------------------------------------------------------
    # First/last token key
    # --------------------------------------------------------

    if len(words) >= 2:

        first = words[0]
        last = words[-1]

        if len(first) >= 3 and len(last) >= 3:
            keys.add(
                (
                    "TFL",
                    first[:4] + "|" + last[:4],
                )
            )

    # --------------------------------------------------------
    # Order-invariant token key
    # --------------------------------------------------------

    if len(words) >= 2:

        # Ignore very short tokens because they generate
        # enormous buckets.
        useful = sorted(
            {
                w
                for w in words
                if len(w) >= 3
            }
        )

        if len(useful) >= 2:

            # First/last after sorting gives an inexpensive
            # order-independent retrieval key.
            keys.add(
                (
                    "TNORD",
                    useful[0][:8] + "|" + useful[-1][:8],
                )
            )

    return tuple(keys)


# ------------------------------------------------------------
# 3. Output database
# ------------------------------------------------------------

AUX_DIR = "/kaggle/working/amazon_ml_solution/auxiliary"

os.makedirs(AUX_DIR, exist_ok=True)

AUX_DB = os.path.join(
    AUX_DIR,
    "train_translit_name.sqlite",
)

# Never silently overwrite an existing auxiliary index.
if os.path.exists(AUX_DB):
    print()
    print("Existing auxiliary index found:")
    print(AUX_DB)
    print(
        f"Size: {os.path.getsize(AUX_DB) / (1024**3):.3f} GiB"
    )

    raise RuntimeError(
        "Auxiliary transliteration index already exists. "
        "Do not overwrite it. Inspect it in the next cell."
    )


# ------------------------------------------------------------
# 4. Disk safety
# ------------------------------------------------------------

disk = shutil.disk_usage("/kaggle/working")

free_gb = disk.free / (1024**3)

print()
print(f"Free disk before build: {free_gb:.2f} GiB")

# The compact index should stay comfortably below this.
# We refuse to risk filling the Kaggle filesystem.
if free_gb < 1.50:
    raise RuntimeError(
        f"Only {free_gb:.2f} GiB free. "
        "Refusing to build and risk corrupting the existing indexes."
    )


# ------------------------------------------------------------
# 5. Create compact SQLite index
# ------------------------------------------------------------

aux_conn = sqlite3.connect(AUX_DB)

aux_conn.execute("PRAGMA journal_mode=OFF")
aux_conn.execute("PRAGMA synchronous=OFF")
aux_conn.execute("PRAGMA temp_store=MEMORY")

aux_conn.execute(
    """
    CREATE TABLE postings (
        key_type TEXT NOT NULL,
        key_value TEXT NOT NULL,
        source TEXT NOT NULL,
        suffix TEXT NOT NULL,
        PRIMARY KEY (
            key_type,
            key_value,
            source,
            suffix
        )
    ) WITHOUT ROWID
    """
)

aux_conn.commit()


# ------------------------------------------------------------
# 6. Discover attrs schema
# ------------------------------------------------------------

def get_attrs_columns_46(index):

    rows = index.conn.execute(
        "PRAGMA table_info(attrs)"
    ).fetchall()

    return [row[1] for row in rows]


s2_cols = get_attrs_columns_46(s2_index)
s3_cols = get_attrs_columns_46(s3_index)

print()
print("S2 attrs columns:", s2_cols)
print("S3 attrs columns:", s3_cols)

required_attrs = {
    "suffix",
    "name",
    "address",
    "country",
}

if not required_attrs.issubset(set(s2_cols)):
    raise RuntimeError(
        f"S2 attrs schema unexpected: {s2_cols}"
    )

if not required_attrs.issubset(set(s3_cols)):
    raise RuntimeError(
        f"S3 attrs schema unexpected: {s3_cols}"
    )


# ------------------------------------------------------------
# 7. Stream records from existing SQLite indexes
# ------------------------------------------------------------

INSERT_SQL = """
INSERT OR IGNORE INTO postings
    (key_type, key_value, source, suffix)
VALUES (?, ?, ?, ?)
"""


def build_source_aux_46(index, source, batch_size=25_000):

    print()
    print("-" * 70)
    print(f"BUILDING TRANSLITERATED INDEX: {source}")
    print("-" * 70)

    cursor = index.conn.execute(
        """
        SELECT suffix, name
        FROM attrs
        """
    )

    batch = []
    n_rows = 0
    n_keys = 0

    while True:

        rows = cursor.fetchmany(batch_size)

        if not rows:
            break

        for suffix, name in rows:

            keys = translit_name_keys_46(name)

            if not keys:
                continue

            for key_type, key_value in keys:

                batch.append(
                    (
                        key_type,
                        key_value,
                        source,
                        str(suffix),
                    )
                )

            n_rows += 1
            n_keys += len(keys)

        if len(batch) >= batch_size:

            aux_conn.executemany(
                INSERT_SQL,
                batch,
            )

            aux_conn.commit()

            batch.clear()

        if n_rows % 250_000 == 0:

            print(
                f"{source}: "
                f"{n_rows:,} records processed | "
                f"{n_keys:,} key rows generated"
            )

    if batch:

        aux_conn.executemany(
            INSERT_SQL,
            batch,
        )

        aux_conn.commit()

        batch.clear()

    print(
        f"{source}: COMPLETE | "
        f"{n_rows:,} records | "
        f"{n_keys:,} generated keys"
    )

    return n_rows, n_keys


s2_count_46, s2_keys_46 = build_source_aux_46(
    s2_index,
    "S2",
)

s3_count_46, s3_keys_46 = build_source_aux_46(
    s3_index,
    "S3",
)


# ------------------------------------------------------------
# 8. Finalize SQLite statistics
# ------------------------------------------------------------

aux_conn.execute(
    "ANALYZE"
)

aux_conn.commit()

total_postings_46 = aux_conn.execute(
    "SELECT COUNT(*) FROM postings"
).fetchone()[0]

distinct_keys_46 = aux_conn.execute(
    """
    SELECT COUNT(*)
    FROM (
        SELECT DISTINCT key_type, key_value, source
        FROM postings
    )
    """
).fetchone()[0]

print()
print("=" * 80)
print("TRANSLITERATED INDEX COMPLETE")
print("=" * 80)

print(f"S2 records processed : {s2_count_46:,}")
print(f"S3 records processed : {s3_count_46:,}")
print(f"Posting rows         : {total_postings_46:,}")
print(f"Distinct keys        : {distinct_keys_46:,}")

aux_size_gb = (
    os.path.getsize(AUX_DB) / (1024**3)
)

print(f"Aux DB size           : {aux_size_gb:.3f} GiB")

print()
print("Database:", AUX_DB)

# Keep aux_conn OPEN for the next cell.
# Do NOT close it.

gc.collect()

print()
print("CELL 46 COMPLETE.")
print("Do NOT restart the kernel.")

================================================================================
CELL 46 — TRANSLITERATED NAME RETRIEVAL INDEX
================================================================================
Transliteration backend: text_unidecode

Free disk before build: 2.08 GiB

S2 attrs columns: ['suffix', 'name', 'address', 'country']
S3 attrs columns: ['suffix', 'name', 'address', 'country']

----------------------------------------------------------------------
BUILDING TRANSLITERATED INDEX: S2
----------------------------------------------------------------------
S2: COMPLETE | 5,012,214 records | 24,076,806 generated keys

----------------------------------------------------------------------
BUILDING TRANSLITERATED INDEX: S3
----------------------------------------------------------------------
S3: COMPLETE | 5,238,163 records | 25,097,282 generated keys

================================================================================
TRANSLITERATED INDEX COMPLETE
================================================================================
S2 records processed : 5,012,214
S3 records processed : 5,238,163
Posting rows         : 49,174,088
Distinct keys        : 9,086,563
Aux DB size           : 1.606 GiB

Database: /kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite

CELL 46 COMPLETE.
Do NOT restart the kernel.

In [134]:
# ============================================================
# CELL 47 — TRANSLITERATION RETRIEVAL RECALL TEST
# REVISED: val_candidate_pairs is list[dict]
# ============================================================

import re
import unicodedata
import gc

print("=" * 80)
print("CELL 47 — TRANSLITERATION RETRIEVAL RECALL TEST")
print("=" * 80)

# ------------------------------------------------------------
# 0. Critical state validation
# ------------------------------------------------------------

required_vars_47 = [
    "aux_conn",
    "val_feature_df",
    "val_candidate_pairs",
    "ground_truth",
    "train_s1",
]

for _v in required_vars_47:
    assert _v in globals(), f"Required variable missing: {_v}"

assert isinstance(
    val_candidate_pairs,
    list
), (
    f"val_candidate_pairs must be a list, "
    f"got {type(val_candidate_pairs)}"
)

assert len(val_candidate_pairs) == 842159, (
    f"Unexpected validation candidate count: "
    f"{len(val_candidate_pairs):,}"
)

assert len(val_candidate_pairs) > 0

# Validate actual candidate-row structure BEFORE doing anything.
_first_pair_47 = val_candidate_pairs[0]

assert isinstance(
    _first_pair_47,
    dict
), (
    f"Expected candidate rows to be dicts, "
    f"got {type(_first_pair_47)}"
)

_required_pair_keys_47 = {
    "source1_entity_id",
    "candidate_entity_id",
    "source",
}

assert _required_pair_keys_47.issubset(
    _first_pair_47.keys()
), (
    f"Candidate-row schema unexpected: "
    f"{_first_pair_47.keys()}"
)

# Verify auxiliary connection points to the intended DB.
aux_db_path_47 = aux_conn.execute(
    "PRAGMA database_list"
).fetchone()[2]

assert aux_db_path_47.endswith(
    "train_translit_name.sqlite"
), (
    "aux_conn is not connected to the expected "
    "transliteration database."
)

print("Aux DB:", aux_db_path_47)
print(
    f"Existing validation candidate rows: "
    f"{len(val_candidate_pairs):,}"
)


# ------------------------------------------------------------
# 1. Verify transliteration backend
# ------------------------------------------------------------

try:
    from text_unidecode import unidecode
    print("Transliteration backend: text_unidecode")
except ImportError:
    try:
        from unidecode import unidecode
        print("Transliteration backend: unidecode")
    except ImportError as e:
        raise RuntimeError(
            "The transliteration backend used by Cell 46 "
            "is unavailable."
        ) from e


# ------------------------------------------------------------
# 2. EXACT same transliteration key logic as Cell 46
# ------------------------------------------------------------

def translit_name_keys_47(name):

    if name is None:
        return ()

    raw = str(name).strip()

    if not raw:
        return ()

    text = unidecode(raw)

    text = unicodedata.normalize(
        "NFKC",
        text,
    ).casefold()

    text = re.sub(
        r"[^a-z0-9]+",
        " ",
        text,
    )

    text = " ".join(text.split())

    if not text:
        return ()

    compact = text.replace(" ", "")
    words = text.split()

    keys = set()

    if len(compact) >= 6:
        keys.add(("TNP6", compact[:6]))

    if len(compact) >= 8:
        keys.add(("TNP8", compact[:8]))

    if len(compact) >= 6:
        keys.add(("TNS6", compact[-6:]))

    if len(words) >= 2:

        first = words[0]
        last = words[-1]

        if len(first) >= 3 and len(last) >= 3:
            keys.add(
                (
                    "TFL",
                    first[:4] + "|" + last[:4],
                )
            )

    if len(words) >= 2:

        useful = sorted(
            {
                w
                for w in words
                if len(w) >= 3
            }
        )

        if len(useful) >= 2:
            keys.add(
                (
                    "TNORD",
                    useful[0][:8] + "|" + useful[-1][:8],
                )
            )

    return tuple(keys)


# ------------------------------------------------------------
# 3. Validation S1 IDs
# ------------------------------------------------------------

VAL_S1_IDS_47 = set(
    val_feature_df[
        "source1_entity_id"
    ].astype(str).unique()
)

assert len(VAL_S1_IDS_47) == 2000, (
    f"Expected 2,000 validation S1 rows, "
    f"found {len(VAL_S1_IDS_47):,}"
)

print(
    f"Validation S1 rows represented: "
    f"{len(VAL_S1_IDS_47):,}"
)


# ------------------------------------------------------------
# 4. Build EXACT validation GT pairs
# ------------------------------------------------------------

gt_rows_47 = []

for s1_id in VAL_S1_IDS_47:

    matched = ground_truth.get(
        s1_id,
        frozenset(),
    )

    for candidate_id in matched:

        gt_rows_47.append(
            (
                str(s1_id),
                str(candidate_id),
            )
        )

assert len(gt_rows_47) == 6914, (
    f"Expected 6,914 validation GT pairs, "
    f"found {len(gt_rows_47):,}"
)

print(
    f"Validation GT pairs: "
    f"{len(gt_rows_47):,}"
)


# ------------------------------------------------------------
# 5. Convert EXISTING candidate list to pair set
#
# IMPORTANT:
# val_candidate_pairs is list[dict].
# ------------------------------------------------------------

existing_pairs_47 = set()

for pair in val_candidate_pairs:

    existing_pairs_47.add(
        (
            str(pair["source1_entity_id"]),
            str(pair["candidate_entity_id"]),
        )
    )

print(
    f"Unique existing validation candidate pairs: "
    f"{len(existing_pairs_47):,}"
)

assert len(existing_pairs_47) > 0


# ------------------------------------------------------------
# 6. Exact previously-established 351 missing GT pairs
# ------------------------------------------------------------

missing_gt_pairs_47 = [
    pair
    for pair in gt_rows_47
    if pair not in existing_pairs_47
]

assert len(missing_gt_pairs_47) == 351, (
    f"Expected exactly 351 missing GT pairs, "
    f"found {len(missing_gt_pairs_47):,}"
)

print(
    f"Missing GT pairs to test: "
    f"{len(missing_gt_pairs_47):,}"
)


# ------------------------------------------------------------
# 7. Recover ONLY affected S1 names
# ------------------------------------------------------------

missing_s1_ids_47 = {
    s1_id
    for s1_id, _ in missing_gt_pairs_47
}

s1_name_map_47 = {}

for row in train_s1:

    entity_id = str(row["entity_id"])

    if entity_id in missing_s1_ids_47:

        s1_name_map_47[entity_id] = (
            row.get("business_name", "")
        )

        if (
            len(s1_name_map_47)
            == len(missing_s1_ids_47)
        ):
            break

assert len(s1_name_map_47) == len(
    missing_s1_ids_47
), (
    "Failed to recover all affected "
    "validation S1 names."
)

print(
    f"Affected S1 names recovered: "
    f"{len(s1_name_map_47):,}"
)


# ------------------------------------------------------------
# 8. READ-ONLY transliteration retrieval
# ------------------------------------------------------------

TRANS_CAP_47 = 1000

retrieved_pairs_47 = set()

key_hits_47 = 0
broad_keys_47 = 0
queried_keys_47 = 0

for s1_id, gt_candidate_id in missing_gt_pairs_47:

    name = s1_name_map_47[s1_id]

    keys = translit_name_keys_47(name)

    for key_type, key_value in keys:

        for source in ("S2", "S3"):

            queried_keys_47 += 1

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    key_type,
                    key_value,
                    source,
                    TRANS_CAP_47 + 1,
                ),
            ).fetchall()

            if len(rows) > TRANS_CAP_47:

                broad_keys_47 += 1
                continue

            if not rows:
                continue

            key_hits_47 += 1

            for (suffix,) in rows:

                candidate_full_id = (
                    f"{source}-{suffix}"
                )

                retrieved_pairs_47.add(
                    (
                        s1_id,
                        candidate_full_id,
                    )
                )


# ------------------------------------------------------------
# 9. Exact pair-level recovery
# ------------------------------------------------------------

recovered_pairs_47 = [
    pair
    for pair in missing_gt_pairs_47
    if pair in retrieved_pairs_47
]

missing_after_translit_47 = [
    pair
    for pair in missing_gt_pairs_47
    if pair not in retrieved_pairs_47
]

recovered_count_47 = len(
    recovered_pairs_47
)

recovery_pct_47 = (
    100.0
    * recovered_count_47
    / len(missing_gt_pairs_47)
)


# ------------------------------------------------------------
# 10. Row-level recovery
# ------------------------------------------------------------

rows_with_missing_gt_47 = {
    s1_id
    for s1_id, _ in missing_gt_pairs_47
}

rows_recovered_47 = {
    s1_id
    for s1_id, _ in recovered_pairs_47
}

row_recovery_pct_47 = (
    100.0
    * len(rows_recovered_47)
    / len(rows_with_missing_gt_47)
)


# ------------------------------------------------------------
# 11. Source breakdown
# ------------------------------------------------------------

s2_missing_47 = [
    p
    for p in missing_gt_pairs_47
    if p[1].startswith("S2-")
]

s3_missing_47 = [
    p
    for p in missing_gt_pairs_47
    if p[1].startswith("S3-")
]

s2_recovered_47 = [
    p
    for p in recovered_pairs_47
    if p[1].startswith("S2-")
]

s3_recovered_47 = [
    p
    for p in recovered_pairs_47
    if p[1].startswith("S3-")
]


# ------------------------------------------------------------
# 12. Final report
# ------------------------------------------------------------

print()
print("=" * 80)
print("CELL 47 RESULT")
print("=" * 80)

print(
    f"Missing GT pairs tested : "
    f"{len(missing_gt_pairs_47):,}"
)

print(
    f"Recovered by translit  : "
    f"{recovered_count_47:,}"
)

print(
    f"Pair recovery          : "
    f"{recovery_pct_47:.4f}%"
)

print()

print(
    f"Rows with missing GT   : "
    f"{len(rows_with_missing_gt_47):,}"
)

print(
    f"Rows recovered         : "
    f"{len(rows_recovered_47):,}"
)

print(
    f"Row recovery           : "
    f"{row_recovery_pct_47:.4f}%"
)

print()

print(
    f"S2 missing/recovered   : "
    f"{len(s2_missing_47):,} / "
    f"{len(s2_recovered_47):,}"
)

print(
    f"S3 missing/recovered   : "
    f"{len(s3_missing_47):,} / "
    f"{len(s3_recovered_47):,}"
)

print()

print(
    f"SQL key queries        : "
    f"{queried_keys_47:,}"
)

print(
    f"Non-empty key hits     : "
    f"{key_hits_47:,}"
)

print(
    f"Broad keys skipped     : "
    f"{broad_keys_47:,}"
)

print()

print("Top recovered examples:")

for s1_id, candidate_id in recovered_pairs_47[:20]:

    print(
        f"  {s1_id}  ->  {candidate_id}"
    )

print()

print("Still-missing examples:")

for s1_id, candidate_id in missing_after_translit_47[:20]:

    print(
        f"  {s1_id}  ->  {candidate_id}"
    )

print()
print("=" * 80)
print("CELL 47 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 47 — TRANSLITERATION RETRIEVAL RECALL TEST
================================================================================
Aux DB: /kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite
Existing validation candidate rows: 842,159
Transliteration backend: text_unidecode
Validation S1 rows represented: 2,000
Validation GT pairs: 6,914
Unique existing validation candidate pairs: 842,159
Missing GT pairs to test: 351
Affected S1 names recovered: 272

================================================================================
CELL 47 RESULT
================================================================================
Missing GT pairs tested : 351
Recovered by translit  : 97
Pair recovery          : 27.6353%

Rows with missing GT   : 272
Rows recovered         : 85
Row recovery           : 31.2500%

S2 missing/recovered   : 156 / 39
S3 missing/recovered   : 195 / 58

SQL key queries        : 3,394
Non-empty key hits     : 2,013
Broad keys skipped     : 1,327

Top recovered examples:
  S1-419925197  ->  S3-912281874
  S1-144873536  ->  S3-685457121
  S1-688260177  ->  S3-358408242
  S1-334424523  ->  S3-193474336
  S1-983193550  ->  S2-613735485
  S1-983193550  ->  S3-85515857
  S1-428978756  ->  S3-777154795
  S1-835876484  ->  S2-347455686
  S1-879955092  ->  S2-618612678
  S1-95823999  ->  S3-783312005
  S1-909326419  ->  S2-170648753
  S1-600198874  ->  S3-139992166
  S1-24929964  ->  S3-52017215
  S1-771594183  ->  S2-557929924
  S1-286581403  ->  S3-606853813
  S1-270310232  ->  S3-300895529
  S1-82778118  ->  S2-784516603
  S1-95730121  ->  S3-762523506
  S1-95730121  ->  S3-481016814
  S1-892493102  ->  S3-807226166

Still-missing examples:
  S1-34528796  ->  S2-795540376
  S1-426723298  ->  S3-556262584
  S1-426723298  ->  S3-991847287
  S1-426723298  ->  S3-662085710
  S1-368174979  ->  S3-420879756
  S1-679221123  ->  S2-974039733
  S1-866227084  ->  S3-259645861
  S1-981078855  ->  S3-669026485
  S1-334424523  ->  S3-303574153
  S1-441138690  ->  S3-482750361
  S1-567541236  ->  S3-648073614
  S1-439875063  ->  S3-16177282
  S1-984233875  ->  S3-772997222
  S1-984233875  ->  S3-655782584
  S1-13582598  ->  S2-740411677
  S1-540232781  ->  S2-431778910
  S1-882755549  ->  S3-672375917
  S1-768345844  ->  S2-628219509
  S1-978805312  ->  S3-408360344
  S1-446695653  ->  S2-89878192

================================================================================
CELL 47 COMPLETE — READ ONLY
================================================================================

0

In [135]:
# ============================================================
# CELL 48 — FULL VALIDATION TRANSLITERATION IMPACT
# ============================================================
#
# PURPOSE
# -------
# Measure the actual cost/benefit of adding the transliteration
# blocking channel to the EXISTING validation candidate set.
#
# For all 2,000 validation S1 rows:
#
#   existing candidates
#          UNION
#   transliteration candidates
#
# Then measure:
#   1. Added unique candidates
#   2. Added candidates per S1
#   3. Total candidate count
#   4. GT pair recall
#   5. Complete-row recall
#
# IMPORTANT:
#   - READ ONLY
#   - No production index modification
#   - No auxiliary DB modification
#   - No model training
#   - GT used ONLY for evaluation
# ============================================================

import gc
import time

print("=" * 80)
print("CELL 48 — FULL VALIDATION TRANSLITERATION IMPACT")
print("=" * 80)

# ------------------------------------------------------------
# 0. State checks
# ------------------------------------------------------------

assert "aux_conn" in globals()
assert "existing_pairs_47" in globals()
assert "ground_truth" in globals()
assert "train_s1" in globals()
assert "VAL_S1_IDS_47" in globals()
assert "translit_name_keys_47" in globals()

assert len(VAL_S1_IDS_47) == 2000
assert len(existing_pairs_47) == 842159

print(
    f"Validation S1 rows       : {len(VAL_S1_IDS_47):,}"
)
print(
    f"Existing candidate pairs : {len(existing_pairs_47):,}"
)

# ------------------------------------------------------------
# 1. Recover the 2,000 validation S1 names
# ------------------------------------------------------------

s1_name_map_48 = {}

for row in train_s1:

    entity_id = str(row["entity_id"])

    if entity_id in VAL_S1_IDS_47:

        s1_name_map_48[entity_id] = (
            row.get("business_name", "")
        )

        if len(s1_name_map_48) == 2000:
            break

assert len(s1_name_map_48) == 2000, (
    f"Expected 2,000 validation S1 names, "
    f"found {len(s1_name_map_48):,}"
)

print(
    f"Validation names loaded : "
    f"{len(s1_name_map_48):,}"
)

# ------------------------------------------------------------
# 2. Existing GT statistics
# ------------------------------------------------------------

total_gt_pairs_48 = 0
rows_with_gt_48 = 0

for s1_id in VAL_S1_IDS_47:

    gt = ground_truth.get(
        s1_id,
        frozenset(),
    )

    if gt:
        rows_with_gt_48 += 1
        total_gt_pairs_48 += len(gt)

assert total_gt_pairs_48 == 6914

print(
    f"Validation GT pairs      : "
    f"{total_gt_pairs_48:,}"
)
print(
    f"Validation S1 rows w/GT  : "
    f"{rows_with_gt_48:,}"
)

# ------------------------------------------------------------
# 3. Transliteration retrieval parameters
# ------------------------------------------------------------

TRANS_CAP_48 = 1000

total_translit_candidates_48 = 0
total_added_candidates_48 = 0

rows_with_translit_48 = 0
rows_with_added_48 = 0

max_translit_per_row_48 = 0
max_added_per_row_48 = 0

rows_with_added_counts_48 = []

# Evaluation only.
existing_gt_found_48 = 0
augmented_gt_found_48 = 0

rows_existing_complete_48 = 0
rows_augmented_complete_48 = 0

t0_48 = time.time()

# ------------------------------------------------------------
# 4. Process each validation S1 independently
#
# We keep ONLY one row's transliteration candidate set
# in memory at a time.
# ------------------------------------------------------------

for counter, s1_id in enumerate(
    sorted(VAL_S1_IDS_47),
    start=1,
):

    name = s1_name_map_48[s1_id]

    keys = translit_name_keys_47(name)

    translit_candidates = set()

    for key_type, key_value in keys:

        for source in ("S2", "S3"):

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    key_type,
                    key_value,
                    source,
                    TRANS_CAP_48 + 1,
                ),
            ).fetchall()

            # Same safety rule used in Cell 47:
            # buckets > 1000 are ignored.
            if len(rows) > TRANS_CAP_48:
                continue

            for (suffix,) in rows:

                translit_candidates.add(
                    (
                        s1_id,
                        f"{source}-{suffix}",
                    )
                )

    n_translit = len(translit_candidates)

    if n_translit > 0:
        rows_with_translit_48 += 1

    total_translit_candidates_48 += n_translit

    if n_translit > max_translit_per_row_48:
        max_translit_per_row_48 = n_translit

    # Remove candidates already present in the production
    # validation candidate set.
    added_candidates = (
        translit_candidates
        - {
            pair
            for pair in existing_pairs_47
            if pair[0] == s1_id
        }
    )

    n_added = len(added_candidates)

    total_added_candidates_48 += n_added

    if n_added > 0:
        rows_with_added_48 += 1

    if n_added > max_added_per_row_48:
        max_added_per_row_48 = n_added

    rows_with_added_counts_48.append(n_added)

    # --------------------------------------------------------
    # Evaluation against GT
    # --------------------------------------------------------

    gt_set = {
        (
            s1_id,
            str(candidate_id),
        )
        for candidate_id
        in ground_truth.get(
            s1_id,
            frozenset(),
        )
    }

    existing_gt_count = len(
        gt_set & existing_pairs_47
    )

    augmented_gt_count = len(
        gt_set
        & (
            existing_pairs_47
            | translit_candidates
        )
    )

    existing_gt_found_48 += existing_gt_count
    augmented_gt_found_48 += augmented_gt_count

    if (
        existing_gt_count
        == len(gt_set)
    ):
        rows_existing_complete_48 += 1

    if (
        augmented_gt_count
        == len(gt_set)
    ):
        rows_augmented_complete_48 += 1

    if counter % 250 == 0:

        elapsed = time.time() - t0_48

        print(
            f"{counter:,}/2,000 | "
            f"translit={total_translit_candidates_48:,} | "
            f"added={total_added_candidates_48:,} | "
            f"elapsed={elapsed:.1f}s"
        )


# ------------------------------------------------------------
# 5. Final metrics
# ------------------------------------------------------------

augmented_total_candidates_48 = (
    len(existing_pairs_47)
    + total_added_candidates_48
)

existing_pair_recall_48 = (
    100.0
    * existing_gt_found_48
    / total_gt_pairs_48
)

augmented_pair_recall_48 = (
    100.0
    * augmented_gt_found_48
    / total_gt_pairs_48
)

existing_row_recall_48 = (
    100.0
    * rows_existing_complete_48
    / rows_with_gt_48
)

augmented_row_recall_48 = (
    100.0
    * rows_augmented_complete_48
    / rows_with_gt_48
)

avg_added_48 = (
    total_added_candidates_48
    / len(VAL_S1_IDS_47)
)

sorted_added_48 = sorted(
    rows_with_added_counts_48
)

median_added_48 = sorted_added_48[
    len(sorted_added_48) // 2
]


# ------------------------------------------------------------
# 6. Final report
# ------------------------------------------------------------

elapsed_total_48 = time.time() - t0_48

print()
print("=" * 80)
print("CELL 48 RESULT")
print("=" * 80)

print(
    f"Existing candidates       : "
    f"{len(existing_pairs_47):,}"
)

print(
    f"Translit candidates       : "
    f"{total_translit_candidates_48:,}"
)

print(
    f"NEW unique candidates     : "
    f"{total_added_candidates_48:,}"
)

print(
    f"Augmented candidates      : "
    f"{augmented_total_candidates_48:,}"
)

print()

print(
    f"Added candidates / S1     : "
    f"{avg_added_48:.2f}"
)

print(
    f"Median added / S1         : "
    f"{median_added_48:,}"
)

print(
    f"Max added / S1            : "
    f"{max_added_per_row_48:,}"
)

print(
    f"S1 rows receiving translit: "
    f"{rows_with_translit_48:,}"
)

print(
    f"S1 rows receiving additions:"
    f" {rows_with_added_48:,}"
)

print()

print(
    f"Existing pair recall      : "
    f"{existing_pair_recall_48:.4f}%"
)

print(
    f"Augmented pair recall     : "
    f"{augmented_pair_recall_48:.4f}%"
)

print(
    f"Pair recall gain          : "
    f"{augmented_pair_recall_48 - existing_pair_recall_48:.4f} pp"
)

print()

print(
    f"Existing complete recall  : "
    f"{existing_row_recall_48:.4f}%"
)

print(
    f"Augmented complete recall : "
    f"{augmented_row_recall_48:.4f}%"
)

print(
    f"Complete-row gain         : "
    f"{augmented_row_recall_48 - existing_row_recall_48:.4f} pp"
)

print()

print(
    f"Runtime                   : "
    f"{elapsed_total_48:.1f} sec"
)

print()
print("=" * 80)
print("CELL 48 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 48 — FULL VALIDATION TRANSLITERATION IMPACT
================================================================================
Validation S1 rows       : 2,000
Existing candidate pairs : 842,159
Validation names loaded : 2,000
Validation GT pairs      : 6,914
Validation S1 rows w/GT  : 1,900
250/2,000 | translit=211,246 | added=171,839 | elapsed=55.0s
500/2,000 | translit=433,068 | added=351,820 | elapsed=110.5s
750/2,000 | translit=617,789 | added=496,755 | elapsed=165.5s
1,000/2,000 | translit=817,370 | added=656,125 | elapsed=220.8s
1,250/2,000 | translit=1,030,620 | added=826,791 | elapsed=276.0s
1,500/2,000 | translit=1,227,857 | added=981,901 | elapsed=330.9s
1,750/2,000 | translit=1,466,367 | added=1,181,655 | elapsed=385.8s
2,000/2,000 | translit=1,701,371 | added=1,372,265 | elapsed=440.7s

================================================================================
CELL 48 RESULT
================================================================================
Existing candidates       : 842,159
Translit candidates       : 1,701,371
NEW unique candidates     : 1,372,265
Augmented candidates      : 2,214,424

Added candidates / S1     : 686.13
Median added / S1         : 371
Max added / S1            : 4,427
S1 rows receiving translit: 1,964
S1 rows receiving additions: 1,716

Existing pair recall      : 94.9233%
Augmented pair recall     : 96.3263%
Pair recall gain          : 1.4030 pp

Existing complete recall  : 90.9474%
Augmented complete recall : 94.6842%
Complete-row gain         : 3.7368 pp

Runtime                   : 440.7 sec

================================================================================
CELL 48 COMPLETE — READ ONLY
================================================================================

0

In [136]:
# ============================================================
# CELL 49 — TRANSLITERATION KEY ABLATION
# ============================================================
#
# PURPOSE
# -------
# Determine WHICH transliteration key types recover the 97
# previously missing GT pairs.
#
# We have 5 transliteration key families:
#   TNP6
#   TNP8
#   TNS6
#   TFL
#   TNORD
#
# We measure:
#   1. Unique GT pairs recovered by each key
#   2. Additional/overlapping recovery
#   3. Number of retrieved postings
#   4. Broad-key frequency
#
# This is READ ONLY.
# It does NOT:
#   - modify any SQLite DB
#   - modify s2_index / s3_index
#   - modify aux_conn
#   - train a model
#   - use test data
#
# ============================================================

from collections import defaultdict
import gc
import time

print("=" * 80)
print("CELL 49 — TRANSLITERATION KEY ABLATION")
print("=" * 80)

# ------------------------------------------------------------
# 0. Validate exact state from Cells 47–48
# ------------------------------------------------------------

assert "aux_conn" in globals()
assert "missing_gt_pairs_47" in globals()
assert "s1_name_map_47" in globals()
assert "translit_name_keys_47" in globals()

assert len(missing_gt_pairs_47) == 351
assert len(s1_name_map_47) == 272

print(
    f"Missing GT pairs under analysis : "
    f"{len(missing_gt_pairs_47):,}"
)

# ------------------------------------------------------------
# 1. Key families
# ------------------------------------------------------------

KEY_TYPES_49 = (
    "TNP6",
    "TNP8",
    "TNS6",
    "TFL",
    "TNORD",
)

TRANS_CAP_49 = 1000

# For each key type:
#
# recovered_by_key[type] =
#     GT pairs directly retrieved by that key type
#
# posting_count_by_key[type] =
#     total postings inspected for all relevant keys
#
# broad_count_by_key[type] =
#     number of key/source lookups whose bucket > 1000
#
recovered_by_key_49 = {
    k: set()
    for k in KEY_TYPES_49
}

posting_count_by_key_49 = {
    k: 0
    for k in KEY_TYPES_49
}

nonempty_lookup_by_key_49 = {
    k: 0
    for k in KEY_TYPES_49
}

broad_count_by_key_49 = {
    k: 0
    for k in KEY_TYPES_49
}

query_count_by_key_49 = {
    k: 0
    for k in KEY_TYPES_49
}

# ------------------------------------------------------------
# 2. Run exact retrieval separately for every key type
# ------------------------------------------------------------

t0_49 = time.time()

for pair_no, (s1_id, gt_candidate_id) in enumerate(
    missing_gt_pairs_47,
    start=1,
):

    name = s1_name_map_47[s1_id]

    keys = translit_name_keys_47(name)

    keys_by_type = defaultdict(list)

    for key_type, key_value in keys:

        if key_type in KEY_TYPES_49:
            keys_by_type[key_type].append(
                key_value
            )

    for key_type in KEY_TYPES_49:

        for key_value in keys_by_type.get(
            key_type,
            []
        ):

            for source in ("S2", "S3"):

                query_count_by_key_49[
                    key_type
                ] += 1

                rows = aux_conn.execute(
                    """
                    SELECT suffix
                    FROM postings
                    WHERE key_type = ?
                      AND key_value = ?
                      AND source = ?
                    LIMIT ?
                    """,
                    (
                        key_type,
                        key_value,
                        source,
                        TRANS_CAP_49 + 1,
                    ),
                ).fetchall()

                # ------------------------------------------------
                # Broad bucket
                # ------------------------------------------------

                if len(rows) > TRANS_CAP_49:

                    broad_count_by_key_49[
                        key_type
                    ] += 1

                    continue

                if not rows:
                    continue

                nonempty_lookup_by_key_49[
                    key_type
                ] += 1

                posting_count_by_key_49[
                    key_type
                ] += len(rows)

                # ------------------------------------------------
                # Check whether THIS key type recovers the
                # specific missing GT pair.
                # ------------------------------------------------

                target_id = str(
                    gt_candidate_id
                )

                for (suffix,) in rows:

                    candidate_full_id = (
                        f"{source}-{suffix}"
                    )

                    if candidate_full_id == target_id:

                        recovered_by_key_49[
                            key_type
                        ].add(
                            (
                                s1_id,
                                gt_candidate_id,
                            )
                        )

    if pair_no % 50 == 0:

        elapsed = time.time() - t0_49

        print(
            f"{pair_no:,}/351 | "
            f"elapsed={elapsed:.1f}s"
        )


# ------------------------------------------------------------
# 3. Union recovery
# ------------------------------------------------------------

union_recovered_49 = set()

for key_type in KEY_TYPES_49:

    union_recovered_49.update(
        recovered_by_key_49[key_type]
    )

assert len(union_recovered_49) <= 351

# This should agree with Cell 47's 97 recovery result.
print()
print(
    f"Union recovered by key families: "
    f"{len(union_recovered_49):,}"
)

assert len(union_recovered_49) == 97, (
    "Key-ablation union does not reproduce the "
    "97-pair Cell 47 recovery. Stop and inspect."
)


# ------------------------------------------------------------
# 4. Exclusive recovery
#
# Pairs recovered by ONLY one key family.
# ------------------------------------------------------------

exclusive_recovery_49 = {}

for key_type in KEY_TYPES_49:

    other_keys = set()

    for other_type in KEY_TYPES_49:

        if other_type != key_type:

            other_keys.update(
                recovered_by_key_49[
                    other_type
                ]
            )

    exclusive_recovery_49[key_type] = (
        recovered_by_key_49[key_type]
        - other_keys
    )


# ------------------------------------------------------------
# 5. Cumulative recovery in sensible order
#
# We sort by raw recovery first.
# This is diagnostic only — it does NOT claim a "best"
# political/evaluative ranking; it is a technical ablation.
# ------------------------------------------------------------

key_order_49 = sorted(
    KEY_TYPES_49,
    key=lambda k: len(
        recovered_by_key_49[k]
    ),
    reverse=True,
)

cumulative_49 = set()

cumulative_rows_49 = []

for key_type in key_order_49:

    before = len(cumulative_49)

    cumulative_49.update(
        recovered_by_key_49[key_type]
    )

    gain = (
        len(cumulative_49)
        - before
    )

    cumulative_rows_49.append(
        (
            key_type,
            len(
                recovered_by_key_49[
                    key_type
                ]
            ),
            len(
                exclusive_recovery_49[
                    key_type
                ]
            ),
            gain,
            len(cumulative_49),
            posting_count_by_key_49[
                key_type
            ],
            nonempty_lookup_by_key_49[
                key_type
            ],
            broad_count_by_key_49[
                key_type
            ],
            query_count_by_key_49[
                key_type
            ],
        )
    )


# ------------------------------------------------------------
# 6. Final report
# ------------------------------------------------------------

print()
print("=" * 80)
print("CELL 49 RESULT")
print("=" * 80)

print(
    "Key type | "
    "GT recovered | "
    "Exclusive | "
    "Cum. gain | "
    "Cum. recovered | "
    "Postings | "
    "Nonempty | "
    "Broad | "
    "Queries"
)

print("-" * 120)

for row in cumulative_rows_49:

    (
        key_type,
        raw_recovered,
        exclusive_recovered,
        cumulative_gain,
        cumulative_recovered,
        postings,
        nonempty,
        broad,
        queries,
    ) = row

    print(
        f"{key_type:7s} | "
        f"{raw_recovered:12,d} | "
        f"{exclusive_recovered:9,d} | "
        f"{cumulative_gain:9,d} | "
        f"{cumulative_recovered:14,d} | "
        f"{postings:8,d} | "
        f"{nonempty:8,d} | "
        f"{broad:5,d} | "
        f"{queries:7,d}"
    )

print()
print(
    f"Total missing GT pairs : 351"
)

print(
    f"Total recovered        : "
    f"{len(union_recovered_49):,}"
)

print(
    f"Recovery               : "
    f"{100.0 * len(union_recovered_49) / 351:.4f}%"
)

print()

# ------------------------------------------------------------
# 7. Identify unrecovered pairs after the strongest
#    individual key families.
# ------------------------------------------------------------

for key_type in key_order_49:

    remaining = (
        set(missing_gt_pairs_47)
        - recovered_by_key_49[key_type]
    )

    print(
        f"After {key_type}: "
        f"{len(remaining):,} GT pairs remain unrecovered"
    )

print()

elapsed_49 = time.time() - t0_49

print(
    f"Runtime: {elapsed_49:.1f} sec"
)

print()
print("=" * 80)
print("CELL 49 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 49 — TRANSLITERATION KEY ABLATION
================================================================================
Missing GT pairs under analysis : 351
50/351 | elapsed=0.2s
100/351 | elapsed=0.3s
150/351 | elapsed=0.5s
200/351 | elapsed=0.6s
250/351 | elapsed=0.8s
300/351 | elapsed=0.9s
350/351 | elapsed=1.1s

Union recovered by key families: 97

================================================================================
CELL 49 RESULT
================================================================================
Key type | GT recovered | Exclusive | Cum. gain | Cum. recovered | Postings | Nonempty | Broad | Queries
------------------------------------------------------------------------------------------------------------------------
TNORD   |           76 |        56 |        76 |             76 |  112,449 |      558 |   107 |     680
TNP6    |           16 |         8 |        10 |             86 |   83,592 |      424 |   268 |     700
TFL     |           14 |         2 |         3 |             89 |  112,681 |      371 |   245 |     630
TNS6    |           12 |         3 |         3 |             92 |   33,608 |      131 |   567 |     700
TNP8    |            9 |         5 |         5 |             97 |   58,478 |      529 |   140 |     684

Total missing GT pairs : 351
Total recovered        : 97
Recovery               : 27.6353%

After TNORD: 275 GT pairs remain unrecovered
After TNP6: 335 GT pairs remain unrecovered
After TFL: 337 GT pairs remain unrecovered
After TNS6: 339 GT pairs remain unrecovered
After TNP8: 342 GT pairs remain unrecovered

Runtime: 1.1 sec

================================================================================
CELL 49 COMPLETE — READ ONLY
================================================================================

0

In [138]:
# ============================================================
# CELL 50 — CORRECTED TNORD-ONLY VALIDATION IMPACT
# ============================================================
#
# IMPORTANT:
# The previous Cell 50 incorrectly hard-coded a historical
# complete-row recall value.
#
# This version derives the baseline directly from the
# established 351 missing GT pairs from Cell 47.
#
# READ ONLY.
# ============================================================

import time
import gc

print("=" * 80)
print("CELL 50 — CORRECTED TNORD-ONLY VALIDATION IMPACT")
print("=" * 80)

# ------------------------------------------------------------
# 0. State checks
# ------------------------------------------------------------

assert isinstance(val_candidate_pairs, list)
assert len(val_candidate_pairs) == 842159
assert len(VAL_S1_IDS_47) == 2000
assert len(missing_gt_pairs_47) == 351

# ------------------------------------------------------------
# 1. Existing candidates grouped by S1
# ------------------------------------------------------------

existing_by_s1_50 = {}

for pair in val_candidate_pairs:

    s1_id = str(pair["source1_entity_id"])
    candidate_id = str(pair["candidate_entity_id"])

    existing_by_s1_50.setdefault(
        s1_id,
        set(),
    ).add(candidate_id)

assert sum(
    len(v)
    for v in existing_by_s1_50.values()
) == 842159

# ------------------------------------------------------------
# 2. Recover validation S1 names
# ------------------------------------------------------------

s1_name_map_50 = {}

for row in train_s1:

    s1_id = str(row["entity_id"])

    if s1_id in VAL_S1_IDS_47:

        s1_name_map_50[s1_id] = (
            row.get("business_name", "")
        )

        if len(s1_name_map_50) == 2000:
            break

assert len(s1_name_map_50) == 2000

# ------------------------------------------------------------
# 3. Derive baseline directly from established facts
# ------------------------------------------------------------

rows_with_gt_50 = sum(
    1
    for s1_id in VAL_S1_IDS_47
    if ground_truth.get(
        s1_id,
        frozenset(),
    )
)

total_gt_50 = sum(
    len(
        ground_truth.get(
            s1_id,
            frozenset(),
        )
    )
    for s1_id in VAL_S1_IDS_47
)

assert rows_with_gt_50 == 1900
assert total_gt_50 == 6914

# These 272 rows are the EXACT rows established in Cell 47
# as having at least one missing GT pair.
affected_rows_50 = {
    s1_id
    for s1_id, _ in missing_gt_pairs_47
}

assert len(affected_rows_50) == 272

# Therefore these are the rows for which ALL GT pairs were
# already found by the original blocker.
baseline_complete_rows_50 = (
    rows_with_gt_50
    - len(affected_rows_50)
)

baseline_row_recall_50 = (
    100.0
    * baseline_complete_rows_50
    / rows_with_gt_50
)

# Established pair recall from Cell 47.
baseline_pair_recall_50 = (
    100.0
    * (
        total_gt_50
        - len(missing_gt_pairs_47)
    )
    / total_gt_50
)

print(
    f"Validation rows w/GT     : "
    f"{rows_with_gt_50:,}"
)

print(
    f"Validation GT pairs      : "
    f"{total_gt_50:,}"
)

print(
    f"Known missing GT pairs   : "
    f"{len(missing_gt_pairs_47):,}"
)

print(
    f"Known affected S1 rows   : "
    f"{len(affected_rows_50):,}"
)

print(
    f"Baseline pair recall     : "
    f"{baseline_pair_recall_50:.4f}%"
)

print(
    f"Baseline complete recall : "
    f"{baseline_row_recall_50:.4f}%"
)

# ------------------------------------------------------------
# 4. TNORD-only retrieval
# ------------------------------------------------------------

TNORD_CAP_50 = 1000

total_tnord_candidates_50 = 0
total_added_50 = 0

rows_with_tnord_50 = 0
rows_with_added_50 = 0

max_tnord_50 = 0
max_added_50 = 0

added_counts_50 = []

augmented_found_50 = 0
rows_augmented_complete_50 = 0

tnord_recovered_missing_50 = set()

broad_50 = 0
nonempty_50 = 0
queries_50 = 0

t0_50 = time.time()

# ------------------------------------------------------------
# 5. Full 2,000-row TNORD retrieval
# ------------------------------------------------------------

for counter, s1_id in enumerate(
    sorted(VAL_S1_IDS_47),
    start=1,
):

    name = s1_name_map_50[s1_id]

    tnord_keys = {
        key_value
        for key_type, key_value
        in translit_name_keys_47(name)
        if key_type == "TNORD"
    }

    tnord_candidates = set()

    for key_value in tnord_keys:

        for source in ("S2", "S3"):

            queries_50 += 1

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    "TNORD",
                    key_value,
                    source,
                    TNORD_CAP_50 + 1,
                ),
            ).fetchall()

            if len(rows) > TNORD_CAP_50:

                broad_50 += 1
                continue

            if not rows:
                continue

            nonempty_50 += 1

            for (suffix,) in rows:

                tnord_candidates.add(
                    f"{source}-{suffix}"
                )

    n_tnord = len(tnord_candidates)

    total_tnord_candidates_50 += n_tnord

    if n_tnord:
        rows_with_tnord_50 += 1

    max_tnord_50 = max(
        max_tnord_50,
        n_tnord,
    )

    existing_ids = existing_by_s1_50.get(
        s1_id,
        set(),
    )

    added = (
        tnord_candidates
        - existing_ids
    )

    n_added = len(added)

    total_added_50 += n_added

    if n_added:
        rows_with_added_50 += 1

    max_added_50 = max(
        max_added_50,
        n_added,
    )

    added_counts_50.append(n_added)

    # --------------------------------------------------------
    # GT evaluation
    # --------------------------------------------------------

    gt_ids = {
        str(x)
        for x in ground_truth.get(
            s1_id,
            frozenset(),
        )
    }

    if gt_ids:

        augmented_ids = (
            existing_ids
            | tnord_candidates
        )

        augmented_found = (
            gt_ids & augmented_ids
        )

        augmented_found_50 += len(
            augmented_found
        )

        # Only count genuinely NEW GT recovery.
        newly_recovered = (
            gt_ids & added
        )

        for candidate_id in newly_recovered:

            tnord_recovered_missing_50.add(
                (
                    s1_id,
                    candidate_id,
                )
            )

        if augmented_found == gt_ids:

            rows_augmented_complete_50 += 1

    if counter % 500 == 0:

        elapsed = time.time() - t0_50

        print(
            f"{counter:,}/2,000 | "
            f"TNORD={total_tnord_candidates_50:,} | "
            f"added={total_added_50:,} | "
            f"elapsed={elapsed:.1f}s"
        )

# ------------------------------------------------------------
# 6. Final metrics
# ------------------------------------------------------------

augmented_total_50 = (
    len(val_candidate_pairs)
    + total_added_50
)

augmented_pair_recall_50 = (
    100.0
    * augmented_found_50
    / total_gt_50
)

augmented_row_recall_50 = (
    100.0
    * rows_augmented_complete_50
    / rows_with_gt_50
)

pair_gain_50 = (
    augmented_pair_recall_50
    - baseline_pair_recall_50
)

row_gain_50 = (
    augmented_row_recall_50
    - baseline_row_recall_50
)

avg_added_50 = (
    total_added_50
    / 2000
)

sorted_added_50 = sorted(
    added_counts_50
)

median_added_50 = sorted_added_50[
    len(sorted_added_50) // 2
]

# ------------------------------------------------------------
# 7. Report
# ------------------------------------------------------------

print()
print("=" * 80)
print("CELL 50 RESULT")
print("=" * 80)

print(
    f"Baseline candidates       : "
    f"{len(val_candidate_pairs):,}"
)

print(
    f"TNORD candidates          : "
    f"{total_tnord_candidates_50:,}"
)

print(
    f"NEW unique candidates     : "
    f"{total_added_50:,}"
)

print(
    f"Augmented candidates      : "
    f"{augmented_total_50:,}"
)

print()

print(
    f"Added candidates / S1     : "
    f"{avg_added_50:.2f}"
)

print(
    f"Median added / S1         : "
    f"{median_added_50:,}"
)

print(
    f"Max TNORD / S1            : "
    f"{max_tnord_50:,}"
)

print(
    f"Max added / S1            : "
    f"{max_added_50:,}"
)

print()

print(
    f"S1 rows with TNORD        : "
    f"{rows_with_tnord_50:,}"
)

print(
    f"S1 rows receiving additions: "
    f"{rows_with_added_50:,}"
)

print()

print(
    f"Baseline pair recall      : "
    f"{baseline_pair_recall_50:.4f}%"
)

print(
    f"TNORD augmented recall    : "
    f"{augmented_pair_recall_50:.4f}%"
)

print(
    f"Pair recall gain          : "
    f"{pair_gain_50:.4f} pp"
)

print()

print(
    f"Baseline complete recall  : "
    f"{baseline_row_recall_50:.4f}%"
)

print(
    f"TNORD complete recall     : "
    f"{augmented_row_recall_50:.4f}%"
)

print(
    f"Complete-row gain         : "
    f"{row_gain_50:.4f} pp"
)

print()

print(
    f"GT pairs newly recovered  : "
    f"{len(tnord_recovered_missing_50):,}"
)

print(
    f"SQL queries               : "
    f"{queries_50:,}"
)

print(
    f"Non-empty lookups         : "
    f"{nonempty_50:,}"
)

print(
    f"Broad lookups skipped     : "
    f"{broad_50:,}"
)

print()

print(
    f"Runtime                   : "
    f"{time.time() - t0_50:.1f}s"
)

print()
print("=" * 80)
print("CELL 50 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 50 — CORRECTED TNORD-ONLY VALIDATION IMPACT
================================================================================
Validation rows w/GT     : 1,900
Validation GT pairs      : 6,914
Known missing GT pairs   : 351
Known affected S1 rows   : 272
Baseline pair recall     : 94.9233%
Baseline complete recall : 85.6842%
500/2,000 | TNORD=79,963 | added=66,455 | elapsed=0.2s
1,000/2,000 | TNORD=154,214 | added=129,544 | elapsed=0.4s
1,500/2,000 | TNORD=240,228 | added=203,891 | elapsed=0.6s
2,000/2,000 | TNORD=328,797 | added=278,739 | elapsed=0.8s

================================================================================
CELL 50 RESULT
================================================================================
Baseline candidates       : 842,159
TNORD candidates          : 328,797
NEW unique candidates     : 278,739
Augmented candidates      : 1,120,898

Added candidates / S1     : 139.37
Median added / S1         : 3
Max TNORD / S1            : 1,963
Max added / S1            : 1,942

S1 rows with TNORD        : 1,703
S1 rows receiving additions: 1,182

Baseline pair recall      : 94.9233%
TNORD augmented recall    : 96.0226%
Pair recall gain          : 1.0992 pp

Baseline complete recall  : 85.6842%
TNORD complete recall     : 88.4211%
Complete-row gain         : 2.7368 pp

GT pairs newly recovered  : 76
SQL queries               : 3,876
Non-empty lookups         : 3,187
Broad lookups skipped     : 466

Runtime                   : 0.8s

================================================================================
CELL 50 COMPLETE — READ ONLY
================================================================================

2431

In [139]:
# ============================================================
# CELL 51 — AUXILIARY DB SCHEMA CHECK
# ============================================================
#
# READ ONLY.
# We only inspect the existing auxiliary SQLite schema.
# No tables, indexes, files, or connections are modified.
# ============================================================

print("=" * 80)
print("CELL 51 — AUXILIARY DB SCHEMA CHECK")
print("=" * 80)

assert aux_conn is not None

tables_51 = aux_conn.execute(
    """
    SELECT name, type
    FROM sqlite_master
    WHERE type IN ('table', 'index')
    ORDER BY type, name
    """
).fetchall()

print("\nObjects:")
for name, obj_type in tables_51:
    print(f"  {obj_type:6s} : {name}")

print("\nTable schemas:")

table_names_51 = [
    name
    for name, obj_type in tables_51
    if obj_type == "table"
]

for table_name in table_names_51:

    print(f"\n--- {table_name} ---")

    schema_row = aux_conn.execute(
        """
        SELECT sql
        FROM sqlite_master
        WHERE type = 'table'
          AND name = ?
        """,
        (table_name,),
    ).fetchone()

    print(schema_row[0] if schema_row else "NO SCHEMA")

print("\nSample rows from postings:")

try:
    sample_51 = aux_conn.execute(
        """
        SELECT *
        FROM postings
        LIMIT 3
        """
    ).fetchall()

    for row in sample_51:
        print(row)

except Exception as e:
    print("postings sample failed:", repr(e))

print("\n" + "=" * 80)
print("CELL 51 COMPLETE — READ ONLY")
print("=" * 80)

================================================================================
CELL 51 — AUXILIARY DB SCHEMA CHECK
================================================================================

Objects:
  table  : postings
  table  : sqlite_stat1

Table schemas:

--- postings ---
CREATE TABLE postings (
        key_type TEXT NOT NULL,
        key_value TEXT NOT NULL,
        source TEXT NOT NULL,
        suffix TEXT NOT NULL,
        PRIMARY KEY (
            key_type,
            key_value,
            source,
            suffix
        )
    ) WITHOUT ROWID


--- sqlite_stat1 ---
CREATE TABLE sqlite_stat1(tbl,idx,stat)

Sample rows from postings:
('TFL', '007a|com', 'S2', '483155324')
('TFL', '007b|com', 'S2', '94630396')
('TFL', '007c|com', 'S2', '372406164')

================================================================================
CELL 51 COMPLETE — READ ONLY
================================================================================

In [140]:
# ============================================================
# CELL 52 — BUILD VERIFIED TNORD-AUGMENTED VALIDATION CANDIDATES
# ============================================================
#
# READ ONLY.
#
# Builds:
#   val_candidate_pairs_tnord_52
#
# from the existing validation candidates plus TNORD candidates.
#
# No production index or auxiliary DB is modified.
# ============================================================

import time
import gc

print("=" * 80)
print("CELL 52 — BUILD VERIFIED TNORD-AUGMENTED VALIDATION CANDIDATES")
print("=" * 80)

t0_52 = time.time()

# ------------------------------------------------------------
# 0. Hard state checks
# ------------------------------------------------------------

assert isinstance(val_candidate_pairs, list)
assert len(val_candidate_pairs) == 842159

assert len(VAL_S1_IDS_47) == 2000
assert len(missing_gt_pairs_47) == 351

assert aux_conn is not None
assert s2_conn is not None

# s3_conn may or may not exist under that exact variable name.
assert "s3_conn" in globals(), (
    "s3_conn is not present in kernel state. "
    "Do not continue until the existing S3 connection is identified."
)

assert s3_conn is not None

# ------------------------------------------------------------
# 1. Existing candidates
# ------------------------------------------------------------

existing_pair_keys_52 = set()

for pair in val_candidate_pairs:

    existing_pair_keys_52.add(
        (
            str(pair["source1_entity_id"]),
            str(pair["candidate_entity_id"]),
        )
    )

assert len(existing_pair_keys_52) == 842159

# ------------------------------------------------------------
# 2. Validation S1 names
# ------------------------------------------------------------

s1_name_map_52 = {}

for row in train_s1:

    s1_id = str(row["entity_id"])

    if s1_id in VAL_S1_IDS_47:

        s1_name_map_52[s1_id] = (
            row.get("business_name", "")
        )

        if len(s1_name_map_52) == 2000:
            break

assert len(s1_name_map_52) == 2000

# ------------------------------------------------------------
# 3. Helper: resolve production-index attributes
#
# Candidate IDs are S2-<suffix> / S3-<suffix>.
# Production get_attrs() expects only the suffix.
# ------------------------------------------------------------

def resolve_candidate_attrs_52(candidate_id):

    candidate_id = str(candidate_id)

    if candidate_id.startswith("S2-"):

        suffix = candidate_id[3:]

        attrs = s2_conn.execute(
            """
            SELECT name, address, country
            FROM attrs
            WHERE suffix = ?
            """,
            (suffix,),
        ).fetchone()

    elif candidate_id.startswith("S3-"):

        suffix = candidate_id[3:]

        attrs = s3_conn.execute(
            """
            SELECT name, address, country
            FROM attrs
            WHERE suffix = ?
            """,
            (suffix,),
        ).fetchone()

    else:
        raise ValueError(
            f"Unexpected candidate ID: {candidate_id}"
        )

    return attrs

# ------------------------------------------------------------
# 4. Generate TNORD additions
# ------------------------------------------------------------

TNORD_CAP_52 = 1000

tnord_pairs_52 = set()

queries_52 = 0
nonempty_52 = 0
broad_52 = 0

rows_with_tnord_52 = 0
rows_with_new_52 = 0

added_counts_52 = []

for counter, s1_id in enumerate(
    sorted(VAL_S1_IDS_47),
    start=1,
):

    name = s1_name_map_52[s1_id]

    tnord_keys = {
        key_value
        for key_type, key_value
        in translit_name_keys_47(name)
        if key_type == "TNORD"
    }

    row_tnord = set()

    for key_value in tnord_keys:

        for source in ("S2", "S3"):

            queries_52 += 1

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    "TNORD",
                    key_value,
                    source,
                    TNORD_CAP_52 + 1,
                ),
            ).fetchall()

            if len(rows) > TNORD_CAP_52:
                broad_52 += 1
                continue

            if not rows:
                continue

            nonempty_52 += 1

            for (suffix,) in rows:

                candidate_id = (
                    f"{source}-{suffix}"
                )

                row_tnord.add(
                    (
                        s1_id,
                        candidate_id,
                    )
                )

    if row_tnord:
        rows_with_tnord_52 += 1

    new_row = (
        row_tnord
        - {
            pair
            for pair in existing_pair_keys_52
            if pair[0] == s1_id
        }
    )

    if new_row:
        rows_with_new_52 += 1

    added_counts_52.append(
        len(new_row)
    )

    tnord_pairs_52.update(row_tnord)

    if counter % 500 == 0:
        print(
            f"{counter:,}/2,000 | "
            f"TNORD pairs={len(tnord_pairs_52):,}"
        )

# ------------------------------------------------------------
# 5. Verify TNORD addition count
# ------------------------------------------------------------

new_tnord_pairs_52 = (
    tnord_pairs_52
    - existing_pair_keys_52
)

assert len(new_tnord_pairs_52) == 278739

# ------------------------------------------------------------
# 6. Verify candidate attributes
# ------------------------------------------------------------

missing_attrs_52 = []
resolved_s2_52 = 0
resolved_s3_52 = 0

for i, (s1_id, candidate_id) in enumerate(
    new_tnord_pairs_52,
    start=1,
):

    attrs = resolve_candidate_attrs_52(
        candidate_id
    )

    if attrs is None:

        missing_attrs_52.append(
            (
                s1_id,
                candidate_id,
            )
        )

        if len(missing_attrs_52) >= 20:
            break

    else:

        if candidate_id.startswith("S2-"):
            resolved_s2_52 += 1
        else:
            resolved_s3_52 += 1

assert not missing_attrs_52, (
    "Could not resolve candidate attributes. "
    f"Examples: {missing_attrs_52[:5]}"
)

# ------------------------------------------------------------
# 7. Final augmented candidate list
# ------------------------------------------------------------

val_candidate_pairs_tnord_52 = list(
    val_candidate_pairs
)

for s1_id, candidate_id in sorted(
    new_tnord_pairs_52
):

    source = (
        "S2"
        if candidate_id.startswith("S2-")
        else "S3"
    )

    val_candidate_pairs_tnord_52.append(
        {
            "source1_entity_id": s1_id,
            "candidate_entity_id": candidate_id,
            "source": source,
            "key_types": ("TNORD",),
            "min_freq": None,
        }
    )

# ------------------------------------------------------------
# 8. Integrity checks
# ------------------------------------------------------------

assert len(
    val_candidate_pairs_tnord_52
) == 1120898

pair_keys_final_52 = {
    (
        str(p["source1_entity_id"]),
        str(p["candidate_entity_id"]),
    )
    for p in val_candidate_pairs_tnord_52
}

assert len(pair_keys_final_52) == 1120898

assert (
    pair_keys_final_52
    == (
        existing_pair_keys_52
        | new_tnord_pairs_52
    )
)

# Every original candidate remains present.
assert existing_pair_keys_52.issubset(
    pair_keys_final_52
)

# ------------------------------------------------------------
# 9. Report
# ------------------------------------------------------------

print()
print("=" * 80)
print("CELL 52 RESULT")
print("=" * 80)

print(
    f"Original candidates       : "
    f"{len(val_candidate_pairs):,}"
)

print(
    f"TNORD candidates          : "
    f"{len(tnord_pairs_52):,}"
)

print(
    f"NEW TNORD candidates      : "
    f"{len(new_tnord_pairs_52):,}"
)

print(
    f"Augmented candidates      : "
    f"{len(val_candidate_pairs_tnord_52):,}"
)

print()

print(
    f"S2 new candidates         : "
    f"{resolved_s2_52:,}"
)

print(
    f"S3 new candidates         : "
    f"{resolved_s3_52:,}"
)

print(
    f"Rows with TNORD           : "
    f"{rows_with_tnord_52:,}"
)

print(
    f"Rows receiving additions  : "
    f"{rows_with_new_52:,}"
)

print()

print(
    f"SQL queries               : "
    f"{queries_52:,}"
)

print(
    f"Non-empty lookups         : "
    f"{nonempty_52:,}"
)

print(
    f"Broad lookups skipped     : "
    f"{broad_52:,}"
)

print()

print(
    f"Runtime                   : "
    f"{time.time() - t0_52:.2f}s"
)

print()
print("=" * 80)
print("CELL 52 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 52 — BUILD VERIFIED TNORD-AUGMENTED VALIDATION CANDIDATES
================================================================================

AssertionError: s3_conn is not present in kernel state. Do not continue until the existing S3 connection is identified.

In [141]:
# ============================================================
# CELL 52 — IDENTIFY EXISTING SQLITE CONNECTIONS
# ============================================================
#
# READ ONLY.
# Does NOT open, close, modify, or checkpoint any database.
# ============================================================

print("=" * 80)
print("CELL 52 — EXISTING SQLITE CONNECTIONS")
print("=" * 80)

import sqlite3

conn_candidates_52 = []

for name, obj in globals().items():

    try:
        if isinstance(obj, sqlite3.Connection):
            conn_candidates_52.append(
                (name, obj)
            )
    except Exception:
        pass

print(
    f"\nSQLite connection objects found: "
    f"{len(conn_candidates_52)}"
)

for name, conn in sorted(conn_candidates_52):

    print(f"\n--- {name} ---")

    try:
        row = conn.execute(
            "PRAGMA database_list"
        ).fetchall()

        print("database_list:")
        for item in row:
            print(" ", item)

    except Exception as e:
        print(
            "database_list failed:",
            repr(e)
        )

print("\n" + "=" * 80)
print("CELL 52 COMPLETE — NO DATABASES MODIFIED")
print("=" * 80)

================================================================================
CELL 52 — EXISTING SQLITE CONNECTIONS
================================================================================

SQLite connection objects found: 4

--- aux_conn ---
database_list:
  (0, 'main', '/kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite')

--- con ---
database_list failed: ProgrammingError('Cannot operate on a closed database.')

--- conn ---
database_list failed: ProgrammingError('Cannot operate on a closed database.')

--- s2_conn ---
database_list:
  (0, 'main', '/kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite')

================================================================================
CELL 52 COMPLETE — NO DATABASES MODIFIED
================================================================================

In [142]:
# ============================================================
# CELL 53 — VERIFY S3 INDEX FILESYSTEM STATE
# ============================================================
#
# READ ONLY.
# Does NOT open the S3 database.
# Does NOT create a missing SQLite file.
# Does NOT modify/delete anything.
# ============================================================

import os
import glob
import shutil

print("=" * 80)
print("CELL 53 — S3 INDEX FILESYSTEM STATE")
print("=" * 80)

s3_path_53 = (
    "/kaggle/working/amazon_ml_solution/"
    "index_train/s3_full.sqlite"
)

print("\nTarget:")
print(s3_path_53)

print("\nFiles:")

for path in sorted(
    glob.glob(
        "/kaggle/working/amazon_ml_solution/"
        "index_train/s3_full.sqlite*"
    )
):

    size_gb = os.path.getsize(path) / (1024**3)

    print(
        f"  {os.path.basename(path):25s}"
        f" {size_gb:.6f} GiB"
        f"  exists={os.path.exists(path)}"
    )

print("\nDirectory listing:")

index_dir_53 = (
    "/kaggle/working/amazon_ml_solution/index_train"
)

for name in sorted(os.listdir(index_dir_53)):

    if "s3" in name.lower():

        path = os.path.join(
            index_dir_53,
            name,
        )

        print(
            f"  {name:35s}"
            f" {os.path.getsize(path)/(1024**3):.6f} GiB"
        )

print("\nDisk:")
usage_53 = shutil.disk_usage(
    "/kaggle/working"
)

print(
    f"  Total : {usage_53.total/(1024**3):.2f} GiB"
)

print(
    f"  Used  : {usage_53.used/(1024**3):.2f} GiB"
)

print(
    f"  Free  : {usage_53.free/(1024**3):.2f} GiB"
)

print("\n" + "=" * 80)
print("CELL 53 COMPLETE — READ ONLY")
print("=" * 80)

================================================================================
CELL 53 — S3 INDEX FILESYSTEM STATE
================================================================================

Target:
/kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite

Files:
  s3_full.sqlite            6.545879 GiB  exists=True
  s3_full.sqlite-shm        0.005035 GiB  exists=True
  s3_full.sqlite-wal        2.585546 GiB  exists=True
  s3_full.sqlite.manifest.json 0.000000 GiB  exists=True

Directory listing:
  s3_full.sqlite                      6.545879 GiB
  s3_full.sqlite-shm                  0.005035 GiB
  s3_full.sqlite-wal                  2.585546 GiB
  s3_full.sqlite.manifest.json        0.000000 GiB

Disk:
  Total : 19.52 GiB
  Used  : 19.03 GiB
  Free  : 0.47 GiB

================================================================================
CELL 53 COMPLETE — READ ONLY
================================================================================

In [144]:
# ============================================================
# CELL 54 — CORRECTED SELF-CONTAINED TNORD + S3 VERIFICATION
# ============================================================
#
# READ ONLY.
#
# This cell does NOT depend on Cell 52 having succeeded.
# It reconstructs the TNORD candidate set directly.
#
# It does NOT:
#   - modify any SQLite DB
#   - checkpoint WAL
#   - create files
#   - close aux_conn
#   - close s2_conn
# ============================================================

import sqlite3
import time
import gc

print("=" * 80)
print("CELL 54 — CORRECTED SELF-CONTAINED TNORD + S3 VERIFICATION")
print("=" * 80)

t0_54 = time.time()

# ------------------------------------------------------------
# 1. Verify only state that actually exists
# ------------------------------------------------------------

assert isinstance(val_candidate_pairs, list)
assert len(val_candidate_pairs) == 842159

assert len(VAL_S1_IDS_47) == 2000
assert len(missing_gt_pairs_47) == 351

assert aux_conn is not None
assert s2_conn is not None

print("Existing validation candidates :", len(val_candidate_pairs))
print("Validation S1 rows             :", len(VAL_S1_IDS_47))
print("Known missing GT pairs         :", len(missing_gt_pairs_47))

# ------------------------------------------------------------
# 2. Existing pair keys
# ------------------------------------------------------------

existing_pair_keys_54 = {
    (
        str(p["source1_entity_id"]),
        str(p["candidate_entity_id"]),
    )
    for p in val_candidate_pairs
}

assert len(existing_pair_keys_54) == 842159

# ------------------------------------------------------------
# 3. Load validation S1 names
# ------------------------------------------------------------

s1_name_map_54 = {}

for row in train_s1:

    s1_id = str(row["entity_id"])

    if s1_id in VAL_S1_IDS_47:

        s1_name_map_54[s1_id] = (
            row.get("business_name", "")
        )

        if len(s1_name_map_54) == 2000:
            break

assert len(s1_name_map_54) == 2000

# ------------------------------------------------------------
# 4. Reconstruct TNORD candidates
# ------------------------------------------------------------

TNORD_CAP_54 = 1000

tnord_pairs_54 = set()

queries_54 = 0
nonempty_54 = 0
broad_54 = 0

rows_with_tnord_54 = 0
rows_with_new_54 = 0

for counter, s1_id in enumerate(
    sorted(VAL_S1_IDS_47),
    start=1,
):

    name = s1_name_map_54[s1_id]

    tnord_keys = {
        key_value
        for key_type, key_value
        in translit_name_keys_47(name)
        if key_type == "TNORD"
    }

    row_tnord = set()

    for key_value in tnord_keys:

        for source in ("S2", "S3"):

            queries_54 += 1

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    "TNORD",
                    key_value,
                    source,
                    TNORD_CAP_54 + 1,
                ),
            ).fetchall()

            if len(rows) > TNORD_CAP_54:
                broad_54 += 1
                continue

            if not rows:
                continue

            nonempty_54 += 1

            for (suffix,) in rows:

                row_tnord.add(
                    (
                        s1_id,
                        f"{source}-{suffix}",
                    )
                )

    if row_tnord:
        rows_with_tnord_54 += 1

    new_row = (
        row_tnord
        - existing_pair_keys_54
    )

    if new_row:
        rows_with_new_54 += 1

    tnord_pairs_54.update(row_tnord)

# ------------------------------------------------------------
# 5. Compute genuinely new candidates
# ------------------------------------------------------------

new_tnord_pairs_54 = (
    tnord_pairs_54
    - existing_pair_keys_54
)

print()
print("TNORD reconstruction complete.")

print(
    "TNORD candidate pairs        : "
    f"{len(tnord_pairs_54):,}"
)

print(
    "NEW TNORD candidate pairs    : "
    f"{len(new_tnord_pairs_54):,}"
)

# Cell 50 established this exact number.
assert len(tnord_pairs_54) == 328797
assert len(new_tnord_pairs_54) == 278739

# ------------------------------------------------------------
# 6. Open S3 WITHOUT allowing SQLite writes
# ------------------------------------------------------------

s3_path_54 = (
    "/kaggle/working/amazon_ml_solution/"
    "index_train/s3_full.sqlite"
)

s3_ro_54 = sqlite3.connect(
    "file:" + s3_path_54 + "?mode=ro&immutable=1",
    uri=True,
)

print("\nS3 immutable read-only connection: OPEN")

# ------------------------------------------------------------
# 7. Verify attrs table
# ------------------------------------------------------------

attrs_table_54 = s3_ro_54.execute(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
      AND name = 'attrs'
    """
).fetchone()

assert attrs_table_54 is not None

print("S3 attrs table: VERIFIED")

# ------------------------------------------------------------
# 8. Verify up to 1000 new TNORD candidates
# ------------------------------------------------------------

sample_54 = list(new_tnord_pairs_54)[:1000]

resolved_s2_54 = 0
resolved_s3_54 = 0
missing_54 = []

for s1_id, candidate_id in sample_54:

    suffix = candidate_id[3:]

    if candidate_id.startswith("S2-"):

        attrs = s2_conn.execute(
            """
            SELECT name, address, country
            FROM attrs
            WHERE suffix = ?
            """,
            (suffix,),
        ).fetchone()

        if attrs is None:
            missing_54.append(
                (s1_id, candidate_id)
            )
        else:
            resolved_s2_54 += 1

    elif candidate_id.startswith("S3-"):

        attrs = s3_ro_54.execute(
            """
            SELECT name, address, country
            FROM attrs
            WHERE suffix = ?
            """,
            (suffix,),
        ).fetchone()

        if attrs is None:
            missing_54.append(
                (s1_id, candidate_id)
            )
        else:
            resolved_s3_54 += 1

    else:

        missing_54.append(
            (s1_id, candidate_id)
        )

assert not missing_54

# ------------------------------------------------------------
# 9. Close ONLY temporary immutable S3 reader
# ------------------------------------------------------------

s3_ro_54.close()

# ------------------------------------------------------------
# 10. Report
# ------------------------------------------------------------

print()
print("=" * 80)
print("CELL 54 RESULT")
print("=" * 80)

print(
    f"TNORD pairs               : "
    f"{len(tnord_pairs_54):,}"
)

print(
    f"NEW TNORD pairs           : "
    f"{len(new_tnord_pairs_54):,}"
)

print(
    f"Sample attributes checked  : "
    f"{len(sample_54):,}"
)

print(
    f"S2 attributes resolved     : "
    f"{resolved_s2_54:,}"
)

print(
    f"S3 attributes resolved     : "
    f"{resolved_s3_54:,}"
)

print(
    f"Attribute failures         : "
    f"{len(missing_54):,}"
)

print(
    f"SQL queries                : "
    f"{queries_54:,}"
)

print(
    f"Non-empty lookups          : "
    f"{nonempty_54:,}"
)

print(
    f"Broad lookups skipped      : "
    f"{broad_54:,}"
)

print(
    f"Rows with TNORD            : "
    f"{rows_with_tnord_54:,}"
)

print(
    f"Rows receiving additions   : "
    f"{rows_with_new_54:,}"
)

print(
    f"Runtime                    : "
    f"{time.time() - t0_54:.2f}s"
)

print()
print("=" * 80)
print("CELL 54 COMPLETE — READ ONLY")
print("=" * 80)

gc.collect()

================================================================================
CELL 54 — CORRECTED SELF-CONTAINED TNORD + S3 VERIFICATION
================================================================================
Existing validation candidates : 842159
Validation S1 rows             : 2000
Known missing GT pairs         : 351

TNORD reconstruction complete.
TNORD candidate pairs        : 328,797
NEW TNORD candidate pairs    : 278,739

S3 immutable read-only connection: OPEN
S3 attrs table: VERIFIED

================================================================================
CELL 54 RESULT
================================================================================
TNORD pairs               : 328,797
NEW TNORD pairs           : 278,739
Sample attributes checked  : 1,000
S2 attributes resolved     : 530
S3 attributes resolved     : 470
Attribute failures         : 0
SQL queries                : 3,876
Non-empty lookups          : 3,187
Broad lookups skipped      : 466
Rows with TNORD            : 1,703
Rows receiving additions   : 1,182
Runtime                    : 2.23s

================================================================================
CELL 54 COMPLETE — READ ONLY
================================================================================

2295

In [145]:
# ============================================================
# CELL 55 — VALIDATION / MODEL STATE INSPECTION
# ============================================================
#
# READ ONLY.
# No database access.
# No feature extraction.
# No model training.
# No files modified.
# ============================================================

print("=" * 80)
print("CELL 55 — VALIDATION / MODEL STATE INSPECTION")
print("=" * 80)

# ------------------------------------------------------------
# 1. Models
# ------------------------------------------------------------

print("\nMODEL OBJECTS:")

for name in sorted(globals()):

    if (
        "model" in name.lower()
        or "lgb" in name.lower()
        or "booster" in name.lower()
    ):

        obj = globals()[name]

        try:
            shape = getattr(obj, "shape", None)
            cls = type(obj).__name__

            if shape is not None:
                print(
                    f"  {name:35s} "
                    f"type={cls:25s} "
                    f"shape={shape}"
                )
            else:
                print(
                    f"  {name:35s} "
                    f"type={cls}"
                )

        except Exception:
            pass

# ------------------------------------------------------------
# 2. Validation dataframes / arrays
# ------------------------------------------------------------

print("\nVALIDATION / FEATURE OBJECTS:")

for name in sorted(globals()):

    lname = name.lower()

    if any(
        token in lname
        for token in [
            "val",
            "feature",
            "prediction",
            "prob",
        ]
    ):

        obj = globals()[name]

        try:
            shape = getattr(obj, "shape", None)
            cls = type(obj).__name__

            if shape is not None:

                print(
                    f"  {name:35s} "
                    f"type={cls:25s} "
                    f"shape={shape}"
                )

            elif cls in {
                "list",
                "dict",
                "set",
                "ndarray",
            }:

                print(
                    f"  {name:35s} "
                    f"type={cls:25s} "
                    f"len={len(obj):,}"
                )

        except Exception:
            pass

# ------------------------------------------------------------
# 3. Feature column definitions
# ------------------------------------------------------------

print("\nFEATURE DEFINITIONS:")

for name in sorted(globals()):

    lname = name.lower()

    if (
        "feature" in lname
        and (
            "column" in lname
            or "cols" in lname
            or "names" in lname
        )
    ):

        obj = globals()[name]

        try:
            print(
                f"  {name}: "
                f"type={type(obj).__name__}, "
                f"len={len(obj):,}"
            )

            if len(obj) <= 40:
                print("   ", list(obj))

        except Exception:
            pass

print()
print("=" * 80)
print("CELL 55 COMPLETE — READ ONLY")
print("=" * 80)

================================================================================
CELL 55 — VALIDATION / MODEL STATE INSPECTION
================================================================================

MODEL OBJECTS:
  booster                             type=Booster
  lgb                                 type=module
  model                               type=LGBMClassifier
  model_expanded                      type=LGBMClassifier
  model_expanded_72                   type=LGBMClassifier
  model_features                      type=list
  model_loss                          type=int64                     shape=()

VALIDATION / FEATURE OBJECTS:
  BASE_FEATURES                       type=list                      len=26
  FEATURE_ROWS                        type=list                      len=424,879
  VAL_S1_IDS_47                       type=set                       len=2,000
  X_val_recovered                     type=DataFrame                 shape=(842159, 26)
  all_val_s1_ids                      type=list                      len=2,000
  expanded_feature_df                 type=DataFrame                 shape=(2110212, 30)
  expanded_feature_rows               type=list                      len=2,110,212
  feature_cols                        type=list                      len=29
  feature_df                          type=DataFrame                 shape=(424879, 27)
  features                            type=dict                      len=27
  ground_truth_val                    type=dict                      len=2,206,821
  ground_truth_val_correct            type=dict                      len=2,000
  gt_val                              type=dict                      len=2,000
  hold_prob                           type=ndarray                   shape=(84976,)
  hold_prob_expanded                  type=ndarray                   shape=(422043,)
  missing_validation_ids              type=set                       len=0
  model_features                      type=list                      len=26
  s1_lookup_val                       type=dict                      len=2,000
  val_X                               type=DataFrame                 shape=(842159, 26)
  val_X_expanded                      type=DataFrame                 shape=(842159, 26)
  val_candidate_pairs                 type=list                      len=842,159
  val_eval                            type=DataFrame                 shape=(842159, 3)
  val_feature_df                      type=DataFrame                 shape=(842159, 32)
  val_feature_rows                    type=list                      len=842,159
  val_groups                          type=dict                      len=2,000
  val_groups_72                       type=dict                      len=2,000
  val_groups_expanded                 type=dict                      len=2,000
  val_ids                             type=set                       len=2,000
  val_indices                         type=list                      len=441,364
  val_pilot_indices                   type=ndarray                   shape=(2000,)
  val_s1_ids                          type=set                       len=2,000
  val_s1_rows                         type=list                      len=2,000

FEATURE DEFINITIONS:
  feature_cols: type=list, len=29
    ['name_exact_match', 'name_char_similarity', 'name_levenshtein_similarity', 'name_token_jaccard', 'name_token_overlap', 'name_compact_similarity', 'name_prefix_similarity', 'name_suffix_similarity', 'name_char_ngram_jaccard', 'address_exact_match', 'address_char_similarity', 'address_levenshtein_similarity', 'address_token_jaccard', 'address_token_overlap', 'address_number_match', 'address_char_ngram_jaccard', 'country_match', 'name_missing', 'address_missing', 'combined_name_address_score', 'name_is_non_latin', 'address_is_non_latin', 'name_char_similarity_unicode', 'name_token_jaccard_unicode', 'blocking_num_keys', 'blocking_min_freq', 'score', 'score_expanded', 'score_expanded_72']

================================================================================
CELL 55 COMPLETE — READ ONLY
================================================================================

In [146]:
# ============================================================
# CELL 56 — TNORD ADDITIONS -> EXISTING MODEL -> F0.5
# ============================================================
#
# PURPOSE:
#   Score ONLY the 278,739 genuinely new TNORD candidates
#   with the EXISTING baseline model.
#
# NO MODEL TRAINING.
# NO DATABASE WRITES.
# NO INDEX MODIFICATION.
#
# Then combine their predictions with the ORIGINAL validation
# predictions and recompute S1-level macro F0.5.
# ============================================================

import sqlite3
import time
import gc
import numpy as np
import pandas as pd

from sklearn.metrics import precision_score, recall_score

print("=" * 80)
print("CELL 56 — TNORD MODEL IMPACT / F0.5")
print("=" * 80)

t0_56 = time.time()

# ------------------------------------------------------------
# 0. Verify required state
# ------------------------------------------------------------

assert isinstance(val_candidate_pairs, list)
assert len(val_candidate_pairs) == 842159

assert isinstance(val_feature_df, pd.DataFrame)
assert len(val_feature_df) == 842159

assert isinstance(model, object)
assert len(model_features) == 26

assert len(VAL_S1_IDS_47) == 2000
assert len(missing_gt_pairs_47) == 351

assert "calculate_features" in globals()
assert "translit_name_keys_47" in globals()

assert aux_conn is not None
assert s2_conn is not None

print("Original validation pairs :", f"{len(val_candidate_pairs):,}")
print("Original feature rows     :", f"{len(val_feature_df):,}")
print("Model features            :", len(model_features))

# ------------------------------------------------------------
# 1. Reconstruct existing candidate keys
# ------------------------------------------------------------

existing_pair_keys_56 = {
    (
        str(p["source1_entity_id"]),
        str(p["candidate_entity_id"]),
    )
    for p in val_candidate_pairs
}

assert len(existing_pair_keys_56) == 842159

# ------------------------------------------------------------
# 2. Load validation S1 attributes
# ------------------------------------------------------------

s1_attr_56 = {}

for row in train_s1:

    s1_id = str(row["entity_id"])

    if s1_id in VAL_S1_IDS_47:

        s1_attr_56[s1_id] = (
            str(row.get("business_name", "") or ""),
            str(row.get("business_address", "") or ""),
            str(row.get("country", "") or ""),
        )

        if len(s1_attr_56) == 2000:
            break

assert len(s1_attr_56) == 2000

# ------------------------------------------------------------
# 3. Reconstruct TNORD candidates AND their key frequencies
# ------------------------------------------------------------

TNORD_CAP_56 = 1000

tnord_candidate_meta_56 = {}
tnord_key_freq_cache_56 = {}

queries_56 = 0
broad_56 = 0
nonempty_56 = 0

for counter, s1_id in enumerate(
    sorted(VAL_S1_IDS_47),
    start=1,
):

    name = s1_attr_56[s1_id][0]

    tnord_keys = {
        key_value
        for key_type, key_value
        in translit_name_keys_47(name)
        if key_type == "TNORD"
    }

    for key_value in tnord_keys:

        for source in ("S2", "S3"):

            queries_56 += 1

            # ------------------------------------------------
            # Get posting count first.
            # This is the actual frequency of the TNORD key.
            # ------------------------------------------------

            count_key = (
                source,
                key_value,
            )

            if count_key not in tnord_key_freq_cache_56:

                freq_row = aux_conn.execute(
                    """
                    SELECT COUNT(*)
                    FROM postings
                    WHERE key_type = ?
                      AND key_value = ?
                      AND source = ?
                    """,
                    (
                        "TNORD",
                        key_value,
                        source,
                    ),
                ).fetchone()

                tnord_key_freq_cache_56[
                    count_key
                ] = int(freq_row[0])

            key_freq = tnord_key_freq_cache_56[
                count_key
            ]

            # Same safety rule used in Cell 50.
            if key_freq > TNORD_CAP_56:
                broad_56 += 1
                continue

            rows = aux_conn.execute(
                """
                SELECT suffix
                FROM postings
                WHERE key_type = ?
                  AND key_value = ?
                  AND source = ?
                LIMIT ?
                """,
                (
                    "TNORD",
                    key_value,
                    source,
                    TNORD_CAP_56 + 1,
                ),
            ).fetchall()

            if not rows:
                continue

            nonempty_56 += 1

            for (suffix,) in rows:

                candidate_id = (
                    f"{source}-{suffix}"
                )

                pair_key = (
                    s1_id,
                    candidate_id,
                )

                # We only care about genuinely new candidates.
                if pair_key in existing_pair_keys_56:
                    continue

                if pair_key not in tnord_candidate_meta_56:

                    tnord_candidate_meta_56[
                        pair_key
                    ] = {
                        "num_keys": 1,
                        "min_freq": key_freq,
                    }

                else:

                    meta = tnord_candidate_meta_56[
                        pair_key
                    ]

                    meta["num_keys"] += 1

                    meta["min_freq"] = min(
                        meta["min_freq"],
                        key_freq,
                    )

    if counter % 500 == 0:

        print(
            f"{counter:,}/2,000 | "
            f"new candidates="
            f"{len(tnord_candidate_meta_56):,}"
        )

# ------------------------------------------------------------
# 4. Hard count verification
# ------------------------------------------------------------

assert len(tnord_candidate_meta_56) == 278739

print()
print(
    "Verified NEW TNORD candidates : "
    f"{len(tnord_candidate_meta_56):,}"
)

print(
    "TNORD key frequencies cached   : "
    f"{len(tnord_key_freq_cache_56):,}"
)

# ------------------------------------------------------------
# 5. Open S3 immutable reader
# ------------------------------------------------------------

s3_path_56 = (
    "/kaggle/working/amazon_ml_solution/"
    "index_train/s3_full.sqlite"
)

s3_ro_56 = sqlite3.connect(
    "file:" + s3_path_56 + "?mode=ro&immutable=1",
    uri=True,
)

# ------------------------------------------------------------
# 6. Collect unique candidate attributes efficiently
# ------------------------------------------------------------

needed_s2_56 = {
    candidate_id[3:]
    for (_, candidate_id) in tnord_candidate_meta_56
    if candidate_id.startswith("S2-")
}

needed_s3_56 = {
    candidate_id[3:]
    for (_, candidate_id) in tnord_candidate_meta_56
    if candidate_id.startswith("S3-")
}

print(
    "Unique S2 candidates        : "
    f"{len(needed_s2_56):,}"
)

print(
    "Unique S3 candidates        : "
    f"{len(needed_s3_56):,}"
)

# ------------------------------------------------------------
# 7. Batched attribute loader
# ------------------------------------------------------------

def load_attrs_batch_56(
    conn,
    suffixes,
    chunk_size=500,
):

    result = {}

    suffixes = list(suffixes)

    for start in range(
        0,
        len(suffixes),
        chunk_size,
    ):

        chunk = suffixes[
            start:start + chunk_size
        ]

        placeholders = ",".join(
            ["?"] * len(chunk)
        )

        rows = conn.execute(
            f"""
            SELECT suffix, name, address, country
            FROM attrs
            WHERE suffix IN ({placeholders})
            """,
            chunk,
        ).fetchall()

        for suffix, name, address, country in rows:

            result[str(suffix)] = (
                str(name or ""),
                str(address or ""),
                str(country or ""),
            )

    return result

# ------------------------------------------------------------
# 8. Load S2 / S3 attributes
# ------------------------------------------------------------

print("\nLoading S2 attributes...")

s2_attrs_56 = load_attrs_batch_56(
    s2_conn,
    needed_s2_56,
)

print(
    "S2 attributes loaded        : "
    f"{len(s2_attrs_56):,}"
)

print("\nLoading S3 attributes...")

s3_attrs_56 = load_attrs_batch_56(
    s3_ro_56,
    needed_s3_56,
)

print(
    "S3 attributes loaded        : "
    f"{len(s3_attrs_56):,}"
)

s3_ro_56.close()

assert len(s2_attrs_56) == len(needed_s2_56)
assert len(s3_attrs_56) == len(needed_s3_56)

# ------------------------------------------------------------
# 9. Build feature rows for ONLY new TNORD candidates
# ------------------------------------------------------------

new_feature_rows_56 = []

missing_attr_56 = []

for (s1_id, candidate_id), meta in (
    tnord_candidate_meta_56.items()
):

    s1_name, s1_address, s1_country = (
        s1_attr_56[s1_id]
    )

    suffix = candidate_id[3:]

    if candidate_id.startswith("S2-"):

        attrs = s2_attrs_56.get(suffix)

    else:

        attrs = s3_attrs_56.get(suffix)

    if attrs is None:

        missing_attr_56.append(
            (
                s1_id,
                candidate_id,
            )
        )
        continue

    s2_name, s2_address, s2_country = attrs

    feature_values = calculate_features(
        s1_name,
        s1_address,
        s1_country,
        s2_name,
        s2_address,
        s2_country,
    )

    # --------------------------------------------------------
    # Normalize the returned feature representation.
    # calculate_features in this pipeline returns a dict.
    # --------------------------------------------------------

    if isinstance(feature_values, dict):

        row_features = {
            col: feature_values.get(
                col,
                0.0,
            )
            for col in model_features
            if col not in {
                "blocking_num_keys",
                "blocking_min_freq",
            }
        }

    else:

        feature_values = list(
            feature_values
        )

        assert len(feature_values) >= 24

        base_names = [
            "name_exact_match",
            "name_char_similarity",
            "name_levenshtein_similarity",
            "name_token_jaccard",
            "name_token_overlap",
            "name_compact_similarity",
            "name_prefix_similarity",
            "name_suffix_similarity",
            "name_char_ngram_jaccard",
            "address_exact_match",
            "address_char_similarity",
            "address_levenshtein_similarity",
            "address_token_jaccard",
            "address_token_overlap",
            "address_number_match",
            "address_char_ngram_jaccard",
            "country_match",
            "name_missing",
            "address_missing",
            "combined_name_address_score",
            "name_is_non_latin",
            "address_is_non_latin",
            "name_char_similarity_unicode",
            "name_token_jaccard_unicode",
        ]

        row_features = dict(
            zip(
                base_names,
                feature_values[:24],
            )
        )

    row_features[
        "blocking_num_keys"
    ] = meta["num_keys"]

    row_features[
        "blocking_min_freq"
    ] = meta["min_freq"]

    new_feature_rows_56.append(
        row_features
    )

    if (
        len(new_feature_rows_56) % 50000
        == 0
    ):

        print(
            "Feature rows:",
            f"{len(new_feature_rows_56):,}"
        )

assert not missing_attr_56
assert len(new_feature_rows_56) == 278739

# ------------------------------------------------------------
# 10. DataFrame + exact model feature order
# ------------------------------------------------------------

tnord_feature_df_56 = pd.DataFrame(
    new_feature_rows_56
)

assert set(model_features).issubset(
    tnord_feature_df_56.columns
)

tnord_X_56 = tnord_feature_df_56[
    model_features
].astype(float)

assert tnord_X_56.shape == (
    278739,
    26,
)

# ------------------------------------------------------------
# 11. Existing model prediction
# ------------------------------------------------------------

tnord_prob_56 = model.predict_proba(
    tnord_X_56
)[:, 1]

assert len(tnord_prob_56) == 278739
assert np.isfinite(tnord_prob_56).all()

print()
print(
    "TNORD probability range     : "
    f"{tnord_prob_56.min():.6f} -> "
    f"{tnord_prob_56.max():.6f}"
)

print(
    "TNORD probability median    : "
    f"{np.median(tnord_prob_56):.6f}"
)

print(
    "TNORD probability >= .944   : "
    f"{np.sum(tnord_prob_56 >= 0.944):,}"
)

# ------------------------------------------------------------
# 12. Pair -> TNORD probability map
# ------------------------------------------------------------

tnord_prob_map_56 = {
    pair: float(prob)
    for pair, prob in zip(
        tnord_candidate_meta_56.keys(),
        tnord_prob_56,
    )
}

assert len(tnord_prob_map_56) == 278739

# ------------------------------------------------------------
# 13. Existing prediction map
#
# Recover the ORIGINAL model score for every existing
# validation candidate from val_feature_df.
# ------------------------------------------------------------

assert "score" in val_feature_df.columns

existing_prob_map_56 = {}

for pair, score in zip(
    (
        (
            str(p["source1_entity_id"]),
            str(p["candidate_entity_id"]),
        )
        for p in val_candidate_pairs
    ),
    val_feature_df["score"].to_numpy(),
):

    existing_prob_map_56[pair] = float(score)

assert len(existing_prob_map_56) == 842159

# ------------------------------------------------------------
# 14. Ground truth
# ------------------------------------------------------------

gt_56 = {
    str(s1_id): {
        str(x)
        for x in ground_truth.get(
            s1_id,
            frozenset(),
        )
    }
    for s1_id in VAL_S1_IDS_47
}

# ------------------------------------------------------------
# 15. Evaluate ORIGINAL vs TNORD-AUGMENTED
#
# Exact S1-level macro F0.5.
# ------------------------------------------------------------

BETA_56 = 0.5

def fbeta_56(tp, fp, fn):

    beta2 = BETA_56 ** 2

    if tp == 0:

        return 0.0

    return (
        (1 + beta2) * tp
        / (
            (1 + beta2) * tp
            + beta2 * fn
            + fp
        )
    )

def evaluate_maps_56(
    prob_map,
    threshold,
):

    scores = []

    for s1_id in VAL_S1_IDS_47:

        gt = gt_56[s1_id]

        predicted = {
            candidate_id
            for (
                pair_s1,
                candidate_id
            ), prob in prob_map.items()

            if (
                pair_s1 == s1_id
                and prob >= threshold
            )
        }

        tp = len(predicted & gt)
        fp = len(predicted - gt)
        fn = len(gt - predicted)

        scores.append(
            fbeta_56(
                tp,
                fp,
                fn,
            )
        )

    return float(
        np.mean(scores)
    )

# ------------------------------------------------------------
# 16. Compare thresholds around the established .944
# ------------------------------------------------------------

thresholds_56 = [
    0.90,
    0.92,
    0.93,
    0.94,
    0.944,
    0.945,
    0.95,
    0.955,
    0.96,
]

# To avoid repeatedly scanning the entire 1.1M map,
# group predictions by S1 first.

existing_by_s1_prob_56 = {}

for (
    s1_id,
    candidate_id
), prob in existing_prob_map_56.items():

    existing_by_s1_prob_56.setdefault(
        s1_id,
        []
    ).append(
        (
            candidate_id,
            prob,
        )
    )

tnord_by_s1_prob_56 = {}

for (
    s1_id,
    candidate_id
), prob in tnord_prob_map_56.items():

    tnord_by_s1_prob_56.setdefault(
        s1_id,
        []
    ).append(
        (
            candidate_id,
            prob,
        )
    )

print()
print("=" * 80)
print("F0.5 THRESHOLD COMPARISON")
print("=" * 80)

for threshold in thresholds_56:

    per_row = []

    total_pred = 0
    total_tp = 0
    total_fp = 0
    total_fn = 0

    for s1_id in VAL_S1_IDS_47:

        gt = gt_56[s1_id]

        predicted = set()

        for candidate_id, prob in (
            existing_by_s1_prob_56.get(
                s1_id,
                []
            )
        ):

            if prob >= threshold:
                predicted.add(candidate_id)

        for candidate_id, prob in (
            tnord_by_s1_prob_56.get(
                s1_id,
                []
            )
        ):

            if prob >= threshold:
                predicted.add(candidate_id)

        tp = len(predicted & gt)
        fp = len(predicted - gt)
        fn = len(gt - predicted)

        total_pred += len(predicted)
        total_tp += tp
        total_fp += fp
        total_fn += fn

        per_row.append(
            fbeta_56(
                tp,
                fp,
                fn,
            )
        )

    macro_f05 = float(
        np.mean(per_row)
    )

    precision = (
        total_tp / total_pred
        if total_pred
        else 0.0
    )

    recall = (
        total_tp / total_gt_56
        if (total_gt_56 := sum(
            len(gt_56[x])
            for x in VAL_S1_IDS_47
        ))
        else 0.0
    )

    print(
        f"threshold={threshold:.3f} | "
        f"macro_F0.5={macro_f05:.6f} | "
        f"precision={precision:.6f} | "
        f"recall={recall:.6f} | "
        f"predicted={total_pred:,} | "
        f"TP={total_tp:,} | "
        f"FP={total_fp:,}"
    )

print()
print("=" * 80)
print("CELL 56 COMPLETE")
print("=" * 80)

print(
    f"Runtime : "
    f"{time.time() - t0_56:.1f}s"
)

gc.collect()

================================================================================
CELL 56 — TNORD MODEL IMPACT / F0.5
================================================================================
Original validation pairs : 842,159
Original feature rows     : 842,159
Model features            : 26
500/2,000 | new candidates=66,455
1,000/2,000 | new candidates=129,544
1,500/2,000 | new candidates=203,891
2,000/2,000 | new candidates=278,739

Verified NEW TNORD candidates : 278,739
TNORD key frequencies cached   : 3,492
Unique S2 candidates        : 114,835
Unique S3 candidates        : 112,847

Loading S2 attributes...
S2 attributes loaded        : 114,835

Loading S3 attributes...
S3 attributes loaded        : 112,847
Feature rows: 50,000
Feature rows: 100,000
Feature rows: 150,000
Feature rows: 200,000
Feature rows: 250,000

TNORD probability range     : 0.000258 -> 0.969422
TNORD probability median    : 0.000608
TNORD probability >= .944   : 30

================================================================================
F0.5 THRESHOLD COMPARISON
================================================================================
threshold=0.900 | macro_F0.5=0.738082 | precision=0.761226 | recall=0.880243 | predicted=7,995 | TP=6,086 | FP=1,909
threshold=0.920 | macro_F0.5=0.748748 | precision=0.782157 | recall=0.861007 | predicted=7,611 | TP=5,953 | FP=1,658
threshold=0.930 | macro_F0.5=0.755739 | precision=0.798771 | recall=0.846254 | predicted=7,325 | TP=5,851 | FP=1,474
threshold=0.940 | macro_F0.5=0.768751 | precision=0.825860 | recall=0.823113 | predicted=6,891 | TP=5,691 | FP=1,200
threshold=0.944 | macro_F0.5=0.784973 | precision=0.885939 | recall=0.767284 | predicted=5,988 | TP=5,305 | FP=683
threshold=0.945 | macro_F0.5=0.780228 | precision=0.895790 | recall=0.744721 | predicted=5,748 | TP=5,149 | FP=599
threshold=0.950 | macro_F0.5=0.688547 | precision=0.975960 | recall=0.569569 | predicted=4,035 | TP=3,938 | FP=97
threshold=0.955 | macro_F0.5=0.003948 | precision=0.928571 | recall=0.001880 | predicted=14 | TP=13 | FP=1
threshold=0.960 | macro_F0.5=0.000000 | precision=0.000000 | recall=0.000000 | predicted=1 | TP=0 | FP=1

================================================================================
CELL 56 COMPLETE
================================================================================
Runtime : 71.7s

0

In [147]:
# ============================================================
# CELL 57 — HIGH-CONFIDENCE SINGLETON RESCUE
# ============================================================
#
# We KEEP the proven baseline:
#     probability >= 0.944
#
# We ONLY examine S1 rows that currently have ZERO matches.
#
# For those rows, test whether the top candidate is sufficiently
# strong AND separated from the second candidate.
#
# This does NOT add candidates.
# This does NOT retrain the model.
# This does NOT touch any database.
#
# Objective: maximize S1-level Macro F0.5 on validation.
# ============================================================

import numpy as np
from collections import defaultdict

print("=" * 80)
print("CELL 57 — HIGH-CONFIDENCE SINGLETON RESCUE")
print("=" * 80)

BASE_THR_57 = 0.944

assert len(val_candidate_pairs) == 842159
assert len(val_feature_df) == 842159
assert "score" in val_feature_df.columns

# ------------------------------------------------------------
# 1. Build per-S1 ranked candidate scores
# ------------------------------------------------------------

scores_by_s1_57 = defaultdict(list)

pair_score_iter_57 = zip(
    val_candidate_pairs,
    val_feature_df["score"].to_numpy(),
)

for pair, score in pair_score_iter_57:

    s1_id = str(pair["source1_entity_id"])
    candidate_id = str(pair["candidate_entity_id"])

    scores_by_s1_57[s1_id].append(
        (
            float(score),
            candidate_id,
        )
    )

# Sort descending once.
for s1_id in scores_by_s1_57:
    scores_by_s1_57[s1_id].sort(
        key=lambda x: x[0],
        reverse=True,
    )

assert len(scores_by_s1_57) == 2000

# ------------------------------------------------------------
# 2. Ground truth
# ------------------------------------------------------------

gt_57 = {
    str(s1_id): {
        str(x)
        for x in ground_truth.get(
            s1_id,
            frozenset(),
        )
    }
    for s1_id in VAL_S1_IDS_47
}

total_gt_57 = sum(
    len(v)
    for v in gt_57.values()
)

assert total_gt_57 == 6914

# ------------------------------------------------------------
# 3. Baseline predictions at 0.944
# ------------------------------------------------------------

baseline_pred_57 = {}

zero_match_rows_57 = []

for s1_id in VAL_S1_IDS_47:

    ranked = scores_by_s1_57[s1_id]

    predicted = {
        candidate_id
        for score, candidate_id in ranked
        if score >= BASE_THR_57
    }

    baseline_pred_57[s1_id] = predicted

    if len(predicted) == 0:
        zero_match_rows_57.append(s1_id)

print(
    f"Rows with zero baseline matches : "
    f"{len(zero_match_rows_57):,}"
)

# ------------------------------------------------------------
# 4. Exact F0.5 implementation
# ------------------------------------------------------------

def f05_57(tp, fp, fn):

    if tp == 0:
        return 0.0

    return (
        1.25 * tp
        / (
            1.25 * tp
            + 0.25 * fn
            + fp
        )
    )

def macro_score_57(predictions):

    vals = []

    for s1_id in VAL_S1_IDS_47:

        gt = gt_57[s1_id]
        pred = predictions[s1_id]

        tp = len(pred & gt)
        fp = len(pred - gt)
        fn = len(gt - pred)

        vals.append(
            f05_57(tp, fp, fn)
        )

    return float(np.mean(vals))

baseline_macro_57 = macro_score_57(
    baseline_pred_57
)

print(
    f"Baseline Macro F0.5          : "
    f"{baseline_macro_57:.6f}"
)

# ------------------------------------------------------------
# 5. Evaluate selective singleton rescue
#
# Rescue ONLY zero-match rows.
#
# Conditions:
#   top score >= threshold
#   top score - second score >= margin
#
# This prevents indiscriminate threshold lowering.
# ------------------------------------------------------------

rescue_thresholds_57 = [
    0.75,
    0.80,
    0.82,
    0.84,
    0.86,
    0.88,
    0.90,
    0.92,
    0.94,
]

rescue_margins_57 = [
    0.00,
    0.01,
    0.02,
    0.03,
    0.05,
    0.08,
    0.10,
    0.15,
]

results_57 = []

for threshold in rescue_thresholds_57:

    for margin in rescue_margins_57:

        predictions = {
            s1_id: set(pred)
            for s1_id, pred
            in baseline_pred_57.items()
        }

        rescued_rows = 0
        rescued_tp = 0
        rescued_fp = 0

        for s1_id in zero_match_rows_57:

            ranked = scores_by_s1_57[s1_id]

            if not ranked:
                continue

            top_score, top_id = ranked[0]

            second_score = (
                ranked[1][0]
                if len(ranked) > 1
                else 0.0
            )

            score_margin = (
                top_score
                - second_score
            )

            if (
                top_score >= threshold
                and score_margin >= margin
            ):

                predictions[s1_id].add(
                    top_id
                )

                rescued_rows += 1

                if top_id in gt_57[s1_id]:
                    rescued_tp += 1
                else:
                    rescued_fp += 1

        macro = macro_score_57(
            predictions
        )

        results_57.append(
            (
                macro,
                threshold,
                margin,
                rescued_rows,
                rescued_tp,
                rescued_fp,
            )
        )

# ------------------------------------------------------------
# 6. Print best configurations
# ------------------------------------------------------------

results_57.sort(
    key=lambda x: x[0],
    reverse=True,
)

print()
print("=" * 80)
print("BEST SINGLETON RESCUE CONFIGURATIONS")
print("=" * 80)

for (
    macro,
    threshold,
    margin,
    rescued,
    tp,
    fp,
) in results_57[:15]:

    print(
        f"F0.5={macro:.6f} | "
        f"thr={threshold:.2f} | "
        f"margin={margin:.2f} | "
        f"rescued={rescued:4d} | "
        f"TP={tp:4d} | "
        f"FP={fp:4d} | "
        f"gain={macro-baseline_macro_57:+.6f}"
    )

# ------------------------------------------------------------
# 7. Best result
# ------------------------------------------------------------

best_57 = results_57[0]

best_macro_57 = best_57[0]
best_thr_57 = best_57[1]
best_margin_57 = best_57[2]
best_rescued_57 = best_57[3]
best_tp_57 = best_57[4]
best_fp_57 = best_57[5]

print()
print("=" * 80)
print("CELL 57 DECISION")
print("=" * 80)

print(
    f"Baseline F0.5              : "
    f"{baseline_macro_57:.6f}"
)

print(
    f"Best rescue F0.5           : "
    f"{best_macro_57:.6f}"
)

print(
    f"Gain                       : "
    f"{best_macro_57 - baseline_macro_57:+.6f}"
)

print(
    f"Rescue threshold           : "
    f"{best_thr_57:.3f}"
)

print(
    f"Required score margin      : "
    f"{best_margin_57:.3f}"
)

print(
    f"Rows rescued               : "
    f"{best_rescued_57:,}"
)

print(
    f"True rescues               : "
    f"{best_tp_57:,}"
)

print(
    f"False rescues              : "
    f"{best_fp_57:,}"
)

# ------------------------------------------------------------
# 8. Save ONLY the best configuration in memory
# ------------------------------------------------------------

best_rescue_config_57 = {
    "base_threshold": BASE_THR_57,
    "rescue_threshold": best_thr_57,
    "rescue_margin": best_margin_57,
    "baseline_f05": baseline_macro_57,
    "rescue_f05": best_macro_57,
}

print()
print("=" * 80)
print("CELL 57 COMPLETE")
print("=" * 80)

================================================================================
CELL 57 — HIGH-CONFIDENCE SINGLETON RESCUE
================================================================================
Rows with zero baseline matches : 122
Baseline Macro F0.5          : 0.784059

================================================================================
BEST SINGLETON RESCUE CONFIGURATIONS
================================================================================
F0.5=0.798781 | thr=0.75 | margin=0.00 | rescued= 112 | TP=  37 | FP=  75 | gain=+0.014721
F0.5=0.798781 | thr=0.80 | margin=0.00 | rescued= 110 | TP=  37 | FP=  73 | gain=+0.014721
F0.5=0.798781 | thr=0.82 | margin=0.00 | rescued= 108 | TP=  37 | FP=  71 | gain=+0.014721
F0.5=0.798781 | thr=0.84 | margin=0.00 | rescued= 107 | TP=  37 | FP=  70 | gain=+0.014721
F0.5=0.798281 | thr=0.86 | margin=0.00 | rescued= 104 | TP=  36 | FP=  68 | gain=+0.014221
F0.5=0.798281 | thr=0.88 | margin=0.00 | rescued= 101 | TP=  36 | FP=  65 | gain=+0.014221
F0.5=0.798281 | thr=0.90 | margin=0.00 | rescued=  94 | TP=  36 | FP=  58 | gain=+0.014221
F0.5=0.797923 | thr=0.92 | margin=0.00 | rescued=  88 | TP=  35 | FP=  53 | gain=+0.013864
F0.5=0.794283 | thr=0.75 | margin=0.01 | rescued=  77 | TP=  25 | FP=  52 | gain=+0.010223
F0.5=0.794283 | thr=0.80 | margin=0.01 | rescued=  75 | TP=  25 | FP=  50 | gain=+0.010223
F0.5=0.794283 | thr=0.82 | margin=0.01 | rescued=  73 | TP=  25 | FP=  48 | gain=+0.010223
F0.5=0.794283 | thr=0.84 | margin=0.01 | rescued=  72 | TP=  25 | FP=  47 | gain=+0.010223
F0.5=0.793858 | thr=0.94 | margin=0.00 | rescued=  60 | TP=  25 | FP=  35 | gain=+0.009799
F0.5=0.793783 | thr=0.86 | margin=0.01 | rescued=  70 | TP=  24 | FP=  46 | gain=+0.009723
F0.5=0.793783 | thr=0.88 | margin=0.01 | rescued=  69 | TP=  24 | FP=  45 | gain=+0.009723

================================================================================
CELL 57 DECISION
================================================================================
Baseline F0.5              : 0.784059
Best rescue F0.5           : 0.798781
Gain                       : +0.014721
Rescue threshold           : 0.750
Required score margin      : 0.000
Rows rescued               : 112
True rescues               : 37
False rescues              : 75

================================================================================
CELL 57 COMPLETE
================================================================================

In [150]:
# ============================================================
# CELL 58A — IDENTIFY EXISTING TEST DATA STATE
# READ-ONLY DIAGNOSTIC — DO NOT MODIFY ANYTHING
# ============================================================

import os
import glob

print("=" * 80)
print("CELL 58A — TEST DATA / INDEX STATE")
print("=" * 80)

# ------------------------------------------------------------
# 1. Variables already present in the notebook
# ------------------------------------------------------------

interesting = [
    name for name in globals()
    if any(
        token in name.lower()
        for token in [
            "test",
            "s1",
            "s2",
            "s3",
            "index",
            "path",
        ]
    )
]

print("\nRelevant existing variables:")
for name in sorted(interesting):
    try:
        obj = globals()[name]

        if isinstance(obj, (str, int, float, bool)):
            print(
                f"  {name:<35} "
                f"{type(obj).__name__:<15} "
                f"{str(obj)[:180]}"
            )
        elif isinstance(obj, (list, tuple, set, dict)):
            print(
                f"  {name:<35} "
                f"{type(obj).__name__:<15} "
                f"len={len(obj):,}"
            )
        else:
            print(
                f"  {name:<35} "
                f"{type(obj).__name__}"
            )

    except Exception as e:
        print(
            f"  {name:<35} "
            f"<inspection failed: {e}>"
        )

# ------------------------------------------------------------
# 2. Check known dataset directory
# ------------------------------------------------------------

DATASET_ROOT_58A = (
    "/kaggle/input/datasets/"
    "tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset"
)

print("\nDataset root:")
print(DATASET_ROOT_58A)

print("\nTest directory contents:")

test_dir_58A = os.path.join(
    DATASET_ROOT_58A,
    "test",
)

if os.path.exists(test_dir_58A):

    for path in sorted(
        glob.glob(
            os.path.join(
                test_dir_58A,
                "*",
            )
        )
    ):

        print(
            " ",
            path,
            f"({os.path.getsize(path)/(1024**2):.2f} MB)"
            if os.path.isfile(path)
            else "<directory>",
        )

else:
    print("  TEST DIRECTORY NOT FOUND")

# ------------------------------------------------------------
# 3. Check working index directory
# ------------------------------------------------------------

INDEX_ROOT_58A = (
    "/kaggle/working/"
    "amazon_ml_solution/"
    "index_train"
)

print("\nWorking index directory:")
print(INDEX_ROOT_58A)

if os.path.exists(INDEX_ROOT_58A):

    for path in sorted(
        glob.glob(
            os.path.join(
                INDEX_ROOT_58A,
                "*",
            )
        )
    ):

        size = (
            os.path.getsize(path) / (1024**3)
            if os.path.isfile(path)
            else 0
        )

        print(
            " ",
            os.path.basename(path),
            f"{size:.3f} GB"
            if os.path.isfile(path)
            else "<directory>",
        )

else:
    print("  INDEX DIRECTORY NOT FOUND")

print()
print("=" * 80)
print("END CELL 58A")
print("=" * 80)

================================================================================
CELL 58A — TEST DATA / INDEX STATE
================================================================================

Relevant existing variables:
  DATA_PATHS                          dict            len=7
  GT_PATH                             str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_ground_truth.tsv
  HAS_TEST_DATA                       bool            True
  INDEXER                             PosixPath
  INDEX_DIR                           str             /kaggle/working/amazon_ml_solution/index_train
  Path                                type
  S1_ID_KEY                           str             entity_id
  S1_PATH                             str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source1.tsv
  S2                                  PosixPath
  S2_DB                               str             /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite
  S2_INDEX                            PosixPath
  S2_MANIFEST                         str             /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite.manifest.json
  S3                                  PosixPath
  S3_DB                               str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
  S3_INDEX                            PosixPath
  S3_MANIFEST                         str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite.manifest.json
  S3_SCRIPT                           str             /kaggle/working/measure_s3_kaggle.py
  SMOKE_TEST                          bool            False
  SqliteIndex                         type
  TEST_REQUIRED                       set             len=3
  TOTAL_S1                            int             2206821
  TRAIN_S1                            str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source1.tsv
  TRAIN_S3                            str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv
  VAL_S1_IDS_47                       set             len=2,000
  address1                            str             AL, Unit 111, 6190 Girby Road, Mobile
  address2                            str             190 Girby Road, Mobile, Alabama
  all_val_s1_ids                      list            len=2,000
  aux_db_path_47                      str             /kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite
  build_index                         function
  candidate_ids_by_s1                 dict            len=999
  candidate_s1_ids                    set             len=2,000
  candidate_test                      tuple           len=3
  discover_dataset_paths              function
  existing_by_s1                      dict            len=2,000
  existing_by_s1_50                   dict            len=2,000
  existing_by_s1_prob_56              dict            len=2,000
  guide_path                          str             /kaggle/input/datasets/tejasweerajput/amazon-v3/HOW_TO_RUN.md
  index                               SqliteIndex
  index_dir_53                        str             /kaggle/working/amazon_ml_solution/index_train
  index_lookup                        dict            len=2
  indexer                             module
  indexes_by_source                   dict            len=2
  missing_name_tests                  list            len=351
  missing_s1_ids_47                   set             len=272
  needed_s2_56                        set             len=114,835
  needed_s3_56                        set             len=112,847
  old_path                            str             /mnt/user-data/uploads/train_ground_truth.tsv
  order_test_df                       DataFrame
  pairs_by_s1                         Counter         len=999
  path                                str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite.manifest.json
  resolved_s2_54                      int             530
  resolved_s3_54                      int             470
  s1                                  str             S1-34528796
  s1_addr                             str             6019 Silent Oaks Drive, Humble, TX
  s1_address                          str             841 Harding Way, Galion, OH
  s1_attr_56                          dict            len=2,000
  s1_col                              str             source1_entity_id
  s1_country                          str             US
  s1_id                               str             S1-936580963
  s1_key                              str             dentistry|pediatric|physicians
  s1_keys                             set             len=15
  s1_lookup                           dict            len=2,206,821
  s1_lookup_val                       dict            len=2,000
  s1_name                             str             Board of Motor Vehicles
  s1_name_map_47                      dict            len=272
  s1_name_map_48                      dict            len=2,000
  s1_name_map_50                      dict            len=2,000
  s1_name_map_54                      dict            len=2,000
  s1_row                              dict            len=4
  s2_address                          str             1230 Pennsylvania Avenue, Steubenville, Ohio
  s2_attrs_56                         dict            len=114,835
  s2_cols                             list            len=4
  s2_conn                             Connection
  s2_count_46                         int             5012214
  s2_country                          str             US
  s2_hits                             list            len=0
  s2_index                            SqliteIndex
  s2_keys_46                          int             24076806
  s2_missing_47                       list            len=156
  s2_name                             str             Board of Vehicles Motor Inc.
  s2_path                             PosixPath
  s2_recovered_47                     list            len=39
  s3_attrs_56                         dict            len=112,847
  s3_cols                             list            len=4
  s3_count_46                         int             5238163
  s3_hits                             list            len=0
  s3_index                            SqliteIndex
  s3_keys_46                          int             25097282
  s3_missing_47                       list            len=195
  s3_path_53                          str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
  s3_path_54                          str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
  s3_path_56                          str             /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
  s3_recovered_47                     list            len=58
  s3_ro_54                            Connection
  s3_ro_56                            Connection
  scores_by_s1_57                     defaultdict     len=2,000
  test_pair                           dict            len=7
  tnord_by_s1_prob_56                 dict            len=1,182
  train_s1                            list            len=2,206,821
  train_s1_lookup                     dict            len=5,000
  train_s2                            str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source2.tsv
  train_s3                            str             /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv
  train_test_split                    function
  val_s1_ids                          set             len=2,000
  val_s1_rows                         list            len=2,000

Dataset root:
/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset

Test directory contents:
  /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source1.tsv (166.91 MB)
  /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv (485.86 MB)
  /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source3.tsv (482.56 MB)

Working index directory:
/kaggle/working/amazon_ml_solution/index_train
  s2_full.sqlite 0.000 GB
  s2_full.sqlite-shm 0.005 GB
  s2_full.sqlite.manifest.json 0.000 GB
  s3_full.sqlite 6.546 GB
  s3_full.sqlite-shm 0.005 GB
  s3_full.sqlite-wal 2.586 GB
  s3_full.sqlite.manifest.json 0.000 GB

================================================================================
END CELL 58A
================================================================================

In [151]:
# ============================================================
# CELL 58B — VERIFY TEST PATH STATE
# READ-ONLY
# ============================================================

print("=" * 80)
print("CELL 58B — TEST PATH STATE")
print("=" * 80)

print("\nDATA_PATHS:")
print(repr(DATA_PATHS))

print("\ncandidate_test:")
print(repr(candidate_test))

print("\nHAS_TEST_DATA:")
print(HAS_TEST_DATA)

print("\nTEST_REQUIRED:")
print(TEST_REQUIRED)

print("=" * 80)

================================================================================
CELL 58B — TEST PATH STATE
================================================================================

DATA_PATHS:
{'train_s1': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source1.tsv', 'train_s2': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source2.tsv', 'train_s3': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_source3.tsv', 'train_gt': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/train/train_ground_truth.tsv', 'test_s1': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source1.tsv', 'test_s2': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv', 'test_s3': '/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source3.tsv'}

candidate_test:
('Physical Therapy Summit  Care LLC', '1738 RICHMOND RD, TX, WHARTON', 'US')

HAS_TEST_DATA:
True

TEST_REQUIRED:
{'test_source3.tsv', 'test_source1.tsv', 'test_source2.tsv'}
================================================================================

In [152]:
# ============================================================
# CELL 58C — LOCATE TEST INDEX / CANDIDATE INFRASTRUCTURE
# READ-ONLY — NO DATA BUILDING
# ============================================================

import os
import glob

print("=" * 80)
print("CELL 58C — TEST INDEX / CANDIDATE INFRASTRUCTURE")
print("=" * 80)

# ------------------------------------------------------------
# 1. Working solution tree
# ------------------------------------------------------------

ROOT_58C = "/kaggle/working/amazon_ml_solution"

print("\nWorking solution files/directories:")

for root, dirs, files in os.walk(ROOT_58C):

    # Avoid printing enormous recursive trees.
    dirs[:] = [
        d for d in dirs
        if d not in {
            "__pycache__",
            ".git",
        }
    ]

    rel_root = os.path.relpath(root, ROOT_58C)

    for f in sorted(files):

        path = os.path.join(root, f)

        try:
            size_mb = os.path.getsize(path) / (1024 ** 2)
        except Exception:
            size_mb = -1

        print(
            f"{os.path.join(rel_root, f):<90} "
            f"{size_mb:10.2f} MB"
        )

# ------------------------------------------------------------
# 2. Search specifically for test/index artifacts
# ------------------------------------------------------------

print("\nPotential TEST / INDEX artifacts:")

patterns_58C = [
    "/kaggle/working/**/*test*",
    "/kaggle/working/**/*index*",
    "/kaggle/working/**/*candidate*",
    "/kaggle/working/**/*.sqlite",
    "/kaggle/working/**/*.manifest.json",
]

found_58C = set()

for pattern in patterns_58C:

    for path in glob.glob(
        pattern,
        recursive=True,
    ):

        if path in found_58C:
            continue

        found_58C.add(path)

        try:
            size_mb = (
                os.path.getsize(path)
                / (1024 ** 2)
            ) if os.path.isfile(path) else None
        except Exception:
            size_mb = None

        if size_mb is None:
            print(
                "[DIR ]",
                path,
            )
        else:
            print(
                "[FILE]",
                path,
                f"({size_mb:.2f} MB)",
            )

# ------------------------------------------------------------
# 3. Existing Python objects whose names suggest test/index
# ------------------------------------------------------------

print("\nRelevant Python objects:")

for name in sorted(globals()):

    lname = name.lower()

    if not any(
        token in lname
        for token in [
            "test_index",
            "testindex",
            "test_candidate",
            "test_candidates",
            "candidate_test",
            "index_test",
        ]
    ):
        continue

    try:

        obj = globals()[name]

        if isinstance(
            obj,
            (str, int, float, bool)
        ):
            desc = str(obj)

        elif isinstance(
            obj,
            (list, tuple, set, dict)
        ):
            desc = (
                f"{type(obj).__name__}, "
                f"len={len(obj):,}"
            )

        else:
            desc = type(obj).__name__

        print(
            f"  {name:<35} {desc}"
        )

    except Exception as e:

        print(
            f"  {name:<35} "
            f"<error: {e}>"
        )

print()
print("=" * 80)
print("END CELL 58C")
print("=" * 80)

================================================================================
CELL 58C — TEST INDEX / CANDIDATE INFRASTRUCTURE
================================================================================

Working solution files/directories:
auxiliary/train_translit_name.sqlite                                                          1644.97 MB
checkpoints/recall_s2.json                                                                       0.14 MB
checkpoints/recall_s3.json                                                                       0.15 MB
index_train/s2_full.sqlite                                                                       0.00 MB
index_train/s2_full.sqlite-shm                                                                   4.66 MB
index_train/s2_full.sqlite.manifest.json                                                         0.00 MB
index_train/s3_full.sqlite                                                                    6702.98 MB
index_train/s3_full.sqlite-shm                                                                   5.16 MB
index_train/s3_full.sqlite-wal                                                                2647.60 MB
index_train/s3_full.sqlite.manifest.json                                                         0.00 MB

Potential TEST / INDEX artifacts:
[DIR ] /kaggle/working/amazon_ml_solution/shards_test
[DIR ] /kaggle/working/amazon_ml_solution/index_test
[DIR ] /kaggle/working/amazon_ml_solution/index_train
[FILE] /kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite (1644.97 MB)
[FILE] /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite (6702.98 MB)
[FILE] /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite (0.00 MB)
[FILE] /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite.manifest.json (0.00 MB)
[FILE] /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite.manifest.json (0.00 MB)

Relevant Python objects:
  candidate_test                      tuple, len=3

================================================================================
END CELL 58C
================================================================================

In [153]:
# ============================================================
# CELL 58D — INSPECT EXISTING TEST INDEX / SHARDS
# READ-ONLY — NO BUILD / NO DELETE / NO MODIFICATION
# ============================================================

import os
import glob

print("=" * 80)
print("CELL 58D — EXISTING TEST INDEX / SHARDS")
print("=" * 80)

for label, directory in [
    (
        "INDEX_TEST",
        "/kaggle/working/amazon_ml_solution/index_test",
    ),
    (
        "SHARDS_TEST",
        "/kaggle/working/amazon_ml_solution/shards_test",
    ),
]:

    print("\n" + "-" * 80)
    print(label)
    print("-" * 80)

    if not os.path.exists(directory):
        print("DIRECTORY DOES NOT EXIST")
        continue

    entries = sorted(
        glob.glob(
            os.path.join(directory, "**"),
            recursive=True,
        )
    )

    if not entries:
        print("EMPTY")
        continue

    for path in entries:

        if os.path.isdir(path):
            print(
                "[DIR ]",
                os.path.relpath(
                    path,
                    directory,
                ),
            )

        elif os.path.isfile(path):

            try:
                size_mb = (
                    os.path.getsize(path)
                    / (1024 ** 2)
                )
            except Exception:
                size_mb = -1

            print(
                "[FILE]",
                os.path.relpath(
                    path,
                    directory,
                ),
                f"({size_mb:.2f} MB)",
            )

print()
print("=" * 80)
print("END CELL 58D")
print("=" * 80)

================================================================================
CELL 58D — EXISTING TEST INDEX / SHARDS
================================================================================

--------------------------------------------------------------------------------
INDEX_TEST
--------------------------------------------------------------------------------
[DIR ] .

--------------------------------------------------------------------------------
SHARDS_TEST
--------------------------------------------------------------------------------
[DIR ] .

================================================================================
END CELL 58D
================================================================================

In [154]:
# ============================================================
# CELL 58E — INSPECT ACTUAL INDEX BUILDER
# READ-ONLY
# ============================================================

import inspect

print("=" * 80)
print("CELL 58E — ACTUAL INDEX BUILDER")
print("=" * 80)

print("\nINDEXER MODULE:")
print(INDEXER)

print("\nINDEXER FILE:")
try:
    print(INDEXER.__file__)
except Exception as e:
    print("Could not read module path:", e)

print("\nBUILD_INDEX OBJECT:")
print(build_index)

print("\nBUILD_INDEX SIGNATURE:")
try:
    print(inspect.signature(build_index))
except Exception as e:
    print("Could not read signature:", e)

print("\nBUILD_INDEX SOURCE:")
try:
    print(inspect.getsource(build_index))
except Exception as e:
    print("Could not read source:", e)

print("\nSQLITE INDEX CLASS:")
print(SqliteIndex)

print("\nSQLITE INDEX SIGNATURE:")
try:
    print(inspect.signature(SqliteIndex))
except Exception as e:
    print("Could not read signature:", e)

print()
print("=" * 80)
print("END CELL 58E")
print("=" * 80)

================================================================================
CELL 58E — ACTUAL INDEX BUILDER
================================================================================

INDEXER MODULE:
/kaggle/input/datasets/tejasweerajput/amazon-v3/modules/indexer.py

INDEXER FILE:
Could not read module path: 'PosixPath' object has no attribute '__file__'

BUILD_INDEX OBJECT:
<function build_index at 0x78093d197420>

BUILD_INDEX SIGNATURE:
(path, source_prefix, limit=None, backend='memory', db_path=None, manifest_path=None)

BUILD_INDEX SOURCE:
def build_index(path, source_prefix, limit=None, backend="memory", db_path=None,
                 manifest_path=None):
    """
    Same signature and behavior as before for backend="memory"
    (no persistence is possible for an in-RAM structure across a
    kernel restart -- if the run dies, a memory-backend index must
    be rebuilt from scratch; use backend="sqlite" for anything
    that needs to survive a Kaggle interruption, per the
    checkpoint/resume plan).

    backend="sqlite" now resumes: if db_path + its manifest show a
    previously COMPLETE build for this source, the existing
    database is reopened and returned immediately (no re-read of
    `path` at all). If the manifest shows a partial build, only
    the remaining rows of `path` are read and appended.
    """

    if backend == "sqlite":
        if db_path is None:
            raise ValueError("db_path is required for the sqlite backend")

        index = SqliteIndex(source_prefix, db_path, manifest_path=manifest_path)
        rows_done, complete = index.resume_point()

        if complete:
            print(
                f"[indexer] {source_prefix} index at {db_path} is already "
                f"complete ({rows_done:,} rows) -- reusing, no rebuild."
            )
            index.count = rows_done
            return index

        if rows_done:
            print(
                f"[indexer] Resuming {source_prefix} index at {db_path}: "
                f"{rows_done:,} rows already indexed, continuing from there."
            )
        index.count = rows_done

    else:
        index = MemoryIndex(source_prefix)
        rows_done = 0

    print(f"[indexer] Building {backend} index for {source_prefix} from: {path}")

    for i, row in enumerate(read_tsv(path)):

        if i < rows_done:
            continue  # already indexed in a previous, interrupted run
            # NOTE: this still parses every skipped row (read_tsv is a
            # plain csv.DictReader generator) -- resume avoids redoing
            # key generation + inserts, which dominate cost, but not
            # the comparatively cheap TSV parse. Acceptable trade-off
            # for correctness/simplicity; revisit only if profiling
            # shows the parse itself is significant.

        if limit is not None and i >= limit:
            break

        index.add_record(
            entity_id=row.get("entity_id", ""),
            name=row.get("business_name", ""),
            address=row.get("business_address", ""),
            country=row.get("country", "").strip(),
        )

        if index.count % 500_000 == 0:
            print(f"[indexer]   indexed {index.count:,} {source_prefix} records...")

    if backend == "sqlite":
        index.finalize()

    print(
        f"[indexer] Finished {source_prefix}: {index.count:,} records, "
        f"{index.num_keys():,} distinct blocking keys."
    )

    return index


SQLITE INDEX CLASS:
<class 'indexer.SqliteIndex'>

SQLITE INDEX SIGNATURE:
(source_prefix, db_path, manifest_path=None)

================================================================================
END CELL 58E
================================================================================

In [155]:
# ============================================================
# CELL 58F — RAM + TEST SIZE SAFETY CHECK
# READ-ONLY
# ============================================================

import os
import psutil

print("=" * 80)
print("CELL 58F — FINAL RESOURCE CHECK")
print("=" * 80)

# ------------------------------------------------------------
# RAM
# ------------------------------------------------------------

vm = psutil.virtual_memory()

print("\nRAM:")
print(
    "  Total     :",
    f"{vm.total / (1024**3):.2f} GB"
)
print(
    "  Available :",
    f"{vm.available / (1024**3):.2f} GB"
)
print(
    "  Used      :",
    f"{vm.used / (1024**3):.2f} GB"
)

# ------------------------------------------------------------
# Disk
# ------------------------------------------------------------

disk = psutil.disk_usage(
    "/kaggle/working"
)

print("\nDisk:")
print(
    "  Total     :",
    f"{disk.total / (1024**3):.2f} GB"
)
print(
    "  Used      :",
    f"{disk.used / (1024**3):.2f} GB"
)
print(
    "  Free      :",
    f"{disk.free / (1024**3):.2f} GB"
)

# ------------------------------------------------------------
# Test S1 row count — stream only, no DataFrame
# ------------------------------------------------------------

test_s1_path_58F = DATA_PATHS["test_s1"]

print("\nCounting test S1 rows:")
print(test_s1_path_58F)

count_58F = 0

with open(
    test_s1_path_58F,
    "r",
    encoding="utf-8",
    errors="replace",
) as f:

    # Header
    header = next(f)

    for _ in f:
        count_58F += 1

print(
    "\nTEST S1 ROWS:",
    f"{count_58F:,}"
)

print()
print("=" * 80)
print("END CELL 58F")
print("=" * 80)

================================================================================
CELL 58F — FINAL RESOURCE CHECK
================================================================================

RAM:
  Total     : 31.35 GB
  Available : 13.59 GB
  Used      : 17.31 GB

Disk:
  Total     : 19.52 GB
  Used      : 19.03 GB
  Free      : 0.47 GB

Counting test S1 rows:
/kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source1.tsv

TEST S1 ROWS: 1,732,544

================================================================================
END CELL 58F
================================================================================

In [156]:
# ============================================================
# CELL 58G — SAFE DISK AUDIT
# READ-ONLY
# NO DELETE / NO CLOSE / NO INDEX MODIFICATION
# ============================================================

import os
import glob

print("=" * 80)
print("CELL 58G — SAFE DISK AUDIT")
print("=" * 80)

ROOT_58G = "/kaggle/working/amazon_ml_solution"

# ------------------------------------------------------------
# 1. Current disk state
# ------------------------------------------------------------

st = os.statvfs("/kaggle/working")

free_gb = (
    st.f_bavail * st.f_frsize
) / (1024 ** 3)

print(
    "\nCurrent free disk:",
    f"{free_gb:.3f} GB"
)

# ------------------------------------------------------------
# 2. Every file under solution directory
# ------------------------------------------------------------

files_58g = []

for root, dirs, files in os.walk(ROOT_58G):

    dirs[:] = [
        d for d in dirs
        if d not in {"__pycache__"}
    ]

    for filename in files:

        path = os.path.join(
            root,
            filename,
        )

        try:
            size = os.path.getsize(path)
        except OSError:
            continue

        files_58g.append(
            (
                size,
                path,
            )
        )

files_58g.sort(
    reverse=True
)

print("\nLargest files:")

for size, path in files_58g:

    print(
        f"{size / (1024**3):8.3f} GB   "
        f"{path}"
    )

# ------------------------------------------------------------
# 3. Directory totals
# ------------------------------------------------------------

print("\nDirectory totals:")

directory_sizes_58g = {}

for size, path in files_58g:

    directory = os.path.dirname(path)

    directory_sizes_58g[directory] = (
        directory_sizes_58g.get(
            directory,
            0,
        )
        + size
    )

for directory, size in sorted(
    directory_sizes_58g.items(),
    key=lambda x: x[1],
    reverse=True,
):

    print(
        f"{size / (1024**3):8.3f} GB   "
        f"{directory}"
    )

print()
print("=" * 80)
print("END CELL 58G")
print("=" * 80)

================================================================================
CELL 58G — SAFE DISK AUDIT
================================================================================

Current free disk: 0.469 GB

Largest files:
   6.546 GB   /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite
   2.586 GB   /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite-wal
   1.606 GB   /kaggle/working/amazon_ml_solution/auxiliary/train_translit_name.sqlite
   0.005 GB   /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite-shm
   0.005 GB   /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite-shm
   0.000 GB   /kaggle/working/amazon_ml_solution/checkpoints/recall_s3.json
   0.000 GB   /kaggle/working/amazon_ml_solution/checkpoints/recall_s2.json
   0.000 GB   /kaggle/working/amazon_ml_solution/index_train/s3_full.sqlite.manifest.json
   0.000 GB   /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite.manifest.json
   0.000 GB   /kaggle/working/amazon_ml_solution/index_train/s2_full.sqlite

Directory totals:
   9.141 GB   /kaggle/working/amazon_ml_solution/index_train
   1.606 GB   /kaggle/working/amazon_ml_solution/auxiliary
   0.000 GB   /kaggle/working/amazon_ml_solution/checkpoints

================================================================================
END CELL 58G
================================================================================

In [157]:
# ============================================================
# CELL 58H — FREE TRAINING-ONLY DISK
# ============================================================
#
# The trained model / validation results remain in RAM.
#
# We are removing ONLY:
#   1. training S2/S3 SQLite index artifacts
#   2. training transliteration auxiliary index
#
# These are NOT needed for final TEST inference.
#
# TEST SOURCE FILES ARE NOT TOUCHED.
# ============================================================

import os
import gc
import shutil

print("=" * 80)
print("CELL 58H — FREE TRAINING-ONLY DISK")
print("=" * 80)

# ------------------------------------------------------------
# 1. Close known training index connections
# ------------------------------------------------------------

closed_58h = []

# Direct S2 connection
if "s2_conn" in globals():

    try:
        s2_conn.close()
        closed_58h.append("s2_conn")
    except Exception as e:
        print("s2_conn close warning:", e)

# S3 read-only connections created during diagnostics
for name in [
    "s3_ro_54",
    "s3_ro_56",
]:

    if name in globals():

        try:
            globals()[name].close()
            closed_58h.append(name)
        except Exception as e:
            print(
                f"{name} close warning:",
                e,
            )

# SqliteIndex objects may own their own connection.
for name in [
    "s2_index",
    "s3_index",
    "index",
]:

    if name not in globals():
        continue

    obj = globals()[name]

    # Try common connection attribute names,
    # but do not fail if this implementation does not expose one.
    for attr in [
        "conn",
        "connection",
    ]:

        if not hasattr(obj, attr):
            continue

        try:

            conn = getattr(obj, attr)

            if conn is not None:
                conn.close()

            closed_58h.append(
                f"{name}.{attr}"
            )

        except Exception as e:

            print(
                f"{name}.{attr} close warning:",
                e,
            )

print(
    "\nClosed training connections:"
)

for name in closed_58h:
    print("  ", name)

gc.collect()

# ------------------------------------------------------------
# 2. Remove ONLY confirmed training artifacts
# ------------------------------------------------------------

training_index_dir_58h = (
    "/kaggle/working/"
    "amazon_ml_solution/"
    "index_train"
)

auxiliary_dir_58h = (
    "/kaggle/working/"
    "amazon_ml_solution/"
    "auxiliary"
)

targets_58h = [
    training_index_dir_58h,
    auxiliary_dir_58h,
]

print("\nRemoving training-only artifacts:")

for path in targets_58h:

    if not os.path.exists(path):

        print(
            "  NOT PRESENT:",
            path,
        )
        continue

    print(
        "  Removing:",
        path,
    )

    shutil.rmtree(path)

    print(
        "  Removed:",
        path,
    )

gc.collect()

# ------------------------------------------------------------
# 3. Verify test input files still exist
# ------------------------------------------------------------

print("\nVerifying TEST input files:")

for key in [
    "test_s1",
    "test_s2",
    "test_s3",
]:

    path = DATA_PATHS[key]

    assert os.path.exists(path), (
        f"TEST INPUT MISSING: {path}"
    )

    print(
        f"  {key:<10}: OK"
    )

# ------------------------------------------------------------
# 4. Verify working directories
# ------------------------------------------------------------

for directory in [
    "/kaggle/working/amazon_ml_solution/index_test",
    "/kaggle/working/amazon_ml_solution/shards_test",
]:

    os.makedirs(
        directory,
        exist_ok=True,
    )

# ------------------------------------------------------------
# 5. Disk report
# ------------------------------------------------------------

st_58h = os.statvfs(
    "/kaggle/working"
)

free_gb_58h = (
    st_58h.f_bavail *
    st_58h.f_frsize
) / (1024 ** 3)

print()
print("=" * 80)
print(
    "FREE DISK AFTER CLEANUP:",
    f"{free_gb_58h:.3f} GB"
)
print("=" * 80)

assert free_gb_58h > 5.0, (
    "Unexpectedly low free disk after cleanup."
)

print(
    "\nCELL 58H COMPLETE — TRAINING ARTIFACTS REMOVED."
)

================================================================================
CELL 58H — FREE TRAINING-ONLY DISK
================================================================================

Closed training connections:
   s2_conn
   s3_ro_54
   s3_ro_56
   s2_index.conn
   s3_index.conn
   index.conn

Removing training-only artifacts:
  Removing: /kaggle/working/amazon_ml_solution/index_train
  Removed: /kaggle/working/amazon_ml_solution/index_train
  Removing: /kaggle/working/amazon_ml_solution/auxiliary
  Removed: /kaggle/working/amazon_ml_solution/auxiliary

Verifying TEST input files:
  test_s1   : OK
  test_s2   : OK
  test_s3   : OK

================================================================================
FREE DISK AFTER CLEANUP: 8.759 GB
================================================================================

CELL 58H COMPLETE — TRAINING ARTIFACTS REMOVED.

In [158]:
# ============================================================
# CELL 58I — BUILD TEST S2 MEMORY INDEX
# ============================================================

import gc
import time
import psutil

print("=" * 80)
print("CELL 58I — BUILD TEST S2 MEMORY INDEX")
print("=" * 80)

TEST_S2_PATH_58I = DATA_PATHS["test_s2"]

assert os.path.exists(TEST_S2_PATH_58I), TEST_S2_PATH_58I

# ------------------------------------------------------------
# Resource check
# ------------------------------------------------------------

vm_58i = psutil.virtual_memory()

print(
    "Available RAM before index :",
    f"{vm_58i.available / (1024**3):.2f} GB"
)

print(
    "Test S2 file               :",
    TEST_S2_PATH_58I
)

# ------------------------------------------------------------
# Build ONLY test S2 in RAM.
#
# backend="memory" means:
#   - no SQLite file
#   - no WAL
#   - no disk growth
# ------------------------------------------------------------

T58I = time.time()

test_s2_index_58i = build_index(
    TEST_S2_PATH_58I,
    "S2",
    limit=None,
    backend="memory",
)

print()
print(
    "TEST S2 INDEX COMPLETE"
)

print(
    "Rows indexed               :",
    f"{test_s2_index_58i.count:,}"
)

print(
    "Distinct blocking keys     :",
    f"{test_s2_index_58i.num_keys():,}"
)

vm_58i_after = psutil.virtual_memory()

print(
    "Available RAM after index  :",
    f"{vm_58i_after.available / (1024**3):.2f} GB"
)

print(
    "Index build time           :",
    f"{time.time() - T58I:.1f} sec"
)

print()
print("=" * 80)
print("S2 TEST INDEX IS READY")
print("=" * 80)

================================================================================
CELL 58I — BUILD TEST S2 MEMORY INDEX
================================================================================
Available RAM before index : 13.55 GB
Test S2 file               : /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv
[indexer] Building memory index for S2 from: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv
[indexer]   indexed 500,000 S2 records...
[indexer]   indexed 1,000,000 S2 records...
[indexer]   indexed 1,500,000 S2 records...
[indexer]   indexed 2,000,000 S2 records...
[indexer]   indexed 2,500,000 S2 records...
[indexer]   indexed 3,000,000 S2 records...
[indexer]   indexed 3,500,000 S2 records...
[indexer]   indexed 4,000,000 S2 records...
[indexer]   indexed 4,500,000 S2 records...
[indexer] Finished S2: 4,887,273 records, 24,029,096 distinct blocking keys.

TEST S2 INDEX COMPLETE
Rows indexed               : 4,887,273
Distinct blocking keys     : 24,029,096
Available RAM after index  : 7.21 GB
Index build time           : 596.9 sec

================================================================================
S2 TEST INDEX IS READY
================================================================================

In [1]:
# ============================================================
# CLEANUP FAILED 58J OUTPUT
# ============================================================

import os
import gc
import psutil

p = "/kaggle/working/amazon_ml_solution/test_s2_candidates.tsv"

if os.path.exists(p):
    print(
        "Deleting incomplete candidate file:",
        f"{os.path.getsize(p)/(1024**3):.3f} GB"
    )
    os.remove(p)
else:
    print("Incomplete candidate file already absent.")

gc.collect()

disk = psutil.disk_usage("/kaggle/working")

print(
    "Free disk after cleanup:",
    f"{disk.free/(1024**3):.3f} GB"
)

Incomplete candidate file already absent.
Free disk after cleanup: 19.502 GB

In [ ]:
# ============================================================
# FINAL TEST S2 INDEX + CANDIDATE GENERATION
# SELF-CONTAINED — NO DEPENDENCE ON PREVIOUS TEST INDEX VARIABLE
# ============================================================

import sys
import os
import csv
import time
import gc
import psutil

MODULE_DIR = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-v3/modules"
)

if MODULE_DIR not in sys.path:
    sys.path.insert(0, MODULE_DIR)

from indexer import build_index
from candidates import generate_candidate_pairs_for_row
from blocking import DEFAULT_FREQ_CAPS

TEST_S1_PATH = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/test/test_source1.tsv"
)

TEST_S2_PATH = (
    "/kaggle/input/datasets/tejasweerajput/"
    "amazon-ml-challenge-2026-student-resource/"
    "student_resource/dataset/test/test_source2.tsv"
)

print("=" * 80)
print("FINAL TEST S2 PIPELINE")
print("=" * 80)

# ------------------------------------------------------------
# Build S2 test index again, in RAM.
# ------------------------------------------------------------

print("\nBuilding TEST S2 index...")

t0 = time.time()

test_s2_index = build_index(
    TEST_S2_PATH,
    "S2",
    limit=None,
    backend="memory",
)

print(
    f"\nS2 indexed: {test_s2_index.count:,}"
)

print(
    f"S2 blocking keys: {test_s2_index.num_keys():,}"
)

print(
    f"Index time: {(time.time()-t0)/60:.1f} min"
)

# ------------------------------------------------------------
# Stream TEST S1.
#
# IMPORTANT:
# We do NOT write the raw candidate set to disk.
# We retain only the candidates that will proceed to scoring.
# ------------------------------------------------------------

print("\nGenerating S2 candidates...")

s2_candidates_by_s1 = {}
s1_rows = {}

raw_pairs = 0
kept_pairs = 0
zero_rows = 0
processed = 0

t1 = time.time()

with open(
    TEST_S1_PATH,
    "r",
    encoding="utf-8",
    errors="replace",
    newline="",
) as f:

    reader = csv.DictReader(
        f,
        delimiter="\t",
    )

    for s1_row in reader:

        processed += 1

        s1_id = str(
            s1_row["entity_id"]
        )

        s1_rows[s1_id] = s1_row

        pairs = generate_candidate_pairs_for_row(
            s1_row,
            {"S2": test_s2_index},
            DEFAULT_FREQ_CAPS,
        )

        raw_pairs += len(pairs)

        # Keep strong blocking candidates.
        kept = []

        for pair in pairs:

            key_types = pair.get(
                "key_types",
                (),
            )

            min_freq = pair.get(
                "min_freq",
                999999999,
            )

            if (
                len(key_types) >= 2
                or min_freq <= 20
            ):
                kept.append(pair)

        if kept:

            s2_candidates_by_s1[
                s1_id
            ] = kept

            kept_pairs += len(kept)

        else:

            zero_rows += 1

        if processed % 100000 == 0:

            ram = psutil.virtual_memory()

            print(
                f"{processed:,}/1,732,544 | "
                f"raw={raw_pairs:,} | "
                f"kept={kept_pairs:,} | "
                f"zero={zero_rows:,} | "
                f"RAM free="
                f"{ram.available/(1024**3):.2f} GB | "
                f"time="
                f"{(time.time()-t1)/60:.1f} min"
            )

print()
print("=" * 80)
print("S2 CANDIDATE GENERATION COMPLETE")
print("=" * 80)

print(
    f"S1 rows             : {processed:,}"
)

print(
    f"Raw S2 candidates   : {raw_pairs:,}"
)

print(
    f"Retained S2 pairs   : {kept_pairs:,}"
)

print(
    f"Retention           : "
    f"{kept_pairs/max(raw_pairs,1):.2%}"
)

print(
    f"Zero retained rows  : {zero_rows:,}"
)

print(
    f"Total runtime       : "
    f"{(time.time()-t0)/60:.1f} min"
)

print("=" * 80)

================================================================================
FINAL TEST S2 PIPELINE
================================================================================

Building TEST S2 index...
[indexer] Building memory index for S2 from: /kaggle/input/datasets/tejasweerajput/amazon-ml-challenge-2026-student-resource/student_resource/dataset/test/test_source2.tsv
[indexer]   indexed 500,000 S2 records...
[indexer]   indexed 1,000,000 S2 records...
[indexer]   indexed 1,500,000 S2 records...
[indexer]   indexed 2,000,000 S2 records...
[indexer]   indexed 2,500,000 S2 records...